Repository Normation/rudder, pull requests merged in 2018-07, with the labels that each got.

#1986 Fixes #12940: Can not create token
  rudder-web/src/main/webapp/javascript/rudder/angular/apiAccount.js
  rudder-web/src/main/webapp/secure/administration/apiManagement.html
Labels: Ready for merge, qa: Can't merge

#1987 Fixes #12947: JS error when changing the status of an api token
  rudder-web/src/main/webapp/javascript/rudder/angular/apiAccount.js
  rudder-web/src/main/webapp/secure/administration/apiManagement.html
Labels: Ready for merge

#1988 Fixes #12474: root node disapeared while upgrading from 4.1 to 4.3 on debian 9
  rudder-core/src/main/scala/com/normation/rudder/services/nodes/NodeInfoService.scala
  rudder-core/src/test/scala/com/normation/rudder/repository/ldap/InventoryNodeInfoCompatTest.scala
Labels: Ready for merge

#1989 Fixes #12988: NodeInfoCache is precise to the second but we need it to be precise to the millisecond
  rudder-core/src/main/scala/com/normation/rudder/services/nodes/NodeInfoService.scala
Labels: Ready for merge

#1993 Fixes #12668: Remove the "Update policy" button
  rudder-web/src/main/scala/com/normation/rudder/web/comet/AsyncDeployment.scala
Labels: qa: Can't merge

#1991 Fixes #12923: Display Rudder Machine ID color scheme is surprising
  rudder-web/src/main/scala/com/normation/rudder/web/services/DisplayNode.scala
  rudder-web/src/main/webapp/style/rudder/rudder-menu.css
Labels: qa: Can't merge

#1992 Fixes #12816: Strange behavior of the generation status icon background
  rudder-web/src/main/webapp/style/rudder/rudder-menu.css
Labels: qa: Can't merge

#2007 Fixes #13073: Missing real-time check of license capabilities for api and others plugins
  rudder-core/src/main/scala/com/normation/rudder/services/workflows/WorkflowService.scala
  rudder-core/src/test/scala/com/normation/rudder/services/policies/NodeConfigData.scala
  rudder-core/src/test/scala/com/normation/rudder/services/policies/write/PathComputerTest.scala
  rudder-web/src/main/scala/bootstrap/liftweb/AppConfig.scala
  rudder-web/src/main/scala/com/normation/plugins/ExtendableSnippet.scala
  rudder-web/src/main/scala/com/normation/plugins/PluginStatus.scala
Labels: Ready for merge
