Repository Normation/rudder, pull requests merged in 2018-05, with the labels that each got.

#1923 Fixes #12556: NumberFormatException in NodeAPI 8 (runResponse)
  rudder-web/src/main/scala/com/normation/rudder/web/rest/node/NodeAPIService8.scala
Labels: qa: Can't merge

#1930 Fixes #12616: ${const.dollar} in generic method parameter leads to missing report
  rudder-core/src/main/scala/com/normation/rudder/services/reports/ExecutionBatch.scala
  rudder-core/src/test/scala/com/normation/rudder/services/reports/ExecutionBatchTest.scala
Labels: qa: Can't merge

#1934 Fixes #12621: Explore alternative format for compliance table
  rudder-core/src/main/resources/Migration/dbMigration-4.1.x-4.1.12-add-compliancelevel-table.sql
  rudder-core/src/main/resources/reportsSchema.sql
  rudder-core/src/main/scala/com/normation/rudder/batch/AutomaticReportsCleaner.scala
  rudder-core/src/main/scala/com/normation/rudder/domain/reports/CleanReportsAction.scala
  rudder-core/src/main/scala/com/normation/rudder/repository/ExpectedReportsRepository.scala
  rudder-core/src/main/scala/com/normation/rudder/repository/jdbc/ComplianceRepository.scala
  rudder-core/src/main/scala/com/normation/rudder/repository/jdbc/ExpectedReportsJdbcRepository.scala
  rudder-core/src/main/scala/com/normation/rudder/services/system/DatabaseManager.scala
  rudder-core/src/test/scala/com/normation/rudder/db/GenerateCompliance.scala
  rudder-web/src/main/resources/configuration.properties.sample
  rudder-web/src/main/scala/bootstrap/liftweb/AppConfig.scala
Labels: qa: Can't merge

#1936 Fixes #12661: Rudder fails to boot because cleaning TTL property is added after rudder reboot by migration script
  rudder-web/src/main/scala/bootstrap/liftweb/AppConfig.scala
Labels: Ready for merge

#1939 Fixes #12629: While adding network in General settings CIDR notation validation fails in special cases
  rudder-web/src/main/webapp/javascript/rudder/rudder.js
Labels: Ready for merge

#1938 Fixes #12666: Missing ipv6 constraint regex test
  rudder-core/src/test/scala/com/normation/cfclerk/domain/ConstraintsTest.scala
Labels: Ready for merge, qa: Can't merge

#1941 Fixes #12674: Policies regeneration error when using a parameters with " char
  rudder-core/src/main/scala/com/normation/rudder/services/policies/write/PrepareTemplateVariables.scala
Labels: Ready for merge, qa: Can't merge

#1945 Fixes #12650: Directive tree filter is very slow
  rudder-web/src/main/webapp/javascript/rudder/angular/filters.js
Labels: qa: Can't merge

#1947 Fixes #12690: Rule tree filter is a bit slow
  rudder-web/src/main/webapp/javascript/rudder/angular/filters.js
Labels: qa: Can't merge

#1944 Fixes #12643: Compliance bar appears partially white in some graphes
  rudder-web/src/main/webapp/javascript/rudder/rudder-datatable.js
Labels: Ready for merge, qa: Can't merge

#1948 Fixes #12638: When deleting an API account the removed row is not the good one
  rudder-web/src/main/webapp/javascript/rudder/angular/apiAccount.js
Labels: qa: Can't merge

#1953 Fixes #11347: Windows node show an empty Certificate Hash field in node details
  rudder-core/src/main/resources/hooks.d/policy-generation-node-ready/90-change-perm
  rudder-core/src/main/scala/com/normation/rudder/domain/nodes/NodeInfo.scala
  rudder-core/src/main/scala/com/normation/rudder/services/nodes/NodeInfoService.scala
  rudder-web/src/main/scala/com/normation/rudder/web/services/DisplayNode.scala
Labels: qa: Can't merge
