Repository Normation/rudder, pull requests merged in 2019-09, with the labels that each got.

#2436 Fixes #15608: When creating a rule via the API the id parameter is only read from url parameters, and not from json
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/RestExtractorService.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/DirectiveApi.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/RuleApi.scala
Labels: Ready for merge, qa: Can't merge

#2437 Fixes #15623: Moving a category fails with "missing ldap attribute"
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/RudderDit.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/ldap/LDAPDirectiveRepository.scala
Labels: Ready for merge, qa: Can't merge

#2439 Fixes #15631: Rudder-pkg prints tables on a dict base source, which lead to unconsistent columns ordering
  relay/sources/rudder-pkg/lib/rudder-pkg/rudderPkg.py
  relay/sources/rudder-pkg/lib/rudder-pkg/rudderPkgUtils.py
Labels: Ready for merge

#2442 Fixes #15638: Error in parent ticket - CmdbQuery is missing a Logger
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/queries/CmdbQuery.scala
Labels: Ready for merge, qa: Can't merge

#2443 Fixes #15646: Memory Leak in Rudder 5.0
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/DeploymentService.scala
Labels: qa: Can't merge

#2445 Fixes #15536: Updating Apache's reverse proxy configuration to handle HTTPS requests on remote-run API
  relay/sources/Makefile
  relay/sources/apache/rudder-apache-relay-common.conf
  relay/sources/apache/rudder-vhost.conf
  relay/sources/relay-api/.gitignore
  relay/sources/relay-api/README
  relay/sources/relay-api/apache/relay-api.wsgi
  relay/sources/relay-api/cleanup.sh
  relay/sources/relay-api/nodeslist.json.example
  relay/sources/relay-api/relay_api/__init__.py
  relay/sources/relay-api/relay_api/common.py
  relay/sources/relay-api/relay_api/remote_run.py
  relay/sources/relay-api/relay_api/shared_files.py
  relay/sources/relay-api/relay_api/views.py
  relay/sources/relay-api/requirements.txt
  relay/sources/relay-api/run.py
  relay/sources/rudder-server-relay-postinst
Labels: Ready for merge, qa: Can't merge

#2446 Fixes #15651: Moving a category from a subcategory to root fails
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/cfclerk/services/TechniqueLibraryUpdateNotification.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/cfclerk/services/impl/TechniqueRepositoryImpl.scala
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/cfclerk/services/TechniqueRepositoryTest.scala
Labels: Ready for merge

#2447 Fixes #15661: Manage nashorn warning parameter from code
  webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala
  webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/checks/CheckNashornWarning.scala
Labels: Ready for merge

#2448 Fixes #15665: Variable should not extend loggable
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/cfclerk/domain/VariableAndSection.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/DataStructures.scala
Labels: Ready for merge

#2451 Fixes #15673: Parent ticket didn't corrected the problem when a category is moved to root
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/cfclerk/services/TechniqueRepositoryTest.scala
Labels: Ready for merge

#2462 Fixes #15710: Batch to purge deleted inventories starts 10 minutes after startup, rather than the defined interval after startup
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/batch/PurgeDeletedInventories.scala
Labels: qa: Can't merge

#2464 Fixes #14209: Impossible to reset the status of a Node using rudder-keys cli
  webapp/sources/ldap-inventory/inventory-api/src/main/scala/com/normation/inventory/services/provisioning/CheckInventoryDigest.scala
Labels: Ready for merge, qa: Can't merge

#2463 Fixes #15488: Virtuozzo Virtual machine reported as "Unknown type"
  webapp/sources/ldap-inventory/inventory-api/src/main/scala/com/normation/inventory/domain/MachineInventory.scala
  webapp/sources/ldap-inventory/inventory-fusion/src/main/scala/com/normation/inventory/provisioning/fusion/FusionReportUnmarshaller.scala
  webapp/sources/ldap-inventory/inventory-fusion/src/test/resources/fusion-report/virtuozzo.ocs
  webapp/sources/ldap-inventory/inventory-fusion/src/test/scala/com/normation/inventory/provisioning/fusion/TestReportParsing.scala
  webapp/sources/ldap-inventory/inventory-repository/src/main/scala/com/normation/inventory/ldap/core/InventoryMapper.scala
  webapp/sources/ldap-inventory/inventory-repository/src/main/scala/com/normation/inventory/ldap/core/LDAPConstants.scala
  webapp/sources/rudder/rudder-web/src/main/resources/default.properties
Labels: qa: Can't merge

#2468 Fixes #15741: Update scala to 2.12.10
  webapp/sources/ldap-inventory/inventory-fusion/src/main/scala/com/normation/inventory/provisioning/fusion/PreUnmarshallCheckConsistency.scala
  webapp/sources/ldap-inventory/inventory-repository/src/main/scala/com/normation/history/impl/FileHistoryLogRepository.scala
  webapp/sources/ldap-inventory/inventory-repository/src/main/scala/com/normation/inventory/ldap/core/InventoryDitServiceImpl.scala
  webapp/sources/ldap-inventory/inventory-repository/src/main/scala/com/normation/inventory/ldap/core/InventoryMapper.scala
  webapp/sources/rudder-commons/utils/src/main/scala/com/normation/utils/Control.scala
  webapp/sources/rudder-parent-pom/pom.xml
  webapp/sources/rudder/rudder-core/pom.xml
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/cfclerk/domain/TechniqueCategory.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/cfclerk/services/impl/TechniqueRepositoryImpl.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/cfclerk/xmlwriters/SectionSpecWriter.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/policies/RuleTarget.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/reports/ReportType.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/hooks/RunHooks.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/ncf/TechniqueWriter.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/jdbc/EventLogJdbcRepository.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/jdbc/ExpectedReportsJdbcRepository.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/ldap/LDAPDirectiveRepository.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/ldap/LDAPEntityMapper.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/ldap/LDAPNodeGroupRepository.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/xml/ItemArchiveManagerImpl.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/xml/ZipUtils.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/rule/category/RuleCategory.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/DeploymentService.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/InterpolatedValueCompiler.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/MergePolicyService.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/SystemVariableService.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/queries/CmdbQueryParser.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/queries/DynGroupService.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/queries/LdapQueryProcessor.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/quicksearch/QuickSearchBackendImpl.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/reports/ExecutionBatch.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/servers/NewNodeManager.scala
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/domain/policies/RuleTargetTest.scala
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/repository/ldap/LoadDemoDataTest.scala
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/policies/TestNodeAndParameterLookup.scala
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/reports/ComplianceTest.scala
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/reports/ExecutionBatchTest.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/web/model/FilePermissions.scala
  webapp/sources/rudder/rudder-web/pom.xml
  webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/Boot.scala
  webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/checks/CheckMigrationDirectiveInterpolatedVariablesHaveRudderNamespace.scala
  webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/checks/CheckNashornWarning.scala
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/plugins/ExtendableSnippet.scala
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/DirectiveApplicationManagement.scala
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/PendingChangeRequestDisplayer.scala
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/RuleDisplayer.scala
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/model/DirectiveFieldEditors.scala
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/model/JsTreeNode.scala
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/model/RudderBaseField.scala
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/services/DisplayDirectiveTree.scala
  webapp/sources/scala-ldap/src/main/scala/com/normation/ldap/sdk/LDAPConnection.scala
Labels: qa: Can't merge

#2470 Fixes #15740: Update libraries to last minor versions
  webapp/sources/ldap-inventory/inventory-provisioning-web/src/main/scala/com/normation/inventory/provisioning/endpoint/InventoryFileWatcher.scala
  webapp/sources/ldap-inventory/inventory-repository/pom.xml
  webapp/sources/pom.xml
  webapp/sources/rudder/rudder-core/pom.xml
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/db/Doobie.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/ncf/TechniqueWriter.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/ldap/LDAPDirectiveRepository.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/ldap/LDAPNodeGroupRepository.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/rule/category/LDAPRuleCategoryRepository.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/DeploymentService.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/JavascriptEngine.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/WriteNodeCertificatesPem.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/write/PolicyWriterService.scala
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/policies/TestJsEngine.scala
  webapp/sources/rudder/rudder-rest/pom.xml
  webapp/sources/rudder/rudder-templates-cli/pom.xml
  webapp/sources/rudder/rudder-web/pom.xml
  webapp/sources/utils/src/main/scala/com/normation/ZioCommons.scala
Labels: qa: Can't merge

#2472 Fixes #15749: A lot of memory (and ressources) seems to be used in PreUnmarshallCheckConsistency
  webapp/sources/ldap-inventory/inventory-fusion/src/main/scala/com/normation/inventory/provisioning/fusion/PreUnmarshallCheckConsistency.scala
Labels: qa: Can't merge

#2474 Fixes #15768: Make inventory processing less memory consuming
  webapp/sources/ldap-inventory/inventory-provisioning-web/src/main/scala/com/normation/inventory/provisioning/endpoint/FusionReportEndpoint.scala
  webapp/sources/ldap-inventory/inventory-provisioning-web/src/main/scala/com/normation/inventory/provisioning/endpoint/InventoryFileWatcher.scala
  webapp/sources/ldap-inventory/inventory-provisioning-web/src/main/scala/com/normation/inventory/provisioning/endpoint/InventoryProcessor.scala
Labels: qa: Can't merge

#2469 Fixes #15747: When receving pleinty of inventories at the same time, the web interface starts to parse them all at once (branch 5.0)
  webapp/sources/ldap-inventory/inventory-provisioning-web/src/main/scala/com/normation/inventory/provisioning/endpoint/InventoryFileWatcher.scala
Labels: qa: Can't merge

#2480 Fixes #15171: Cannot get Rule tree with the API in Rudder 5.0
  webapp/sources/ldap-inventory/inventory-provisioning-core/src/main/scala/com/normation/inventory/ldap/provisioning/DefaultReportSaver.scala
  webapp/sources/ldap-inventory/inventory-provisioning-core/src/main/scala/com/normation/inventory/ldap/provisioning/SoftwareIdFinder.scala
  webapp/sources/ldap-inventory/inventory-repository/src/test/scala/com/normation/inventory/ldap/core/TestInventory.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/EndpointsDefinition.scala
Labels: qa: Can't merge

#2481 Fixes #15791: Missing generation failure hook
  webapp/sources/rudder/rudder-core/src/main/resources/hooks.d/policy-generation-failed/hook-template
  webapp/sources/rudder/rudder-core/src/main/resources/hooks.d/policy-generation-failed/readme.adoc
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/hooks/RunHooks.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/DeploymentService.scala
  webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala
Labels: qa: Can't merge

#2482 Fixes #15792: When writing policies, we replace the RudderUniqueId with replaceAll which is twice as slow as StringUtils.replace
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/write/PolicyWriterService.scala
Labels: qa: Can't merge

#2471 Fixes #15752: Merge inventory endpoint and rudder webapps
  webapp/sources/ldap-inventory/inventory-provisioning-web/pom.xml
  webapp/sources/ldap-inventory/inventory-provisioning-web/src/main/resources/configuration.properties.sample
  webapp/sources/ldap-inventory/inventory-provisioning-web/src/main/resources/logback.xml.sample
  webapp/sources/ldap-inventory/inventory-provisioning-web/src/main/scala/com/normation/inventory/provisioning/endpoint/FusionReportEndpoint.scala
  webapp/sources/ldap-inventory/inventory-provisioning-web/src/main/scala/com/normation/inventory/provisioning/endpoint/config/AppConfig.scala
  webapp/sources/ldap-inventory/inventory-provisioning-web/src/main/scala/com/normation/inventory/provisioning/endpoint/config/LogbackContextInitListener.scala
  webapp/sources/ldap-inventory/inventory-provisioning-web/src/main/scala/com/normation/inventory/provisioning/endpoint/config/PropertyPlaceholderConfig.scala
  webapp/sources/ldap-inventory/inventory-provisioning-web/src/main/webapp/WEB-INF/web.xml
  webapp/sources/ldap-inventory/inventory-provisioning-web/src/test/resources/cert-nodeid-bad.pem
  webapp/sources/ldap-inventory/inventory-provisioning-web/src/test/resources/cert-nodeid-ok-new.pem
  webapp/sources/ldap-inventory/inventory-provisioning-web/src/test/resources/cert-nodeid-ok.pem
  webapp/sources/ldap-inventory/inventory-provisioning-web/src/test/resources/key-nodeid-bad.pem
  webapp/sources/ldap-inventory/inventory-provisioning-web/src/test/resources/key-nodeid-ok-new.pem
  webapp/sources/ldap-inventory/inventory-provisioning-web/src/test/resources/key-nodeid-ok.pem
  webapp/sources/ldap-inventory/inventory-provisioning-web/src/test/resources/linux-cert-sign.ocs
  webapp/sources/ldap-inventory/inventory-provisioning-web/src/test/resources/linux-cert-sign.ocs.sign
  webapp/sources/ldap-inventory/inventory-provisioning-web/src/test/resources/linux-cfe-sign.ocs
  webapp/sources/ldap-inventory/inventory-provisioning-web/src/test/resources/linux-cfe-sign.ocs.sign
  webapp/sources/ldap-inventory/inventory-provisioning-web/src/test/resources/readme.txt
  webapp/sources/ldap-inventory/inventory-provisioning-web/src/test/resources/rudder-sign
  webapp/sources/ldap-inventory/inventory-provisioning-web/src/test/resources/windows-bad-certificate.ocs
  webapp/sources/ldap-inventory/inventory-provisioning-web/src/test/resources/windows-bad-certificate.ocs.sign
  webapp/sources/ldap-inventory/inventory-provisioning-web/src/test/resources/windows-new-certificate.ocs
  webapp/sources/ldap-inventory/inventory-provisioning-web/src/test/resources/windows-new-certificate.ocs.sign
  webapp/sources/ldap-inventory/inventory-provisioning-web/src/test/resources/windows-same-certificate.ocs
  webapp/sources/ldap-inventory/inventory-provisioning-web/src/test/resources/windows-same-certificate.ocs.sign
  webapp/sources/ldap-inventory/inventory-provisioning-web/src/test/scala/com/normation/inventory/provisioning/endpoint/InventoryFileWatcherTest.scala
  webapp/sources/ldap-inventory/inventory-provisioning-web/src/test/scala/com/normation/inventory/provisioning/endpoint/TestCertificate.scala
  webapp/sources/ldap-inventory/pom.xml
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/cfclerk/services/impl/SystemVariableSpecServiceImpl.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/inventory/InventoryFileWatcher.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/inventory/InventoryProcessor.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/SystemVariableService.scala
  webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/node-cfe-with-500-directives/rules/cfengine-community/rudder.json
  webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/node-cfe-with-two-directives/rules/cfengine-community/rudder.json
  webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/node-gen-var-def-override/rules/cfengine-community/rudder.json
  webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/root-default-install/distributePolicy/1.0/common.cf
  webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/root-default-install/rudder.json
  webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/root-with-one-multipolicy/distributePolicy/1.0/common.cf
  webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/root-with-one-multipolicy/rudder.json
  webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/root-with-two-directives/distributePolicy/1.0/common.cf
  webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/root-with-two-directives/rudder.json
  webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/techniques/system/distributePolicy/1.0/common.st
  webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/techniques/system/distributePolicy/1.0/metadata.xml
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/policies/NodeConfigData.scala
  webapp/sources/rudder/rudder-rest/pom.xml
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/EndpointsDefinition.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/RestUtils.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/InventoryApi.scala
  webapp/sources/rudder/rudder-web/pom.xml
  webapp/sources/rudder/rudder-web/src/main/resources/configuration.properties.sample
  webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/Boot.scala
  webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala
Labels: qa: Can't merge

#2488 Fixes #15686: Fix Rudder remote-run API
  relay/sources/relayd/Cargo.lock
  relay/sources/relayd/Cargo.toml
  relay/sources/relayd/src/api.rs
  relay/sources/relayd/src/data/node.rs
  relay/sources/relayd/src/lib.rs
  relay/sources/relayd/src/output/upstream.rs
  relay/sources/relayd/src/remote_run.rs
  relay/sources/relayd/tests/fake_agent.sh
  relay/sources/relayd/tests/remote_run.rs
Labels: qa: Can't merge
