Repository Normation/rudder, pull requests merged in 2019-07, with the labels that each got.

#2275 Fixes #15102: Port NuCommand and RunHooks to ZIO
  webapp/sources/ldap-inventory/inventory-provisioning-web/pom.xml
  webapp/sources/pom.xml
  webapp/sources/rudder/rudder-core/src/main/resources/hooks.d/policy-generation-node-ready/10-cf-promise-check
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/logger/PolicyLogger.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/hooks/RunHooks.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/hooks/RunNuCommand.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/MergePolicyService.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/write/PolicyWriterService.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/system/DebugInfoService.scala
  webapp/sources/rudder/rudder-core/src/test/resources/hooks.d/test/echoCODE.sh
  webapp/sources/rudder/rudder-core/src/test/resources/hooks.d/test/error10.sh
  webapp/sources/rudder/rudder-core/src/test/resources/hooks.d/test/success.sh
  webapp/sources/rudder/rudder-core/src/test/resources/hooks.d/test/warning50.sh
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/hooks/HooksTest.scala
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/hooks/RunNuCommandTest.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/SystemApi.scala
  webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/web/rest/RestTestSetUp.scala
  webapp/sources/rudder/rudder-web/pom.xml
  webapp/sources/utils/src/main/scala/com/normation/ZioCommons.scala
Labels: qa: Can't merge

#2287 Fixes #15011: Error at the end of a policy generation with too many nodes
  webapp/sources/rudder/rudder-core/pom.xml
  webapp/sources/rudder/rudder-core/src/main/resources/hooks.d/policy-generation-finished/50-reload-policy-file-server
  webapp/sources/rudder/rudder-core/src/main/resources/hooks.d/policy-generation-finished/60-trigger-node-update
  webapp/sources/rudder/rudder-core/src/main/resources/hooks.d/policy-generation-finished/hook-template
  webapp/sources/rudder/rudder-core/src/main/resources/hooks.d/policy-generation-finished/readme.adoc
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/DeploymentService.scala
  webapp/sources/rudder/rudder-core/src/test/resources/hooks.d/test-hooks.sh
  webapp/sources/rudder/rudder-web/pom.xml
  webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala
Labels: qa: Can't merge

#2288 Fixes #15144: Build Elm JS during project build
  .gitignore
  webapp/sources/rudder/rudder-web/pom.xml
  webapp/sources/rudder/rudder-web/src/main/elm/build-app.sh
  webapp/sources/rudder/rudder-web/src/main/elm/notifications/elm.json
  webapp/sources/rudder/rudder-web/src/main/elm/notifications/sources/rudder-notifications.elm
  webapp/sources/rudder/rudder-web/src/main/webapp/elm/rudder-notifications/build-app.sh
  webapp/sources/rudder/rudder-web/src/main/webapp/elm/rudder-notifications/elm-package.json
  webapp/sources/rudder/rudder-web/src/main/webapp/javascript/rudder/elm/keep
  webapp/sources/rudder/rudder-web/src/main/webapp/javascript/rudder/rudder-elm.js
  webapp/sources/rudder/rudder-web/src/main/webapp/templates-hidden/common-layout.html
Labels: qa: Can't merge

#2290 Fixes #15159: Webapp stops at ncf boot check
  webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/checks/CheckNcfTechniqueUpdate.scala
Labels: Ready for merge

#2291 Fixes #15164: Improve logging
  relay/sources/relayd/Cargo.lock
  relay/sources/relayd/Cargo.toml
  relay/sources/relayd/src/data/report.rs
  relay/sources/relayd/src/data/runlog.rs
  relay/sources/relayd/src/lib.rs
  relay/sources/relayd/src/relayd.rs
  relay/sources/relayd/src/status.rs
  relay/sources/relayd/tests/reports_database.rs
Labels: Ready for merge, qa: Can't merge

#2273 Fixes #15056: Implementing agents effectively in remote-run API
  relay/sources/relayd/Cargo.lock
  relay/sources/relayd/Cargo.toml
  relay/sources/relayd/hashtest.txt
  relay/sources/relayd/src/api.rs
  relay/sources/relayd/src/data/node.rs
  relay/sources/relayd/src/error.rs
  relay/sources/relayd/src/remote_run.rs
  relay/sources/relayd/src/shared_files.rs
  relay/sources/relayd/tests/api_tests.rs
  relay/sources/relayd/tests/files/metadata.txt
  relay/sources/relayd/tests/test_simple/config/logging.conf
Labels: Ready for merge

#2294 Fixes #14389: Duplicate dependency "jsr305" in rudder-core/pom.xml
  webapp/sources/rudder/rudder-core/pom.xml
Labels: qa: Can't merge

#2301 Fixes #15202: Logging the remote-run API with warp
  relay/sources/relayd/src/api.rs
  relay/sources/relayd/src/remote_run.rs
  relay/sources/relayd/src/shared_files.rs
Labels: Ready for merge

#2305 Fixes #15209: Control runlog consistency before inserting it
  relay/sources/relayd/src/api.rs
  relay/sources/relayd/src/data/runinfo.rs
  relay/sources/relayd/src/data/runlog.rs
  relay/sources/relayd/src/output/database.rs
  relay/sources/relayd/src/processing.rs
  relay/sources/relayd/tests/relay_api.rs
  relay/sources/relayd/tests/reports_database.rs
  relay/sources/relayd/tests/runlogs/2017-08-24T15:55:01+00:00@e745a140-40bc-4b86-b6dc-084488fc906b.log
  relay/sources/relayd/tests/runlogs/2017-08-24T15:55:01+00:00@e745a140-40bc-4b86-b6dc-084488fc906b.signed
  relay/sources/relayd/tests/runlogs/2018-08-24T15:55:01+00:00@e745a140-40bc-4b86-b6dc-084488fc906b.json
  relay/sources/relayd/tests/runlogs/2018-08-24T15:55:01+00:00@e745a140-40bc-4b86-b6dc-084488fc906b.log
  relay/sources/relayd/tests/runlogs/2018-08-24T15:55:01+00:00@e745a140-40bc-4b86-b6dc-084488fc906b.signed
  relay/sources/relayd/tests/runlogs/2018-08-24T15:55:01+00:00@e745a140-40bc-4b86-b6dc-084488fc906c.log
Labels: Ready for merge, qa: Can't merge

#2308 Fixes #15214: Add an API endpoint to reload config
  relay/sources/relayd/Cargo.lock
  relay/sources/relayd/src/api.rs
  relay/sources/relayd/src/lib.rs
  relay/sources/relayd/tests/reports_database.rs
Labels: qa: Can't merge

#2309 Fixes #14866:
  webapp/sources/ldap-inventory/inventory-api/src/main/scala/com/normation/inventory/services/provisioning/CheckInventoryDigest.scala
  webapp/sources/ldap-inventory/inventory-api/src/main/scala/com/normation/inventory/services/provisioning/DefaultReportUnmarshaller.scala
  webapp/sources/ldap-inventory/inventory-api/src/main/scala/com/normation/inventory/services/provisioning/GenericIdFinder.scala
  webapp/sources/ldap-inventory/inventory-api/src/main/scala/com/normation/inventory/services/provisioning/IdFinderAction.scala
  webapp/sources/ldap-inventory/inventory-api/src/main/scala/com/normation/inventory/services/provisioning/PostCommit.scala
  webapp/sources/ldap-inventory/inventory-api/src/main/scala/com/normation/inventory/services/provisioning/PreCommit.scala
  webapp/sources/ldap-inventory/inventory-api/src/main/scala/com/normation/inventory/services/provisioning/PreUnmarshall.scala
  webapp/sources/ldap-inventory/inventory-api/src/main/scala/com/normation/inventory/services/provisioning/ReportSaver.scala
  webapp/sources/ldap-inventory/inventory-api/src/main/scala/com/normation/inventory/services/provisioning/ReportUnmarshaller.scala
  webapp/sources/ldap-inventory/inventory-fusion/src/test/scala/com/normation/inventory/provisioning/fusion/TestSignatureService.scala
  webapp/sources/ldap-inventory/inventory-provisioning-web/src/main/scala/com/normation/inventory/provisioning/endpoint/InventoryProcessor.scala
  webapp/sources/ldap-inventory/inventory-provisioning-web/src/main/scala/com/normation/inventory/provisioning/endpoint/config/AppConfig.scala
  webapp/sources/ldap-inventory/inventory-provisioning-web/src/test/resources/cert-nodeid-bad.pem
  webapp/sources/ldap-inventory/inventory-provisioning-web/src/test/resources/cert-nodeid-ok-new.pem
  webapp/sources/ldap-inventory/inventory-provisioning-web/src/test/resources/cert-nodeid-ok.pem
  webapp/sources/ldap-inventory/inventory-provisioning-web/src/test/resources/key-nodeid-bad.pem
  webapp/sources/ldap-inventory/inventory-provisioning-web/src/test/resources/key-nodeid-ok-new.pem
  webapp/sources/ldap-inventory/inventory-provisioning-web/src/test/resources/key-nodeid-ok.pem
  webapp/sources/ldap-inventory/inventory-provisioning-web/src/test/resources/readme.txt
  webapp/sources/ldap-inventory/inventory-provisioning-web/src/test/resources/rudder-sign
  webapp/sources/ldap-inventory/inventory-provisioning-web/src/test/resources/windows-bad-certificate.ocs
  webapp/sources/ldap-inventory/inventory-provisioning-web/src/test/resources/windows-bad-certificate.ocs.sign
  webapp/sources/ldap-inventory/inventory-provisioning-web/src/test/resources/windows-new-certificate.ocs
  webapp/sources/ldap-inventory/inventory-provisioning-web/src/test/resources/windows-new-certificate.ocs.sign
  webapp/sources/ldap-inventory/inventory-provisioning-web/src/test/resources/windows-same-certificate.ocs
  webapp/sources/ldap-inventory/inventory-provisioning-web/src/test/resources/windows-same-certificate.ocs.sign
  webapp/sources/ldap-inventory/inventory-provisioning-web/src/test/scala/com/normation/inventory/provisioning/endpoint/TestCertificate.scala
Labels: qa: Can't merge

#2304 Fixes #15207: Error when modifying a Directive when having the Change Request plugin
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/workflows/CommitAndDeployChangeRequestService.scala
Labels: qa: Can't merge

#2312 Fixes #15228: Update test and lint configuration
  relay/sources/Makefile
  relay/sources/relayd/tests/relay_api.rs
Labels: qa: Can't merge

#2319 Fixes #15245: Limiting conditions length to 1024 characters
  relay/sources/relayd/src/remote_run.rs
  relay/sources/relayd/tests/relay_api.rs
Labels: qa: Can't merge

#2323 Fixes #15251: Add an option to allow disabling log_ reports insertion
  relay/sources/relayd/src/configuration.rs
  relay/sources/relayd/src/data/report.rs
  relay/sources/relayd/src/data/runlog.rs
  relay/sources/relayd/src/processing.rs
  relay/sources/relayd/src/shared_files.rs
  relay/sources/relayd/tests/files/config/main.conf
  relay/sources/relayd/tests/test_simple/config/main.conf
  relay/sources/relayd/tools/config/main.conf
Labels: qa: Can't merge

#2313 Fixes #15212: Generate a file on root server containing all nodes certificate
  webapp/sources/ldap-inventory/inventory-fusion/src/test/scala/com/normation/inventory/provisioning/fusion/TestPreUnmarshaller.scala
  webapp/sources/ldap-inventory/inventory-fusion/src/test/scala/com/normation/inventory/provisioning/fusion/TestSignatureService.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/ldap/Lock.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/xml/GitArchiverUtils.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/xml/GitFindUtils.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/xml/ItemArchiveManagerImpl.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/xml/ZipUtils.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/DeploymentService.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/WriteNodeCertificatesPem.scala
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/policies/TestWriteNodeCertificatesPem.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/SystemApi.scala
  webapp/sources/rudder/rudder-web/src/main/resources/configuration.properties.sample
  webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala
  webapp/sources/utils/src/main/scala/com/normation/ZioCommons.scala
  webapp/sources/utils/src/test/scala/com/normation/ZioCommonsTest.scala
Labels: qa: Can't merge

#2316 Fixes #15236: New node inventories without certificate aren't accepted anymore
  webapp/sources/ldap-inventory/inventory-api/src/main/scala/com/normation/inventory/services/core/FullInventoryRepository.scala
  webapp/sources/ldap-inventory/inventory-api/src/main/scala/com/normation/inventory/services/provisioning/CheckInventoryDigest.scala
  webapp/sources/ldap-inventory/inventory-provisioning-web/src/test/resources/linux-cfe-sign.ocs
  webapp/sources/ldap-inventory/inventory-provisioning-web/src/test/resources/linux-cfe-sign.ocs.sign
  webapp/sources/ldap-inventory/inventory-provisioning-web/src/test/scala/com/normation/inventory/provisioning/endpoint/TestCertificate.scala
  webapp/sources/ldap-inventory/inventory-repository/src/main/scala/com/normation/inventory/ldap/core/FullInventoryRepositoryImpl.scala
Labels: qa: Can't merge

#2324 Fixes #15254: Remove relayd tests from qa-test
  qa-test
  relay/sources/Makefile
Labels: qa: Can't merge

#2331 Fixes #15274: Handle errors in log filter
  relay/sources/Makefile
  relay/sources/relayd/src/error.rs
  relay/sources/relayd/src/lib.rs
Labels: qa: Can't merge

#2335 Fixes #15292: Move /opt/rudder/etc/ssl/nodeslist.cert to /var/rudder/lib/ssl
  relay/sources/Makefile
  relay/sources/rudder-server-relay-postinst
Labels: qa: Can't merge

#2321 Fixes #15239: Generate a list of directives with their id and mode
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/write/PolicyWriterService.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/write/PrepareTemplateVariables.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/write/PromiseWriteDataStructures.scala
  webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/node-cfe-with-500-directives/rules/cfengine-community/rudder-directives.csv
  webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/node-cfe-with-two-directives/rules/cfengine-community/rudder-directives.csv
  webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/node-gen-var-def-override/rules/cfengine-community/rudder-directives.csv
  webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/root-default-install/rudder-directives.csv
  webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/root-with-one-multipolicy/rudder-directives.csv
  webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/root-with-two-directives/rudder-directives.csv
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/policies/NodeConfigData.scala
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/policies/write/WriteTechniquesTest.scala
Labels: qa: Can't merge

#2340 Fixes #15305: Update link in readme to rudder.io
  README.asciidoc
  webapp/sources/ldap-inventory/README.asciidoc
  webapp/sources/rudder-commons/README.asciidoc
  webapp/sources/rudder-parent-pom/README.asciidoc
  webapp/sources/scala-ldap/README.asciidoc
Labels: qa: Can't merge

#2344 Fixes #15313: Policy generation error is not clear in log anymore
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/DeploymentService.scala
Labels: Ready for merge, qa: Can't merge

#2348 Fixes #15331: Broken certificate handling in Unix nodes
  webapp/sources/ldap-inventory/inventory-provisioning-web/src/test/resources/linux-cert-sign.ocs
  webapp/sources/ldap-inventory/inventory-provisioning-web/src/test/resources/linux-cert-sign.ocs.sign
  webapp/sources/ldap-inventory/inventory-provisioning-web/src/test/scala/com/normation/inventory/provisioning/endpoint/TestCertificate.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/nodes/NodeInfo.scala
Labels: qa: Can't merge

#2349 Fixes #15344: API for node key management
  webapp/sources/ldap-inventory/inventory-api/src/main/scala/com/normation/inventory/domain/DataTypes.scala
  webapp/sources/ldap-inventory/inventory-api/src/main/scala/com/normation/inventory/services/provisioning/CheckInventoryDigest.scala
  webapp/sources/ldap-inventory/inventory-provisioning-web/src/main/scala/com/normation/inventory/provisioning/endpoint/InventoryProcessor.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/nodes/Node.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/nodes/NodeInfo.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/NodeRepository.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/ldap/LDAPEntityMapper.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/ldap/LDAPNodeRepository.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/eventlog/EventLogDetailsService.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/eventlog/EventLogFactory.scala
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/eventlog/NodeEventLogFormatV6Test.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/RestExtractorService.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/data/RestData.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/NodeApi.scala
  webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/services/EventListDisplayer.scala
Labels: qa: Can't merge

#2282 Fixes #15117: Use a queue for "changes" cache update
  webapp/sources/ldap-inventory/inventory-repository/src/main/scala/com/normation/inventory/ldap/core/ReadOnlySoftwareInventoryDAOImpl.scala
  webapp/sources/ldap-inventory/inventory-repository/src/main/scala/com/normation/inventory/ldap/core/SoftwareService.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/logger/ReportLogger.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/reports/execution/ReportsExecutionService.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/ReportsRepository.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/jdbc/ReportsJdbcRepository.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/nodes/NodeInfoService.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/reports/NodeChangesService.scala
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/repository/jdbc/ReportingServiceTest.scala
  webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/RuleCompliance.scala
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/RuleGrid.scala
  webapp/sources/utils/src/main/scala/com/normation/ZioCommons.scala
Labels: Ready for merge

#2352 Fixes #15355: MANAGED_NODES_NAME is still needed for CFE nodes
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/SystemVariableService.scala
Labels: qa: Can't merge

#2333 Fixes #15265: Migrate ncf delete api and improve workflow
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/ncf/TechniqueWriter.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/workflows/ChangeRequestService.scala
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/ncf/TestTechniqueWriter.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/EndpointsDefinition.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/RestExtractorService.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/NcfApi.scala
  webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala
Labels: qa: Can't merge
