Repository Normation/rudder, pull requests merged in 2019-10, with the labels that each got.

#2490 Fixes #15808: Fix synchronous remote run test
  relay/sources/relayd/Cargo.lock
  relay/sources/relayd/src/data/node.rs
  relay/sources/relayd/tests/fake_agent.sh
  relay/sources/relayd/tests/remote_run.rs
Labels: qa: Can't merge

#2495 Fixes #15104:
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/Authorizations.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/RoleApiMapping.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/internal/RestQuicksearch.scala
  webapp/sources/rudder/rudder-web/src/main/resources/demo-rudder-users.xml
  webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/Boot.scala
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/configuration/ParameterManagement.scala
Labels: qa: Can't merge

#2497 Fixes #15827: Job to clean unreference software may delete software for pending nodes
  webapp/sources/ldap-inventory/inventory-repository/src/main/scala/com/normation/inventory/ldap/core/ReadOnlySoftwareInventoryDAOImpl.scala
Labels: qa: Can't merge

#2489 Fixes #15802: Clean up report with level log info more than once a day
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/batch/AutomaticReportsCleaner.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/ReportsRepository.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/jdbc/ReportsJdbcRepository.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/system/DatabaseManager.scala
  webapp/sources/rudder/rudder-web/src/main/resources/configuration.properties.sample
  webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala
Labels: qa: Can't merge

#2502 Fixes #15849: Missing a fork for clean report info batch
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/batch/AutomaticReportsCleaner.scala
Labels: Ready for merge

#2503 Fixes #15836: Fix async & keep_output behavior
  relay/sources/relayd/Cargo.lock
  relay/sources/relayd/src/remote_run.rs
  relay/sources/relayd/tests/remote_run.rs
Labels: Ready for merge

#2505 Fixes #15862: Fixes to event log pagination
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/EventLogRepository.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/jdbc/EventLogJdbcRepository.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/internal/EventLogAPI.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/web/services/EventLogDetailsGenerator.scala
  webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/services/EventListDisplayer.scala
  webapp/sources/rudder/rudder-web/src/main/webapp/javascript/rudder/rudder-datatable.js
Labels: Ready for merge

#2506 Fixes #15866: Improve relayd API
  relay/sources/apache/rudder-apache-relay-common.conf
  relay/sources/relayd/Cargo.lock
  relay/sources/relayd/fuzz/Cargo.lock
  relay/sources/relayd/src/api.rs
  relay/sources/relayd/src/data/node.rs
  relay/sources/relayd/src/status.rs
  relay/sources/relayd/tests/api_info.rs
  relay/sources/relayd/tests/api_status.rs
  relay/sources/relayd/tests/common.rs
  relay/sources/relayd/tests/remote_run.rs
  relay/sources/relayd/tests/remote_run_error.rs
  relay/sources/relayd/tests/reports_database.rs
  relay/sources/relayd/tests/shared_files.rs
  relay/sources/relayd/tests/shared_folder.rs
Labels: Ready for merge, qa: Can't merge

#2507 Fixes #15880: Cache relayd builds
  relay/sources/Makefile
Labels: Ready for merge

#2508 Fixes #15882: Cache relayd builds
  relay/sources/Makefile
Labels: Ready for merge

#2509 Fixes #15883: Refactor api code in relayd
  relay/sources/relayd/Cargo.lock
  relay/sources/relayd/Cargo.toml
  relay/sources/relayd/src/api.rs
  relay/sources/relayd/src/api/remote_run.rs
  relay/sources/relayd/src/api/shared_files.rs
  relay/sources/relayd/src/api/shared_folder.rs
  relay/sources/relayd/src/api/system.rs
  relay/sources/relayd/src/data/node.rs
  relay/sources/relayd/src/lib.rs
  relay/sources/relayd/src/relayd.rs
Labels: Ready for merge

#2510 Fixes #15890: Batch which deletes log reports displays an error when default run interval is not defined
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/batch/AutomaticReportsCleaner.scala
Labels: Ready for merge, qa: Can't merge

#2512 Fixes #15896: Normalize datetime format to ISO8601/rfc3339
  webapp/sources/ldap-inventory/inventory-fusion/src/main/scala/com/normation/inventory/provisioning/fusion/FusionReportUnmarshaller.scala
  webapp/sources/ldap-inventory/inventory-repository/src/main/scala/com/normation/history/impl/FileHistoryLogRepository.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/batch/AbstractScheduler.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/batch/UpdateDynamicGroups.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/system/DebugInfoService.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/RestDataSerializer.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/data/NodeDetailLevel.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/internal/EventLogAPI.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/SystemApi.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/web/components/DateFormaterService.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/web/services/EventLogDetailsGenerator.scala
  webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/web/rest/RestTestSetUp.scala
  webapp/sources/rudder/rudder-web/src/main/resources/logback.xml
  webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/services/ComplianceData.scala
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/services/DisplayNode.scala
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/services/SrvGrid.scala
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/administration/Archives.scala
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/administration/DatabaseManagement.scala
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/configuration/DirectiveManagement.scala
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/node/AcceptNode.scala
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/node/PendingHistoryGrid.scala
Labels: Ready for merge

#2514 Fixes #15902: Only cache dependencies
  relay/sources/Makefile
Labels: Ready for merge, qa: Can't merge

#2516 Fixes #15904: "add global param" button still available for read-only role
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/configuration/ParameterManagement.scala
Labels: Ready for merge

#2517 Fixes #15906: Only cache dependencies
  relay/sources/Makefile
Labels: Ready for merge

#2519 Fixes #15909: Disable lto for relayd release builds
  relay/sources/relayd/Cargo.toml
Labels: Ready for merge

#2522 Fixes #15919: Remove unwanted logger
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/RestAuthentication.scala
Labels: Ready for merge

#2523 Fixes #15920: Only cache dependencies
  relay/sources/Makefile
Labels: Ready for merge

#2524 Fixes #15923: Only cache dependencies
  relay/sources/Makefile
Labels: Ready for merge

#2530 Fixes #15965: Changing LdapEntry broke tests
  webapp/sources/scala-ldap/src/main/scala/com/normation/ldap/sdk/LDAPEntry.scala
Labels: Ready for merge

#2526 Fixes #15949: Improve error type definitions
  relay/sources/relayd/Cargo.lock
  relay/sources/relayd/Cargo.toml
  relay/sources/relayd/src/api.rs
  relay/sources/relayd/src/api/remote_run.rs
  relay/sources/relayd/src/error.rs
  relay/sources/relayd/src/hashing.rs
  relay/sources/relayd/tests/remote_run_error.rs
Labels: qa: Can't merge

#2527 Fixes #15952: Rudder package does not work when there are no plugin compatible with the current version of Rudder
  relay/sources/rudder-pkg/lib/rudder-pkg/rudderPkgUtils.py
Labels: qa: Can't merge

#2564 Fixes #16076: relayd should stop when a thread panics
  relay/sources/relayd/src/api.rs
  relay/sources/relayd/src/error.rs
  relay/sources/relayd/src/input.rs
  relay/sources/relayd/src/lib.rs
  relay/sources/relayd/src/relayd.rs
  relay/sources/relayd/tests/api_remote_run.rs
  relay/sources/relayd/tests/api_shared_folder.rs
  relay/sources/relayd/tests/api_system_info.rs
  relay/sources/relayd/tests/api_system_reload.rs
  relay/sources/relayd/tests/api_system_status.rs
Labels: qa: Can't merge

#2565 Fixes #16077: Rudder-pkg fails to build since subprocess.DEVNULL is undefined before python 3.3
  relay/sources/rudder-pkg/lib/rudder-pkg/rudderPkgUtils.py
Labels: qa: Can't merge

#2566 Fixes #16079: Allow overriding RUST_BACKTRACE
  relay/sources/relayd/src/data/node.rs
  relay/sources/relayd/src/relayd.rs
Labels: qa: Can't merge

#2567 Fixes #15943: Date handling in API Token Creation is broken
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/RestDataSerializer.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/RestExtractorService.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/web/components/DateFormaterService.scala
Labels: qa: Can't merge
