Repository Normation/rudder, pull requests merged in 2019-01, with the labels that each got.

#2102 Fixes #13920: Remove jquery-ui related css libraries
  rudder-web/src/main/scala/com/normation/rudder/web/components/ShowNodeDetailsFromNode.scala
  rudder-web/src/main/scala/com/normation/rudder/web/services/DisplayNode.scala
  rudder-web/src/main/scala/com/normation/rudder/web/snippet/administration/PropertiesManagement.scala
  rudder-web/src/main/scala/com/normation/rudder/web/snippet/configuration/DirectiveManagement.scala
  rudder-web/src/main/webapp/javascript/rudder/rudder.js
  rudder-web/src/main/webapp/secure/administration/policyServerManagement.html
  rudder-web/src/main/webapp/secure/nodeManager/searchNodes.html
  rudder-web/src/main/webapp/secure/utilities/eventLogs.html
  rudder-web/src/main/webapp/style/bootstrap/tw-bs-bootstrap-3.3.7.css
  rudder-web/src/main/webapp/style/jquery-ui/jquery-ui.min.css
  rudder-web/src/main/webapp/style/jquery-ui/jquery-ui.structure.min.css
  rudder-web/src/main/webapp/style/jquery-ui/jquery-ui.theme.min.css
  rudder-web/src/main/webapp/style/rudder/rudder-groups.css
  rudder-web/src/main/webapp/style/rudder/rudder-jquery-ui.css
  rudder-web/src/main/webapp/style/rudder/rudder-menu.css
  rudder-web/src/main/webapp/style/rudder/rudder.css
  rudder-web/src/main/webapp/templates-hidden/common-layout.html
  rudder-web/src/main/webapp/templates-hidden/components/ComponentAgentPolicyMode.html
  rudder-web/src/main/webapp/templates-hidden/components/ComponentAgentSchedule.html
  rudder-web/src/main/webapp/templates-hidden/components/ComponentComplianceMode.html
  rudder-web/src/main/webapp/templates-hidden/node_logs_tabs.html
  rudder-web/src/main/webapp/templates-hidden/server/server_details.html
Labels: Ready for merge

#2108 Fixes #14107: Syntax error in migration script
  rudder-core/src/main/resources/Migration/dbMigration-4.3.x-4.3.8-correct-indexes-on-compliancelevel.sql
Labels: Ready for merge

#2110 Fixes #14119: Compilation error on 5.0 after generation flag feature
  rudder-web/src/main/scala/bootstrap/liftweb/checks/TriggerPolicyUpdate.scala
Labels: Ready for merge

#2112 Fixes #10973: When hooks are exiting an error we can have stackoverfloww error if there are many of them
  rudder-core/src/main/scala/com/normation/rudder/services/policies/DeploymentService.scala
  rudder-core/src/main/scala/com/normation/rudder/services/policies/write/Cf3PromisesFileWriterService.scala
Labels: qa: Can't merge

#2096 Fixes #4904: When refreshing a rule details, the current tab is not memorized
  rudder-web/src/main/scala/com/normation/rudder/web/components/RuleEditForm.scala
  rudder-web/src/main/scala/com/normation/rudder/web/components/RuleGrid.scala
  rudder-web/src/main/scala/com/normation/rudder/web/components/popup/CreateRulePopup.scala
  rudder-web/src/main/scala/com/normation/rudder/web/snippet/configuration/RuleManagement.scala
  rudder-web/src/main/webapp/javascript/rudder/rudder-datatable.js
Labels: qa: Can't merge

#2116 Fixes #14205: Update links in Rudder interface
  rudder-web/src/main/webapp/index.html
Labels: qa: Can't merge

#2118 Fixes #14212: In technique editor, ncf index is cached which defeats #14194 correction on migration
  rudder-web/src/main/scala/com/normation/rudder/web/snippet/WithCachedResource.scala
  rudder-web/src/main/webapp/secure/utilities/techniqueEditor.html
Labels: qa: Can't merge

#2120 Fixes #14219: A var, leading to compilation error, was introduced
  rudder-web/src/main/scala/com/normation/rudder/web/components/popup/CreateRulePopup.scala
Labels: qa: Can't merge

#2122 Fixes #14221: (un)escape html entities where needed
  rudder-web/src/main/scala/com/normation/rudder/web/services/JsTableData.scala
  rudder-web/src/main/scala/com/normation/rudder/web/services/LogDisplayer.scala
  rudder-web/src/main/webapp/javascript/rudder/rudder-datatable.js
Labels: qa: Can't merge

#2123 Fixes #14231:
  rudder-web/src/main/scala/com/normation/rudder/web/snippet/administration/ChangeRequestManagement.scala
Labels: qa: Can't merge

#2127 Fixes #14245: Error when creating a rule
  rudder-web/src/main/scala/com/normation/rudder/web/snippet/configuration/RuleManagement.scala
Labels: Ready for merge, qa: Can't merge

#2129 Fixes #14248: Duplicate dependency "jsr305" in rudder-core/pom.xml
  rudder-core/pom.xml
Labels: Ready for merge, qa: Can't merge

#2128 Fixes #14247: Update very old maven-assembly version used for template-cli
  rudder-templates-cli/pom.xml
Labels: Ready for merge
