Repository Normation/rudder, pull requests merged in 2019-08, with the labels that each got.

#2357 Fixes #15372: Missing logs on NodeCompliance archive/deletion
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/jdbc/ExpectedReportsJdbcRepository.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/jdbc/ReportsJdbcRepository.scala
Labels: qa: Can't merge

#2364 Fixes #15384: Relayd service is not loaded
  relay/sources/rudder-server-relay-postinst
Labels: qa: Can't merge

#2363 Fixes #15383: Unhandled error if the LDAP connection is unavailable
  webapp/sources/pom.xml
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/cfclerk/services/impl/GitTechniqueReader.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/batch/CheckInventoryUpdate.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/ClearCacheService.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/reports/NodeChangesService.scala
  webapp/sources/scala-ldap/src/main/scala/com/normation/ldap/listener/InMemoryDsConnectionProvider.scala
  webapp/sources/scala-ldap/src/main/scala/com/normation/ldap/sdk/LDAPConnectionProvider.scala
  webapp/sources/scala-ldap/src/main/scala/com/normation/ldap/sdk/LDAPIOResult.scala
Labels: qa: Can't merge

#2366 Fixes #15387: Clean-up Jetty abort on boot
  webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/Boot.scala
  webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/LiftInitContextListener.scala
  webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala
  webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/ThrowIllegalAccessException.java
Labels: qa: Can't merge

#2372 Fixes #15405: Only treat file with report extension in relayd
  relay/sources/relayd/src/processing.rs
Labels: qa: Can't merge

#2374 Fixes #3112: Allow to get informations from the node inventory to use them in Directives and ncf techniques
  webapp/sources/ldap-inventory/inventory-api/src/main/scala/com/normation/inventory/domain/MachineInventory.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/cfclerk/services/impl/SystemVariableSpecServiceImpl.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/SystemVariableService.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/write/PolicyWriterService.scala
Labels: qa: Can't merge

#2383 Fixes #15435: Forward reports to upper relays in relayd
  relay/sources/relayd/Cargo.lock
  relay/sources/relayd/src/configuration/logging.rs
  relay/sources/relayd/src/configuration/main.rs
  relay/sources/relayd/src/data/report.rs
  relay/sources/relayd/src/error.rs
  relay/sources/relayd/src/input/watch.rs
  relay/sources/relayd/src/lib.rs
  relay/sources/relayd/src/output.rs
  relay/sources/relayd/src/output/database.rs
  relay/sources/relayd/src/output/upstream.rs
  relay/sources/relayd/src/processing.rs
  relay/sources/relayd/src/processing/reporting.rs
  relay/sources/relayd/tests/files/config/logging.conf
  relay/sources/relayd/tests/files/config/main.conf
  relay/sources/relayd/tests/test_simple/config/logging.conf
  relay/sources/relayd/tests/test_simple/config/main.conf
  relay/sources/relayd/tools/config/main.conf
Labels: qa: Can't merge

#2235 Fixes #14943: Move rudder-pkg to rudder repo
  qa-test
  relay/sources/Makefile
  relay/sources/rudder-pkg
  relay/sources/rudder-pkg/lib/docopt.py
  relay/sources/rudder-pkg/lib/rudder-pkg/plugin.py
  relay/sources/rudder-pkg/lib/rudder-pkg/rpkg.py
  relay/sources/rudder-pkg/lib/rudder-pkg/rudderPkg.py
  relay/sources/rudder-pkg/lib/rudder-pkg/rudderPkgUtils.py
  relay/sources/rudder-pkg/lib/rudder-pkg/tests/test.py
  relay/sources/rudder-pkg/lib/rudder-pkg/tests/testall
  relay/sources/rudder-pkg/makeIndex.sh
  relay/sources/rudder-pkg/rudder-pkg
  relay/sources/rudder-pkg/rudder-pkg.conf
  relay/sources/rudder-pkg/rudder_apt_key.pub
  relay/sources/rudder-server-relay-postinst
Labels: Ready for merge

#2387 Fixes #15467: Remove \r in reports in relayd
  relay/sources/Makefile
  relay/sources/relayd/Cargo.lock
  relay/sources/relayd/src/data/report.rs
  relay/sources/relayd/src/output/database.rs
Labels: qa: Can't merge

#2390 Fixes #15476: rudder-pkg does not install properly
  relay/sources/Makefile
  relay/sources/rudder-pkg/rudder-pkg.conf
  relay/sources/rudder-pkg/rudder_apt_key.pub
  relay/sources/rudder-server-relay-postinst
Labels: qa: Can't merge

#2395 Fixes #15477: Make rudder-pkg handle confiparser in python 2 and 3
  relay/sources/rudder-pkg/lib/rudder-pkg/rudderPkg.py
  relay/sources/rudder-pkg/lib/rudder-pkg/rudderPkgUtils.py
Labels: Ready for merge

#2404 Fixes #15497: Add inventory forwarding on relays in relayd
  relay/sources/relayd/Cargo.lock
  relay/sources/relayd/src/api.rs
  relay/sources/relayd/src/lib.rs
  relay/sources/relayd/src/output/database.rs
  relay/sources/relayd/src/output/upstream.rs
  relay/sources/relayd/src/processing.rs
  relay/sources/relayd/src/processing/inventory.rs
  relay/sources/relayd/src/processing/reporting.rs
  relay/sources/relayd/src/shared_files.rs
Labels: qa: Can't merge

#2406 Fixes #15502: Add autocompletion to rudder-pkg
  relay/sources/Makefile
  relay/sources/rudder-pkg/rudder-pkg
  relay/sources/rudder-server-relay-postinst
Labels: qa: Can't merge

#2410 Fixes #15529: Add autocompletion to rudder-pkg
  relay/sources/Makefile
Labels: qa: Can't merge

#2408 Arch 15521/add hardening config in relayd systemd unit
  relay/sources/Makefile
  relay/sources/rudder-relay.sudo
  relay/sources/rudder-server-relay-postinst
  relay/sources/systemd/rudder-relayd-hardening
  relay/sources/systemd/rudder-relayd.service
Labels: qa: Can't merge

#2420 Fixes #15555: Missing directories in relay install target
  relay/sources/Makefile
Labels: qa: Can't merge

#2423 Fixes #15567: rudder-pkg command in /opt/rudder/bin should not be created in postinst but at build time
  relay/sources/Makefile
  relay/sources/rudder-server-relay-postinst
Labels: qa: Can't merge

#2429 Fixes #2613: Problem when updating a category name for Technique Management in /var/rudder
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/cfclerk/services/TechniqueLibraryUpdateNotification.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/cfclerk/services/impl/TechniqueRepositoryImpl.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/TechniqueAcceptationDatetimeUpdater.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/TechniqueReloadingCallbacks.scala
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/services/TechniqueReloadingCallbacks.scala
Labels: qa: Can't merge

#2428 Fixes #15575: Avoid duplicating technique category when changing category name
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/TechniqueAcceptationDatetimeUpdater.scala
Labels: qa: Can't merge

#2347 Fixes #9445: If we filter event logs with only a start or end date, we get a super ugly error
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/services/EventListDisplayer.scala
  webapp/sources/rudder/rudder-web/src/main/webapp/secure/utilities/eventLogs.html
Labels: qa: Can't merge

#2422 Fixes #15556: List all plugin in plugin status page
  webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/Boot.scala
  webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/plugins/RudderPluginJson.scala
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/administration/PluginManagement.scala
  webapp/sources/rudder/rudder-web/src/test/scala/com/normation/plugins/RudderPluginJsonTest.scala
Labels: qa: Can't merge

#2431 Fixes #15423: Filtering tags with more than one tag with same "key" did not return correct results
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/services/DisplayDirectiveTree.scala
  webapp/sources/rudder/rudder-web/src/main/webapp/javascript/rudder/angular/filters.js
  webapp/sources/rudder/rudder-web/src/main/webapp/javascript/rudder/angular/tags.js
  webapp/sources/rudder/rudder-web/src/main/webapp/javascript/rudder/tree-tag-plugin.js
  webapp/sources/rudder/rudder-web/src/main/webapp/templates-hidden/components/ComponentTags.html
Labels: Ready for merge, qa: Can't merge

#2432 Fixes #15419: Tags are not properly set when changing only value field before new insertion
  webapp/sources/rudder/rudder-web/src/main/webapp/javascript/rudder/angular/tags.js
Labels: Ready for merge

#2434 Fixes #15590: Renaming/moving technique category fails in several way
  webapp/sources/ldap-inventory/inventory-api/src/main/scala/com/normation/inventory/domain/MachineInventory.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/cfclerk/services/TechniqueLibraryUpdateNotification.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/cfclerk/services/TechniqueRepository.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/cfclerk/services/impl/TechniqueRepositoryImpl.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/RudderDit.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/DirectiveRepository.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/ldap/LDAPDirectiveRepository.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/DeploymentService.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/TechniqueAcceptationDatetimeUpdater.scala
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/cfclerk/services/DummyTechniqueRepository.scala
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/cfclerk/services/TechniqueRepositoryTest.scala
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/services/EventListDisplayer.scala
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/administration/TechniqueLibraryManagement.scala
Labels: Ready for merge, qa: Can't merge
