Repository Normation/rudder, pull requests merged in 2019-02, with the labels that each got.

#2130 Fixes #10773: Rounding error in compliance bar
  rudder-core/src/main/scala/com/normation/rudder/domain/reports/ComplianceLevel.scala
  rudder-web/src/main/webapp/javascript/rudder/rudder-datatable.js
  rudder-web/src/main/webapp/style/rudder/rudder.css
Labels: qa: Can't merge

#2132 Fixes #14272: Sort by compliance broken
  rudder-web/src/main/webapp/javascript/rudder/rudder-datatable.js
Labels: Ready for merge

#2133 Fixes #14273: Bad rights for hooks
  qa-test
  rudder-core/src/main/resources/hooks.d/policy-generation-node-ready/10-cf-promise-check
  rudder-core/src/main/resources/hooks.d/policy-generation-node-ready/90-change-perm
Labels: qa: Can't merge

#2134 Fixes #13962: Mandatory fields in the Inventory are not correctly checked during consistency check
  webapp/sources/ldap-inventory/inventory-fusion/src/main/scala/com/normation/inventory/provisioning/fusion/PostUnmarshallCheckConsistency.scala
  webapp/sources/ldap-inventory/inventory-fusion/src/test/resources/fusion-report/windows2016-incomplete.ocs
  webapp/sources/ldap-inventory/inventory-fusion/src/test/scala/com/normation/inventory/provisioning/fusion/TestReportParsing.scala
Labels: qa: Can't merge

#2136 Fixes #14290: Compilation fails with Java 11
  webapp/sources/rudder-parent-pom/pom.xml
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/db/Doobie.scala
Labels: Ready for merge, qa: Can't merge

#2138 Fixes #14054: Remove red button code from rudder
  webapp/sources/ldap-inventory/inventory-provisioning-web/src/main/scala/com/normation/inventory/provisioning/endpoint/InventoryFileWatcher.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/system/StartStopOrchestrator.scala
  webapp/sources/rudder/rudder-web/src/main/resources/configuration.properties.sample
  webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/RuleEditForm.scala
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/EmergencyStop.scala
Labels: Ready for merge

#2137 Fixes #14291: Remove deprecated (and not use) code causing warning
  webapp/sources/scala-ldap/src/main/scala/com/normation/ldap/sdk/LDAPEntry.scala
  webapp/sources/scala-ldap/src/main/scala/com/normation/ldap/sdk/LDAPTree.scala
Labels: Ready for merge
