Repository Normation/rudder, pull requests merged in 2020-05, with the labels that each got.

#2941 Fixes #17290: RuleID is not trimmed when copied from the GUI
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/RuleCompliance.scala
  webapp/sources/rudder/rudder-web/src/main/webapp/templates-hidden/components/ComponentRuleEditForm.html
Labels: qa: Can't merge

#2947 Fixes #17324: Group properties inheritance error when it should not
  webapp/sources/pom.xml
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/nodes/MergeNodeProperties.scala
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/nodes/TestMergeGroupProperties.scala
  webapp/sources/rudder/rudder-web/src/main/webapp/templates-hidden/components/ComponentNodeProperties.html
Labels: Ready for merge

#2951 Fixes #17334: Property name aren't limited to ascii
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/nodes/NodeGroup.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/ldap/LDAPDiffMapper.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/ldap/LDAPEntityMapper.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/InterpolatedValueCompiler.scala
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/policies/TestNodeAndGlobalParameterLookup.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/RestExtractorService.scala
Labels: qa: Can't merge

#2953 Fixes #17227: Prevent removal of 'system' global and group properties
  webapp/sources/rudder/rudder-core/src/main/resources/ldap/bootstrap.ldif
  webapp/sources/rudder/rudder-core/src/main/resources/ldap/rudder.schema
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/RudderDit.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/RudderLDAPConstants.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/nodes/Node.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/nodes/NodeGroup.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/nodes/Properties.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/parameters/GlobalParameter.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/parameters/ParameterDiff.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/workflows/ChangeRequest.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/ItemArchiveManager.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/ParameterRepository.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/ldap/LDAPDiffMapper.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/ldap/LDAPEntityMapper.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/ldap/LDAPParameterRepository.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/xml/GitArchiverImpl.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/eventlog/EventLogDetailsService.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/eventlog/EventLogFactory.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/marshalling/XmlSerialisation.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/marshalling/XmlSerialisationImpl.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/marshalling/XmlUnserialisation.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/marshalling/XmlUnserialisationImpl.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/nodes/MergeNodeProperties.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/nodes/NodePropertiesOverridingService.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/nodes/NodePropertiesProviderInfo.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/DataStructures.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/DeploymentService.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/InterpolatedValueCompiler.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/ParameterService.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/write/PolicyWriterService.scala
  webapp/sources/rudder/rudder-core/src/test/resources/ldap-data/schema/099-1-rudder.ldif
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/domain/nodes/NodePropertiesTest.scala
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/nodes/TestMergeGroupProperties.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/RestDataSerializer.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/RestExtractorService.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/data/NodeDetailLevel.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/data/RestData.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/internal/RestQuicksearch.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/GroupsApi.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/ParametersApi.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/web/model/JsInitContextLinkUtil.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/web/services/EventLogDetailsGenerator.scala
  webapp/sources/rudder/rudder-web/src/main/resources/rudder-system-global-parameter.conf
  webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/checks/CheckRudderGlobalParameter.scala
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/popup/CreateOrUpdateGlobalParameterPopup.scala
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/configuration/ParameterManagement.scala
Labels: qa: Can't merge

#2966 Fixes #17372: Historization of node count reports wrong value for pending nodes
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/metrics/HistorizeNodeCountService.scala
Labels: Ready for merge

#2964 Fixes #17373: duplicates entries when saving node compliance levels
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/reports/ReportingServiceImpl.scala
Labels: Ready for merge

#2967 Fixes #17383: Improve notification display in Rudder
  webapp/sources/rudder/rudder-web/src/main/elm/notifications/build-dev.sh
  webapp/sources/rudder/rudder-web/src/main/elm/notifications/sources/rudder-notifications.elm
  webapp/sources/rudder/rudder-web/src/main/webapp/javascript/rudder/rudder-elm.js
  webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-notifications.css
Labels: Ready for merge

#2939 Fixes #17289: add contributing documentation
  rudder-lang/docs/contributing.adoc
  rudder-lang/docs/resources/compilation-process-1.svg
  rudder-lang/docs/resources/compilation-process-2.svg
  rudder-lang/docs/resources/compile.svg
  rudder-lang/docs/resources/generate-lib.svg
  rudder-lang/docs/resources/io-file-formats.svg
  rudder-lang/docs/resources/rudderc.svg
  rudder-lang/docs/resources/test-loop.svg
  rudder-lang/docs/resources/translate.svg
Labels: Ready for merge

#2970 Fixes #17396: err17: can not update attribute in parameter
  webapp/sources/rudder/rudder-core/src/main/resources/ldap/rudder.schema
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/ldap/LDAPDiffMapper.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/ldap/LDAPParameterRepository.scala
Labels: Ready for merge

#2971 Fixes #17405: fix compilation failure
  rudder-lang/src/ast.rs
Labels: Ready for merge

#2968 Fixes #17384: Update relayd dependencies to remove unmaintained "spin" crate
  relay/sources/relayd/Cargo.lock
Labels: Ready for merge

#2976 Fixes #17412: Add a feature switch for rudder-lang test loop
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/ncf/TechniqueWriter.scala
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/ncf/TestTechniqueWriter.scala
  webapp/sources/rudder/rudder-web/src/main/resources/configuration.properties.sample
  webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala
Labels: Ready for merge

#2975 Fixes #17411: Stacktrace in test introduce in #17341
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/reports/CachedFindRuleNodeStatusReportsTest.scala
Labels: Ready for merge

#2977 Fixes #17416: Inventories from new nodes should be sent using the "rudder" password and not generated one
  relay/sources/relayd/src/configuration/main.rs
  relay/sources/relayd/src/output/upstream.rs
  relay/sources/relayd/tests/files/config/main.conf
  relay/sources/relayd/tools/config/main.conf
Labels: Ready for merge

#2973 Fixes #17325: We can't choose between string and json for global parameters
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/DirectiveEditForm.scala
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/popup/CreateOrUpdateGlobalParameterPopup.scala
  webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-directives.css
  webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-menu.css
Labels: Ready for merge

#2981 Fixes #17434: Missing validated user endpoints in change validation api doc
  webapp/sources/api-doc/code_samples/curl/change-requests/remove-valid-users.sh
  webapp/sources/api-doc/code_samples/curl/change-requests/update-valid-users.sh
  webapp/sources/api-doc/code_samples/curl/change-requests/valid-users.sh
  webapp/sources/api-doc/components/schemas/validated-user.yml
  webapp/sources/api-doc/openapi.src.yml
  webapp/sources/api-doc/paths/change-requests/remove-valid-users.yml
  webapp/sources/api-doc/paths/change-requests/update-valid-users.yml
  webapp/sources/api-doc/paths/change-requests/valid-users.yml
Labels: Ready for merge

#2980 Fixes #17427: Separate System Rules from USer Defined Rules in Node compliance display
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/reports/ReportingService.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/reports/ReportingServiceImpl.scala
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/repository/jdbc/ReportingServiceTest.scala
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/reports/CachedFindRuleNodeStatusReportsTest.scala
  webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/ShowNodeDetailsFromNode.scala
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/services/AsyncComplianceService.scala
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/services/ReportDisplayer.scala
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/services/SrvGrid.scala
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/node/Node.scala
  webapp/sources/rudder/rudder-web/src/main/webapp/javascript/rudder/rudder-datatable.js
  webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-bootstrap.css
  webapp/sources/rudder/rudder-web/src/main/webapp/templates-hidden/server/server_details.html
Labels: Ready for merge, qa: Can't merge

#2937 Fixes #17252: translate should not use hardcoded path for libraries
  rudder-lang/src/bin/rudderc.rs
  rudder-lang/src/compile.rs
  rudder-lang/src/generators.rs
  rudder-lang/src/parser.rs
  rudder-lang/src/translate.rs
Labels: qa: Can't merge

#2984 Fixes #17441: Ignored node lead to an error log during generation
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/RuleValService.scala
Labels: Ready for merge

#2979 Fixes #17426: Use hocon as an internal format for node properties
  webapp/sources/rudder/rudder-core/pom.xml
  webapp/sources/rudder/rudder-core/src/main/resources/ldap/rudder.schema
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/nodes/Properties.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/parameters/GlobalParameter.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/parameters/ParameterDiff.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/queries/CmdbQuery.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/metrics/HistorizeNodeCountService.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/ldap/LDAPDiffMapper.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/ldap/LDAPEntityMapper.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/ldap/LDAPParameterRepository.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/eventlog/EventLogDetailsService.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/eventlog/EventLogFactory.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/marshalling/XmlSerialisationImpl.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/marshalling/XmlUnserialisationImpl.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/nodes/MergeNodeProperties.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/nodes/NodePropertiesOverridingService.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/DataStructures.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/DeploymentService.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/InterpolatedValueCompiler.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/reports/ReportingServiceImpl.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/workflows/CommitAndDeployChangeRequestService.scala
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/domain/nodes/GenericPropertiesTest.scala
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/domain/nodes/NodePropertiesTest.scala
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/eventlog/NodeEventLogFormatV6Test.scala
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/nodes/TestMergeGroupProperties.scala
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/policies/TestNodeAndGlobalParameterLookup.scala
  webapp/sources/rudder/rudder-rest/pom.xml
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/RestDataSerializer.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/RestExtractorService.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/data/RestData.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/ParametersApi.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/web/services/EventLogDetailsGenerator.scala
  webapp/sources/rudder/rudder-web/pom.xml
  webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/checks/CheckRudderGlobalParameter.scala
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/popup/CreateOrUpdateGlobalParameterPopup.scala
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/configuration/ParameterManagement.scala
  webapp/sources/utils/src/main/scala/com/normation/ZioCommons.scala
Labels: Ready for merge

#2915 Fixes #17191: add debug to makefile
  rust.makefile
Labels: Ready for merge

#2982 Fixes #15422: Some inventories are not correctly noticed by inotify file watcher
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/inventory/InventoryFileWatcher.scala
  webapp/sources/rudder/rudder-web/src/main/resources/configuration.properties.sample
  webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala
Labels: Ready for merge, qa: Can't merge

#2991 Fixes #17458: Ignore invalid hash in nodeslist
  relay/sources/relayd/src/data/node.rs
  relay/sources/relayd/src/hashing.rs
  relay/sources/relayd/tests/files/nodeslist.json
Labels: qa: Can't merge

#2996 Fixes #17482: Webapp block at start on inventory processing
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/inventory/InventoryFileWatcher.scala
  webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/Boot.scala
  webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/NodeGroupForm.scala
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/services/DisplayNode.scala
Labels: qa: Can't merge

#2911 Fixes #17176: Purge of unreferenced software may still fail on very large system
  webapp/sources/ldap-inventory/inventory-repository/src/main/scala/com/normation/inventory/ldap/core/ReadOnlySoftwareInventoryDAOImpl.scala
Labels: qa: Can't merge

#2995 Fixes #14697: Strip rust release binaries
  rust.makefile
Labels: qa: Can't merge

#3002 Fixes #17457: Parameters are not restored from archive
  webapp/sources/api-doc/code_samples/curl/system/get-archive-zip.sh
  webapp/sources/api-doc/code_samples/curl/system/restore-archive.sh
  webapp/sources/api-doc/components/parameters/archive-kind.yml
  webapp/sources/api-doc/openapi.src.yml
  webapp/sources/api-doc/paths/system/archives-restore.yml
  webapp/sources/api-doc/paths/system/archives-zip.yml
  webapp/sources/api-doc/paths/system/archives.yml
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/cfclerk/xmlparsers/VariableSpecParser.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/ItemArchiveManager.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/ldap/LDAPParameterRepository.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/xml/ItemArchiveManagerImpl.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/marshalling/XmlUnserialisationImpl.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/EndpointsDefinition.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/SystemApi.scala
  webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/administration/Archives.scala
  webapp/sources/rudder/rudder-web/src/main/webapp/secure/utilities/archiveManagement.html
Labels: qa: Can't merge

#3009 Fixes #17521: A repaired in system policies should not be seen as a problem for warning display in nodes list
  webapp/sources/rudder/rudder-web/src/main/webapp/javascript/rudder/rudder-datatable.js
Labels: qa: Can't merge

#3007 Fixes #17507: inventory watcher should ignore uuid.hive file
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/inventory/InventoryFileWatcher.scala
Labels: qa: Can't merge

#3012 Fixes #17525: remove progressive output from postinstall
  relay/sources/rudder-pkg/lib/rudder-pkg/rudderPkg.py
  relay/sources/rudder-pkg/lib/rudder-pkg/rudderPkgUtils.py
  relay/sources/rudder-pkg/rudder-pkg
  relay/sources/rudder-server-relay-postinst
Labels: qa: Can't merge

#3013 Fixes #17527: When no User rules are defined on a node, compliance tab on node details shows an error
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/logger/DebugComplianceLogger.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/reports/StatusReports.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/jdbc/ComplianceRepository.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/reports/ExecutionBatch.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/reports/ReportingServiceImpl.scala
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/services/ReportDisplayer.scala
Labels: qa: Can't merge

#3017 Fixes #17523: error when a technique with a directive attached change in 6.1 blocks all technique updates
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/TechniqueAcceptationDatetimeUpdater.scala
Labels: Ready for merge

#3006 Fixes #15557: When adding tags, if anything is wrong in the directive form, all unsaved tags are wiped out
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/DirectiveEditForm.scala
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/RuleCompliance.scala
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/RuleEditForm.scala
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/TagsEditForm.scala
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/configuration/DirectiveManagement.scala
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/configuration/RuleManagement.scala
  webapp/sources/rudder/rudder-web/src/main/webapp/javascript/rudder/angular/tags.js
Labels: qa: Can't merge

#3021 Fixes #17546: z-index of group property inherited tooltip is bad
  webapp/sources/rudder/rudder-web/src/main/webapp/templates-hidden/components/ComponentNodeProperties.html
Labels: qa: Can't merge
