Repository Normation/rudder, pull requests merged in 2020-11, with the labels that each got.

#3313 Fixes #18457: Typo in API doc
  webapp/sources/api-doc/paths/nodes/apply-policy.yml
Labels: Ready for merge, Trigger test

#3316 Fixes #18462: Compliance does not show up if you don't click on refresh
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/reports/ReportingService.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/reports/ReportingServiceImpl.scala
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/repository/jdbc/ReportingServiceTest.scala
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/reports/CachedFindRuleNodeStatusReportsTest.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/NodeApi.scala
  webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/services/SrvGrid.scala
  webapp/sources/rudder/rudder-web/src/main/webapp/javascript/rudder/rudder-datatable.js
Labels: qa: Can't merge

#3320 Fixes #18468: fix makefile test
  rudder-lang/src/bin/rudderc.rs
  rudder-lang/src/io/output.rs
  rudder-lang/tests/techniques/simplest/technique.cf
  rudder-lang/tests/techniques/simplest/technique.json
Labels: Ready for merge

#3323 Fixes #18476: Store columns used in localstorage in nodes list
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/NodeApi.scala
  webapp/sources/rudder/rudder-web/src/main/webapp/javascript/rudder/rudder-datatable.js
Labels: qa: Can't merge

#3325 Fixes #18477: Improve health check texts
  webapp/sources/api-doc/openapi.src.yml
  webapp/sources/api-doc/paths/healthcheck/all.yml
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/healthcheck/HealthcheckService.scala
  webapp/sources/rudder/rudder-web/src/main/elm/healthcheck/sources/View.elm
  webapp/sources/rudder/rudder-web/src/main/webapp/secure/utilities/healthcheck.html
Labels: Trigger test, qa: Can't merge

#3326 Fixes #18480: Check parition should check the lowest space available first
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/healthcheck/HealthcheckService.scala
Labels: Trigger test

#3330 Fixes #18483: Documentation for /nodes/status page
  webapp/sources/api-doc/code_samples/curl/nodes/status.sh
  webapp/sources/api-doc/paths/nodes/status.yml
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/NodeApi.scala
Labels: Trigger test, qa: Can't merge

#3334 Fixes #18497: Broken report parser on some info messages
  relay/sources/relayd/src/data/report.rs
Labels: Trigger test, qa: Can't merge

#3331 Fixes #18495: Add a reset columns button and some guard on localstorage cache
  webapp/sources/rudder/rudder-web/src/main/webapp/javascript/rudder/rudder-datatable.js
Labels: Ready for merge, qa: Can't merge

#3335 Fixes #18466: Inherited node prop arrays are replaced not merged contrary to doc
  webapp/sources/rudder/rudder-core/src/main/resources/ldap/rudder.schema
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/RudderLDAPConstants.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/nodes/Properties.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/parameters/GlobalParameter.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/parameters/ParameterDiff.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/ldap/LDAPDiffMapper.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/ldap/LDAPEntityMapper.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/eventlog/EventLogDetailsService.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/marshalling/XmlSerialisationImpl.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/marshalling/XmlUnserialisationImpl.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/nodes/MergeNodeProperties.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/DeploymentService.scala
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/domain/nodes/GenericPropertiesTest.scala
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/domain/nodes/NodePropertiesTest.scala
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/repository/ldap/GlobalParamMigration61Test.scala
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/eventlog/NodeEventLogFormatV6Test.scala
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/nodes/TestMergeGroupProperties.scala
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/policies/TestNodeAndGlobalParameterLookup.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/RestExtractorService.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/data/RestData.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/GroupsApi.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/NodeApi.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/ParametersApi.scala
  webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/checks/CheckRudderGlobalParameter.scala
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/popup/CreateOrUpdateGlobalParameterPopup.scala
Labels: Trigger test

#3342 Fixes #18515: Parent breaks build
  webapp/sources/api-doc/components/parameters/node-ids.yml
  webapp/sources/api-doc/paths/nodes/status.yml
Labels: Trigger test, qa: Can't merge

#3333 Fixes #18482: Move health check API in /system/
  webapp/sources/api-doc/code_samples/curl/healthcheck/all.sh
  webapp/sources/api-doc/code_samples/curl/system/healthcheck.sh
  webapp/sources/api-doc/openapi.src.yml
  webapp/sources/api-doc/paths/system/healthcheck.yml
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/EndpointsDefinition.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/RoleApiMapping.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/HealthcheckApi.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/SystemApi.scala
  webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/rest/RestTestSetUp.scala
  webapp/sources/rudder/rudder-web/src/main/elm/healthcheck/sources/ApiCalls.elm
  webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala
Labels: Trigger test

#3322 Fixes #18474: Width of the Directive tree changes according to the selected Directive.
  webapp/sources/rudder/rudder-web/src/main/webapp/secure/utilities/healthcheck.html
  webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-healthcheck.css
  webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-menu.css
  webapp/sources/rudder/rudder-web/src/main/webapp/templates-hidden/common-layout.html
Labels: Trigger test

#3341 Fixes #18498: after editing columns in the group or serach node page, there's a JS error when doing a search
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/services/SrvGrid.scala
  webapp/sources/rudder/rudder-web/src/main/webapp/javascript/rudder/rudder-datatable.js
Labels: qa: Can't merge

#3345 Fixes #18528: ifTrace/Debug/etcIsEnabled on pure logger does nothings
  webapp/sources/utils/src/main/scala/com/normation/ZioCommons.scala
Labels: Trigger test, qa: Can't merge

#3346 Fixes #18529: If LDAP server does not support subtree deletion, we get error when entry does not exists
  webapp/sources/scala-ldap/src/main/scala/com/normation/ldap/sdk/LDAPConnection.scala
Labels: Trigger test, qa: Can't merge

#3350 Fixes #18535: test broken because of parent ticket
  webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/rest/RestTestSetUp.scala
Labels: Ready for merge

#3351 Fixes #18534: Skip non-standard moint FS for free-space check
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/healthcheck/HealthcheckService.scala
Labels: Trigger test

#3353 Fixes #18437: Too many open files in relayd when disk is full
  relay/sources/relayd/Cargo.lock
Labels: Trigger test, qa: Can't merge

#3354 Fixes #18540: Healthcheck checks happen to often
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/healthcheck/HealthcheckNotificationService.scala
  webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/Boot.scala
  webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala
Labels: Trigger test

#3348 Fixes #18530: We don't know which hook timeout when it happens
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/hooks/RunHooks.scala
  webapp/sources/rudder/rudder-core/src/test/resources/hooks.d/test/timeout.sh
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/hooks/HooksTest.scala
Labels: Trigger test, qa: Can't merge

#3367 Fixes #16773: Batch of new nodes can overflow rudder server with inventories
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/inventory/InventoryFileWatcher.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/inventory/InventoryProcessor.scala
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/inventory/TestCertificate.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/InventoryApi.scala
  webapp/sources/rudder/rudder-web/src/main/resources/configuration.properties.sample
Labels: Trigger test, qa: Can't merge

#3369 Fixes #18574: Light in healthcheck notif are not displayed
  webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-menu.css
Labels: Trigger test

#3360 Fixes #18563: Skip performance test
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/domain/reports/StatusReportTest.scala
Labels: qa: Can't merge

#3364 Fixes #18508: Missing a PATCH API for allowed networks
  webapp/sources/api-doc/code_samples/curl/settings/get-allowed-networks.sh
  webapp/sources/api-doc/code_samples/curl/settings/set-allowed-networks-diff.sh
  webapp/sources/api-doc/code_samples/curl/settings/set-allowed-networks.sh
  webapp/sources/api-doc/components/parameters/setting-allowed-networks.yml
  webapp/sources/api-doc/openapi.src.yml
  webapp/sources/api-doc/paths/settings/allowed_networks.yml
  webapp/sources/api-doc/paths/settings/allowed_networks_diff.yml
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/batch/AbstractScheduler.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/servers/PolicyServerManagementService.scala
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/policies/NodeConfigData.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/EndpointsDefinition.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/SettingsApi.scala
Labels: Trigger test, qa: Can't merge

#3377 Fixes #18591: Rename "Server" node list column to "Policy server"
  webapp/sources/rudder/rudder-web/src/main/webapp/javascript/rudder/rudder-datatable.js
Labels: Trigger test, qa: Can't merge

#3347 Fixes #18035: API to totally erase a node everywhere
  webapp/sources/api-doc/paths/nodes/id.yml
  webapp/sources/pom.xml
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/logger/ApplicationLogger.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/ExpectedReportsRepository.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/NodeGroupRepository.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/jdbc/ExpectedReportsJdbcRepository.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/ldap/LDAPNodeGroupRepository.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/ldap/Lock.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/nodes/NodeInfoService.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/servers/PolicyServerManagementService.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/servers/RemoveNodeService.scala
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/repository/jdbc/ReportingServiceTest.scala
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/policies/NodeConfigData.scala
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/reports/CachedFindRuleNodeStatusReportsTest.scala
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/servers/TestRemoveNodeService.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/NodeApi.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/SettingsApi.scala
  webapp/sources/rudder/rudder-web/src/main/resources/configuration.properties.sample
  webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/services/DisplayNode.scala
Labels: Ready for merge, Trigger test, qa: Can't merge

#3376 Fixes #18590: Rename node menu entries for consistency
  webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/Boot.scala
  webapp/sources/rudder/rudder-web/src/main/webapp/secure/nodeManager/manageNewNode.html
Labels: Trigger test, qa: Can't merge

#3390 Fixes #18622: Bad file name in api-doc: some more errors
  webapp/sources/api-doc/components/parameters/node-delete-mode.yml
  webapp/sources/api-doc/paths/nodes/id.yml
  webapp/sources/api-doc/paths/settings/allowed_networks_diff.yml
Labels: Trigger test, qa: Can't merge

#3373 Fixes #18584: semaphore gurading LDAP repos are created each time
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/ldap/LDAPNodeGroupRepository.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/ldap/LDAPNodeRepository.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/ldap/LDAPParameterRepository.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/ldap/LDAPRuleRepository.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/ldap/Lock.scala
  webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala
Labels: Ready for merge, Trigger test, qa: Can't merge

#3393 Fixes #18629: Inherited mode is not returned in API
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/nodes/TestMergeGroupProperties.scala
Labels: Ready for merge

#3394 Fixes #18424: Beautify Nodes page
  webapp/sources/rudder/rudder-web/src/main/webapp/secure/administration/apiManagement.html
  webapp/sources/rudder/rudder-web/src/main/webapp/secure/administration/databaseManagement.html
  webapp/sources/rudder/rudder-web/src/main/webapp/secure/administration/policyServerManagement.html
  webapp/sources/rudder/rudder-web/src/main/webapp/secure/configurationManager/directiveManagement.html
  webapp/sources/rudder/rudder-web/src/main/webapp/secure/configurationManager/parameterManagement.html
  webapp/sources/rudder/rudder-web/src/main/webapp/secure/configurationManager/techniqueEditor.html
  webapp/sources/rudder/rudder-web/src/main/webapp/secure/nodeManager/groups.html
  webapp/sources/rudder/rudder-web/src/main/webapp/secure/nodeManager/manageNewNode.html
  webapp/sources/rudder/rudder-web/src/main/webapp/secure/nodeManager/node.html
  webapp/sources/rudder/rudder-web/src/main/webapp/secure/nodeManager/nodes.html
  webapp/sources/rudder/rudder-web/src/main/webapp/secure/nodeManager/searchNodes.html
  webapp/sources/rudder/rudder-web/src/main/webapp/secure/plugins/pluginInformation.html
  webapp/sources/rudder/rudder-web/src/main/webapp/secure/utilities/archiveManagement.html
  webapp/sources/rudder/rudder-web/src/main/webapp/secure/utilities/eventLogs.html
  webapp/sources/rudder/rudder-web/src/main/webapp/secure/utilities/healthcheck.html
  webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-bootstrap.css
  webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-datatable.css
  webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-node.css
  webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-rules.css
  webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-template.css
  webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder.css
  webapp/sources/rudder/rudder-web/src/main/webapp/templates-hidden/common-layout.html
  webapp/sources/rudder/rudder-web/src/main/webapp/templates-hidden/components/ComponentNodeState.html
  webapp/sources/rudder/rudder-web/src/main/webapp/templates-hidden/components/ComponentRuleEditForm.html
  webapp/sources/rudder/rudder-web/src/main/webapp/templates-hidden/node_logs_tabs.html
  webapp/sources/rudder/rudder-web/src/main/webapp/templates-hidden/server/server_details.html
Labels: Trigger test

#3399 Fixes #18626: Popup error on group page with a readonly user in 6.2
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/EndpointsDefinition.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/RoleApiMapping.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/NodeApi.scala
Labels: Trigger test

#3397 Fixes #18634: Add a script example for auto-acceptation of nodes by hook
  webapp/sources/rudder/rudder-core/src/main/resources/hooks.d/node-inventory-received-pending/auto-accept-nodes.example
  webapp/sources/rudder/rudder-core/src/main/resources/hooks.d/node-inventory-received-pending/hook-template
  webapp/sources/rudder/rudder-core/src/main/resources/hooks.d/node-inventory-received-pending/readme.adoc
Labels: Trigger test, qa: Can't merge

#3404 Fixes #18618: Pretty-print json properties in nodes list
  webapp/sources/rudder/rudder-web/src/main/webapp/javascript/rudder/rudder-datatable.js
Labels: qa: Can't merge

#3389 Fixes #18555: Remove useless output from rudder package
  relay/sources/rudder-pkg/lib/rudder-pkg/rudderPkg.py
  relay/sources/rudder-pkg/lib/rudder-pkg/rudderPkgUtils.py
  relay/sources/rudder-pkg/rudder-pkg
Labels: qa: Can't merge

#3407 Fixes #18641: Add a property column without inherited values in node list
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/NodeApi.scala
  webapp/sources/rudder/rudder-web/src/main/webapp/javascript/rudder/rudder-datatable.js
Labels: Ready for merge

#3405 Fixes #18645: Upgrading 6.2 nightly to 6.2 nightly with plugins fails
  relay/sources/rudder-pkg/lib/rudder-pkg/rudderPkg.py
Labels: qa: Can't merge

#3415 Fixes #18627: In read_only mode, many things are editable
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/services/DisplayDirectiveTree.scala
  webapp/sources/rudder/rudder-web/src/main/webapp/secure/configurationManager/techniqueEditor.html
Labels: Trigger test

#3420 Fixes #18682: Error code should be 404 and not 500 when a node is not found for details API
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/NodeApi.scala
Labels: qa: Can't merge

#3416 Fixes #18681: Inherited properties always displayed in the column, even if checkbox unchecked
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/NodeApi.scala
  webapp/sources/rudder/rudder-web/src/main/webapp/javascript/rudder/rudder-datatable.js
Labels: qa: Can't merge

#3425 Fixes #18694: Rudder-pkg fails at upgrade when no newer version of a plugin are available
  relay/sources/rudder-pkg/lib/rudder-pkg/rudderPkg.py
Labels: Ready for merge, qa: Can't merge

#3426 Fixes #18693: Filter for name for generic methods in technique editor doesn't filter
  webapp/sources/rudder/rudder-web/src/main/webapp/secure/configurationManager/techniqueEditor.html
  webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-technique-editor.css
  webapp/sources/rudder/rudder-web/src/main/webapp/techeditor/js/ncf.js
Labels: Ready for merge
