Repository Normation/rudder, pull requests merged in 2020-09, with the labels that each got.

#3197 Fixes #18136: Implement resource level variables
  rudder-lang/src/ast.rs
  rudder-lang/src/ast/resource.rs
  rudder-lang/src/ast/variable.rs
  rudder-lang/src/parser.rs
  rudder-lang/src/parser/tests.rs
Labels: Ready for merge

#3198 Fixes #18152: Rename ast to IR ans split it
  rudder-lang/src/bin/rudderc.rs
  rudder-lang/src/compile.rs
  rudder-lang/src/generator.rs
  rudder-lang/src/generator/cfengine.rs
  rudder-lang/src/generator/dsc.rs
  rudder-lang/src/generator/json.rs
  rudder-lang/src/generator/markdown.rs
  rudder-lang/src/ir.rs
  rudder-lang/src/ir/context.rs
  rudder-lang/src/ir/enum_tree.rs
  rudder-lang/src/ir/enums.rs
  rudder-lang/src/ir/resource.rs
  rudder-lang/src/ir/value.rs
  rudder-lang/src/ir/variable.rs
  rudder-lang/src/lib.rs
  rudder-lang/src/parser.rs
  rudder-lang/src/rudderlang_lib.rs
  rudder-lang/src/technique.rs
  rudder-lang/src/technique/from_ir.rs
  rudder-lang/tests/compile_techniques/f_fuzzy.rl
  rudder-lang/tests/compile_techniques/f_header.rl
Labels: Ready for merge

#3196 Fixes #18151: AgentRunsTest and ReportsTest not passing on master
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/reports/execution/ReportsExecutionRepositoryImpl.scala
Labels: Ready for merge

#3199 Fixes #18110: Unused index on table Ruddersysevents
  webapp/sources/rudder/rudder-core/src/main/resources/Migration/dbMigration-6.1-6.2-remove-unused-index-on-ruddersysevents.sql
  webapp/sources/rudder/rudder-core/src/main/resources/reportsSchema.sql
Labels: Ready for merge

#3201 Fixes #18161: Add tests to ir
  rudder-lang/src/compile.rs
  rudder-lang/src/generator.rs
  rudder-lang/src/generator/cfengine.rs
  rudder-lang/src/generator/dsc.rs
  rudder-lang/src/generator/json.rs
  rudder-lang/src/generator/markdown.rs
  rudder-lang/src/ir.rs
  rudder-lang/src/ir/enum_tree.rs
  rudder-lang/src/ir/enums.rs
  rudder-lang/src/ir/ir1.rs
  rudder-lang/src/ir/ir2.rs
  rudder-lang/src/ir/resource.rs
  rudder-lang/src/rudderlang_lib.rs
  rudder-lang/src/technique/from_ir.rs
Labels: Ready for merge

#3200 Fixes #18076: Use new UI template in Directives page
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/DirectiveEditForm.scala
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/NodeGroupForm.scala
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/RuleDisplayer.scala
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/RuleGrid.scala
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/TechniqueEditForm.scala
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/services/DisplayDirectiveTree.scala
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/configuration/DirectiveManagement.scala
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/configuration/RuleManagement.scala
  webapp/sources/rudder/rudder-web/src/main/webapp/javascript/rudder/angular/filters.js
  webapp/sources/rudder/rudder-web/src/main/webapp/javascript/rudder/directive.js
  webapp/sources/rudder/rudder-web/src/main/webapp/javascript/rudder/rudder.js
  webapp/sources/rudder/rudder-web/src/main/webapp/secure/configurationManager/directiveManagement.html
  webapp/sources/rudder/rudder-web/src/main/webapp/secure/nodeManager/groups.html
  webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-directives.css
  webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-menu.css
  webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-rules.css
  webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-tags.css
  webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-template.css
  webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder.css
  webapp/sources/rudder/rudder-web/src/main/webapp/templates-hidden/components/ComponentDirectiveEditForm.html
  webapp/sources/rudder/rudder-web/src/main/webapp/templates-hidden/components/ComponentTechniqueEditForm.html
Labels: Ready for merge

#3203 Fixes #18167: compilation issue due to misplaced doc
  rudder-lang/src/ir/ir1.rs
Labels: Ready for merge

#3205 Fixes #18172: Group query with OR composition and searching for Node properties return all nodes in place of none
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/queries/LdapQueryProcessor.scala
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/queries/TestQueryProcessor.scala
Labels: Ready for merge

#3206 Fixes #18189: Do not fail on missing config id
  relay/sources/relayd/src/data/runlog.rs
  relay/sources/relayd/src/error.rs
  relay/sources/relayd/src/output/database.rs
Labels: Ready for merge, Trigger test, qa: Can't merge

#3204 Fixes #18169: rudder-lang fails to test its documentation examples
  rudder-lang/docs/examples/statements.rl
Labels: Ready for merge

#3208 Fixes #18193: fix version for serde and rudderlang techniques
  rudder-lang/docs/examples/ntp.rl
  rudder-lang/docs/images/translate.svg
  rudder-lang/src/technique.rs
  rudder-lang/src/technique/from_ir.rs
  rudder-lang/tests/compile_techniques/s_basic.rl
  rudder-lang/tests/compile_techniques/s_basic.rl.cf
  rudder-lang/tests/helpers/admin_management.rl
  rudder-lang/tests/helpers/cis.rl
  rudder-lang/tests/helpers/cis9.1_cron.rl
  rudder-lang/tests/helpers/lines_present.rl
  rudder-lang/tests/helpers/s_basic.rl
  rudder-lang/tests/helpers/wazuh_windows.rl
  rudder-lang/tests/techniques/6.1.rc5/technique.rl
  rudder-lang/tests/techniques/condition_andor/technique.rl
  rudder-lang/tests/techniques/condition_anybsd/technique.rl
  rudder-lang/tests/techniques/condition_errorprone/technique.rl
  rudder-lang/tests/techniques/conditional_method/technique.rl
  rudder-lang/tests/techniques/multiple_simple/technique.rl
  rudder-lang/tests/techniques/parameters/technique.rl
  rudder-lang/tests/techniques/parameters_err/technique.rl
  rudder-lang/tests/techniques/parameters_mult/technique.rl
  rudder-lang/tests/techniques/simplest/technique.rl
Labels: Ready for merge

#3209 Fixes #18192: Resources are lost during an upgrade from 6.0 to 6.1
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/ncf/Technique.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/NcfApi.scala
  webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala
  webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/checks/CheckNcfTechniqueUpdate.scala
Labels: Ready for merge, qa: Can't merge

#3210 Fixes #18197: pending changes of resources (files deleted / modified / added ) are commited automatically during upgrade
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/ncf/Technique.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/ncf/TechniqueWriter.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/NcfApi.scala
  webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/checks/CheckNcfTechniqueUpdate.scala
Labels: Ready for merge, qa: Can't merge

#3212 Fixes #18205: Logs from all nodes are always reported in all.log
  webapp/sources/rudder/rudder-templates/src/main/scala/com/normation/templates/FillTemplatesService.scala
Labels: Ready for merge

#3213 Fixes #18207: Groups are not commited in configuration-repository on modification
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/ldap/LDAPNodeGroupRepository.scala
Labels: Ready for merge, qa: Can't merge

#3214 Fixes #18208: add test for parent ticket
  webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/root-sys-var-false/clientlist/clientlist.cf
  webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/root-sys-var-false/common/1.0/cf-serverd.cf
  webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/root-sys-var-false/common/1.0/check-rsyslog-version
  webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/root-sys-var-false/common/1.0/common.cf
  webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/root-sys-var-false/common/1.0/cron-setup.cf
  webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/root-sys-var-false/common/1.0/environment-variables.cf
  webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/root-sys-var-false/common/1.0/hooks.cf
  webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/root-sys-var-false/common/1.0/internal-security.cf
  webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/root-sys-var-false/common/1.0/monitoring.cf
  webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/root-sys-var-false/common/1.0/properties.cf
  webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/root-sys-var-false/common/1.0/reporting-http.cf
  webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/root-sys-var-false/common/1.0/restart-services.cf
  webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/root-sys-var-false/common/1.0/rudder-groups.cf
  webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/root-sys-var-false/common/1.0/rudder-parameters.cf
  webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/root-sys-var-false/common/1.0/site.cf
  webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/root-sys-var-false/common/1.0/update.cf
  webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/root-sys-var-false/common/cron/rudder-agent-community-cron
  webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/root-sys-var-false/distributePolicy/1.0/apache-acl.cf
  webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/root-sys-var-false/distributePolicy/1.0/common.cf
  webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/root-sys-var-false/distributePolicy/1.0/nodescerts.pem
  webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/root-sys-var-false/distributePolicy/1.0/nodeslist.json
  webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/root-sys-var-false/distributePolicy/1.0/propagatePromises.cf
  webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/root-sys-var-false/distributePolicy/1.0/rsyslogConf.cf
  webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/root-sys-var-false/distributePolicy/1.0/send-clean.sh
  webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/root-sys-var-false/distributePolicy/rsyslog.conf/rudder-rsyslog-relay.conf
  webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/root-sys-var-false/distributePolicy/rsyslog.conf/rudder-rsyslog-root.conf
  webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/root-sys-var-false/failsafe.cf
  webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/root-sys-var-false/inventory/1.0/fusionAgent.cf
  webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/root-sys-var-false/inventory/1.0/test-inventory.pl
  webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/root-sys-var-false/promises.cf
  webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/root-sys-var-false/properties.d/properties.json
  webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/root-sys-var-false/rudder-directives.cf
  webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/root-sys-var-false/rudder-directives.csv
  webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/root-sys-var-false/rudder-parameters.json
  webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/root-sys-var-false/rudder-promises-generated
  webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/root-sys-var-false/rudder-server-roles.conf
  webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/root-sys-var-false/rudder-system-directives.cf
  webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/root-sys-var-false/rudder-vars.json
  webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/root-sys-var-false/rudder.json
  webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/root-sys-var-false/rudder_promises_generated
  webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/root-sys-var-false/run_interval
  webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/root-sys-var-false/server-roles/1.0/alive-check.cf
  webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/root-sys-var-false/server-roles/1.0/common.cf
  webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/root-sys-var-false/server-roles/1.0/component-check.cf
  webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/root-sys-var-false/server-roles/1.0/compress-ldap-backups.cf
  webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/root-sys-var-false/server-roles/1.0/compress-webapp-log.cf
  webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/root-sys-var-false/server-roles/1.0/integrity-check.cf
  webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/root-sys-var-false/server-roles/1.0/logrotate-check.cf
  webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/root-sys-var-false/server-roles/1.0/metrics-reporting.cf
  webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/root-sys-var-false/server-roles/1.0/network-check.cf
  webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/root-sys-var-false/server-roles/1.0/password-check.cf
  webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/root-sys-var-false/server-roles/1.0/postgres-check.cf
  webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/root-sys-var-false/server-roles/1.0/relayd.cf
  webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/root-sys-var-false/server-roles/1.0/relayd.conf.tpl
  webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/root-sys-var-false/server-roles/1.0/servers-by-role.cf
  webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/root-sys-var-false/server-roles/1.0/service-check.cf
  webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/root-sys-var-false/server-roles/1.0/technique-reload.cf
  webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/root-sys-var-false/server-roles/logrotate.conf/rudder
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/policies/write/WriteTechniquesTest.scala
Labels: Ready for merge

#3215 Fixes #18209: Correct tests for branch 6.1
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/policies/write/WriteTechniquesTest.scala
Labels: Ready for merge

#3216 Fixes #18138: Split Number in Integer and Float
  rudder-lang/docs/lexical-structure.adoc
  rudder-lang/docs/types.adoc
  rudder-lang/src/generator/cfengine.rs
  rudder-lang/src/generator/cfengine/syntax.rs
  rudder-lang/src/generator/dsc.rs
  rudder-lang/src/ir/context.rs
  rudder-lang/src/ir/value.rs
  rudder-lang/src/parser.rs
  rudder-lang/src/parser/tests.rs
  rudder-lang/tests/tmp/s_basic/technique.rl
Labels: Ready for merge, Trigger test, qa: Can't merge

#3222 Fixes #18232: Add svg logos to the repo
  logo/rudder-logo-rect-black.svg
  logo/rudder-logo-rect-white.svg
  logo/rudder-logo-square-black.svg
  logo/rudder-logo-square-white.svg
Labels: Trigger test

#3224 Fixes #18237: cli rework: doc
  rudder-lang/docs/usage.adoc
  rudder-lang/src/opt.rs
Labels: qa: Can't merge

#3234 Fixes #18270: Parent change does not do what it says
  relay/sources/relayd/src/api.rs
  relay/sources/relayd/src/error.rs
Labels: Trigger test, qa: Can't merge
