Repository Normation/rudder, pull requests merged in 2020-03, with the labels that each got.

#2801 Fixes #16848: It is impossible to use the /nodes/applyPolicy endpoint
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/EndpointsDefinition.scala
Labels: Ready for merge, qa: Can't merge

#2803 Fixes #16847: LDAP connection pool error are not correctly reported
  webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala
  webapp/sources/scala-ldap/src/main/scala/com/normation/ldap/sdk/LDAPConnectionProvider.scala
Labels: Ready for merge, qa: Can't merge

#2789 Fixes #16807: rl add cfengine_core to libs, which declares global variables
  rudder-lang/libs/cfengine_core.rl
  rudder-lang/src/bin/main.rs
  rudder-lang/src/compile.rs
  rudder-lang/tests/compile.rs
Labels: Ready for merge, qa: Can't merge

#2810 Fixes #16871: Rename openapi.html to index.html
  api-doc/build.py
Labels: Ready for merge

#2811 Fixes #16874: Syntax errors in API doc
  webapp/sources/api-doc/components/schemas/node-full.yml
  webapp/sources/api-doc/openapi.src.yml
  webapp/sources/api-doc/paths/change-requests/accept.yml
  webapp/sources/api-doc/paths/directives/id-check.yml
  webapp/sources/api-doc/paths/directives/id.yml
Labels: qa: Can't merge

#2807 Fixes #16346: Display tags when listing directives
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/policies/Tags.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/ldap/LDAPEntityMapper.scala
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/domain/policies/TagsTest.scala
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/RuleEditForm.scala
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/TagsEditForm.scala
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/services/DisplayDirectiveTree.scala
  webapp/sources/rudder/rudder-web/src/main/webapp/javascript/rudder/angular/ruleDirectives.js
  webapp/sources/rudder/rudder-web/src/main/webapp/javascript/rudder/tree.js
  webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-rules.css
  webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-tags.css
  webapp/sources/rudder/rudder-web/src/main/webapp/templates-hidden/components/ComponentRuleEditForm.html
Labels: qa: Can't merge

#2790 Fixes #16811: rl oslib generated on cargo build + config file changes to prepare integration
  rudder-lang/Cargo.toml
  rudder-lang/Makefile
  rudder-lang/README.adoc
  rudder-lang/build.rs
  rudder-lang/libs/stdlib.rl
  rudder-lang/src/bin/main.rs
  rudder-lang/src/compile.rs
  rudder-lang/src/file_paths.rs
  rudder-lang/src/lib.rs
  rudder-lang/src/translate.rs
  rudder-lang/tests/helpers/cfjson_tester
  rudder-lang/tests/tester.sh
  rudder-lang/tests/utils/mod.rs
  rudder-lang/tools/generate-lib
  rudder-lang/tools/osbuilder.ron
  rudder-lang/tools/rudderc-dev.conf
  rudder-lang/tools/rudderc.conf
  rudder-lang/tools/translate_config.toml
Labels: Ready for merge, qa: Can't merge

#2816 Fixes #16869: Display directive tags inside Compliance tables
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/RuleGrid.scala
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/services/ComplianceData.scala
  webapp/sources/rudder/rudder-web/src/main/webapp/javascript/rudder/rudder-datatable.js
  webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-tags.css
Labels: qa: Can't merge

#2817 Fixes #16892: Upgrade to ZIO RC18
  webapp/sources/pom.xml
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/batch/AutomaticReportsCleaner.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/batch/CheckInventoryUpdate.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/batch/PurgeDeletedInventories.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/batch/PurgeUnreferencedSoftwares.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/db/Doobie.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/hooks/RunNuCommand.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/inventory/InventoryFileWatcher.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/inventory/InventoryProcessor.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/reports/execution/ReportsExecutionRepositoryImpl.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/jdbc/HistorizationJdbcRepository.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/DeploymentService.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/JavascriptEngine.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/WriteNodeCertificatesPem.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/write/BuildBundleSequence.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/write/PolicyWriterService.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/write/PrepareTemplateVariables.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/reports/NodeChangesService.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/reports/ReportingServiceImpl.scala
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/SomeTestNonUnit.scala
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/hooks/HooksTest.scala
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/policies/TestBuildNodeConfiguration.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/NodeApi.scala
  webapp/sources/rudder/rudder-templates/src/main/scala/com/normation/templates/FillTemplatesService.scala
  webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala
  webapp/sources/scala-ldap/src/main/scala/com/normation/ldap/sdk/LDAPConnection.scala
  webapp/sources/scala-ldap/src/main/scala/com/normation/ldap/sdk/LDAPConnectionProvider.scala
  webapp/sources/utils/src/main/scala/com/normation/ZioCommons.scala
  webapp/sources/utils/src/main/scala/zio/internal/RudderBlockingService.scala
  webapp/sources/utils/src/main/scala/zio/syntax.scala
  webapp/sources/utils/src/test/scala/com/normation/ZioCommonsTest.scala
Labels: qa: Can't merge

#2819 Fixes #16906: Be able to save in LDAP a Policy Server Target
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/RudderDit.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/NodeGroupRepository.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/NodeRepository.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/ldap/LDAPNodeGroupRepository.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/ldap/LDAPNodeRepository.scala
  webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala
Labels: WIP

#2836 Fixes #16946: Infinite loop in `for` may leak memory
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/inventory/InventoryFileWatcher.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/inventory/InventoryProcessor.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/reports/NodeChangesService.scala
Labels: qa: Can't merge

#2837 Fixes #16886: rudder-lang packaging update
  rudder-lang/Makefile
  rudder-lang/src/bin/rudderc.rs
  rudder-lang/src/file_paths.rs
  rudder-lang/src/generators/cfengine.rs
  rudder-lang/src/translate.rs
  rudder-lang/tests/test_files/rl/s_declare.rl
  rudder-lang/tests/test_files/tester/condition_andor/technique.cf
  rudder-lang/tests/test_files/tester/condition_andor/technique.json
  rudder-lang/tests/test_files/tester/condition_andor/technique.rl
  rudder-lang/tests/test_files/tester/condition_andor/technique.rl.cf
  rudder-lang/tests/test_files/tester/condition_andor/technique.rl.cf.json
  rudder-lang/tests/test_files/tester/condition_anybsd/technique.json
  rudder-lang/tests/test_files/tester/condition_anybsd/technique.rl
  rudder-lang/tests/test_files/tester/condition_anybsd/technique.rl.cf
  rudder-lang/tests/test_files/tester/condition_anybsd/technique.rl.cf.json
  rudder-lang/tests/test_files/tester/condition_dyn/technique.json
  rudder-lang/tests/test_files/tester/condition_errorprone/technique.json
  rudder-lang/tests/test_files/tester/condition_errorprone/technique.rl
  rudder-lang/tests/test_files/tester/condition_errorprone/technique.rl.cf
  rudder-lang/tests/test_files/tester/condition_errorprone/technique.rl.cf.json
  rudder-lang/tests/test_files/tester/conditional_method/technique.rl.cf
  rudder-lang/tests/test_files/tester/json/var.json
  rudder-lang/tests/test_files/tester/json/var_prefix.json
  rudder-lang/tests/test_files/tester/json/var_same.json
  rudder-lang/tests/test_files/tester/json/var_same_as_param.json
  rudder-lang/tests/test_files/tester/multiple_simple/technique.json
  rudder-lang/tests/test_files/tester/multiple_simple/technique.rl
  rudder-lang/tests/test_files/tester/multiple_simple/technique.rl.cf
  rudder-lang/tests/test_files/tester/multiple_simple/technique.rl.cf.json
  rudder-lang/tests/test_files/tester/parameters/technique.rl.cf
  rudder-lang/tests/test_files/tester/parameters_err/technique.json
  rudder-lang/tests/test_files/tester/parameters_err/technique.rl
  rudder-lang/tests/test_files/tester/parameters_mult/technique.json
  rudder-lang/tests/test_files/tester/parameters_mult/technique.rl
  rudder-lang/tests/test_files/tester/parameters_mult/technique.rl.cf
  rudder-lang/tests/test_files/tester/parameters_mult/technique.rl.cf.json
  rudder-lang/tests/test_files/tester/rl/simplest.json.rl
  rudder-lang/tests/test_files/tester/rl/variables.rl
  rudder-lang/tests/test_files/tester/rl/variables.rl.cf
  rudder-lang/tests/test_files/tester/simplest/technique.rl.cf
  rudder-lang/tools/cfjson_tester
  rudder-lang/tools/generate-lib
  rudder-lang/tools/rudderc-dev.conf
  rudder-lang/tools/rudderc.conf
  rudder-lang/tools/tester.sh
Labels: qa: Can't merge

#2827 Fixes #16906: Be able to save in LDAP a Policy Server Target
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/RudderDit.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/NodeGroupRepository.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/NodeRepository.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/ldap/LDAPNodeGroupRepository.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/ldap/LDAPNodeRepository.scala
  webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala
Labels: qa: Can't merge

#2822 Fixes #16878: Fix generation of parameters and conditions from cfengine files
  rudder-lang/libs/stdlib.rl
  rudder-lang/src/bin/rudderc.rs
  rudder-lang/src/compile.rs
  rudder-lang/src/generators.rs
  rudder-lang/src/generators/cfengine.rs
  rudder-lang/src/translate.rs
  rudder-lang/tests/compile.rs
  rudder-lang/tests/helpers/cfjson_tester
  rudder-lang/tests/test_files/tester/condition_errorprone/technique.rl
  rudder-lang/tests/test_files/tester/condition_errorprone/technique.rl.cf
  rudder-lang/tests/test_files/tester/condition_errorprone/technique.rl.cf.json
  rudder-lang/tests/test_files/tester/simplest/technique.cf
  rudder-lang/tests/test_files/tester/simplest/technique.json
  rudder-lang/tests/test_files/tester/simplest/technique.json.rl
  rudder-lang/tests/test_files/tester/simplest/technique.rl
  rudder-lang/tests/test_files/tester/simplest/technique.rl.cf
  rudder-lang/tests/test_files/tester/simplest/technique.rl.cf.json
  rudder-lang/tests/utils/mod.rs
  rudder-lang/tools/__pycache__/docopt.cpython-37.pyc
  rudder-lang/tools/cfjson_tester
  rudder-lang/tools/docopt.pyc
  rudder-lang/tools/generate-lib
  rudder-lang/tools/jsondiff/__init__.pyc
  rudder-lang/tools/jsondiff/__pycache__/__init__.cpython-37.pyc
  rudder-lang/tools/jsondiff/__pycache__/symbols.cpython-37.pyc
  rudder-lang/tools/jsondiff/symbols.pyc
  rudder-lang/tools/tester-dev.sh
  rudder-lang/tools/tester.sh
  rudder-lang/tools/translate_config.toml
Labels: Ready for merge

#2842 Fixes #16967: rudder-lang packaging changes
  relay/sources/relayd/Makefile
  rudder-lang/Makefile
  rust.makefile
Labels: qa: Can't merge

#2844 Fixes #16969: Display Rust tooling version in build
  relay/sources/Makefile
  relay/sources/relayd/Makefile
  rudder-lang/Makefile
  rust.makefile
Labels: qa: Can't merge

#2841 Fixes #16928: Add range to enum expressions
  rudder-lang/Cargo.lock
  rudder-lang/Cargo.toml
  rudder-lang/build.rs
  rudder-lang/libs/oslib.rl
  rudder-lang/src/ast.rs
  rudder-lang/src/ast/enums.rs
  rudder-lang/src/ast/enums_old.rs
  rudder-lang/src/generators/cfengine.rs
  rudder-lang/src/parser.rs
  rudder-lang/src/parser/tests.rs
  rudder-lang/tests/compile.rs
  rudder-lang/tests/helpers/basic.ncf
  rudder-lang/tests/test_files/source_rl/f_fuzzy.rl
  rudder-lang/tests/test_files/source_rl/s_enum_mapping.rl
  rudder-lang/tests/test_files/source_rl/s_state_case.rl
  rudder-lang/tools/osbuilder.ron
Labels: qa: Can't merge
