Repository Normation/rudder, pull requests merged in 2020-10, with the labels that each got.

#3235 Fixes #18272: Optionally accept node with same hostname as an already accepted one
  webapp/sources/api-doc/components/schemas/settings.yml
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/servers/NewNodeManager.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/appconfig/ConfigService.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/SettingsApi.scala
  webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala
Labels: Trigger test, qa: Can't merge

#3218 Fixes #17250: Webapp does not regerate policies when webdav password is changed, breaking inventories after 5.0 -> 6.0 upgrade
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/batch/AsyncDeploymentActor.scala
  webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala
  webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/checks/ResumePolicyUpdateRunning.scala
  webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/checks/TriggerPolicyUpdate.scala
Labels: qa: Can't merge

#3232 Fixes #18266: Uncommited rudder_reporting.cf when creating a with a condition
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/ncf/TechniqueWriter.scala
Labels: Ready for merge, qa: Can't merge

#3219 Fixes #18224: Possible deadlock when connection pool is full
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/db/Doobie.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/jdbc/RudderDatasourceProvider.scala
Labels: Trigger test

#3163 Fixes #15024: It should be forbidden to create a user technique with the same name as n existing technique
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/NcfApi.scala
  webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala
Labels: WIP

#3241 Fixes #18285: Array as root json are seens as string or only first element is taken
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/nodes/Properties.scala
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/domain/nodes/GenericPropertiesTest.scala
Labels: Ready for merge

#3237 Fixes #18277: Bad condition on name checking for technique existence
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/NcfApi.scala
  webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala
Labels: Ready for merge, Trigger test

#3239 Fixes #18283: Broken url for local api in relay api doc
  relay/sources/api-doc/openapi.src.yml
Labels: Ready for merge

#3236 Fixes #18275: internally use a more secured version type for techniques version
  rudder-lang/src/output.rs
  rudder-lang/src/technique.rs
  rudder-lang/src/technique/from_ir.rs
  rudder-lang/tests/techniques/simplest/technique.rl
Labels: Ready for merge, qa: Can't merge

#3191 Fixes #18119: refactoring DSC generator
  rudder-lang/src/generator/cfengine.rs
  rudder-lang/src/generator/cfengine/syntax.rs
  rudder-lang/src/generator/dsc.rs
  rudder-lang/src/generator/dsc/syntax.rs
  rudder-lang/src/ir/enums.rs
  rudder-lang/src/ir/resource.rs
  rudder-lang/src/ir/value.rs
  rudder-lang/src/opt.rs
  rudder-lang/src/technique.rs
  rudder-lang/src/technique/from_ir.rs
  rudder-lang/tests/compile_techniques/s_basic.rl.ps1
  rudder-lang/tests/techniques/6.1.rc5/technique.ee.json
  rudder-lang/tests/techniques/6.1.rc5/technique.rl
  rudder-lang/tests/techniques/condition_andor/technique.json
  rudder-lang/tests/techniques/condition_andor/technique.rl
  rudder-lang/tests/techniques/condition_andor/technique.rl.ps1
  rudder-lang/tests/techniques/condition_anybsd/technique.rl
  rudder-lang/tests/techniques/simplest/technique.rl
  rudder-lang/tests/techniques/simplest/technique.rl.cf
  rudder-lang/tests/techniques/simplest/technique.rl.ps1
Labels: Ready for merge

#3230 Fixes #18256: impl new logger
  rudder-lang/Cargo.lock
  rudder-lang/Cargo.toml
  rudder-lang/src/bin/rudderc.rs
  rudder-lang/src/compile.rs
  rudder-lang/src/error.rs
  rudder-lang/src/io.rs
  rudder-lang/src/lib.rs
  rudder-lang/src/logger.rs
  rudder-lang/src/migrate.rs
  rudder-lang/src/opt.rs
  rudder-lang/src/output.rs
  rudder-lang/src/rudderlang_lib.rs
  rudder-lang/src/technique.rs
  rudder-lang/tests/utils/mod.rs
Labels: Ready for merge

#3244 Fixes #18289: Missing system variable "POLICY_SERVER_KEY"
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/cfclerk/services/impl/SystemVariableSpecServiceImpl.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/SystemVariableService.scala
  webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/root-default-install/rudder.json
  webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/root-with-one-multipolicy/rudder.json
  webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/root-with-two-directives/rudder.json
Labels: Ready for merge, Trigger test, qa: Can't merge

#3249 Fixes #18306: Create healthcheck API
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/logger/HealthcheckLogger.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/healthcheck/HealthcheckService.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/EndpointsDefinition.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/RestDataSerializer.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/RoleApiMapping.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/HealthcheckApi.scala
  webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala
Labels: Trigger test, WIP

#3228 Fixes #17752: Reorganize dockerfiles and start documentation
  docker/agent/cf-execd.Dockerfile
  docker/agent/cf-execd.sh
  docker/agent/cf-serverd.Dockerfile
  docker/agent/cf-serverd.sh
  docker/agent/docker-compose.yml
  docker/agent/policy_server.dat
  docker/relay/README.adoc
  docker/relay/cf-execd.Dockerfile
  docker/relay/cf-execd.sh
  docker/relay/cf-serverd.Dockerfile
  docker/relay/cf-serverd.sh
  docker/relay/docker-compose.yml
  docker/relay/httpd.Dockerfile
  docker/relay/httpd.sh
  docker/relay/policy_server.dat
  docker/relay/relay.Dockerfile
  docker/relay/relay.sh
  docker/relay/relayd.Dockerfile
  docker/relay/relayd.sh
  docker/relay/script.sh
Labels: Trigger test, WIP, qa: Can't merge

#3258 Fixes #18327:
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/SystemVariableService.scala
  webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/node-cfe-with-500-directives/rules/cfengine-community/rudder.json
  webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/node-cfe-with-two-directives/rules/cfengine-community/rudder.json
  webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/node-gen-var-def-override/rules/cfengine-community/rudder.json
Labels: qa: Can't merge

#3261 Fixes #18336: improve documentation on ho o change a key for a node by stating that \n is mandatory around begin and end
  webapp/sources/api-doc/components/schemas/agent-key.yml
  webapp/sources/rudder/rudder-core/pom.xml
  webapp/sources/rudder/rudder-core/src/test/resources/certificates/cert-nodeid-bad.pem
  webapp/sources/rudder/rudder-core/src/test/resources/certificates/cert-nodeid-ok-new.pem
  webapp/sources/rudder/rudder-core/src/test/resources/certificates/cert-nodeid-ok.pem
  webapp/sources/rudder/rudder-core/src/test/resources/certificates/key-nodeid-bad.pem
  webapp/sources/rudder/rudder-core/src/test/resources/certificates/key-nodeid-ok-new.pem
  webapp/sources/rudder/rudder-core/src/test/resources/certificates/key-nodeid-ok.pem
  webapp/sources/rudder/rudder-core/src/test/resources/certificates/linux-cfe-sign.ocs
  webapp/sources/rudder/rudder-core/src/test/resources/certificates/linux-cfe-sign.ocs.sign
  webapp/sources/rudder/rudder-core/src/test/resources/certificates/readme.txt
  webapp/sources/rudder/rudder-core/src/test/resources/certificates/rudder-sign
  webapp/sources/rudder/rudder-core/src/test/resources/certificates/windows-bad-certificate.ocs
  webapp/sources/rudder/rudder-core/src/test/resources/certificates/windows-bad-certificate.ocs.sign
  webapp/sources/rudder/rudder-core/src/test/resources/certificates/windows-new-certificate.ocs
  webapp/sources/rudder/rudder-core/src/test/resources/certificates/windows-new-certificate.ocs.sign
  webapp/sources/rudder/rudder-core/src/test/resources/certificates/windows-same-certificate.ocs
  webapp/sources/rudder/rudder-core/src/test/resources/certificates/windows-same-certificate.ocs.sign
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/inventory/TestCertificate.scala
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/ncf/TestTechniqueWriter.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/NcfApi.scala
Labels: Trigger test, qa: Can't merge

#3264 Fixes #18338: Rudder SSL default configuration should follow the system default one
  relay/sources/apache/rudder-vhost.conf
Labels: qa: Can't merge

#3269 Fixes #18351: Add Health Check endpoint in API doc
  webapp/sources/api-doc/code_samples/curl/healthcheck/all.sh
  webapp/sources/api-doc/components/schemas/check.yml
  webapp/sources/api-doc/openapi.src.yml
  webapp/sources/api-doc/paths/healthcheck/all.yml
Labels: Trigger test

#3272 Fixes #18346: Make the group option to include the Rudder server or not in the group more clear
  webapp/sources/rudder/rudder-web/src/main/webapp/templates-hidden/server/server_details.html
Labels: Trigger test, qa: Can't merge

#3257 Fixes #18326: Handle proxies in rudder package command
  relay/sources/rudder-pkg/lib/rudder-pkg/rudderPkg.py
  relay/sources/rudder-pkg/lib/rudder-pkg/rudderPkgUtils.py
  relay/sources/rudder-pkg/rudder-pkg.conf
Labels: qa: Can't merge

#3277 Fixes #18366: Beautify Event logs page
  webapp/sources/rudder/rudder-web/src/main/webapp/secure/utilities/eventLogs.html
Labels: Trigger test

#3274 Fixes #18355: Reorganize some sections
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/administration/PropertiesManagement.scala
  webapp/sources/rudder/rudder-web/src/main/webapp/javascript/rudder/rudder.js
  webapp/sources/rudder/rudder-web/src/main/webapp/secure/administration/policyServerManagement.html
  webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-template.css
  webapp/sources/rudder/rudder-web/src/main/webapp/templates-hidden/components/ComponentAgentPolicyMode.html
  webapp/sources/rudder/rudder-web/src/main/webapp/templates-hidden/components/ComponentComplianceMode.html
Labels: Trigger test

#3283 Fixes #18363: Add check name in healthcheck API
  webapp/sources/api-doc/components/schemas/check.yml
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/healthcheck/HealthcheckService.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/RestDataSerializer.scala
Labels: Trigger test

#3275 Fixes #18347: Group owner of files under configuration-repository are inconsistent
  webapp/sources/pom.xml
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/inventory/InventoryFileWatcher.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/metrics/HistorizeNodeCountService.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/ncf/TechniqueWriter.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/xml/GitArchiverImpl.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/xml/GitArchiverUtils.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/rule/category/GitRuleCategoryArchiver.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/WriteNodeCertificatesPem.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/ncf/TechniqueReader.scala
  webapp/sources/rudder/rudder-web/src/main/resources/configuration.properties.sample
  webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/administration/PropertiesManagement.scala
Labels: Trigger test, qa: Can't merge

#3251 Fixes #18317: Support source package in Rudder inventory
  webapp/sources/ldap-inventory/inventory-api/src/main/scala/com/normation/inventory/domain/Software.scala
  webapp/sources/ldap-inventory/inventory-fusion/src/main/scala/com/normation/inventory/provisioning/fusion/FusionReportUnmarshaller.scala
  webapp/sources/ldap-inventory/inventory-provisioning-core/src/main/scala/com/normation/inventory/ldap/provisioning/SoftwareIdFinder.scala
  webapp/sources/ldap-inventory/inventory-repository/src/main/resources/ldap/inventory.schema
  webapp/sources/ldap-inventory/inventory-repository/src/main/scala/com/normation/inventory/ldap/core/InventoryMapper.scala
  webapp/sources/ldap-inventory/inventory-repository/src/main/scala/com/normation/inventory/ldap/core/LDAPConstants.scala
Labels: qa: Can't merge

#3287 Fixes #18371: Rudder-lang doc build broken by ncf parameter
  rudder-lang/Makefile
  rudder-lang/src/bin/rudderc.rs
  rudder-lang/src/io.rs
  rudder-lang/src/io/cli_parser.rs
  rudder-lang/tools/generate_lib
Labels: Trigger test, qa: Can't merge

#3290 Fixes #18393: Update relayd dependencies
  relay/sources/relayd/Cargo.lock
Labels: qa: Can't merge

#3280 Fixes #18375: Directly generate policies with correct rights
  webapp/sources/rudder/rudder-core/src/main/resources/hooks.d/policy-generation-node-ready/90-change-perm
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/write/PolicyWriterService.scala
  webapp/sources/rudder/rudder-core/src/test/resources/hooks.d/test-hooks.sh
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/inventory/TestCertificate.scala
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/policies/write/WriteTechniquesTest.scala
  webapp/sources/rudder/rudder-web/src/main/resources/configuration.properties.sample
  webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala
Labels: qa: Can't merge

#3293 Fixes #18395: Update dependencies for the webapp
  webapp/sources/pom.xml
  webapp/sources/rudder/rudder-templates/pom.xml
  webapp/sources/rudder/rudder-templates/src/main/scala/com/normation/templates/FillTemplatesService.scala
  webapp/sources/rudder/rudder-web/pom.xml
Labels: qa: Can't merge

#3252 Fixes #18314: Create Healthcheck webpage
  webapp/sources/rudder/rudder-web/src/main/elm/build-app.sh
  webapp/sources/rudder/rudder-web/src/main/elm/healthcheck/elm.json
  webapp/sources/rudder/rudder-web/src/main/elm/healthcheck/sources/ApiCalls.elm
  webapp/sources/rudder/rudder-web/src/main/elm/healthcheck/sources/DataTypes.elm
  webapp/sources/rudder/rudder-web/src/main/elm/healthcheck/sources/Init.elm
  webapp/sources/rudder/rudder-web/src/main/elm/healthcheck/sources/JsonDecoder.elm
  webapp/sources/rudder/rudder-web/src/main/elm/healthcheck/sources/View.elm
  webapp/sources/rudder/rudder-web/src/main/elm/healthcheck/sources/rudder-healthcheck.elm
  webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/Boot.scala
  webapp/sources/rudder/rudder-web/src/main/webapp/secure/utilities/healthcheck.html
  webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-healthcheck.css
  webapp/sources/rudder/rudder-web/src/main/webapp/templates-hidden/common-layout.html
Labels: Trigger test

#3296 Fixes #18405: Upgrade to ZIO 1.0.1 - branch 6.2
  webapp/sources/ldap-inventory/inventory-fusion/src/main/scala/com/normation/inventory/provisioning/fusion/FusionReportUnmarshaller.scala
  webapp/sources/ldap-inventory/inventory-repository/src/main/scala/com/normation/inventory/ldap/core/InventoryMapper.scala
  webapp/sources/ldap-inventory/inventory-repository/src/main/scala/com/normation/inventory/ldap/core/ReadOnlySoftwareInventoryDAOImpl.scala
  webapp/sources/pom.xml
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/batch/AutomaticReportsCleaner.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/metrics/Scheduler.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/NodeGroupRepository.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/ldap/LDAPEntityMapper.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/ldap/LDAPNodeGroupRepository.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/ldap/LDAPNodeRepository.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/xml/GitArchiverImpl.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/xml/GitParseRudderObjects.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/xml/ItemArchiveManagerImpl.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/nodes/NodeInfoService.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/DependencyAndDeletionService.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/DeploymentService.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/write/PrepareTemplateVariables.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/queries/LdapQueryProcessor.scala
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/inventory/TestCertificate.scala
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/metrics/NodeCountHistorizationTest.scala
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/metrics/SchedulerTest.scala
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/policies/TestJsEngine.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/RestExtractorService.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/NcfApi.scala
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/plugins/RudderPluginJson.scala
  webapp/sources/utils/src/main/scala/com/normation/ZioCommons.scala
  webapp/sources/utils/src/test/scala/com/normation/ZioCommonsTest.scala
Labels: qa: Can't merge

#3297 Fixes #18406: Missing base class of plugins breaks `reflections` with caffeine version 2.8.2
  webapp/sources/pom.xml
  webapp/sources/rudder/rudder-web/pom.xml
  webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/Boot.scala
Labels: Trigger test, qa: Can't merge

#3299 Fixes #18412: Update relayd after reporting changes in webapp
  relay/sources/relayd/src/api/shared_files.rs
  relay/sources/relayd/src/configuration/logging.rs
  relay/sources/relayd/src/configuration/main.rs
  relay/sources/relayd/src/data/node.rs
  relay/sources/relayd/src/data/runlog.rs
  relay/sources/relayd/src/data/shared_file.rs
  relay/sources/relayd/src/error.rs
  relay/sources/relayd/src/hashing.rs
  relay/sources/relayd/src/output/database.rs
  relay/sources/relayd/src/processing/inventory.rs
  relay/sources/relayd/src/processing/reporting.rs
  relay/sources/relayd/tests/api_system_info.rs
  relay/sources/relayd/tests/api_system_reload.rs
  relay/sources/relayd/tests/api_system_status.rs
  relay/sources/relayd/tests/common.rs
  relay/sources/relayd/tests/processing_reporting.rs
  relay/sources/relayd/tests/processing_reporting_old.rs
  relay/sources/relayd/tests/remote_run.rs
  relay/sources/relayd/tests/shared_files.rs
  relay/sources/relayd/tests/shared_folder.rs
  relay/sources/relayd/tools/create-database.sql
Labels: Ready for merge

#3267 Fixes #18328: Healthcheck notification in navigation bar
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/healthcheck/HealthcheckNotificationService.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/healthcheck/HealthcheckService.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/HealthcheckApi.scala
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/HealthcheckInfo.scala
Labels: Ready for merge, Trigger test

#3302 Fixes #18413: Missing RudderConfig parameter pour healthcheck period
  webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala
Labels: Ready for merge

#3301 Fixes #18357: Add check for free space
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/healthcheck/HealthcheckService.scala
  webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala
Labels: Ready for merge, Trigger test, qa: Can't merge

#3300 Fixes #17666: Node status API must not return an error when the node is not here
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/EndpointsDefinition.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/NodeApi.scala
  webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala
Labels: Ready for merge, Trigger test, qa: Can't merge

#3304 Fixes #18417: Improve freeSpace check messages
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/healthcheck/HealthcheckService.scala
  webapp/sources/rudder/rudder-web/src/main/elm/healthcheck/sources/View.elm
Labels: Ready for merge

#3303 Fixes #18414: Add check for File Descriptor limit
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/healthcheck/HealthcheckService.scala
  webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala
Labels: Ready for merge, Trigger test

#3308 Fixes #18443: Fix compilation issues after merge
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/healthcheck/HealthcheckService.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/NodeApi.scala
Labels: Ready for merge

#3310 Fixes #18453: rudder package config may not have the new parameters and may fail when reading them
  relay/sources/rudder-pkg/lib/rudder-pkg/rudderPkg.py
  relay/sources/rudder-pkg/lib/rudder-pkg/rudderPkgUtils.py
  relay/sources/rudder-pkg/rudder-pkg
Labels: qa: Can't merge
