Repository Normation/rudder, pull requests merged in 2021-06, with the labels that each got.

#3654 Fixes #19351: queryAndChekNodeId sometimes query for 0 nodes
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/nodes/NodeInfoService.scala
Labels: Trigger test, qa: Can't merge

#3655 Fixes #19359: Backport typos checks to 6.1
  Jenkinsfile
  relay/sources/relayd/deny.toml
  relay/sources/relayd/tests/remote_run.rs
  relay/sources/relayd/tools/openssl.cnf
  relay/sources/rudder-pkg/lib/docopt.py
  relay/sources/rudder-pkg/lib/rudder-pkg/plugin.py
  relay/sources/rudder-pkg/lib/rudder-pkg/rudderPkgUtils.py
  webapp/sources/api-doc/code_samples/curl/compliance/nodes.sh
  webapp/sources/api-doc/code_samples/curl/datasources/update.sh
  webapp/sources/api-doc/components/schemas/node-full.yml
  webapp/sources/api-doc/introduction.md
Labels: Trigger test, qa: Can't merge

#3657 Fixes #19367: Backport typos checks to 6.2
  relay/sources/rudder-pkg/lib/rudder-pkg/rudderPkgUtils.py
Labels: Trigger test

#3656 Fixes #19363: Semaphore in APIAccountRepository,GitArchiverUtils and maybe PolicyServerManagementService are not semaphoring
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/api/ApiAccountRepository.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/xml/GitArchiverUtils.scala
Labels: Trigger test

#3653 Fixes #19345: Since we forbid chars in technique version, we actually have to not use them
  webapp/sources/rudder/rudder-rest/src/test/resources/api/api_techniques.yml
Labels: Trigger test

#3659 Fixes #19374: API shows only part of the memory information
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/data/NodeDetailLevel.scala
Labels: Trigger test

#3660 Fixes #19375: relayd on relays fails to retry inventories upload
  relay/sources/relayd/src/input/watch.rs
  relay/sources/relayd/src/processing/inventory.rs
  relay/sources/relayd/src/processing/reporting.rs
Labels: Trigger test, qa: Can't merge

#3662 Fixes #19381: Confusing message when we disable non-compliant-report log
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/batch/AutomaticReportLogger.scala
Labels: Trigger test

#3663 Fixes #19396: Move use of cache outside of semaphore in NodeInfoService
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/nodes/NodeInfoService.scala
Labels: Trigger test

#3664 Fixes #19395: Info API is not documented
  webapp/sources/api-doc/code_samples/curl/info/all.sh
  webapp/sources/api-doc/code_samples/curl/info/get-endpoint.sh
  webapp/sources/api-doc/code_samples/curl/info/get-section.sh
  webapp/sources/api-doc/components/schemas/api-endpoints.yml
  webapp/sources/api-doc/components/schemas/api-version.yml
  webapp/sources/api-doc/components/schemas/api-versions.yml
  webapp/sources/api-doc/openapi.src.yml
  webapp/sources/api-doc/paths/info/all.yml
  webapp/sources/api-doc/paths/info/endpoint-id.yml
  webapp/sources/api-doc/paths/info/section-id.yml
Labels: Trigger test, qa: Can't merge

#3667 Fixes #19400: Update snakeyaml dependency for security
  webapp/sources/rudder/rudder-rest/pom.xml
Labels: Trigger test

#3665 Fixes #19394: When a node is totally deleted, cache in NodeInfoService can't know about it
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/ldap/LDAPNodeRepository.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/nodes/NodeInfoService.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/servers/RemoveNodeService.scala
Labels: Trigger test, qa: Can't merge

#3669 Fixes #19405: rudder-pkg test should use python3
  relay/sources/rudder-pkg/lib/rudder-pkg/tests/testall
Labels: Trigger test

#3671 Fixes #19407: CVE in spring dependency
  webapp/sources/pom.xml
Labels: Trigger test

#3673 Fixes #19413: rudder-pkg version parsing does not support version numbers containing a git hash
  relay/sources/rudder-pkg/lib/rudder-pkg/rudderPkgUtils.py
Labels: Trigger test

#3674 Fixes #19416: Missing default value for HTTPS port
  webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala
Labels: Trigger test

#3675 Fixes #19414: Inventory with updated properties doesn't always start a policy generation
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/batch/CheckInventoryUpdate.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/nodes/NodeInfoService.scala
Labels: Trigger test, qa: Can't merge

#3677 Fixes #19435: Missing cleanup of /var/rudder/reports/failed
  relay/sources/relayd/src/processing/reporting.rs
Labels: Trigger test, qa: Can't merge

#3678 Fixes #19436: Missing cleanup of /var/rudder/reports/failed - master fix
  relay/sources/relayd/src/processing/reporting.rs
Labels: Trigger test

#3682 Fixes #19447: Broken short hostname in agent certificate
  relay/sources/rudder-server-relay-postinst
Labels: Ready for merge, Trigger test

#3681 Fixes #19442:
  relay/sources/rudder-pkg/lib/rudder-pkg/rudderPkgUtils.py
  relay/sources/rudder-pkg/lib/rudder-pkg/tests/assets/helloworld.rpkg
  relay/sources/rudder-pkg/lib/rudder-pkg/tests/rudderPkgUtils.test.py
  relay/sources/rudder-pkg/lib/rudder-pkg/tests/testall
  relay/sources/rudder-pkg/rudder-pkg
Labels: Trigger test, qa: Can't merge

#3679 Fixes #19441: Improve pylint config and add formatter to rudder-pkg
  relay/sources/Makefile
  relay/sources/rudder-pkg/lib/rudder-pkg/plugin.py
  relay/sources/rudder-pkg/lib/rudder-pkg/rpkg.py
  relay/sources/rudder-pkg/lib/rudder-pkg/rudderPkg.py
  relay/sources/rudder-pkg/lib/rudder-pkg/rudderPkgLogger.py
  relay/sources/rudder-pkg/lib/rudder-pkg/rudderPkgUtils.py
  relay/sources/rudder-pkg/lib/rudder-pkg/tests/rudderPkgUtils.test.py
  relay/sources/rudder-pkg/lib/rudder-pkg/tests/test.py
  relay/sources/rudder-pkg/pyproject.toml
  relay/sources/rudder-pkg/rudder-pkg
Labels: Trigger test, WIP, qa: Can't merge

#3683 Fixes #19449: Improve pylint config and add formatter to rudder-pkg - master
  relay/sources/rudder-pkg/lib/rudder-pkg/rpkg.py
  relay/sources/rudder-pkg/lib/rudder-pkg/rudderPkg.py
  relay/sources/rudder-pkg/lib/rudder-pkg/rudderPkgUtils.py
  relay/sources/rudder-pkg/lib/rudder-pkg/tests/test.py
Labels: Trigger test

#3684 Fixes #19455:
  relay/sources/relayd/src/api/remote_run.rs
  relay/sources/relayd/tests/remote_run.rs
Labels: Trigger test

#3685 Fixes #19461:
  relay/sources/relayd/tests/remote_run.rs
Labels: Ready for merge, Trigger test

#3686 Fixes #19457:
  webapp/sources/ldap-inventory/inventory-fusion/src/main/scala/com/normation/inventory/provisioning/fusion/PreUnmarshallCheckConsistency.scala
  webapp/sources/ldap-inventory/inventory-repository/src/main/scala/com/normation/inventory/ldap/core/FullInventoryRepositoryImpl.scala
  webapp/sources/ldap-inventory/inventory-repository/src/test/scala/com/normation/inventory/ldap/core/TestInventory.scala
  webapp/sources/utils/src/main/scala/com/normation/utils/HashcodeCaching.scala
  webapp/sources/utils/src/main/scala/com/normation/utils/StandardFieldsValidation.scala
  webapp/sources/utils/src/main/scala/com/normation/utils/UuidRegex.scala
Labels: Trigger test

#3687 Fixes #19466: upmege of parent ticket is inefficient
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/nodes/NodeInfoService.scala
Labels: Trigger test

#3688 Fixes #19467: Inefficient comparision of strings in Rudder
  webapp/sources/ldap-inventory/inventory-api/src/main/scala/com/normation/inventory/domain/DataTypes.scala
  webapp/sources/ldap-inventory/inventory-api/src/main/scala/com/normation/inventory/services/provisioning/CheckInventoryDigest.scala
  webapp/sources/ldap-inventory/inventory-repository/src/main/scala/com/normation/inventory/ldap/core/InventoryMapper.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/queries/CmdbQuery.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/RestExtractorService.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/InfoApi.scala
Labels: Trigger test

#3691 Fixes #19470: Relayd does not start since some keys are missing from its logging.conf file
  relay/sources/relayd/src/configuration/logging.rs
Labels: Trigger test

#3692 Fixes #19471: Add a lint option to rudderc
  language/src/bin/rudderc.rs
  language/src/command.rs
  language/src/command/lint.rs
  language/src/io.rs
  language/src/io/cli_parser.rs
  language/tools/rudderc-dev.conf
Labels: Ready for merge, Trigger test

#3693 Fixes #19472: Fix language documentation
  language/Cargo.lock
  language/Cargo.toml
  language/docs/examples/documentation_ntp.rd.cf
  language/docs/examples/documentation_ntp.rd.ps1
  language/src/io/output.rs
Labels: Ready for merge, Trigger test

#3694 Fixes #19478: Missing catchup limit in 7.0
  relay/sources/relayd/src/input/watch.rs
Labels: Trigger test

#3696 Fixes #19479: Broken reports watcher in 7.0
  relay/sources/relayd/Cargo.lock
  relay/sources/relayd/src/input/watch.rs
  relay/sources/relayd/src/processing/reporting.rs
Labels: Trigger test

#3697 Fixes #19480: Parent ticket break the plugin scripts execution
  relay/sources/rudder-pkg/lib/rudder-pkg/rudderPkgUtils.py
Labels: Ready for merge, Trigger test

#3698 Fixes #19487: Directive details display is broken if the name of a directive is too long.
  webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-template.css
Labels: Trigger test

#3699 Fixes #18788: Use agent certificate in httpd configuration
  relay/sources/apache/rudder-apache-relay-ssl.conf
  relay/sources/rudder-server-relay-postinst
Labels: Ready for merge, Trigger test

#3700 Fixes #19497: relayd fails to start because of incorrect default logging config handling
  relay/sources/relayd/src/configuration/logging.rs
Labels: Trigger test
