Repository Normation/rudder, pull requests merged in 2021-02, with the labels that each got.

#3492 Fixes #18876: Workflow rights are not used for rules
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/RuleApi.scala
Labels: Trigger test

#3496 Fixes #18846: Agent run schedule problem
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/reports/ExpectedReports.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/reports/ReportingConfiguration.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/DeploymentService.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/SystemVariableService.scala
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/policies/TestComputeSchedule.scala
  webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/rest/RestTestSetUp.scala
  webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala
Labels: Trigger test

#3497 Fixes #18882: Build broken by automatic upmerge of parent ticket
  webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/rest/RestTestSetUp.scala
Labels: Ready for merge, Trigger test

#3499 Fixes #18877: "Skipped" Directives on Rules Screen
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/reports/ReportingServiceImpl.scala
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/policies/TestComputeSchedule.scala
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/reports/ReportingServiceUtilsTest.scala
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/services/ComplianceData.scala
  webapp/sources/rudder/rudder-web/src/main/webapp/javascript/rudder/rudder.js
Labels: Trigger test

#3500 Fixes #18883: Line break after each ip address
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/services/DisplayNode.scala
Labels: Trigger test

#3504 Fixes #18899: Error in postCommit pipeline with processor 'post_commit_inventory:pending_node_for_deleted_server'
  webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala
Labels: Trigger test

#3480 Fixes #18845: Add a settings to delay start of policy generation
  webapp/sources/api-doc/components/schemas/settings.yml
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/batch/AsyncDeploymentActor.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/ClearCacheService.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/DeploymentService.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/appconfig/ConfigService.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/SettingsApi.scala
  webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala
Labels: qa: Can't merge

#3490 Fixes #18873: purge software batch sometime terminate in error without log message
  webapp/sources/ldap-inventory/inventory-repository/src/main/scala/com/normation/inventory/ldap/core/ReadOnlySoftwareInventoryDAOImpl.scala
  webapp/sources/ldap-inventory/inventory-repository/src/main/scala/com/normation/inventory/ldap/core/SoftwareService.scala
  webapp/sources/ldap-inventory/inventory-repository/src/test/scala/com/normation/inventory/ldap/core/TestInventory.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/batch/PurgeUnreferencedSoftwares.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/SystemApi.scala
Labels: Ready for merge, Trigger test, qa: Can't merge

#3501 Fixes #18849: Save button moves when switching of compliance reporting mode
  webapp/sources/rudder/rudder-web/src/main/webapp/secure/administration/policyServerManagement.html
Labels: Trigger test, qa: Can't merge

#3509 Fixes #18922: Merge error in parent ticket leads to stackoverflow at boot
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/batch/AsyncDeploymentActor.scala
  webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala
Labels: Trigger test, qa: Can't merge

#3511 Fixes #18923: Missing API addition for version 13 in doc
  webapp/sources/api-doc/introduction.md
Labels: Trigger test, qa: Can't merge

#3512 Fixes #18930: Documentation API doesn't build anymore
  webapp/sources/api-doc/paths/settings/allowed_networks_diff.yml
  webapp/sources/api-doc/paths/system/purge-software.yml
Labels: Trigger test

#3514 Fixes #18931: No skipped directives on Rule screen after parent ticket
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/reports/ReportingService.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/reports/ReportingServiceImpl.scala
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/repository/jdbc/ReportingServiceTest.scala
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/reports/CachedFindRuleNodeStatusReportsTest.scala
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/reports/ReportingServiceUtilsTest.scala
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/RuleCompliance.scala
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/services/ComplianceData.scala
Labels: Ready for merge, Trigger test, qa: Can't merge

#3515 Fixes #18935: Double scrollbar in settings page when branding plugin is enabled
  webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-template.css
Labels: Trigger test

#3481 Fixes #18844: Add a curl/openssl wrapper for sending file to policy server without validating host
  agent/sources/client/.clang-format
  agent/sources/client/.clang-tidy
  agent/sources/client/.gitignore
  agent/sources/client/Makefile
  agent/sources/client/README.md
  agent/sources/client/config/agent.conf
  agent/sources/client/man.adoc
  agent/sources/client/qa-test
  agent/sources/client/src/argtable3.c
  agent/sources/client/src/argtable3.h
  agent/sources/client/src/cli.c
  agent/sources/client/src/cli.h
  agent/sources/client/src/config.c
  agent/sources/client/src/config.h
  agent/sources/client/src/http.c
  agent/sources/client/src/http.h
  agent/sources/client/src/log.c
  agent/sources/client/src/log.h
  agent/sources/client/src/main.c
  agent/sources/client/src/utils.c
  agent/sources/client/src/utils.h
  agent/sources/client/tests/config/agent.toml
  agent/sources/client/tests/config/empty.toml
  agent/sources/client/tests/config/minimal.toml
  agent/sources/client/tests/config/policy.toml
  agent/sources/client/tests/config/policy_server.dat
  agent/sources/client/tests/run.c
Labels: Trigger test, WIP, qa: Can't merge

#3516 Fixes #18940: rudder api doc doesn't list nodes/pending
  webapp/sources/api-doc/code_samples/curl/nodes/pending-all.sh
  webapp/sources/api-doc/openapi.src.yml
  webapp/sources/api-doc/paths/nodes/pending-all.yml
Labels: Trigger test, qa: Can't merge

#3513 Fixes #18926: nodes API with include managementTechnologyDetails leads to error 500 response
  webapp/sources/ldap-inventory/inventory-api/src/main/scala/com/normation/inventory/domain/DataTypes.scala
  webapp/sources/ldap-inventory/inventory-repository/src/main/scala/com/normation/inventory/ldap/core/FullInventoryRepositoryImpl.scala
  webapp/sources/ldap-inventory/inventory-repository/src/main/scala/com/normation/inventory/ldap/core/InventoryMapper.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/NodeApi.scala
  webapp/sources/rudder/rudder-rest/src/test/resources/api/api_nodes.yml
  webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/MockServices.scala
  webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/rest/RestTestSetUp.scala
  webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/rest/TestRestFromFileDef.scala
Labels: Trigger test, qa: Can't merge
