Repository Normation/rudder, pull requests merged in 2021-09, with the labels that each got.

#3852 Fixes #19865: Technique editor allows empty technique name
  webapp/sources/rudder/rudder-web/src/main/elm/editor/sources/ViewTechnique.elm
Labels: qa: Can't merge, Trigger test

#3856 Fixes #19786: When we delete a directive, it's not removed from the rules
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/ldap/LDAPDiffMapper.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/ldap/LDAPEntityMapper.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/RestDataSerializer.scala
  webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/MockServices.scala
Labels: Trigger test

#3861 Fixes #19897: Display result of search with thousands of nodes is really slow on 6.2 & 7.0
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/nodes/NodeInfoService.scala
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/repository/jdbc/ReportingServiceTest.scala
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/reports/CachedFindRuleNodeStatusReportsTest.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/NodeApi.scala
  webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/MockServices.scala
Labels: qa: Can't merge, Trigger test

#3865 Fixes #19719: disable reporting option is not saved in technique editor
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/ncf/EditorTechnique.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/ncf/TechniqueWriter.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/RestExtractorService.scala
Labels: Trigger test

#3863 Fixes #19398: Git error when deleting a node or archiving everything, and very slow git
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/cfclerk/services/GitUtils.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/cfclerk/services/impl/GitUtilsImpl.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/xml/GitArchiverUtils.scala
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/cfclerk/services/JGitRepositoryTest.scala
Labels: Ready for merge, Trigger test

#3860 Fixes #19571: Error about cfengine key when deleting a node
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/servers/RemoveNodeService.scala
Labels: Ready for merge, Trigger test

#3866 Fixes #19907: Compilation error after #19398 merge on upper branches
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/cfclerk/services/JGitRepositoryTest.scala
Labels: Ready for merge, Trigger test

#3868 Fixes #19913: Display number of techniques in the editor
  webapp/sources/rudder/rudder-web/src/main/elm/editor/sources/ViewTechniqueList.elm
  webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-template.css
Labels: Trigger test

#3867 Fixes #19881: Saving groups in the rules UI is broken
  webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/JsonDecoder.elm
Labels: Ready for merge, Trigger test

#3849 Fixes #19808: Add a button to create a new Rule category
  webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/ApiCalls.elm
  webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/DataTypes.elm
  webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/Init.elm
  webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/JsonDecoder.elm
  webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/JsonEncoder.elm
  webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/Rules.elm
  webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/View.elm
  webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/ViewCategoryDetails.elm
  webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/ViewRuleDetails.elm
  webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-template.css
Labels: qa: Can't merge, Trigger test

#3870 Fixes #19923: wrong option name in rudder package command
  relay/sources/rudder-pkg/rudder-pkg
Labels: Ready for merge

#3877 Fixes #19938: Copy to clipboard button for user creation command in login page
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/Login.scala
  webapp/sources/rudder/rudder-web/src/main/webapp/index.html
  webapp/sources/rudder/rudder-web/src/main/webapp/style/login.css
Labels: Trigger test

#3876 Fixes #19740: When 2 changes are close in time, expected report on the compliance page don't show the new config
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/DeploymentService.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/reports/NodeConfigurationService.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/reports/ReportingServiceImpl.scala
  webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala
Labels: Trigger test

#3873 Fixes #19775: there aren't any authorizations on the rules pages
  webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/DataTypes.elm
  webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/Init.elm
  webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/Rules.elm
  webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/View.elm
  webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/ViewCategoryDetails.elm
  webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/ViewRuleDetails.elm
  webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/ViewTabContent.elm
  webapp/sources/rudder/rudder-web/src/main/webapp/secure/configurationManager/ruleManagement.html
  webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-rules.css
Labels: qa: Can't merge, Trigger test

#3878 Fixes #19943: Change format to call engines in properties
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/InterpolatedValueCompiler.scala
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/policies/TestNodeAndGlobalParameterLookup.scala
Labels: Trigger test

#3879 Fixes #19946: Remove exception classes
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/exceptions/NotFoundException.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/exceptions/ParsingException.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/DataStructures.scala
Labels: Trigger test

#3880 Fixes #19951: Remove all.log setting
  webapp/sources/api-doc/components/schemas/settings.yml
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/cfclerk/services/impl/SystemVariableSpecServiceImpl.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/SystemVariableService.scala
  webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/node-cfe-with-500-directives/rules/cfengine-community/rudder.json
  webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/node-cfe-with-two-directives/rules/cfengine-community/rudder.json
  webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/node-gen-var-def-override/rules/cfengine-community/rudder.json
  webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/root-default-install/distributePolicy/rsyslog.conf/rudder-rsyslog-relay.conf
  webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/root-default-install/distributePolicy/rsyslog.conf/rudder-rsyslog-root.conf
  webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/root-default-install/rudder.json
  webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/root-sys-var-false/common/1.0/cf-serverd.cf
  webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/root-sys-var-false/rudder.json
  webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/root-with-one-multipolicy/distributePolicy/rsyslog.conf/rudder-rsyslog-relay.conf
  webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/root-with-one-multipolicy/distributePolicy/rsyslog.conf/rudder-rsyslog-root.conf
  webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/root-with-one-multipolicy/rudder.json
  webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/root-with-two-directives/distributePolicy/rsyslog.conf/rudder-rsyslog-relay.conf
  webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/root-with-two-directives/distributePolicy/rsyslog.conf/rudder-rsyslog-root.conf
  webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/root-with-two-directives/rudder.json
  webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/technique-and-revisions/distributePolicy/rsyslog.conf/rudder-rsyslog-relay.conf
  webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/technique-and-revisions/distributePolicy/rsyslog.conf/rudder-rsyslog-root.conf
  webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/technique-and-revisions/rudder.json
  webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/techniques/system/distributePolicy/1.0/metadata.xml
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/policies/NodeConfigData.scala
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/policies/write/WriteTechniquesTest.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/appconfig/ConfigService.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/SettingsApi.scala
  webapp/sources/rudder/rudder-rest/src/test/resources/api/api_settings.yml
  webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/MockServices.scala
  webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/administration/PropertiesManagement.scala
  webapp/sources/rudder/rudder-web/src/main/webapp/secure/administration/policyServerManagement.html
Labels: Trigger test

#3883 Fixes #19959: cannot remove a method within a block
  webapp/sources/rudder/rudder-web/src/main/elm/editor/sources/Editor.elm
  webapp/sources/rudder/rudder-web/src/main/elm/editor/sources/MethodElemUtils.elm
  webapp/sources/rudder/rudder-web/src/main/elm/editor/sources/ViewBlock.elm
  webapp/sources/rudder/rudder-web/src/main/elm/editor/sources/ViewMethod.elm
Labels: Trigger test

#3882 Fixes #19956: Typo in log "deletedbut"
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/TechniqueAcceptationDatetimeUpdater.scala
Labels: qa: Can't merge, Trigger test

#3885 Fixes #19960: Remove useless bootchecks in rudder 7.0
  webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala
  webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/checks/CheckApiTokenAutorizationKind.scala
  webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/checks/CheckCfengineSystemRuleTargets.scala
  webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/checks/CheckInitXmlExport.scala
  webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/checks/CheckNashornWarning.scala
  webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/checks/CheckSystemGroups.scala
  webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/checks/action/CheckNcfTechniqueUpdate.scala
  webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/checks/action/CheckTechniqueLibraryReload.scala
  webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/checks/action/CreateSystemToken.scala
  webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/checks/action/LoadNodeComplianceCache.scala
  webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/checks/action/TriggerPolicyUpdate.scala
  webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/checks/consistency/CheckConnections.scala
  webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/checks/consistency/CheckDIT.scala
  webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/checks/consistency/CheckRudderGlobalParameter.scala
  webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/checks/migration/CheckMigrationXmlFileFormat.scala
  webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/checks/onetimeinit/CheckInitUserTemplateLibrary.scala
  webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/checks/onetimeinit/CheckInitXmlExport.scala
Labels: Trigger test

#3886 Fixes #19953: error in technique editor in rudder 7 when copying class result from within a block
  webapp/sources/rudder/rudder-web/src/main/webapp/secure/configurationManager/techniqueEditor.html
Labels: Trigger test

#3884 Fixes #19871: rules sorting does not work and they are not sorted by default
  webapp/sources/rudder/rudder-web/src/main/elm/rules/elm.json
  webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/DataTypes.elm
  webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/Init.elm
  webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/Rules.elm
  webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/View.elm
  webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/ViewCategoryDetails.elm
  webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/ViewRuleDetails.elm
  webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/ViewRulesTable.elm
  webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/ViewTabContent.elm
  webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/ViewUtilsCompliance.elm
  webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-template.css
Labels: qa: Can't merge, Trigger test

#3888 Fixes #19967: Improve rudder package output
  relay/sources/rudder-pkg/lib/rudder-pkg/rudderPkg.py
  relay/sources/rudder-pkg/lib/rudder-pkg/rudderPkgUtils.py
  relay/sources/rudder-pkg/rudder-pkg
Labels: Trigger test

#3889 Fixes #19969: Don't allow directory traversal through plugin URL
  relay/sources/rudder-pkg/lib/rudder-pkg/rudderPkg.py
  relay/sources/rudder-pkg/lib/rudder-pkg/rudderPkgUtils.py
Labels: qa: Can't merge, Trigger test

#3875 Fixes #19872: Rules can't be accessed directly by url, all redirection broken
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/web/model/JsInitContextLinkUtil.scala
  webapp/sources/rudder/rudder-web/src/main/elm/rules/elm.json
  webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/ApiCalls.elm
  webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/DataTypes.elm
  webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/Init.elm
  webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/Rules.elm
  webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/View.elm
  webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/ViewRulesTable.elm
  webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/Boot.scala
  webapp/sources/rudder/rudder-web/src/main/webapp/javascript/rudder/rudder-datatable.js
  webapp/sources/rudder/rudder-web/src/main/webapp/secure/configurationManager/ruleManagement.html
Labels: qa: Can't merge, WIP, Trigger test

#3872 Fixes #19926: Support reporting logic metadata in language
  language/src/technique.rs
  language/src/technique/from_ir.rs
  language/tests/techniques/inner_block/technique.json
  language/tests/techniques/simple_block/technique.json
Labels: qa: Can't merge, Trigger test

#3899 Fixes #20006: Store processes of an inventory after storing the inventory
  webapp/sources/ldap-inventory/inventory-provisioning-core/src/main/scala/com/normation/inventory/ldap/provisioning/DefaultReportSaver.scala
  webapp/sources/ldap-inventory/inventory-repository/src/main/scala/com/normation/inventory/ldap/core/InventoryMapper.scala
  webapp/sources/scala-ldap/src/main/scala/com/normation/ldap/sdk/LDAPConnection.scala
Labels: qa: Can't merge, Trigger test

#3901 Fixes #20009: In CI, technique migration test sometimes throw an NPE
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/servers/PolicyServerManagementService.scala
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/repository/ldap/LoadDemoDataTest.scala
  webapp/sources/rudder/rudder-web/src/test/resources/ldap-data/schema/00-core.ldif
  webapp/sources/rudder/rudder-web/src/test/resources/ldap-data/schema/01-pwpolicy.ldif
  webapp/sources/rudder/rudder-web/src/test/resources/ldap-data/schema/04-rfc2307bis.ldif
  webapp/sources/rudder/rudder-web/src/test/resources/ldap-data/schema/05-rfc4876.ldif
  webapp/sources/rudder/rudder-web/src/test/resources/ldap-data/schema/099-0-inventory.ldif
  webapp/sources/rudder/rudder-web/src/test/resources/ldap-data/schema/099-1-rudder.ldif
  webapp/sources/rudder/rudder-web/src/test/scala/bootstrap/liftweb/checks/migration/TestMigrateSystemTechnique7_0.scala
Labels: Trigger test

#3892 Fixes #19977: Tags of a rule cannot be deleted
  webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/Rules.elm
  webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/View.elm
  webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/ViewCategoryDetails.elm
  webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/ViewRuleDetails.elm
  webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/ViewRulesTable.elm
  webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/ViewTabContent.elm
  webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-template.css
Labels: qa: Can't merge, Trigger test

#3894 Fixes #19981: Display the name of the groups of a rule instead of their id
  webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/Rules.elm
  webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/ViewRuleDetails.elm
  webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/ViewTabContent.elm
  webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-template.css
Labels: Trigger test

#3890 Fixes #19971: Make the search bar of the Rules list work
  webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/DataTypes.elm
  webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/Rules.elm
  webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/View.elm
  webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/ViewRulesTable.elm
  webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/ViewUtilsRules.elm
  webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-template.css
Labels: Trigger test

#3906 Fixes #20027: Compilation issue on branch 6.2
  webapp/sources/ldap-inventory/inventory-repository/src/main/scala/com/normation/inventory/ldap/core/InventoryMapper.scala
Labels: Ready for merge
