Repository Normation/rudder, pull requests merged in 2021-08, with the labels that each got.

#3759 Fixes #19639: Updgrade zio-json to last version for rudder 7.0
  webapp/sources/pom.xml
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/ldap/LDAPNodeRepository.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/JsonSchema.scala
Labels: Trigger test

#3754 Fixes #19632: Incorrect pattern matching leads to error in inventory parsing
  webapp/sources/ldap-inventory/inventory-fusion/src/main/scala/com/normation/inventory/provisioning/fusion/FusionReportUnmarshaller.scala
Labels: Trigger test, qa: Can't merge

#3761 Fixes #19643: Improve certificate handling in relayd
  relay/sources/relayd/src/configuration/main.rs
  relay/sources/relayd/src/lib.rs
  relay/sources/relayd/tests/files/config/main.conf
  relay/sources/relayd/tools/config/main.conf
Labels: Trigger test

#3769 Fixes #19657: need to add back RUDDER_REPORTS_DB_NAME for .pgpass
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/cfclerk/services/impl/SystemVariableSpecServiceImpl.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/SystemVariableService.scala
  webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/root-default-install/rudder.json
  webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/root-sys-var-false/rudder.json
  webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/root-with-one-multipolicy/rudder.json
  webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/root-with-two-directives/rudder.json
  webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/technique-and-revisions/rudder.json
  webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/techniques/system/distributePolicy/1.0/metadata.xml
Labels: Trigger test

#3768 Fixes #19656: Add a button to delete the selected rule
  webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/ApiCalls.elm
  webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/DataTypes.elm
  webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/Init.elm
  webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/JsonDecoder.elm
  webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/View.elm
  webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/ViewRuleDetails.elm
  webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/rudder-rules.elm
Labels: Trigger test

#3767 Fixes #19658: Update elm to 0.19.1
  Jenkinsfile
  contributing/webapp.md
  webapp/sources/rudder/rudder-web/src/main/elm/build-app.sh
  webapp/sources/rudder/rudder-web/src/main/elm/editor/elm.json
  webapp/sources/rudder/rudder-web/src/main/elm/editor/sources/Editor.elm
  webapp/sources/rudder/rudder-web/src/main/elm/healthcheck/elm.json
  webapp/sources/rudder/rudder-web/src/main/elm/healthcheck/sources/Healthcheck.elm
  webapp/sources/rudder/rudder-web/src/main/elm/notifications/elm.json
  webapp/sources/rudder/rudder-web/src/main/elm/notifications/sources/Notifications.elm
  webapp/sources/rudder/rudder-web/src/main/elm/onboarding/elm.json
  webapp/sources/rudder/rudder-web/src/main/elm/onboarding/sources/Onboarding.elm
  webapp/sources/rudder/rudder-web/src/main/elm/rules/elm.json
  webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/Rules.elm
Labels: Trigger test

#3771 Fixes #19615: Compliance problem in 7.0
  relay/sources/relayd/src/data/runinfo.rs
  relay/sources/relayd/src/data/runlog.rs
Labels: Trigger test

#3772 Fixes #19661: Add a button to clone the selected rule
  webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/DataTypes.elm
  webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/Rules.elm
  webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/ViewRuleDetails.elm
Labels: Trigger test

#3773 Fixes #19667: Display Directive compliance in the Rules UI
  webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/ViewRuleDetails.elm
  webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/ViewRulesTable.elm
  webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/ViewTabContent.elm
  webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/ViewUtilsCompliance.elm
  webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-rules.css
Labels: Trigger test

#3763 Fixes #19652: Update certificate validation setting for 7.0
  webapp/sources/rudder/rudder-web/src/main/webapp/secure/administration/policyServerManagement.html
Labels: Trigger test

#3774 Fixes #19674: Update SELinux config for new relayd files
  relay/sources/selinux/rudder-relay.fc
Labels: Trigger test

#3775 Fixes #19680:
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/SystemVariableService.scala
Labels: Trigger test

#3776 Fixes #19682: typo in onboarding program for metrics
  webapp/sources/rudder/rudder-web/src/main/elm/onboarding/sources/View.elm
Labels: Trigger test

#3777 Fixes #19683: Read nodecerts.pem on simple relayd - apache
  relay/sources/apache/rudder-apache-relay-ssl.conf
Labels: Trigger test

#3779 Fixes #19688: build-app does not fail if the elm compiler is not there
  webapp/sources/rudder/rudder-web/src/main/elm/build-app.sh
Labels: Trigger test

#3780 Fixes #19689: Fail on elm build error
  webapp/sources/rudder/rudder-web/src/main/elm/build-app.sh
Labels: qa: Can't merge

#3781 Fixes #19690: rudder packages refuses to install -SNAPSHOT plugins
  relay/sources/rudder-pkg/lib/rudder-pkg/rudderPkgUtils.py
Labels: Trigger test

#3782 Fixes #19691: Language tests ignore method unique id
  language/src/technique.rs
  language/src/technique/from_ir.rs
  language/tests/techniques/6.1.rc5/technique.cf
  language/tests/techniques/6.1.rc5/technique.json
  language/tests/techniques/6.1.rc5/technique.ps1
  language/tests/techniques/CIS/technique.cf
  language/tests/techniques/CIS/technique.json
  language/tests/techniques/CIS/technique.ps1
  language/tests/techniques/cdt/technique.cf
  language/tests/techniques/cdt/technique.json
  language/tests/techniques/condition_alias/technique.cf
  language/tests/techniques/condition_alias/technique.json
  language/tests/techniques/condition_anybsd/technique.cf
  language/tests/techniques/condition_anybsd/technique.json
  language/tests/techniques/condition_dyn/technique.cf
  language/tests/techniques/condition_dyn/technique.json
  language/tests/techniques/condition_errorprone/technique.cf
  language/tests/techniques/condition_errorprone/technique.json
  language/tests/techniques/condition_foreign_variable/technique.cf
  language/tests/techniques/condition_foreign_variable/technique.json
  language/tests/techniques/condition_priority/technique.cf
  language/tests/techniques/condition_priority/technique.json
  language/tests/techniques/condition_useless_brackets/technique.cf
  language/tests/techniques/condition_useless_brackets/technique.json
  language/tests/techniques/conditional_method/technique.cf
  language/tests/techniques/conditional_method/technique.json
  language/tests/techniques/deprecated/technique.cf
  language/tests/techniques/deprecated/technique.json
  language/tests/techniques/dsc/technique.cf
  language/tests/techniques/dsc/technique.json
  language/tests/techniques/duplicated/technique.cf
  language/tests/techniques/duplicated/technique.json
  language/tests/techniques/escaped/technique.cf
  language/tests/techniques/escaped/technique.json
  language/tests/techniques/inner_block/technique.json
  language/tests/techniques/multiple_simple/technique.cf
  language/tests/techniques/multiple_simple/technique.json
  language/tests/techniques/parameters/technique.cf
  language/tests/techniques/parameters/technique.json
  language/tests/techniques/parameters_mult/technique.cf
  language/tests/techniques/parameters_mult/technique.json
  language/tests/techniques/simplest/technique.cf
  language/tests/techniques/simplest/technique.json
  language/tests/techniques/stateless/technique.cf
  language/tests/techniques/stateless/technique.json
  language/tests/techniques/supported_formats/technique.cf
  language/tests/techniques/supported_formats/technique.json
Labels: Trigger test

#3783 Fixes #19692: language tests fail
  language/Makefile
  language/src/generator/dsc.rs
  language/tests/techniques/condition_useless_brackets/technique.json
  language/tests/techniques/condition_useless_brackets/technique.ps1
  language/tests/techniques/inner_block/technique.cf
  language/tests/techniques/inner_block/technique.ps1
  language/tests/techniques/simple_block/technique.cf
  language/tests/techniques/simple_block/technique.json
  language/tests/techniques/stateless/technique.ps1
  language/tools/tester.sh
Labels: Trigger test

#3785 Fixes #19697: technique editor uses .rl extension instead of .rd
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/ncf/TechniqueWriter.scala
Labels: Trigger test

#3786 Fixes #19695: rudderc cannot save technique editor data
  language/src/bin/rudderc.rs
  language/src/command/save.rs
  language/src/command/technique_generate.rs
  language/src/technique.rs
  language/src/technique/from_ir.rs
  language/tests/techniques/CIS/technique.json
  language/tests/techniques/cdt/technique.json
  language/tests/techniques/condition_alias/technique.json
  language/tests/techniques/condition_anybsd/technique.json
  language/tests/techniques/condition_dyn/technique.json
  language/tests/techniques/condition_errorprone/technique.json
  language/tests/techniques/condition_foreign_variable/technique.json
  language/tests/techniques/condition_priority/technique.json
  language/tests/techniques/condition_useless_brackets/technique.json
  language/tests/techniques/conditional_method/technique.json
  language/tests/techniques/deprecated/technique.json
  language/tests/techniques/dsc/technique.json
  language/tests/techniques/duplicated/technique.json
  language/tests/techniques/escaped/technique.json
  language/tests/techniques/inner_block/technique.json
  language/tests/techniques/multiple_simple/technique.json
  language/tests/techniques/parameters/technique.json
  language/tests/techniques/parameters_mult/technique.json
  language/tests/techniques/simple_block/technique.json
  language/tests/techniques/simplest/technique.json
  language/tests/techniques/stateless/technique.json
  language/tests/techniques/supported_formats/technique.json
  language/tools/generated_formats_tester
  language/tools/test_all_techniques.sh
Labels: Trigger test

#3787 Fixes #19710: Missing nodescerts.pem during postinst
  relay/sources/rudder-server-relay-postinst
Labels: Trigger test

#3791 Fixes #19728: improve fix of parent ticket
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/DeploymentService.scala
Labels: Trigger test

#3794 Fixes #19731: Two vulnerabilities in hyper
  relay/sources/relayd/deny.toml
Labels: Trigger test

#3795 Fixes #19732: Two vulnerabilities in hyper - fixed in 7.0
  relay/sources/relayd/deny.toml
Labels: Trigger test

#3796 Fixes #19665: Display of configuration of nodes table column is not great in 7.0
  webapp/sources/rudder/rudder-web/src/main/webapp/javascript/rudder/rudder-datatable.js
  webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-datatable.css
  webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-menu.css
Labels: Trigger test

#3797 Fixes #19733: Redirect everything to https
  relay/sources/apache/rudder-apache-relay-nossl.conf
Labels: Trigger test

#3799 Fixes #19736: Missing changes in SELinux configuration
  relay/sources/selinux/rudder-relay.fc
  relay/sources/selinux/rudder-relay.te
Labels: Trigger test

#3798 Fixes #19666: there is no indication on column sorting in nodes table in rudder 7.0
  webapp/sources/rudder/rudder-web/src/main/webapp/javascript/rudder/rudder-datatable.js
  webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-datatable.css
Labels: Trigger test

#3801 Fixes #19744: When we save a rule, the directives are not saved
  webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/JsonEncoder.elm
Labels: Trigger test

#3805 Fixes #19751: cannot execute command because of parent ticket - revert nuprocess to 2.0.1
  webapp/sources/pom.xml
Labels: Trigger test

#3806 Fixes #19750: Remove useless log messages from packages scripts - rudder side
  relay/sources/rudder-server-relay-postinst
Labels: Trigger test

#3807 Fixes #19748: Add timing logger to technique editor
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/ncf/TechniqueWriter.scala
Labels: Trigger test

#3804 Fixes #19745: Add a button to disable or enable the selected rule
  webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/ApiCalls.elm
  webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/DataTypes.elm
  webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/Rules.elm
  webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/View.elm
  webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/ViewRuleDetails.elm
  webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-template.css
Labels: Trigger test

#3802 Fixes #19743: Refresh the list of Rules after saving
  webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/Rules.elm
  webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/View.elm
  webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/ViewTabContent.elm
Labels: Trigger test

#3809 Fixes #19758: Missing SELinux for root.pem
  relay/sources/rudder-server-relay-postinst
Labels: Ready for merge

#3810 Fixes #19759: Missing SELinux for root.pem - directory does not exist
  relay/sources/rudder-server-relay-postinst
Labels: Ready for merge

#3812 Fixes #19565: Filter on generic methods name should not be case sensitive
  webapp/sources/rudder/rudder-web/src/main/elm/editor/sources/ViewMethodsList.elm
Labels: Trigger test

#3815 Fixes #19770: Missing right to read symlinks
  relay/sources/selinux/rudder-relay.te
Labels: Ready for merge, Trigger test

#3817 Fixes #19779: Allowed networks are not saved for the Relay
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/servers/PolicyServerManagementService.scala
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/policies/NodeConfigData.scala
  webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/MockServices.scala
Labels: Trigger test

#3821 Arch 19793/7 0 has api version 14 7
  webapp/sources/api-doc/introduction.md
  webapp/sources/api-doc/openapi.src.yml
Labels: qa: Can't merge, Ready for merge

#3823 Fixes #19798: Use the Lato files from the docs in API docs
  api-doc/custom.css
Labels: Trigger test

#3825 Fixes #19806: Fix API docs CSS
  api-doc/custom.css
Labels: Trigger test

#3808 Fixes #19753: Make rule categories editable
  webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/ApiCalls.elm
  webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/DataTypes.elm
  webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/Init.elm
  webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/JsonDecoder.elm
  webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/JsonEncoder.elm
  webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/Rules.elm
  webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/View.elm
  webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/ViewCategoryDetails.elm
  webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/ViewRuleDetails.elm
  webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-template.css
Labels: Ready for merge, Trigger test

#3819 Fixes #19790: Use gumdrop instead of structopt
  relay/sources/relayd/Cargo.lock
  relay/sources/relayd/Cargo.toml
  relay/sources/relayd/src/api/system.rs
  relay/sources/relayd/src/configuration/cli.rs
  relay/sources/relayd/src/http_client.rs
  relay/sources/relayd/src/lib.rs
  relay/sources/relayd/src/main.rs
Labels: Trigger test

#3826 Fixes #19810: Use gumdrop instead of structopt - 7.0 branch
  relay/sources/relayd/Cargo.lock
  relay/sources/relayd/Cargo.toml
  relay/sources/relayd/src/api/system.rs
  relay/sources/relayd/src/configuration/cli.rs
  relay/sources/relayd/src/http_client.rs
  relay/sources/relayd/src/lib.rs
  relay/sources/relayd/src/main.rs
Labels: Ready for merge

#3827 Fixes #19813: File watchers on inventories do not work
  relay/sources/relayd/src/processing/inventory.rs
Labels: Trigger test

#3818 Fixes #19784: Warn in check config when relayd has an insecure configuration
  relay/sources/relayd/src/api/system.rs
  relay/sources/relayd/src/configuration.rs
  relay/sources/relayd/src/configuration/main.rs
  relay/sources/relayd/src/lib.rs
  relay/sources/relayd/src/main.rs
Labels: Trigger test

#3829 Fixes #19821: Refactor apache configs
  relay/sources/apache/rudder-apache-relay-common.conf
  relay/sources/apache/rudder-apache-relay-nossl.conf
  relay/sources/apache/rudder-apache-relay-ssl.conf
  relay/sources/apache/rudder-vhost.conf
Labels: Trigger test

#3841 Fixes #19832: nom 7.0
  relay/sources/relayd/Cargo.lock
  relay/sources/relayd/Cargo.toml
Labels: Trigger test

#3843 Fixes #19834: Improve relayd compilation time by 30-40%
  relay/sources/relayd/src/api.rs
  relay/sources/relayd/src/api/metrics.rs
  relay/sources/relayd/src/api/shared_files.rs
  relay/sources/relayd/src/api/shared_folder.rs
  relay/sources/relayd/src/api/system.rs
Labels: Trigger test

#3842 Fixes #19833: Data race in crossbeam-deque
  relay/sources/relayd/Cargo.lock
Labels: qa: Can't merge, Trigger test

#3844 Fixes #19835: Data race in crossbeam-deque - 6.2
  relay/sources/relayd/Cargo.lock
Labels: qa: Can't merge

#3800 Fixes #19730: API documentation for secret variabel feature
  webapp/sources/api-doc/code_samples/curl/secret/add.sh
  webapp/sources/api-doc/code_samples/curl/secret/all.sh
  webapp/sources/api-doc/code_samples/curl/secret/delete.sh
  webapp/sources/api-doc/code_samples/curl/secret/getOne.sh
  webapp/sources/api-doc/components/parameters/secret-name.yml
  webapp/sources/api-doc/components/schemas/secrets.yml
  webapp/sources/api-doc/openapi.src.yml
  webapp/sources/api-doc/paths/secret/all.yml
  webapp/sources/api-doc/paths/secret/id.yml
Labels: Trigger test

#3837 Fixes #19809: Replace the main colours of the interface with those of the new graphic charter
  webapp/sources/rudder/rudder-web/src/main/webapp/images/login/background.jpg
  webapp/sources/rudder/rudder-web/src/main/webapp/images/login/logo-rudder.svg
  webapp/sources/rudder/rudder-web/src/main/webapp/images/logo-rudder-nologo.svg
  webapp/sources/rudder/rudder-web/src/main/webapp/images/logo-rudder-sm.svg
  webapp/sources/rudder/rudder-web/src/main/webapp/images/logo-rudder-white.svg
  webapp/sources/rudder/rudder-web/src/main/webapp/index.html
  webapp/sources/rudder/rudder-web/src/main/webapp/style/AdminLTE/AdminLTE.min.css
  webapp/sources/rudder/rudder-web/src/main/webapp/style/login.css
  webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-bootstrap.css
  webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-directives.css
  webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-filemanager.css
  webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-menu.css
  webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-quicksearch.css
  webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-technique-editor.css
  webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-template.css
  webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder.css
  webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/technique-editor-filemanager.css
  webapp/sources/rudder/rudder-web/src/main/webapp/templates-hidden/common-layout.html
Labels: Trigger test

#3845 Fixes #19837: New logo for 7.0
  README.adoc
  logo/rudder-logo-rect-black.svg
  logo/rudder-logo-rect-monochrome-black.svg
  logo/rudder-logo-rect-monochrome-white.svg
  logo/rudder-logo-rect-white.svg
  logo/rudder-logo-square-black.svg
  logo/rudder-logo-square-monochrome-black.svg
  logo/rudder-logo-square-monochrome-white.svg
  logo/rudder-logo-square-white.svg
  readme-resources/color_logo_horizontal_small.png
Labels: Trigger test

#3840 Fixes #19829: Move elm test in the webapp step to avoid concurrent builds
  Jenkinsfile
Labels: Trigger test

#3813 Fixes #19646: Secrets variables event log
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/Constants.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/eventlog/EventLogCategories.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/eventlog/SecretEventLog.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/secret/Secret.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/EventLogRepository.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/jdbc/EventLogJdbcRepository.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/eventlog/EventLogDetailsService.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/eventlog/EventLogFactory.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/eventlog/SecretEventLogService.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/marshalling/XmlSerialisation.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/marshalling/XmlSerialisationImpl.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/marshalling/XmlUnserialisation.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/marshalling/XmlUnserialisationImpl.scala
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/eventlog/NodeEventLogFormatV6Test.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/web/services/EventLogDetailsGenerator.scala
  webapp/sources/rudder/rudder-web/src/main/resources/eventLogTypeNames.properties
  webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala
Labels: Trigger test

#3848 Fixes #19855: language cannot use resource parameter
  language/src/generator/cfengine.rs
  language/src/generator/dsc.rs
  language/src/ir/enums.rs
  language/src/ir/resource.rs
  language/src/ir/value.rs
  language/src/parser.rs
  language/tests/compile.rs
  language/tests/compile_techniques/s_parameter_usage.rd
  language/tests/compile_techniques/s_parameters.rd
  language/tests/techniques/parameters/technique.cf
  language/tests/techniques/parameters/technique.json
  language/tests/techniques/parameters/technique.ps1
  language/tools/test_all_techniques.sh
Labels: Trigger test

#3850 Fixes #19858: rudderc fails to read blocks in techniques
  language/src/generator/dsc.rs
  language/src/ir/resource.rs
  language/src/ir/value.rs
  language/src/parser.rs
  language/src/parser/tests.rs
  language/src/technique.rs
  language/src/technique/from_ir.rs
  language/tests/techniques/inner_block/technique.json
  language/tests/techniques/simple_block/technique.json
Labels: Trigger test

#3857 Fixes #19886: Format the rudder-pkg python files
  relay/sources/rudder-pkg/lib/rudder-pkg/plugin.py
  relay/sources/rudder-pkg/lib/rudder-pkg/rpkg.py
  relay/sources/rudder-pkg/lib/rudder-pkg/rudderPkg.py
  relay/sources/rudder-pkg/lib/rudder-pkg/rudderPkgLogger.py
  relay/sources/rudder-pkg/lib/rudder-pkg/rudderPkgUtils.py
Labels: qa: Can't merge, Trigger test

#3854 Fixes #19874: rudder package does not print the plugin content at install time
  relay/sources/rudder-pkg/lib/rudder-pkg/rudderPkgUtils.py
Labels: Ready for merge, Trigger test

#3858 Fixes #19894: debug_timing debug log is polluted by cache last run hashmap
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/logger/DebugComplianceLogger.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/reports/execution/ReportsExecutionRepository.scala
Labels: Trigger test

#3859 Fixes #19892: importing directives from rudder 6.2 breaks everything in 7.0
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/cfclerk/domain/Technique.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/cfclerk/domain/TechniqueVersion.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/cfclerk/xmlparsers/SectionSpecParser.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/ncf/TechniqueWriter.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/ldap/LDAPDirectiveRepository.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/eventlog/EventLogFactory.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/marshalling/XmlSerialisationImpl.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/MergePolicyService.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/TechniqueAcceptationDatetimeUpdater.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/write/PrepareTemplateVariables.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/quicksearch/QuickSearchBackendImpl.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/DirectiveApi.scala
  webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/MockServices.scala
Labels: Trigger test
