Repository Normation/rudder, pull requests merged in 2021-01, with the labels that each got.

#3458 Fixes #18738: Message on save for group must appear only when button is disabled
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/NodeGroupForm.scala
  webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-groups.css
  webapp/sources/rudder/rudder-web/src/main/webapp/templates-hidden/components/NodeGroupForm.html
Labels: qa: Can't merge

#3448 Fixes #18768: Node name not visible in node configuration screen
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/RuleApi.scala
  webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-tags.css
Labels: qa: Can't merge

#3450 Fixes #18770: Add API tests for rules
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/DirectiveRepository.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/workflows/CommitAndDeployChangeRequestService.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/RestExtractorService.scala
  webapp/sources/rudder/rudder-rest/src/test/resources/api/api_rules.yml
  webapp/sources/rudder/rudder-rest/src/test/resources/api/api_v2.yml
  webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/MockServices.scala
  webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/rest/RestDataExtractorTest.scala
  webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/rest/RestTestSetUp.scala
  webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/rest/TestRestFromFileDef.scala
  webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/checks/CheckInitUserTemplateLibrary.scala
  webapp/sources/utils/src/main/scala/com/normation/utils/StringUuidGenerator.scala
Labels: qa: Can't merge

#3460 Fixes #18805: Bad doc on API for rules/target
  webapp/sources/api-doc/components/schemas/rule.yml
Labels: Ready for merge

#3422 Fixes #18556: Global parameters format is not preserved when editing
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/popup/CreateOrUpdateGlobalParameterPopup.scala
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/model/RudderBaseField.scala
Labels: Trigger test, qa: Can't merge

#3414 Fixes #18677: Accepting a node by API or UI doesn't do the same things exactly
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/servers/NewNodeManager.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/NodeApi.scala
  webapp/sources/rudder/rudder-web/src/main/resources/logback.xml
Labels: Ready for merge, Trigger test, qa: Can't merge

#3447 Fixes #18750: Markdown documentation rendering is inconsistent
  webapp/sources/rudder/rudder-web/src/main/webapp/secure/configurationManager/directiveManagement.html
  webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-directives.css
  webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-menu.css
  webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder.css
  webapp/sources/rudder/rudder-web/src/main/webapp/templates-hidden/components/ComponentDirectiveEditForm.html
Labels: qa: Can't merge

#3466 Fixes #18824: Security advisories for relayd dependencies
  relay/sources/relayd/Cargo.lock
Labels: qa: Can't merge

#3475 Fixes #18835: Make more clear error message when several rudder.war are present
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/reports/execution/ReportsExecutionService.scala
Labels: Trigger test, qa: Can't merge

#3474 Fixes #18830: Missing doc for purgeSoftware API endpoint
  webapp/sources/api-doc/code_samples/curl/system/purge-software.sh
  webapp/sources/api-doc/openapi.src.yml
  webapp/sources/api-doc/paths/system/purge-software.yml
Labels: Trigger test, qa: Can't merge

#3477 Fixes #18840: Bad URL for doc of purgeSoftware API
  webapp/sources/api-doc/code_samples/curl/system/purge-software.sh
Labels: Ready for merge

#3467 Fixes #18818: Update relayd to tokio 1.0
  relay/sources/relayd/Cargo.lock
  relay/sources/relayd/Cargo.toml
  relay/sources/relayd/deny.toml
  relay/sources/relayd/src/api/remote_run.rs
  relay/sources/relayd/src/api/shared_files.rs
  relay/sources/relayd/src/configuration/main.rs
  relay/sources/relayd/src/data/node.rs
  relay/sources/relayd/src/error.rs
  relay/sources/relayd/src/input/watch.rs
  relay/sources/relayd/src/lib.rs
  relay/sources/relayd/src/processing/inventory.rs
  relay/sources/relayd/src/processing/reporting.rs
  relay/sources/relayd/tests/files/config/main.conf
  relay/sources/relayd/tests/processing_reporting_old.rs
  relay/sources/relayd/tools/config/main.conf
  rudder-lang/deny.toml
Labels: Ready for merge, Trigger test, qa: Can't merge

#3462 Fixes #18511: Remove API v1 endpoints
  webapp/sources/api-doc/code_samples/curl/unauthenticated/status.sh
  webapp/sources/api-doc/components/securitySchemes/token.yml
  webapp/sources/api-doc/openapi.src.yml
  webapp/sources/api-doc/paths/unauthenticated/status.yml
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/reports/execution/ReportsExecutionRepositoryImpl.scala
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/repository/jdbc/ReportExecutionTest.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/RestAuthentication.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/v1/RestArchiving.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/v1/RestDeploy.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/v1/RestDyngroupReload.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/v1/RestGetGitCommitAsZip.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/v1/RestStatus.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/v1/RestTechniqueReload.scala
  webapp/sources/rudder/rudder-rest/src/test/resources/api/api_v1.yml
  webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/rest/RestTestSetUp.scala
  webapp/sources/rudder/rudder-web/src/main/resources/configuration.properties.sample
  webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/AppConfigAuth.scala
  webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/Boot.scala
  webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala
Labels: Trigger test

#3479 Fixes #18841: rudder package upgrade-all does not upgrade each plugin independently
  relay/sources/rudder-pkg/lib/rudder-pkg/rudderPkg.py
  relay/sources/rudder-pkg/lib/rudder-pkg/rudderPkgUtils.py
Labels: Trigger test, qa: Can't merge

#3485 Fixes #18865: parent ticket merge override more recent changes in 6.2 branch
  relay/sources/rudder-pkg/lib/rudder-pkg/rudderPkg.py
Labels: Trigger test

#3443 Fixes #18746: library checker should not be hardcoded
  rudder-lang/src/parser/token.rs
  rudder-lang/src/technique/from_ir.rs
  rudder-lang/tools/generate_lib
Labels: Ready for merge

#3484 Fixes #18856: Event logs are not written when fields are set to empty (ie short description)
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/ldap/LDAPDiffMapper.scala
Labels: qa: Can't merge

#3461 Fixes #18800: fix invalid escape in parameter strings
  rudder-lang/src/generator/cfengine.rs
  rudder-lang/src/generator/dsc.rs
  rudder-lang/src/parser.rs
  rudder-lang/src/technique.rs
  rudder-lang/src/technique/from_ir.rs
  rudder-lang/tests/techniques/escaped/technique.cf
  rudder-lang/tests/techniques/escaped/technique.json
  rudder-lang/tests/techniques/escaped/technique.ps1
  rudder-lang/tools/test_all_techniques.sh
Labels: qa: Can't merge

#3486 Fixes #18867: id parameter is ignored in rule category creation API and tags are lost on update
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/RestDataSerializer.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/RestExtractorService.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/data/RestData.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/RuleApi.scala
  webapp/sources/rudder/rudder-rest/src/test/resources/api/api_rules.yml
  webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/MockServices.scala
  webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/rest/RestTestSetUp.scala
  webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/rest/TestRestFromFileDef.scala
Labels: Trigger test, qa: Can't merge

#3483 Fixes #18839: Backport new inventory priorisation, software deletion API and log correction in 6.1
  webapp/sources/ldap-inventory/inventory-api/src/main/scala/com/normation/inventory/services/core/SoftwareDAO.scala
  webapp/sources/ldap-inventory/inventory-provisioning-core/src/main/scala/com/normation/inventory/ldap/provisioning/DefaultReportSaver.scala
  webapp/sources/ldap-inventory/inventory-repository/src/main/scala/com/normation/inventory/ldap/core/ReadOnlySoftwareInventoryDAOImpl.scala
  webapp/sources/ldap-inventory/inventory-repository/src/main/scala/com/normation/inventory/ldap/core/SoftwareService.scala
  webapp/sources/ldap-inventory/inventory-repository/src/test/scala/com/normation/inventory/ldap/core/TestInventory.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/batch/PurgeUnreferencedSoftwares.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/inventory/InventoryFileWatcher.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/servers/NewNodeManager.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/EndpointsDefinition.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/SystemApi.scala
  webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/rest/RestTestSetUp.scala
  webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala
Labels: qa: Can't merge

#3491 Fixes #18874: Do not try to upgrade cis or openscap plugins
  relay/sources/rudder-pkg/lib/rudder-pkg/rudderPkg.py
Labels: Trigger test
