Repository Normation/rudder, pull requests merged in 2021-11, with the labels that each got.

#3977 Fixes #20229: Don't historize names of nodes, rules & groups in the database
  webapp/sources/rudder/rudder-core/src/main/resources/reportsSchema.sql
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/db/DB.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/HistorizationRepository.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/jdbc/HistorizationJdbcRepository.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/eventlog/HistorizationService.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/DeploymentService.scala
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/cfclerk/domain/TechniqueVersionTest.scala
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/repository/jdbc/HistorizationRepositoryTest.scala
  webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/rest/RestTestSetUp.scala
  webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala
Labels: Trigger test

#3976 Fixes #20223: Update OS conditions in the technique editor
  language/libs/oslib.rd
  webapp/sources/rudder/rudder-web/src/main/elm/editor/sources/MethodConditions.elm
Labels: qa: Can't merge, Trigger test

#3983 Fixes #19935: source map missing in 7.0
  webapp/sources/rudder/rudder-web/src/main/webapp/javascript/utils/showdown.min.js.map
Labels: Trigger test

#3982 Fixes #20233: create a migration script to remove historization tables
  webapp/sources/rudder/rudder-core/src/main/resources/Migration/dbMigration-6.x-7.0-drop-historization-table.sql
Labels: Trigger test

#3980 Fixes #20243: Display Groups list in the 'Compliance by nodes' tab
  webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/DataTypes.elm
  webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/ViewRuleDetails.elm
  webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/ViewTabContent.elm
  webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/ViewUtils.elm
Labels: Ready for merge, Trigger test

#3989 Fixes #20239: Rocky Linux is not recognized
  webapp/sources/ldap-inventory/inventory-api/src/main/scala/com/normation/inventory/domain/NodeInventory.scala
  webapp/sources/ldap-inventory/inventory-fusion/src/main/scala/com/normation/inventory/provisioning/fusion/FusionInventoryParser.scala
  webapp/sources/ldap-inventory/inventory-fusion/src/test/resources/fusion-inventories/rocky.ocs
  webapp/sources/ldap-inventory/inventory-fusion/src/test/scala/com/normation/inventory/provisioning/fusion/TestReportParsing.scala
  webapp/sources/ldap-inventory/inventory-repository/src/main/scala/com/normation/inventory/ldap/core/InventoryMapper.scala
  webapp/sources/ldap-inventory/inventory-repository/src/main/scala/com/normation/inventory/ldap/core/LDAPConstants.scala
  webapp/sources/rudder/rudder-web/src/main/resources/ldapObjectAndAttributes.properties
  webapp/sources/rudder/rudder-web/src/main/webapp/images/os/rocky-logo.svg
  webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-node.css
Labels: Trigger test

#3987 Fixes #20253: improve compliance computation efficiency
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/reports/ExecutionBatch.scala
Labels: Ready for merge, Trigger test

#3986 Fixes #19782: Remove SKIPIDENTIFY system variable
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/cfclerk/services/impl/SystemVariableSpecServiceImpl.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/SystemVariableService.scala
  webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/node-cfe-with-500-directives/rules/cfengine-community/rudder.json
  webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/node-cfe-with-two-directives/rules/cfengine-community/rudder.json
  webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/node-gen-var-def-override/rules/cfengine-community/rudder.json
  webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/root-default-install/rudder.json
  webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/root-sys-var-false/rudder.json
  webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/root-with-one-multipolicy/rudder.json
  webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/root-with-two-directives/rudder.json
  webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/technique-and-revisions/rudder.json
  webapp/sources/rudder/rudder-templates-cli/src/test/resources/templates1/cf-served.st
  webapp/sources/rudder/rudder-templates-cli/src/test/resources/templates1/variables.json
Labels: Ready for merge, Trigger test

#3988 Fixes #20254: same as parent ticket for branch 6.1
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/reports/ExecutionBatch.scala
Labels: qa: Can't merge, Ready for merge, Trigger test

#3981 Fixes #20241: Technique draft should be deleted on save
  webapp/sources/rudder/rudder-web/src/main/elm/editor/sources/Editor.elm
Labels: Ready for merge

#3992 Fixes #19888: technique cannot be compile if name contains \\"x
  language/src/error.rs
  language/src/language_lib.rs
  language/src/parser.rs
  language/src/technique.rs
Labels: Ready for merge, Trigger test

#3991 Fixes #20257: Automatic merge of perf enhancement breaks compilation
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/reports/ExecutionBatch.scala
Labels: qa: Can't merge, Ready for merge, Trigger test

#3985 Fixes #20197: Improve compliance bars display in Rules UI
  webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/ComplianceUtils.elm
  webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/ViewRulesTable.elm
  webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/ViewTabContent.elm
  webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/ViewUtils.elm
  webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-menu.css
  webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-template.css
Labels: Ready for merge, Trigger test

#3984 Fixes #17767: Do a `git gc` periodically
  webapp/sources/pom.xml
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/batch/GitGC.scala
  webapp/sources/rudder/rudder-web/src/main/resources/configuration.properties.sample
  webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala
  webapp/sources/utils/pom.xml
  webapp/sources/utils/src/main/scala/com/normation/utils/CronParser.scala
Labels: qa: Can't merge, Ready for merge, Trigger test

#3995 Fixes #20269: Vulnerability in tokio
  relay/sources/relayd/deny.toml
Labels: Ready for merge, Trigger test

#3994 Fixes #20262: Missing documentation for relay to node demote API
  webapp/sources/api-doc/openapi.src.yml
  webapp/sources/api-doc/paths/scale-out-relay/demote.yml
Labels: Ready for merge, Trigger test

#3996 Fixes #20272: Dockerify api-doc test, build and publication
  Jenkinsfile
  api-doc/.gitignore
  api-doc/Dockerfile
  api-doc/requirements.txt
  ci/typos.Dockerfile
  relay/sources/rudder-pkg/Dockerfile
  relay/sources/rudder-pkg/requirements.txt
Labels: qa: Can't merge, Ready for merge, Trigger test

#3993 Fixes #20264: Allow to customize in which menu plugins are set
  webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/Boot.scala
  webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/plugins/PublicPlugin.scala
Labels: qa: Can't merge, Ready for merge

#4000 Fixes #20183: 404 error when opening a technique in the technique editor
  webapp/sources/rudder/rudder-web/src/main/elm/editor/sources/ViewTechniqueTabs.elm
Labels: Ready for merge, Trigger test

#3999 Fixes #19879: Rule editor does not use webapp context path value
  webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/Init.elm
  webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/ViewTabContent.elm
  webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/ViewUtils.elm
  webapp/sources/rudder/rudder-web/src/main/webapp/secure/configurationManager/ruleManagement.html
Labels: Trigger test

#3978 Fixes #20236: Make the rows of the compliance tables foldable to show more levels of compliance in Rules UI
  webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/ComplianceUtils.elm
  webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/DataTypes.elm
  webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/Init.elm
  webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/ViewTabContent.elm
  webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/ViewUtils.elm
  webapp/sources/rudder/rudder-web/src/main/webapp/secure/configurationManager/ruleManagement.html
  webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-datatable.css
  webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-tags.css
  webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-template.css
Labels: WIP, Trigger test

#3932 Fixes #20114: add a default value for bind to interface in rudder parameter
  webapp/sources/rudder/rudder-web/src/main/resources/rudder-system-global-parameter.conf
Labels: Trigger test

#3990 Fixes #20256: Add mock in test lib for secrets eventlogs
  webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/rest/RestTestSetUp.scala
Labels: Trigger test

#3998 Fixes #20275: Dockerify tests
  Jenkinsfile
  Jenkinsfile-security
  api-doc/Dockerfile
  ci/pylint.Dockerfile
  ci/rust.sh
  ci/shellcheck.Dockerfile
  ci/user.sh
  relay/sources/relayd/Dockerfile
  relay/sources/relayd/Makefile
  relay/sources/relayd/README.md
  relay/sources/relayd/src/configuration/main.rs
  relay/sources/relayd/src/output/database.rs
  relay/sources/relayd/tests/files/config/main.conf
  relay/sources/relayd/tests/processing_reporting.rs
  relay/sources/relayd/tools/create-database.sql
  relay/sources/rudder-pkg/Dockerfile
  rudder-lang/Dockerfile
  rudder-lang/Makefile
  rust.makefile
  webapp/sources/Dockerfile
Labels: qa: Can't merge, Trigger test

#3997 Fixes #20273: dashboard only shows the compliance of the nodes that really answer when logging on the test platform in 7.0
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/DeploymentService.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/reports/ExecutionBatch.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/reports/ReportingServiceImpl.scala
Labels: qa: Can't merge, Trigger test

#3893 Fixes #19980: spurious "connection_read(9): no connection!" in /var/log/rudder/ldap/slapd.log
  webapp/sources/scala-ldap/src/main/scala/com/normation/ldap/sdk/LDAPIOResult.scala
Labels: qa: Can't merge, Ready for merge, Trigger test

#4002 Fixes #20283: Missing elm 0.19.1 in 7.0 tests
  Jenkinsfile
  Jenkinsfile-security
  ci/rust.sh
  language/Dockerfile
  relay/sources/relayd/Dockerfile
  relay/sources/relayd/Makefile
  rudder-lang/Makefile
  webapp/sources/Dockerfile
  webapp/sources/rudder/rudder-web/src/main/elm/Dockerfile
Labels: qa: Can't merge, Ready for merge, Trigger test

#4004 Fixes #20285: Language docs publication does not work
  Jenkinsfile
  language/Dockerfile
Labels: qa: Can't merge, Ready for merge, Trigger test

#4006 Fixes #20289: Can't use rudder with openjdk17: cannot access class sun.net.util.IPAddressUtil
  webapp/sources/rudder/rudder-core/pom.xml
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/servers/PolicyServerData.scala
Labels: Ready for merge, Trigger test

#4008 Fixes #20237: Alma Linux is detected as CentOS
  webapp/sources/ldap-inventory/inventory-api/src/main/scala/com/normation/inventory/domain/NodeInventory.scala
  webapp/sources/ldap-inventory/inventory-fusion/src/main/scala/com/normation/inventory/provisioning/fusion/FusionInventoryParser.scala
  webapp/sources/ldap-inventory/inventory-fusion/src/test/resources/fusion-inventories/alma.ocs
  webapp/sources/ldap-inventory/inventory-fusion/src/test/scala/com/normation/inventory/provisioning/fusion/TestReportParsing.scala
  webapp/sources/ldap-inventory/inventory-repository/src/main/scala/com/normation/inventory/ldap/core/InventoryMapper.scala
  webapp/sources/ldap-inventory/inventory-repository/src/main/scala/com/normation/inventory/ldap/core/LDAPConstants.scala
  webapp/sources/rudder/rudder-web/src/main/resources/ldapObjectAndAttributes.properties
  webapp/sources/rudder/rudder-web/src/main/webapp/images/os/alma-logo.svg
  webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-node.css
Labels: Trigger test

#4007 Fixes #20291: Add redirect to latest API doc version to Jenkinsfile
  Jenkinsfile
Labels: qa: Can't merge, Trigger test

#4009 Fixes #20295: Technique editor encoder is not correct with API changes
  webapp/sources/rudder/rudder-web/src/main/elm/editor/sources/JsonEncoder.elm
Labels: Ready for merge

#4011 Fixes #20297: by default, group condition should not be displayed
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/NodeGroupForm.scala
  webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-groups.css
Labels: Trigger test

#4019 Fixes #20320: Split test and build tasks in Jenkins file
  Jenkinsfile
Labels: Trigger test

#4020 Fixes #20322: Make JVM version configurable
  webapp/sources/Dockerfile
Labels: qa: Can't merge, Ready for merge, Trigger test

#4021 Fixes #20323: Only run compatibility tests during the night
  Jenkinsfile
Labels: Trigger test

#4025 Fixes #20231: Loading and first connection pages don't use new rudder 7.0 theme
  webapp/sources/rudder/rudder-web/src/main/resources/load-page/files/pattern.png
  webapp/sources/rudder/rudder-web/src/main/resources/load-page/rudder-loading.html
  webapp/sources/rudder/rudder-web/src/main/resources/load-page/rudder-not-loaded.html
Labels: Ready for merge, Trigger test

#4024 Fixes #20327: Add relayd man page build to Jenkinsfile
  Jenkinsfile
  Jenkinsfile-security
  ci/asciidoctor.Dockerfile
  ci/shellcheck.Dockerfile
Labels: qa: Can't merge, Trigger test

#4029 Fixes #20339: Broken 7.0 tests due to missing user_id variable in Jenkinsfile
  Jenkinsfile
Labels: Ready for merge, Trigger test

#4028 Fixes #20336: Bad logs for migration error when technique is missing
  webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/checks/migration/CheckMigrateSystemTechniques7_0.scala
Labels: Trigger test

#4030 Fixes #20341: Empty value for certificate should not kill rudder
  webapp/sources/ldap-inventory/inventory-api/src/main/scala/com/normation/inventory/domain/DataTypes.scala
Labels: Trigger test

#4022 Fixes #20286: multiple save buttons on rule page
  webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/ViewTabContent.elm
  webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-menu.css
Labels: Trigger test
