Repository Normation/rudder, pull requests merged in 2021-12, with the labels that each got.

#4026 Fixes #20332: Don't use a passphrase for agent key anymore - rudder repo
  docker/rudder-agent/cf-execd.sh
  docker/rudder-relay-split/cf-execd.sh
  docker/rudder-relay/rudder-relay.sh
  relay/arch-doc/rudder-7-communications-security.md
Labels: Trigger test

#4034 Fixes #20349: Refactor apache configuration for easy separation between agent and web flows
  relay/sources/apache/rudder-apache-relay-ssl.conf
  relay/sources/apache/rudder-vhost.conf
Labels: Ready for merge, Trigger test

#4035 Fixes #20350: gitgc is always run at start whatever its schedule is and run every 3min42
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/batch/GitGC.scala
  webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala
Labels: Trigger test

#4036 Fixes #20351: System technique migration fails on old server
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/TechniqueAcceptationDatetimeUpdater.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/servers/PolicyServerManagementService.scala
  webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/checks/migration/CheckMigrateSystemTechniques7_0.scala
  webapp/sources/rudder/rudder-web/src/test/scala/bootstrap/liftweb/checks/migration/TestMigrateSystemTechnique7_0.scala
Labels: Trigger test

#4037 Fixes #20354: Rudder-pkg tests timeout sometimes
  relay/sources/rudder-pkg/lib/rudder-pkg/tests/test.py
Labels: qa: Can't merge, Ready for merge, Trigger test

#4038 Fixes #20359: techniques are seens as deleted even if there are there in Rudder 7.0
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/servers/PolicyServerManagementService.scala
  webapp/sources/rudder/rudder-web/src/test/scala/bootstrap/liftweb/checks/migration/TestMigrateSystemTechnique7_0.scala
Labels: qa: Can't merge, Trigger test

#4040 Fixes #20361: Mount elm tmp dir in tmpfs to avoid lock failure on con…
  webapp/sources/Dockerfile
Labels: qa: Can't merge

#4017 Fixes #20310: Method getByRulesCompliance used by API is highly inefficient
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/ComplianceApi.scala
Labels: qa: Can't merge, Trigger test

#4031 Fixes #20342: Add a worst-case, weighted 1 for block compliance mode
  webapp/sources/ldap-inventory/inventory-api/src/main/scala/com/normation/inventory/domain/DataTypes.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/cfclerk/domain/VariableAndSectionSpec.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/cfclerk/xmlparsers/SectionSpecParser.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/reports/ExpectedReports.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/reports/StatusReports.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/ncf/EditorTechnique.scala
  webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/techniques/ncf_techniques/technique_by_Rudder/1.0/metadata.xml
  webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/techniques/ncf_techniques/technique_with_blocks/1.0/metadata.xml
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/ncf/TestEditorTechniqueWriter.scala
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/policies/NodeExpectedReportTest.scala
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/reports/ExecutionBatchTest.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/RestExtractorService.scala
  webapp/sources/rudder/rudder-web/src/main/elm/editor/sources/DataTypes.elm
  webapp/sources/rudder/rudder-web/src/main/elm/editor/sources/Editor.elm
  webapp/sources/rudder/rudder-web/src/main/elm/editor/sources/JsonDecoder.elm
  webapp/sources/rudder/rudder-web/src/main/elm/editor/sources/JsonEncoder.elm
  webapp/sources/rudder/rudder-web/src/main/elm/editor/sources/ViewBlock.elm
Labels: Trigger test

#4032 Fixes #20343: Add a worst-case, weighted sum for block compliance mode - rudderc
  language/src/technique.rs
  language/src/technique/from_ir.rs
  language/tests/techniques/inner_block/technique.json
  language/tests/techniques/simple_block/technique.json
Labels: qa: Can't merge, Trigger test

#4018 Fixes #20318: Improve performance of getUserAndSystemNodeStatusReports by exploring only once cache
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/reports/StatusReports.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/reports/ReportingService.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/reports/ReportingServiceImpl.scala
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/repository/jdbc/ReportingServiceTest.scala
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/reports/CachedFindRuleNodeStatusReportsTest.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/NodeApi.scala
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/services/AsyncComplianceService.scala
Labels: qa: Can't merge, Trigger test

#4043 Fixes #20383: Non system technique appears in "System status tab"
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/ShowNodeDetailsFromNode.scala
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/services/ComplianceData.scala
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/services/ReportDisplayer.scala
Labels: qa: Can't merge, Trigger test

#4044 Fixes #20394: Remove metrics section from wizard
  webapp/sources/rudder/rudder-web/src/main/elm/onboarding/sources/Init.elm
Labels: Trigger test

#4046 Fixes #20308: when we edit the content of a generic method in 7.0, there is no way to know which method it is
  webapp/sources/rudder/rudder-web/src/main/elm/editor/sources/ViewMethod.elm
  webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-technique-editor.css
Labels: Trigger test

#4049 Fixes #20410: Rudder build when skipping tests
  webapp/sources/rudder/rudder-core/pom.xml
  webapp/sources/rudder/rudder-rest/pom.xml
Labels: Trigger test

#4048 Fixes #20408: Discard old builds
  Jenkinsfile
Labels: Trigger test

#4047 Fixes #20385: Plugins upgrade broken in 7.0 rc
  relay/sources/rudder-pkg/lib/rudder-pkg/rpkg.py
  relay/sources/rudder-pkg/lib/rudder-pkg/tests/fuzz.py
  relay/sources/rudder-pkg/lib/rudder-pkg/tests/testPluginVersion.py
  relay/sources/rudder-pkg/lib/rudder-pkg/tests/testall
  relay/sources/rudder-pkg/requirements.txt
Labels: qa: Can't merge, Trigger test

#4050 Fixes #20416: Test that the distributed config files are valid
  relay/sources/relayd/tests/default_configuration.rs
Labels: Trigger test

#4014 Fixes #20293: group page is not scrollable, so we can't see the full list of nodes in 7.0
  webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-template.css
  webapp/sources/rudder/rudder-web/src/main/webapp/templates-hidden/components/NodeGroupForm.html
Labels: Trigger test

#4039 Fixes #20367: first go at improving perfs for rules/tree
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/policies/RuleApplicationStatus.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/rule/category/LDAPRuleCategoryRepository.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/RuleApplicationStatusService.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/RuleApi.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/web/services/ComputePolicyMode.scala
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/RuleGrid.scala
Labels: qa: Can't merge, Trigger test

#4051 Fixes #20421: Upgrade logback version for LOGBACK-1591 / JNDI
  webapp/sources/pom.xml
Labels: qa: Can't merge

#4003 Fixes #20281: Query seems to be ignored for pendings nodes
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/queries/DynGroupService.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/queries/LdapQueryProcessor.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/queries/QueryProcessor.scala
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/queries/TestPendingNodePolicies.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/NodeApi.scala
  webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/rest/RestTestSetUp.scala
  webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala
Labels: qa: Can't merge, Trigger test

#4033 Fixes #20302: Repair compliance display in Rules page
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/data/Compliance.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/ComplianceApi.scala
  webapp/sources/rudder/rudder-web/src/main/elm/rules/elm.json
  webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/ApiCalls.elm
  webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/ComplianceUtils.elm
  webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/DataTypes.elm
  webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/Init.elm
  webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/JsonDecoder.elm
  webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/Rules.elm
  webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/ViewRulesTable.elm
  webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/ViewTabContent.elm
  webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/ViewUtils.elm
Labels: Ready for merge

#4053 Fixes #20429: Update openssl to 1.1.1m - relayd
  relay/sources/relayd/Cargo.lock
Labels: Ready for merge

#4054 Fixes #20430: Upgrade jquery to 3.6.0
  webapp/sources/rudder/rudder-web/src/main/webapp/index.html
  webapp/sources/rudder/rudder-web/src/main/webapp/javascript/jquery/jquery-3.1.0.min.js
  webapp/sources/rudder/rudder-web/src/main/webapp/javascript/jquery/jquery-3.1.0.min.map
  webapp/sources/rudder/rudder-web/src/main/webapp/javascript/jquery/jquery-3.6.0.min.js
  webapp/sources/rudder/rudder-web/src/main/webapp/javascript/jquery/jquery-3.6.0.min.map
  webapp/sources/rudder/rudder-web/src/main/webapp/javascript/utils/showdown.min.js.map
  webapp/sources/rudder/rudder-web/src/main/webapp/templates-hidden/common-layout.html
Labels: qa: Can't merge, Ready for merge, Trigger test

#4056 Fixes #20439: Do not skip tests in when publising maven or else we will miss tests jar that are needed to build plugins
  Jenkinsfile
Labels: Ready for merge

#4057 Fixes #20395: css of generation status is dubious in 7.0
  webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-menu.css
Labels: Ready for merge, Trigger test

#4060 Fixes #20365: when we hit enter key on rule category creation,page is reloaded
  webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/ViewCategoryDetails.elm
  webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/ViewTabContent.elm
Labels: Ready for merge, Trigger test

#4062 Fixes #20446: Don't insert partial runs as run logs
  relay/sources/relayd/benches/benches.rs
  relay/sources/relayd/src/data/report.rs
  relay/sources/relayd/src/data/runlog.rs
  relay/sources/relayd/src/output/database.rs
  relay/sources/relayd/src/processing/reporting.rs
  relay/sources/relayd/tests/files/runlogs/2020-03-24T12:29:54+00:00@root.json
Labels: qa: Can't merge, Ready for merge, Trigger test

#4045 Fixes #20390: webapp doesn't start after upgrade from 6.2 to 7.0
  webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala
Labels: Ready for merge, Trigger test

#4061 Fixes #19887: icons on login page are not centered
  webapp/sources/rudder/rudder-web/src/main/webapp/index.html
  webapp/sources/rudder/rudder-web/src/main/webapp/style/login.css
Labels: Trigger test

#4064 Fixes #20459: Value 'focus:48137400-7f48-48bd-a888-9522167b5b81' is not a valid reporting composition rule
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/cfclerk/domain/VariableAndSectionSpec.scala
Labels: qa: Can't merge, Trigger test

#4052 Fixes #20364: buttons on rule creation page don't have the same width
  webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-rules.css
  webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-template.css
Labels: Trigger test

#4065 Fixes #20460: Invalid attribute 'special:all_servers_with_role' (or special:all_nodes_without_role) for entry ruleTarget
  webapp/sources/api-doc/components/schemas/rule-target.yml
  webapp/sources/api-doc/paths/rules/tree.yml
  webapp/sources/rudder/rudder-core/src/main/resources/ldap/bootstrap.ldif
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/policies/RuleTarget.scala
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/queries/TestQueryProcessor.scala
  webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala
  webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/checks/migration/CheckAddSpecialTargetAllPolicyServers.scala
  webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/checks/migration/CheckMigrateSystemTechniques7_0.scala
  webapp/sources/rudder/rudder-web/src/test/resources/ldap-data/bootstrap-6_2.ldif
  webapp/sources/rudder/rudder-web/src/test/scala/bootstrap/liftweb/checks/migration/TestMigrateSystemTechnique7_0.scala
Labels: qa: Can't merge, Trigger test

#4063 Fixes #20030: The left menu is under the menu bar's shadow
  webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-menu.css
Labels: Trigger test

#4055 Fixes #20344: It's hard to know how to edit a block/method in editor
  webapp/sources/rudder/rudder-web/src/main/elm/editor/sources/DataTypes.elm
  webapp/sources/rudder/rudder-web/src/main/elm/editor/sources/Editor.elm
  webapp/sources/rudder/rudder-web/src/main/elm/editor/sources/ViewBlock.elm
  webapp/sources/rudder/rudder-web/src/main/elm/editor/sources/ViewMethod.elm
  webapp/sources/rudder/rudder-web/src/main/elm/editor/sources/ViewMethodsList.elm
  webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-technique-editor.css
Labels: Trigger test

#4066 Fixes #20462: Delay policy generation until rudder app is fully boot
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/batch/AsyncDeploymentActor.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/logger/PolicyGenerationLogger.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/NodeGroupRepository.scala
  webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/rest/RestTestSetUp.scala
  webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/Boot.scala
  webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala
Labels: Trigger test

#4067 Fixes #20414: Broken technique resources in drafts
  webapp/sources/rudder/rudder-web/src/main/elm/editor/sources/ApiCalls.elm
  webapp/sources/rudder/rudder-web/src/main/elm/editor/sources/Editor.elm
  webapp/sources/rudder/rudder-web/src/main/elm/editor/sources/ViewTechnique.elm
  webapp/sources/rudder/rudder-web/src/main/elm/editor/sources/ViewTechniqueTabs.elm
Labels: Trigger test

#4069 Fixes #20471: generate_lib outputs a debug line
  language/tools/generate_lib
Labels: Trigger test

#4068 Fixes #20348: Missing special target in group selection for rules
  webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/DataTypes.elm
  webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/JsonDecoder.elm
  webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/JsonEncoder.elm
  webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/Rules.elm
  webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/ViewRuleDetails.elm
  webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/ViewTabContent.elm
  webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/ViewUtils.elm
  webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-rules.css
Labels: Trigger test

#4071 Fixes #20479: error in webapp log at start
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/apidata/RestDataSerializer.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/policies/RuleTarget.scala
  webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/checks/migration/CheckAddSpecialTargetAllPolicyServers.scala
Labels: Trigger test

#4074 Fixes #20488: Wrong technique name displayed in deletion message
  webapp/sources/rudder/rudder-web/src/main/elm/editor/sources/ViewTechnique.elm
Labels: Trigger test

#4075 Fixes #20487: Cancel button is missing when deleting a technique
  webapp/sources/rudder/rudder-web/src/main/elm/editor/sources/ViewTechnique.elm
Labels: Trigger test

#4076 Fixes #20445: When we move a technique in editor, resources are not moved
  webapp/sources/rudder/rudder-web/src/main/elm/editor/sources/ViewTechniqueTabs.elm
Labels: Trigger test

#4077 Fixes #20474: error on system status tabs when there are missing reports
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/services/ReportDisplayer.scala
Labels: Trigger test
