Repository Normation/rudder, pull requests merged in 2021-03, with the labels that each got.

#3519 Fixes #18954: Compilation error after 18926 upmerge
  webapp/sources/ldap-inventory/inventory-repository/src/main/scala/com/normation/inventory/ldap/core/FullInventoryRepositoryImpl.scala
  webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/MockServices.scala
  webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/rest/RestTestSetUp.scala
Labels: Ready for merge

#3526 Fixes #18791: "By agent version" pie chart leads to empty page
  webapp/sources/rudder/rudder-web/src/main/webapp/secure/nodeManager/searchNodes.html
Labels: Trigger test

#3528 Fixes #18990: Rudder-lang doc misses a mkdir
  relay/sources/relayd/Makefile
  rudder-lang/Makefile
  rudder-lang/tools/generate_lib
  rust.makefile
Labels: Trigger test

#3529 Fixes #18991: Rudderify doc rudder-lang doc theme
  rudder-lang/Makefile
  rudder-lang/docs/assets/css/rudder.css
Labels: Ready for merge, Trigger test, qa: Can't merge

#3533 Fixes #18976: Implement missing calls in network client
  agent/sources/client/config/agent.conf
  agent/sources/client/src/cli.c
  agent/sources/client/src/config.c
  agent/sources/client/src/config.h
  agent/sources/client/src/http.c
  agent/sources/client/src/http.h
  agent/sources/client/src/utils.c
  agent/sources/client/src/utils.h
  agent/sources/client/tests/certs/README
  agent/sources/client/tests/certs/agent.cert
  agent/sources/client/tests/certs/agent.priv
  agent/sources/client/tests/certs/agent.pub
  agent/sources/client/tests/certs/server.cert
  agent/sources/client/tests/certs/server.nopass.priv
  agent/sources/client/tests/certs/server.priv
  agent/sources/client/tests/certs/server.pub
  agent/sources/client/tests/config/agent.toml
  agent/sources/client/tests/config/complete.toml
  agent/sources/client/tests/config/test.toml
  agent/sources/client/tests/config/uuid.hive
  agent/sources/client/tests/run.c
  agent/sources/client/tests/server.py
Labels: Trigger test, WIP

#3532 Fixes #18995: Missing mandatory directive parameter doesn't fail policy generation
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/DataStructures.scala
Labels: Trigger test, qa: Can't merge

#3535 Fixes #19004: FileUploadBaseSizeLimitExceededException with an 10MB inventory
  webapp/sources/ldap-inventory/inventory-provisioning-web/src/main/scala/com/normation/inventory/provisioning/endpoint/config/AppConfig.scala
Labels: Trigger test, qa: Can't merge

#3503 Fixes #18900: Missing exception details in change request update
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/DependencyAndDeletionService.scala
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/popup/ModificationValidationPopup.scala
Labels: Trigger test

#3525 Fixes #18978: Missing licence info in pom.xml
  webapp/sources/ldap-inventory/pom.xml
  webapp/sources/pom.xml
  webapp/sources/rudder/pom.xml
  webapp/sources/scala-ldap/pom.xml
  webapp/sources/utils/pom.xml
Labels: Trigger test, qa: Can't merge

#3521 Fixes #18959: Inherited node properties are not returned in API
  webapp/sources/api-doc/code_samples/curl/nodes/node-inherited-properties.sh
  webapp/sources/api-doc/components/parameters/include.yml
  webapp/sources/api-doc/components/schemas/node-inherited-properties.yml
  webapp/sources/api-doc/openapi.src.yml
  webapp/sources/api-doc/paths/nodes/inherited-properties.yml
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/NodeApi.scala
Labels: Trigger test

#3508 Fixes #18915: We don't know when generation hooks takes more time than expected, massively impacting generation time
  webapp/sources/rudder/rudder-core/src/main/resources/hooks.d/node-post-acceptance/hook-template
  webapp/sources/rudder/rudder-core/src/main/resources/hooks.d/node-post-deletion/hook-template
  webapp/sources/rudder/rudder-core/src/main/resources/hooks.d/node-pre-deletion/hook-template
  webapp/sources/rudder/rudder-core/src/main/resources/hooks.d/policy-generation-failed/hook-template
  webapp/sources/rudder/rudder-core/src/main/resources/hooks.d/policy-generation-finished/hook-template
  webapp/sources/rudder/rudder-core/src/main/resources/hooks.d/policy-generation-node-finished/hook-template
  webapp/sources/rudder/rudder-core/src/main/resources/hooks.d/policy-generation-node-ready/hook-template
  webapp/sources/rudder/rudder-core/src/main/resources/hooks.d/policy-generation-started/hook-template
  webapp/sources/rudder/rudder-core/src/main/resources/hooks.d/readme.adoc
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/cfclerk/services/impl/GitTechniqueReader.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/nodes/Properties.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/hooks/RunHooks.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/write/PolicyWriterService.scala
  webapp/sources/rudder/rudder-core/src/test/resources/hooks.d/test/timeout_ok.sh
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/hooks/HooksTest.scala
  webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/Boot.scala
Labels: Trigger test, qa: Can't merge

#3540 Fixes #18998: Add tests for Rudder client
  agent/sources/client/Makefile
  agent/sources/client/src/cli.c
  agent/sources/client/src/cli.h
  agent/sources/client/src/config.c
  agent/sources/client/src/config.h
  agent/sources/client/src/http.c
  agent/sources/client/src/http.h
  agent/sources/client/src/log.c
  agent/sources/client/src/log.h
  agent/sources/client/src/main.c
  agent/sources/client/src/utils.h
  agent/sources/client/tests/config/policy_server.dat
  agent/sources/client/tests/config/uuid.hive
  agent/sources/client/tests/run.c
  agent/sources/client/tests/server.py
Labels: Ready for merge, Trigger test, qa: Can't merge

#3544 Fixes #19028: AIX fails to build - bis
  agent/sources/client/argtable-aix.patch
  agent/sources/client/src/argtable3.c
  rudder-lang/tools/generate_lib
Labels: Trigger test

#3545 Fixes #19032: Hook timeout info must specify to add command near the top in the template
  webapp/sources/rudder/rudder-core/src/main/resources/hooks.d/node-post-acceptance/hook-template
  webapp/sources/rudder/rudder-core/src/main/resources/hooks.d/node-post-deletion/hook-template
  webapp/sources/rudder/rudder-core/src/main/resources/hooks.d/node-pre-deletion/hook-template
  webapp/sources/rudder/rudder-core/src/main/resources/hooks.d/policy-generation-failed/hook-template
  webapp/sources/rudder/rudder-core/src/main/resources/hooks.d/policy-generation-finished/hook-template
  webapp/sources/rudder/rudder-core/src/main/resources/hooks.d/policy-generation-node-finished/hook-template
  webapp/sources/rudder/rudder-core/src/main/resources/hooks.d/policy-generation-node-ready/hook-template
  webapp/sources/rudder/rudder-core/src/main/resources/hooks.d/policy-generation-started/hook-template
Labels: Trigger test

#3550 Fixes #19049: Error technique in editor
  webapp/sources/rudder/rudder-web/src/main/webapp/techeditor/js/ncf.js
Labels: Ready for merge

#3548 Fixes #19046: Add windows support to http client build
  agent/sources/client/Makefile
  agent/sources/client/toml.patch
Labels: Trigger test

#3444 Fixes #18669: Properly locate entity errors if the source has metadatas attached
  rudder-lang/.gitignore
  rudder-lang/src/parser.rs
  rudder-lang/src/parser/baseparsers.rs
  rudder-lang/src/parser/error.rs
  rudder-lang/src/parser/tests.rs
Labels: Trigger test, qa: Can't merge

#3554 Fixes #19065: Missing example for server key reset
  webapp/sources/api-doc/code_samples/curl/nodes/id-update.sh
  webapp/sources/api-doc/components/schemas/agent-key.yml
Labels: Trigger test, qa: Can't merge

#3552 Fixes #19048: replace library metadata by is_dependency based on cli parameters
  rudder-lang/src/command/compile.rs
  rudder-lang/src/generator/cfengine.rs
  rudder-lang/src/generator/dsc.rs
  rudder-lang/src/io.rs
  rudder-lang/src/ir/ir1.rs
  rudder-lang/src/ir/resource.rs
  rudder-lang/src/parser.rs
  rudder-lang/src/parser/tests.rs
  rudder-lang/src/rudderlang_lib.rs
  rudder-lang/src/technique/from_ir.rs
  rudder-lang/tools/generate_lib
  rudder-lang/tools/rudderc-dev.conf
Labels: Trigger test

#3555 Fixes #19072: Inventory named as "Report" in log message
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/inventory/InventoryProcessor.scala
Labels: Trigger test

#3556 Fixes #19080: Use Rust 1.51.0
  relay/sources/relayd/rust-toolchain
  rudder-lang/rust-toolchain
Labels: Trigger test

#3558 Fixes #19083: Split cargo-deny from qa-test
  rust.makefile
Labels: Trigger test

#3559 Fixes #18903: Vulnerabilities in relayd hyper dependency
  relay/sources/relayd/Cargo.lock
Labels: Trigger test, qa: Can't merge

#3560 Fixes #19087: Vulnerability in relayd dependencies diesel and generic-array
  relay/sources/relayd/Cargo.lock
Labels: Trigger test, qa: Can't merge

#3562 Fixes #19086: Add more tests for API (directives, techniques, parameters)
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/batch/UpdateDynamicGroups.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/DirectiveRepository.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/DependencyAndDeletionService.scala
  webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/techniques/systemSettings/misc/genericVariableDefinition/1.0/changelog
  webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/techniques/systemSettings/misc/genericVariableDefinition/1.0/genericVariableDefinition.st
  webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/techniques/systemSettings/misc/genericVariableDefinition/1.0/metadata.xml
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/RestDataSerializer.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/DirectiveApi.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/web/services/Translator.scala
  webapp/sources/rudder/rudder-rest/src/test/resources/api/api_directives.yml
  webapp/sources/rudder/rudder-rest/src/test/resources/api/api_parameters.yml
  webapp/sources/rudder/rudder-rest/src/test/resources/api/api_rules.yml
  webapp/sources/rudder/rudder-rest/src/test/resources/api/api_techniques.yml
  webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/MockServices.scala
  webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/rest/RestDataExtractorTest.scala
  webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/rest/RestTestSetUp.scala
  webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/rest/TestRestFromFileDef.scala
  webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala
Labels: Ready for merge, qa: Can't merge

#3564 Fixes #19096: Reload cf-serverd only is needed
  webapp/sources/rudder/rudder-core/src/main/resources/hooks.d/policy-generation-finished/50-reload-policy-file-server
Labels: Trigger test, qa: Can't merge

#3563 Fixes #19093: Parse id of method calls with rudderc
  rudder-lang/Cargo.lock
  rudder-lang/Cargo.toml
  rudder-lang/src/ir.rs
  rudder-lang/src/ir/enum_tree.rs
  rudder-lang/src/technique.rs
  rudder-lang/src/technique/from_ir.rs
Labels: Trigger test, qa: Can't merge

#3507 Fixes #18851: Allow verifying upstream server certificate when forwarding files
  relay/sources/relayd/Cargo.lock
  relay/sources/relayd/Cargo.toml
  relay/sources/relayd/src/api.rs
  relay/sources/relayd/src/api/remote_run.rs
  relay/sources/relayd/src/api/shared_files.rs
  relay/sources/relayd/src/configuration/main.rs
  relay/sources/relayd/src/data/node.rs
  relay/sources/relayd/src/lib.rs
  relay/sources/relayd/src/output/upstream.rs
  relay/sources/relayd/tests/files/config/main.conf
  relay/sources/relayd/tests/files/config/uuid.hive
  relay/sources/relayd/tests/files/keys/37817c4d-fbf7-4850-a985-50021f4e8f41.nopass.priv
  relay/sources/relayd/tests/files/nodeslist.json
  relay/sources/relayd/tests/processing_reporting.rs
  relay/sources/relayd/tests/remote_run.rs
  relay/sources/relayd/tests/server.py
  relay/sources/relayd/tools/config/logging.conf
  relay/sources/relayd/tools/config/main.conf
Labels: Trigger test, qa: Can't merge
