Repository Normation/rudder, pull requests merged in 2021-10, with the labels that each got.

#3910 Fixes #20041: rudder-lang in 7.0 should use ncf 7.0
  language/Makefile
Labels: Trigger test

#3911 Fixes #20051: Missing rights/role mapping for 7.0 endpoints
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/RoleApiMapping.scala
Labels: Trigger test

#3900 Fixes #19988: Number of CPU is wrongly reported
  webapp/sources/ldap-inventory/inventory-fusion/src/main/scala/com/normation/inventory/provisioning/fusion/FusionReportUnmarshaller.scala
  webapp/sources/ldap-inventory/inventory-fusion/src/test/resources/fusion-report/cpus-count.ocs
  webapp/sources/ldap-inventory/inventory-fusion/src/test/scala/com/normation/inventory/provisioning/fusion/TestReportParsing.scala
Labels: qa: Can't merge, Trigger test

#3907 Fixes #20036: Make a nice index page for logos
  logo/README.md
  logo/rudder-logo-rect-monochrome-white.svg
  logo/rudder-logo-square-monochrome-white.svg
Labels: qa: Can't merge, Trigger test

#3903 Fixes #20015: disable reporting in the technique editor does nothing in rudderc
  language/src/technique.rs
  language/tests/techniques/CIS/technique.json
  language/tests/techniques/cdt/technique.json
  language/tests/techniques/condition_alias/technique.json
  language/tests/techniques/condition_anybsd/technique.json
  language/tests/techniques/condition_dyn/technique.json
  language/tests/techniques/condition_errorprone/technique.json
  language/tests/techniques/condition_foreign_variable/technique.json
  language/tests/techniques/condition_priority/technique.json
  language/tests/techniques/condition_useless_brackets/technique.json
  language/tests/techniques/conditional_method/technique.json
  language/tests/techniques/deprecated/technique.json
  language/tests/techniques/dsc/technique.json
  language/tests/techniques/duplicated/technique.json
  language/tests/techniques/escaped/technique.json
  language/tests/techniques/inner_block/technique.json
  language/tests/techniques/multiple_simple/technique.json
  language/tests/techniques/parameters/technique.json
  language/tests/techniques/parameters_mult/technique.json
  language/tests/techniques/simple_block/technique.json
  language/tests/techniques/simplest/technique.json
  language/tests/techniques/stateless/technique.json
  language/tests/techniques/supported_formats/technique.json
  language/tools/generate_lib
Labels: qa: Can't merge, Trigger test

#3914 Fixes #20061: Use standard formatting for GPLv3
  LICENSE
Labels: Ready for merge, Trigger test
