Repository Normation/rudder, pull requests merged in 2021-07, with the labels that each got.

#3702 Fixes #19503: Vulnerability in spring-security
  webapp/sources/pom.xml
Labels: Ready for merge, Trigger test, qa: Can't merge

#3703 Fixes #19504: Fix certificate configuration for httpd
  relay/sources/apache/rudder-vhost.conf
  relay/sources/rudder-server-relay-postinst
  relay/sources/selinux/rudder-relay.fc
Labels: Ready for merge

#3704 Fixes #19456:
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/nodes/NodeInfoServiceCachedTest.scala
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/services/ComplianceData.scala
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/services/SrvGrid.scala
Labels: Trigger test

#3705 Fixes #19505:
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/nodes/Properties.scala
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/nodes/TestMergeGroupProperties.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/NodeApi.scala
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/ShowNodeDetailsFromNode.scala
  webapp/sources/rudder/rudder-web/src/main/webapp/javascript/rudder/rudder-datatable.js
Labels: Ready for merge

#3706 Fixes #19513: Hostname is not escpaed in page details title
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/nodes/Properties.scala
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/nodes/TestMergeGroupProperties.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/EndpointsDefinition.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/GroupsApi.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/NodeApi.scala
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/ShowNodeDetailsFromNode.scala
  webapp/sources/rudder/rudder-web/src/main/webapp/javascript/rudder/angular/nodeProperties.js
Labels: Ready for merge, Trigger test, qa: Can't merge

#3708 Fixes #19518: Property with inherited values display is broken on page reload on node list
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/NodeApi.scala
Labels: Ready for merge, Trigger test

#3701 Fixes #19502: Missing 'settings' layer in the allowed_networks API doc
  webapp/sources/api-doc/components/parameters/setting-allowed-networks.yml
  webapp/sources/api-doc/components/schemas/api-version.yml
  webapp/sources/api-doc/components/schemas/api-versions.yml
  webapp/sources/api-doc/openapi.src.yml
  webapp/sources/api-doc/paths/settings/allowed_networks.yml
  webapp/sources/api-doc/paths/settings/allowed_networks_diff.yml
Labels: Ready for merge, Trigger test, qa: Can't merge

#3709 Fixes #19520: Memory corruption in tokio
  relay/sources/relayd/Cargo.lock
Labels: Ready for merge, Trigger test

#3710 Fixes #19523: Improve command error message
  relay/sources/rudder-pkg/lib/rudder-pkg/rudderPkgUtils.py
Labels: Ready for merge

#3711 Fixes #19525: Read base64 hash in nodeslist.conf
  relay/sources/relayd/Cargo.lock
  relay/sources/relayd/Cargo.toml
  relay/sources/relayd/src/hashing.rs
  relay/sources/relayd/tests/files/nodeslist.json
Labels: Ready for merge, Trigger test, qa: Can't merge

#3714 Fixes #19530: CVE in jsonpath dependency
  webapp/sources/pom.xml
  webapp/sources/rudder/rudder-core/pom.xml
Labels: Ready for merge, Trigger test

#3712 Fixes #19528: Store hashes as bytes
  relay/sources/relayd/src/api/shared_files.rs
  relay/sources/relayd/src/api/shared_folder.rs
  relay/sources/relayd/src/data/node.rs
  relay/sources/relayd/src/data/shared_file.rs
  relay/sources/relayd/src/hashing.rs
Labels: Ready for merge, Trigger test

#3716 Fixes #19535: Correctly name LICENSES folder in repo
  LICENSES/CC-BY-SA-2.0.txt
  LICENSES/GPL-3.0-or-later.txt
  LICENSES/LicenseRef-RUDDER_EXCEPTION.txt
Labels: Ready for merge, Trigger test

#3715 Fixes #19529: Add root.pem and policy-server.pem in node inputs
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/write/PolicyWriterService.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/write/PrepareTemplateVariables.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/write/PromiseWriteDataStructures.scala
  webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/node-cfe-with-500-directives/rules/cfengine-community/certs/policy-server.pem
  webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/node-cfe-with-500-directives/rules/cfengine-community/certs/root.pem
  webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/node-cfe-with-500-directives/rules/cfengine-community/rudder.json
  webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/node-cfe-with-two-directives/rules/cfengine-community/certs/policy-server.pem
  webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/node-cfe-with-two-directives/rules/cfengine-community/certs/root.pem
  webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/node-cfe-with-two-directives/rules/cfengine-community/rudder.json
  webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/node-gen-var-def-override/rules/cfengine-community/certs/policy-server.pem
  webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/node-gen-var-def-override/rules/cfengine-community/certs/root.pem
  webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/node-gen-var-def-override/rules/cfengine-community/rudder.json
  webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/root-default-install/certs/policy-server.pem
  webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/root-default-install/certs/root.pem
  webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/root-default-install/common/1.0/cf-serverd.cf
  webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/root-default-install/distributePolicy/1.0/nodeslist.json
  webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/root-default-install/rudder.json
  webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/root-sys-var-false/certs/policy-server.pem
  webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/root-sys-var-false/certs/root.pem
  webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/root-sys-var-false/common/1.0/cf-serverd.cf
  webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/root-sys-var-false/distributePolicy/1.0/nodeslist.json
  webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/root-sys-var-false/rudder.json
  webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/root-with-one-multipolicy/certs/policy-server.pem
  webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/root-with-one-multipolicy/certs/root.pem
  webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/root-with-one-multipolicy/common/1.0/cf-serverd.cf
  webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/root-with-one-multipolicy/distributePolicy/1.0/nodeslist.json
  webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/root-with-one-multipolicy/rudder.json
  webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/root-with-two-directives/certs/policy-server.pem
  webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/root-with-two-directives/certs/root.pem
  webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/root-with-two-directives/common/1.0/cf-serverd.cf
  webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/root-with-two-directives/distributePolicy/1.0/nodeslist.json
  webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/root-with-two-directives/rudder.json
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/policies/NodeConfigData.scala
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/policies/TestWriteNodeCertificatesPem.scala
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/policies/write/WriteTechniquesTest.scala
Labels: Trigger test

#3721 Fixes #19538: Or selector for property Name=Value selector returns 0 elements
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/queries/CmdbQuery.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/nodes/NodeInfoService.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/queries/LdapQueryProcessor.scala
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/queries/TestQueryProcessor.scala
Labels: Ready for merge, Trigger test, qa: Can't merge

#3713 Fixes #19492: Add policy server certificate information to policies
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/cfclerk/services/impl/SystemVariableSpecServiceImpl.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/nodes/NodeInfo.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/reports/ExpectedReports.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/SystemVariableService.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/servers/RemoveNodeService.scala
  webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/node-cfe-with-500-directives/rules/cfengine-community/rudder.json
  webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/node-cfe-with-two-directives/rules/cfengine-community/rudder.json
  webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/node-gen-var-def-override/rules/cfengine-community/rudder.json
  webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/root-default-install/distributePolicy/1.0/nodeslist.json
  webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/root-default-install/rudder.json
  webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/root-sys-var-false/distributePolicy/1.0/nodeslist.json
  webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/root-sys-var-false/rudder.json
  webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/root-with-one-multipolicy/distributePolicy/1.0/nodeslist.json
  webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/root-with-one-multipolicy/rudder.json
  webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/root-with-two-directives/distributePolicy/1.0/nodeslist.json
  webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/root-with-two-directives/rudder.json
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/domain/nodes/NodeKeyHashTest.scala
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/services/DisplayNode.scala
Labels: Trigger test, qa: Can't merge

#3717 Fixes #18730: Move allowed network data to settings
  webapp/sources/api-doc/paths/settings/allowed_networks.yml
  webapp/sources/api-doc/paths/settings/allowed_networks_diff.yml
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/cfclerk/services/impl/SystemVariableSpecServiceImpl.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/Constants.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/SystemVariableService.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/servers/NewNodeManager.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/servers/PolicyServerData.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/servers/PolicyServerManagementService.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/servers/RemoveNodeService.scala
  webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/node-cfe-with-500-directives/rules/cfengine-community/common/1.0/cf-serverd.cf
  webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/node-cfe-with-500-directives/rules/cfengine-community/rudder.json
  webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/node-cfe-with-two-directives/rules/cfengine-community/common/1.0/cf-serverd.cf
  webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/node-cfe-with-two-directives/rules/cfengine-community/rudder.json
  webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/node-gen-var-def-override/rules/cfengine-community/common/1.0/cf-serverd.cf
  webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/node-gen-var-def-override/rules/cfengine-community/rudder.json
  webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/root-default-install/rudder.json
  webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/root-sys-var-false/rudder.json
  webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/root-with-one-multipolicy/rudder.json
  webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/root-with-two-directives/rudder.json
  webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/techniques/system/common/1.0/cf-serverd.st
  webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/techniques/system/common/1.0/metadata.xml
  webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/techniques/system/distributePolicy/1.0/metadata.xml
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/policies/NodeConfigData.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/appconfig/ConfigService.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/JsonSchema.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/SettingsApi.scala
  webapp/sources/rudder/rudder-rest/src/test/resources/api/api_settings.yml
  webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/MockServices.scala
  webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/rest/RestTestSetUp.scala
  webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/rest/TestRestFromFileDef.scala
  webapp/sources/rudder/rudder-templates-cli/src/test/resources/templates1/cf-served.st
  webapp/sources/rudder/rudder-templates-cli/src/test/resources/templates1/variables.json
  webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/administration/EditPolicyServerAllowedNetwork.scala
  webapp/sources/utils/src/main/scala/com/normation/ZioCommons.scala
Labels: Trigger test

#3718 Fixes #19536: Do not fail technique parsing on missing system variable
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/cfclerk/xmlparsers/TechniqueParser.scala
Labels: Trigger test

#3720 Fixes #19537: Add Kali Linux to the list of recognized OS
  webapp/sources/api-doc/components/schemas/os.yml
  webapp/sources/ldap-inventory/inventory-api/src/main/scala/com/normation/inventory/domain/NodeInventory.scala
  webapp/sources/ldap-inventory/inventory-fusion/src/main/scala/com/normation/inventory/provisioning/fusion/FusionReportUnmarshaller.scala
  webapp/sources/ldap-inventory/inventory-repository/src/main/scala/com/normation/inventory/ldap/core/InventoryMapper.scala
  webapp/sources/ldap-inventory/inventory-repository/src/main/scala/com/normation/inventory/ldap/core/LDAPConstants.scala
  webapp/sources/rudder/rudder-web/src/main/resources/ldapObjectAndAttributes.properties
  webapp/sources/rudder/rudder-web/src/main/webapp/images/os/kali-logo.svg
  webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-node.css
Labels: Trigger test

#3719 Fixes #18140: Remove syslog-related config from webapp
  webapp/sources/api-doc/components/schemas/settings.yml
  webapp/sources/rudder/rudder-core/src/main/resources/ldap/bootstrap.ldif
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/cfclerk/services/impl/SystemVariableSpecServiceImpl.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/reports/ReportingConfiguration.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/SystemVariableService.scala
  webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/node-cfe-with-500-directives/rules/cfengine-community/promises.cf
  webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/node-cfe-with-500-directives/rules/cfengine-community/rudder.json
  webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/node-cfe-with-two-directives/rules/cfengine-community/promises.cf
  webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/node-cfe-with-two-directives/rules/cfengine-community/rudder.json
  webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/node-gen-var-def-override/rules/cfengine-community/promises.cf
  webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/node-gen-var-def-override/rules/cfengine-community/rudder.json
  webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/root-default-install/promises.cf
  webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/root-default-install/rudder.json
  webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/root-sys-var-false/promises.cf
  webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/root-sys-var-false/rudder.json
  webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/root-with-one-multipolicy/promises.cf
  webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/root-with-one-multipolicy/rudder.json
  webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/root-with-two-directives/promises.cf
  webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/root-with-two-directives/rudder.json
  webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/techniques/system/common/1.0/metadata.xml
  webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/techniques/system/common/1.0/promises.st
  webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/techniques/system/distributePolicy/1.0/metadata.xml
  webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/techniques/system/distributePolicy/1.0/rudder-rsyslog-relay.st
  webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/techniques/system/distributePolicy/1.0/rudder-rsyslog-root.st
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/policies/NodeConfigData.scala
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/queries/TestQueryProcessor.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/appconfig/ConfigService.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/SettingsApi.scala
  webapp/sources/rudder/rudder-rest/src/test/resources/api/api_settings.yml
  webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/MockServices.scala
  webapp/sources/rudder/rudder-templates-cli/src/test/resources/templates1/expected/promises
  webapp/sources/rudder/rudder-templates-cli/src/test/resources/templates1/promises.st
  webapp/sources/rudder/rudder-templates-cli/src/test/resources/templates1/variables.json
  webapp/sources/rudder/rudder-web/src/main/resources/configuration.properties.sample
  webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/administration/PropertiesManagement.scala
  webapp/sources/rudder/rudder-web/src/main/webapp/secure/administration/policyServerManagement.html
Labels: Ready for merge, Trigger test

#3722 Fixes #19550: Rudder-server-relay postinstall script fails to modify the certificate paths in the apache configuration
  relay/sources/rudder-server-relay-postinst
Labels: Trigger test, qa: Can't merge

#3725 Fixes #19556: Modify the internal rules and directives at install time to support the new system techniques
  webapp/sources/rudder/rudder-core/src/main/resources/ldap/bootstrap.ldif
  webapp/sources/rudder/rudder-core/src/main/resources/ldap/init-policy-server.ldif
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/queries/TestQueryProcessor.scala
Labels: Ready for merge, Trigger test

#3731 Fixes #19568: Correct rudder bootchecks to match new structure
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/Constants.scala
  webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/checks/CheckDIT.scala
Labels: Trigger test

#3730 Fixes #19555: Allow the creation of a rule in the new IU
  webapp/sources/rudder/rudder-web/src/main/elm/rules/elm.json
  webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/ApiCalls.elm
  webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/DataTypes.elm
  webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/View.elm
  webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/rudder-rules.elm
Labels: Trigger test

#3729 Fixes #19567: Rudder fails to stop on boot error
  webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/LiftInitContextListener.scala
  webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala
Labels: Trigger test, qa: Can't merge

#3732 Fixes #19569: Prevent race condition in relayd tests
  Jenkinsfile
Labels: Ready for merge, Trigger test, qa: Can't merge

#3733 Fixes #19570: Normalize system technique, directive, rule names
  webapp/sources/rudder/rudder-core/src/main/resources/ldap/bootstrap.ldif
  webapp/sources/rudder/rudder-core/src/main/resources/ldap/init-policy-server.ldif
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/cfclerk/xmlparsers/TechniqueParser.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/ldap/LDAPEntityMapper.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/SystemVariableService.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/servers/PolicyServerData.scala
  webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/checks/CheckDIT.scala
Labels: Ready for merge, Trigger test

#3736 Fixes #19579: Create the Actions button dropdown
  webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/View.elm
  webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-technique-editor.css
  webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-template.css
Labels: Trigger test

#3735 Fixes #19547: Relayd deadlocks when trying to forward a shared-file
  relay/sources/relayd/src/api/shared_files.rs
Labels: Trigger test

#3738 Fixes #19588: Missing lint section in rudderc config file
  language/tools/rudderc-prod.conf
Labels: Ready for merge, Trigger test

#3737 Fixes #19587: Still a Path.of in TestRestFromFileDef.scala
  webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/rest/TestRestFromFileDef.scala
Labels: Trigger test

#3739 Fixes #19586: Parent task failed to stop jetty when ldap connection is down at boot
  webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/LiftInitContextListener.scala
  webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala
Labels: Trigger test

#3740 Fixes #19589: NoSuchFileException: /var/rudder/policy-generation-info/node-configuration-hashes.json
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/nodeconfig/NodeConfigurationCacheRepository.scala
Labels: Trigger test, qa: Can't merge

#3742 Fixes #19597: Properties tab is broken in rudder 7.0
  webapp/sources/rudder/rudder-web/src/main/webapp/javascript/rudder/angular/nodeProperties.js
Labels: Ready for merge, Trigger test

#3743 Fixes #19600: error getting techniques when coming back on technique page
  webapp/sources/rudder/rudder-web/src/main/elm/editor/sources/JsonDecoder.elm
  webapp/sources/rudder/rudder-web/src/main/elm/editor/sources/rudder-editor.elm
Labels: Trigger test

#3745 Fixes #19607: wrong correction in parent ticket
  webapp/sources/rudder/rudder-core/src/main/resources/hooks.d/policy-generation-finished/40-nodelist-relay-configuration
Labels: Ready for merge, Trigger test

#3734 Fixes #19576: Add system configuration object for scale-out-relay plugin
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/policies/Rule.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/servers/PolicyServerManagementService.scala
Labels: Trigger test

#3744 Fixes #19605: "reporting based on" is duplicated on component
  webapp/sources/rudder/rudder-web/src/main/elm/editor/sources/ViewBlock.elm
  webapp/sources/rudder/rudder-web/src/main/elm/editor/sources/ViewMethod.elm
Labels: Trigger test

#3746 Fixes #19609: versionning is too technical on the directive tree
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/xml/GitArchiverImpl.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/eventlog/HistorizationService.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/marshalling/XmlSerialisation.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/quicksearch/QuickSearchBackendImpl.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/workflows/CommitAndDeployChangeRequestService.scala
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/policies/write/WriteTechniquesTest.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/TechniqueApi.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/web/services/EventLogDetailsGenerator.scala
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/services/DisplayDirectiveTree.scala
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/configuration/DirectiveManagement.scala
Labels: Ready for merge, Trigger test

#3748 Fixes #19617: Rename settings menu to administration
  webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/Boot.scala
Labels: Trigger test

#3747 Fixes #19614: Remove server roles in node details
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/services/DisplayNode.scala
Labels: Trigger test

#3457 Fixes #18772: Create a parser for encrypted properties feature
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/logger/ApplicationLogger.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/nodes/PropertyEngineService.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/DataStructures.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/DeploymentService.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/InterpolatedValueCompiler.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/RuleValService.scala
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/ncf/TestEditorTechniqueWriter.scala
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/policies/RuleValServiceTest.scala
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/policies/TestBuildNodeConfiguration.scala
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/policies/TestNodeAndGlobalParameterLookup.scala
  webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala
Labels: Ready for merge, Trigger test

#3750 Fixes #19626: Update Rust to 1.54.0
  language/Cargo.lock
  language/rust-toolchain
  language/tests/utils/mod.rs
  relay/sources/relayd/Cargo.lock
  relay/sources/relayd/rust-toolchain
  relay/sources/relayd/src/api/metrics.rs
  relay/sources/relayd/src/data/node.rs
  relay/sources/relayd/src/output/database.rs
  rust.makefile
Labels: Trigger test

#3753 Fixes #19631: It is impossible to read properties with a read-only account
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/RoleApiMapping.scala
Labels: Trigger test, qa: Can't merge

#3695 Fixes #19476: Make rudder package command use version files
  relay/sources/rudder-pkg/lib/rudder-pkg/rudderPkg.py
  relay/sources/rudder-pkg/lib/rudder-pkg/rudderPkgUtils.py
Labels: Trigger test

#3755 Fixes #19581: Improving the UX when creating a rule
  webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/DataTypes.elm
  webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/View.elm
  webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/rudder-rules.elm
  webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-rules.css
  webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-technique-editor.css
  webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-template.css
Labels: Ready for merge, Trigger test

#3760 Fixes #19642: Adapt code to scale-out-relay in rudder 7
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/eventlog/EventLogCategories.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/eventlog/NodeEventLog.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/EventLogRepository.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/ldap/LDAPDirectiveRepository.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/ldap/LDAPEntityMapper.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/ldap/LDAPRuleRepository.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/eventlog/EventLogFactory.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/servers/PolicyServerManagementService.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/web/services/EventLogDetailsGenerator.scala
Labels: Ready for merge, Trigger test

#3752 Fixes #19630: more server role/component cleaning
  webapp/sources/rudder/rudder-core/src/main/resources/ldap/bootstrap.ldif
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/quicksearch/QuickSearchBackendImpl.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/quicksearch/QuickSearchDomain.scala
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/queries/TestQueryProcessor.scala
  webapp/sources/rudder/rudder-web/src/main/webapp/templates-hidden/server/server_details.html
Labels: Ready for merge, Trigger test
