Repository Normation/rudder, pull requests merged in 2021-04, with the labels that each got.

#3567 Fixes #19108: Syntax helper in the parameter page is outdated
  webapp/sources/rudder/rudder-web/src/main/webapp/secure/configurationManager/parameterManagement.html
Labels: Trigger test, qa: Can't merge

#3569 Fixes #19112: reload cf-serverd only if file changed
  webapp/sources/rudder/rudder-core/src/main/resources/hooks.d/policy-generation-finished/50-reload-policy-file-server
Labels: Trigger test, qa: Can't merge

#3568 Fixes #19085: Inherited node properties are displayed with escape
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/nodes/Properties.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/EndpointsDefinition.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/NodeApi.scala
  webapp/sources/rudder/rudder-web/src/main/webapp/javascript/rudder/angular/nodeProperties.js
Labels: Trigger test

#3570 Fixes #19114: Overridden directives in the same rule are missing (not even "skipped")
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/reports/ReportingServiceImpl.scala
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/reports/ReportingServiceUtilsTest.scala
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/services/ComplianceData.scala
Labels: Ready for merge, Trigger test

#3571 Fixes #19115: Allow to put empty value in technique parameters
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/ncf/Technique.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/ncf/TechniqueWriter.scala
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/ncf/TestTechniqueWriter.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/RestExtractorService.scala
Labels: qa: Can't merge

#3524 Fixes #18853: Make an onboarding wizard in Elm
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/plugins/PluginSettings.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/SystemVariableService.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/appconfig/ConfigService.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/EndpointsDefinition.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/PluginApi.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/SettingsApi.scala
  webapp/sources/rudder/rudder-web/src/main/elm/build-app.sh
  webapp/sources/rudder/rudder-web/src/main/elm/onboarding/elm.json
  webapp/sources/rudder/rudder-web/src/main/elm/onboarding/sources/ApiCalls.elm
  webapp/sources/rudder/rudder-web/src/main/elm/onboarding/sources/DataTypes.elm
  webapp/sources/rudder/rudder-web/src/main/elm/onboarding/sources/Init.elm
  webapp/sources/rudder/rudder-web/src/main/elm/onboarding/sources/JsonDecoder.elm
  webapp/sources/rudder/rudder-web/src/main/elm/onboarding/sources/JsonEncoder.elm
  webapp/sources/rudder/rudder-web/src/main/elm/onboarding/sources/View.elm
  webapp/sources/rudder/rudder-web/src/main/elm/onboarding/sources/rudder-onboarding.elm
  webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/Boot.scala
  webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/SendMetricsPopup.scala
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/administration/PropertiesManagement.scala
  webapp/sources/rudder/rudder-web/src/main/webapp/secure/administration/policyServerManagement.html
  webapp/sources/rudder/rudder-web/src/main/webapp/secure/administration/setup.html
  webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-wizard.css
Labels: Trigger test

#3574 Fixes #19119: Add empty technique parameter in technique editor (6.2 only)
  webapp/sources/rudder/rudder-web/src/main/webapp/secure/configurationManager/techniqueEditor.html
  webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-technique-editor.css
  webapp/sources/rudder/rudder-web/src/main/webapp/techeditor/js/ncf.js
Labels: qa: Can't merge

#3576 Fixes #19124: Group properties fails with missing "displayInheritedProperties" API
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/EndpointsDefinition.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/GroupsApi.scala
Labels: Trigger test

#3565 Fixes #19101: Client fails to validate certs on some systems
  agent/sources/client/Makefile
  agent/sources/client/config/agent.conf
  agent/sources/client/qa-test
  agent/sources/client/src/config.c
  agent/sources/client/src/config.h
  agent/sources/client/src/http.c
  agent/sources/client/tests/certs/README
  agent/sources/client/tests/certs/README.md
  agent/sources/client/tests/certs/policy_server_hash
  agent/sources/client/tests/certs/server.pem
  agent/sources/client/tests/config/complete.toml
  agent/sources/client/tests/config/empty.toml
  agent/sources/client/tests/config/minimal.toml
  agent/sources/client/tests/config/test.toml
  agent/sources/client/tests/run.c
  qa-test
  relay/arch-doc/rudder-6-reporting-relayd.md
  relay/sources/relayd/tests/files/keys/e745a140-40bc-4b86-b6dc-084488fc906b.nopass.priv
  relay/sources/relayd/tests/remote_run.rs
  relay/sources/relayd/tests/server.py
Labels: Trigger test, qa: Can't merge

#3578 Fixes #19131: cf-serverd always reloads
  webapp/sources/rudder/rudder-core/src/main/resources/hooks.d/policy-generation-finished/50-reload-policy-file-server
Labels: Trigger test

#3579 Fixes #19129: Clone group via API ask for query
  webapp/sources/api-doc/paths/groups/all.yml
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/batch/UpdateDynamicGroups.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/nodes/NodeGroupDiff.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/ldap/LDAPDiffMapper.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/RestDataSerializer.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/data/RestData.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/GroupsApi.scala
  webapp/sources/rudder/rudder-rest/src/test/resources/api/api_groups.yml
  webapp/sources/rudder/rudder-rest/src/test/resources/api/api_nodes.yml
  webapp/sources/rudder/rudder-rest/src/test/resources/api/api_rules.yml
  webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/MockServices.scala
  webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/rest/RestTestSetUp.scala
  webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala
Labels: Trigger test

#3580 Fixes #19136: Delay remote trigger on change
  webapp/sources/rudder/rudder-core/src/main/resources/hooks.d/policy-generation-finished/60-trigger-node-update
Labels: Trigger test, qa: Can't merge

#3581 Fixes #19138: Add an option to invert result of a node query
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/queries/CmdbQuery.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/queries/CmdbQueryParser.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/queries/LdapQueryProcessor.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/servers/NewNodeManager.scala
  webapp/sources/rudder/rudder-core/src/test/resources/ldap-data/inventory-sample-data.ldif
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/nodes/TestMergeGroupProperties.scala
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/queries/TestJsonQueryLexing.scala
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/queries/TestPendingNodePolicies.scala
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/queries/TestQueryProcessor.scala
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/queries/TestStringQueryParser.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/RestExtractorService.scala
  webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/checks/CheckSystemGroups.scala
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/SearchNodeComponent.scala
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/popup/CreateCategoryOrGroupPopup.scala
  webapp/sources/rudder/rudder-web/src/main/webapp/templates-hidden/server/server_details.html
Labels: Trigger test

#3582 Fixes #19139: "isBlank" is not supported in jvm8
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/RestExtractorService.scala
Labels: Ready for merge, Trigger test

#3584 Fixes #19143: inverting a request with 0 answer leads to 0 answer
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/queries/LdapQueryProcessor.scala
  webapp/sources/rudder/rudder-core/src/test/resources/ldap-data/inventory-sample-data.ldif
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/queries/TestQueryProcessor.scala
Labels: Ready for merge, Trigger test, qa: Can't merge

#3585 Fixes #19145: parent ticket broke the rudder-pkg tests
  relay/sources/rudder-pkg/lib/rudder-pkg/rpkg.py
  relay/sources/rudder-pkg/lib/rudder-pkg/tests/test.py
Labels: Ready for merge, Trigger test

#3587 Fixes #19149: Fix compilation issue
  webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/rest/RestTestSetUp.scala
Labels: Ready for merge

#3586 Fixes #19146: in some case inverting a request leads to an error and 0 results
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/queries/LdapQueryProcessor.scala
Labels: Ready for merge, Trigger test

#3589 Fixes #19158: Cannot load file browser if subfolders of the shared-folder contain dead symlinks
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/internal/SharedFilesAPI.scala
Labels: Ready for merge

#3551 Fixes #18999: when we install a plugin, if the dependency (package manager) is not met, it still tries to install it and fails
  relay/sources/rudder-pkg/lib/rudder-pkg/rudderPkgUtils.py
Labels: Ready for merge, qa: Can't merge

#3590 Fixes #19160: Query type constructor broke scale out relay plugin
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/queries/CmdbQuery.scala
Labels: Ready for merge, qa: Can't merge

#3592 Fixes #19164:
  contributing/settings.xml
  webapp/sources/ldap-inventory/pom.xml
  webapp/sources/pom.xml
  webapp/sources/rudder/pom.xml
  webapp/sources/scala-ldap/pom.xml
Labels: Ready for merge, Trigger test

#3593 Fixes #19170: Binary compatibility still broken by query
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/RudderDit.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/nodes/NodeGroup.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/nodes/NodeGroupDiff.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/queries/CmdbQuery.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/eventlog/EventLogDetailsService.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/eventlog/EventLogFactory.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/queries/CmdbQueryParser.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/queries/DynGroupService.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/queries/LdapQueryProcessor.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/queries/QueryProcessor.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/servers/NewNodeManager.scala
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/nodes/TestMergeGroupProperties.scala
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/queries/TestPendingNodePolicies.scala
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/queries/TestQueryProcessor.scala
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/queries/TestStringQueryParser.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/RestDataSerializer.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/RestExtractorService.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/data/RestData.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/NodeApi.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/web/services/EventLogDetailsGenerator.scala
  webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/MockServices.scala
  webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/checks/CheckSystemGroups.scala
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/NodeGroupForm.scala
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/SearchNodeComponent.scala
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/popup/CreateCategoryOrGroupPopup.scala
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/node/SearchNodes.scala
Labels: Ready for merge

#3594 Fixes #19171: Lots of files are created in /var/rudder/inventories/debug
  webapp/sources/ldap-inventory/inventory-provisioning-core/src/main/scala/com/normation/inventory/ldap/provisioning/LdifReportLogger.scala
Labels: Ready for merge, qa: Can't merge

#3596 Fixes #19180: Broken pom after merge
  webapp/sources/pom.xml
Labels: Trigger test

#3600 Fixes #19185: postinstall fails on machines with long hostname
  relay/sources/rudder-server-relay-postinst
Labels: Trigger test

#3602 Fixes #19186: Webapp tests fail if repository path contains an '@'
  webapp/sources/ldap-inventory/inventory-fusion/src/test/scala/com/normation/inventory/provisioning/fusion/TestReportParsing.scala
  webapp/sources/ldap-inventory/inventory-repository/src/test/scala/com/normation/history/impl/TestFileHistoryLogRepository.scala
  webapp/sources/ldap-inventory/inventory-repository/src/test/scala/com/normation/inventory/ldap/core/TestInventory.scala
  webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/techniques/applications/rpmPackageInstallation/7.0/metadata.xml
  webapp/sources/rudder/rudder-core/src/test/resources/test-compliance/test-same-directive-several-rules/nodeconfig
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/cfclerk/domain/SectionTest.scala
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/domain/reports/StatusReportTest.scala
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/hooks/HooksTest.scala
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/inventory/TestCertificate.scala
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/repository/ldap/CheckNormationOidTest.scala
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/repository/ldap/LoadDemoDataTest.scala
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/policies/NodeConfigData.scala
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/policies/TestBuildNodeConfiguration.scala
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/policies/write/PolicyAgregationTest.scala
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/policies/write/WriteTechniquesTest.scala
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/queries/TestQueryProcessor.scala
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/reports/CachedFindRuleNodeStatusReportsTest.scala
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/reports/ExecutionBatchTest.scala
  webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/rest/TestRestFromFileDef.scala
  webapp/sources/scala-ldap/src/test/scala/com/normation/ldap/sdk/LDAPTreeTest.scala
  webapp/sources/scala-ldap/src/test/scala/com/normation/ldap/sdk/LoadDemoDataTest.scala
Labels: Ready for merge, Trigger test

#3601 Fixes #19187: Detection of dependencies for plugin can fail if the python lib of another distrib is present
  relay/sources/rudder-pkg/lib/rudder-pkg/rudderPkgUtils.py
Labels: Trigger test

#3599 Fixes #19184: Add scripts to setup Rust build environements in CI
  Jenkinsfile
  Jenkinsfile-security
  relay/sources/relayd/Makefile
  rust.makefile
Labels: Trigger test, qa: Can't merge

#3603 Fixes #19192: Broken security checks with cargo
  Jenkinsfile-security
Labels: Trigger test

#3605 Fixes #19197: Add maven deploy task to pipeline
  Jenkinsfile
  Jenkinsfile-security
Labels: Trigger test, qa: Can't merge

#3606 Fixes #19198: Broken mvn in Jenkinsfile-security
  Jenkinsfile-security
Labels: Trigger test

#3604 Fixes #19195: Add rudder-lang publication to Jenkinsfile
  Jenkinsfile
  relay/sources/relayd/tests/common.rs
  relay/sources/relayd/tests/processing_reporting.rs
  rudder-lang/src/parser/error.rs
  rudder-lang/src/technique.rs
  rudder-lang/tests/utils/mod.rs
  rust.makefile
Labels: Trigger test, WIP, qa: Can't merge

#3607 Fixes #19200: Broken language-publish step
  Jenkinsfile
Labels: Ready for merge, qa: Can't merge

#3609 Fixes #19009: cis technique compiler fixes
  rudder-lang/.gitignore
  rudder-lang/src/generator/cfengine.rs
  rudder-lang/src/generator/cfengine/syntax.rs
  rudder-lang/src/generator/dsc.rs
  rudder-lang/src/generator/dsc/syntax.rs
  rudder-lang/src/io/output.rs
  rudder-lang/src/ir/context.rs
  rudder-lang/src/ir/enums.rs
  rudder-lang/src/ir/ir1.rs
  rudder-lang/src/ir/ir2.rs
  rudder-lang/src/ir/resource.rs
  rudder-lang/src/ir/value.rs
  rudder-lang/src/ir/variable.rs
  rudder-lang/src/parser.rs
  rudder-lang/src/technique.rs
  rudder-lang/src/technique/from_ir.rs
  rudder-lang/tests/compile.rs
  rudder-lang/tests/techniques/6.1.rc5/technique.rl
  rudder-lang/tests/techniques/6.1.rc5/technique.rl.cf
  rudder-lang/tests/techniques/6.1.rc5/technique.rl.json
  rudder-lang/tests/techniques/6.2-CIS/technique.cf
  rudder-lang/tests/techniques/6.2-CIS/technique.json
  rudder-lang/tests/techniques/6.2-CIS/technique.ps1
  rudder-lang/tests/techniques/cis/technique.cf
  rudder-lang/tests/techniques/cis/technique.json
  rudder-lang/tests/techniques/cis/technique.ps1
  rudder-lang/tests/techniques/condition_alias/technique.cf
  rudder-lang/tests/techniques/condition_alias/technique.ps1
  rudder-lang/tests/techniques/condition_foreign_variable/technique.cf
  rudder-lang/tests/techniques/condition_foreign_variable/technique.ps1
  rudder-lang/tests/techniques/condition_useless_brackets/technique.json
  rudder-lang/tests/techniques/condition_useless_brackets/technique.ps1
  rudder-lang/tests/techniques/deprecated/technique.json
  rudder-lang/tests/techniques/deprecated/technique.ps1
  rudder-lang/tests/techniques/duplicated/technique.ps1
  rudder-lang/tests/techniques/escaped/technique.cf
  rudder-lang/tests/techniques/escaped/technique.json
  rudder-lang/tests/techniques/escaped/technique.ps1
  rudder-lang/tests/techniques/mob/technique.cf
  rudder-lang/tests/techniques/mob/technique.json
  rudder-lang/tests/techniques/mob/technique.ps1
  rudder-lang/tests/techniques/simplest/technique.cf
  rudder-lang/tests/techniques/stateless/technique.cf
  rudder-lang/tests/techniques/stateless/technique.json
  rudder-lang/tests/techniques/stateless/technique.ps1
  rudder-lang/tests/techniques/supported_formats/technique.rl
  rudder-lang/tests/techniques/supported_formats/technique.rl.cf
  rudder-lang/tools/generate_lib
  rudder-lang/tools/rudderc-dev.conf
  rudder-lang/tools/test_all_techniques.sh
Labels: Ready for merge
