Repository Normation/rudder, pull requests merged in 2022-12, with the labels that each got.

#4574 Fixes #22094: Build frontend files with gulp
  Jenkinsfile
  Jenkinsfile-security
  qa-test
  webapp/sources/Dockerfile
  webapp/sources/rudder/rudder-web/pom.xml
  webapp/sources/rudder/rudder-web/src/main/build.sh
  webapp/sources/rudder/rudder-web/src/main/elm/Dockerfile
  webapp/sources/rudder/rudder-web/src/main/elm/accounts/build-dev.sh
  webapp/sources/rudder/rudder-web/src/main/elm/build.sh
  webapp/sources/rudder/rudder-web/src/main/elm/editor/build-dev.sh
  webapp/sources/rudder/rudder-web/src/main/elm/hooks/build-dev.sh
  webapp/sources/rudder/rudder-web/src/main/elm/notifications/build-dev.sh
  webapp/sources/rudder/rudder-web/src/main/elm/onboarding/build-dev.sh
  webapp/sources/rudder/rudder-web/src/main/elm/rules/build-dev.sh
  webapp/sources/rudder/rudder-web/src/main/gulpfile.js
  webapp/sources/rudder/rudder-web/src/main/package-lock.json
  webapp/sources/rudder/rudder-web/src/main/package.json
  webapp/sources/rudder/rudder-web/src/main/webapp/templates-hidden/common-layout.html
Labels: qa: Can't merge

#4601 Fixes #22176: Monthly schedule in January/December can be wrong
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/campaigns/MainCampaignService.scala
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/campaign/CampaignSchedulerTest.scala
Labels: Ready for merge

#4598 Fixes #22169: Update spring version to last one on rudder 7.2
  webapp/sources/pom.xml
Labels: qa: Can't merge

#4549 Fixes # 22011: update javascript libraries
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/web/services/EventLogDetailsGenerator.scala
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/services/DisplayNode.scala
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/services/NodeGrid.scala
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/services/ReportDisplayer.scala
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/configuration/ParameterManagement.scala
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/node/AcceptNode.scala
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/node/PendingHistoryGrid.scala
  webapp/sources/rudder/rudder-web/src/main/webapp/javascript/angular/angucomplete-alt.min.js
  webapp/sources/rudder/rudder-web/src/main/webapp/javascript/angular/angular-animate.min.js
  webapp/sources/rudder/rudder-web/src/main/webapp/javascript/angular/angular-animate.min.js.map
  webapp/sources/rudder/rudder-web/src/main/webapp/javascript/angular/angular-filemanager.min.js
  webapp/sources/rudder/rudder-web/src/main/webapp/javascript/angular/angular-touch.min.js
  webapp/sources/rudder/rudder-web/src/main/webapp/javascript/angular/angular-touch.min.js.map
  webapp/sources/rudder/rudder-web/src/main/webapp/javascript/angular/angular-translate.min.js
  webapp/sources/rudder/rudder-web/src/main/webapp/javascript/angular/angular.min.js
  webapp/sources/rudder/rudder-web/src/main/webapp/javascript/angular/angular.min.js.map
  webapp/sources/rudder/rudder-web/src/main/webapp/javascript/angular/elastic.min.js
  webapp/sources/rudder/rudder-web/src/main/webapp/javascript/angular/ng-file-upload.min.js
  webapp/sources/rudder/rudder-web/src/main/webapp/javascript/jquery/jquery-ui.min.js
  webapp/sources/rudder/rudder-web/src/main/webapp/javascript/rudder/angular/nodeProperties.js
  webapp/sources/rudder/rudder-web/src/main/webapp/javascript/rudder/angular/quicksearch.js
  webapp/sources/rudder/rudder-web/src/main/webapp/javascript/rudder/rudder-datatable.js
  webapp/sources/rudder/rudder-web/src/main/webapp/style/jquery-ui/images/ui-anim_basic_16x16.gif
  webapp/sources/rudder/rudder-web/src/main/webapp/style/jquery-ui/images/ui-bg_glass_55_fbf9ee_1x400.png
  webapp/sources/rudder/rudder-web/src/main/webapp/style/jquery-ui/images/ui-bg_glass_65_ffffff_1x400.png
  webapp/sources/rudder/rudder-web/src/main/webapp/style/jquery-ui/images/ui-bg_glass_75_dadada_1x400.png
  webapp/sources/rudder/rudder-web/src/main/webapp/style/jquery-ui/images/ui-bg_glass_75_e6e6e6_1x400.png
  webapp/sources/rudder/rudder-web/src/main/webapp/style/jquery-ui/images/ui-bg_glass_95_fef1ec_1x400.png
  webapp/sources/rudder/rudder-web/src/main/webapp/style/jquery-ui/images/ui-bg_highlight-soft_75_cccccc_1x100.png
  webapp/sources/rudder/rudder-web/src/main/webapp/style/jquery-ui/images/ui-icons_222222_256x240.png
  webapp/sources/rudder/rudder-web/src/main/webapp/style/jquery-ui/images/ui-icons_2e83ff_256x240.png
  webapp/sources/rudder/rudder-web/src/main/webapp/style/jquery-ui/images/ui-icons_444444_256x240.png
  webapp/sources/rudder/rudder-web/src/main/webapp/style/jquery-ui/images/ui-icons_454545_256x240.png
  webapp/sources/rudder/rudder-web/src/main/webapp/style/jquery-ui/images/ui-icons_555555_256x240.png
  webapp/sources/rudder/rudder-web/src/main/webapp/style/jquery-ui/images/ui-icons_777620_256x240.png
  webapp/sources/rudder/rudder-web/src/main/webapp/style/jquery-ui/images/ui-icons_777777_256x240.png
  webapp/sources/rudder/rudder-web/src/main/webapp/style/jquery-ui/images/ui-icons_888888_256x240.png
  webapp/sources/rudder/rudder-web/src/main/webapp/style/jquery-ui/images/ui-icons_cc0000_256x240.png
  webapp/sources/rudder/rudder-web/src/main/webapp/style/jquery-ui/images/ui-icons_cd0a0a_256x240.png
  webapp/sources/rudder/rudder-web/src/main/webapp/style/jquery-ui/images/ui-icons_ffffff_256x240.png
Labels: qa: Can't merge, Ready for merge

#4609 Fixes #22195: update dependency check exception
  webapp/sources/dependency-check-suppression.xml
Labels: qa: Can't merge, Ready for merge

#4604 Fixes #22186: Authorize "_" (underscore) in hostname / fqdn
  webapp/sources/utils/src/main/scala/com/normation/utils/StandardFieldsValidation.scala
  webapp/sources/utils/src/test/scala/com/normation/utils/TestStandardFieldValidation.scala
Labels: qa: Can't merge

#4619 Fixes #22217: Improve npm audit
  Jenkinsfile-security
  webapp/sources/rudder/rudder-web/src/main/.nsprc
  webapp/sources/rudder/rudder-web/src/main/package-lock.json
  webapp/sources/rudder/rudder-web/src/main/package.json
Labels: Ready for merge

#4620 Fixes #22216: Missing support for Windows 2022
  webapp/sources/ldap-inventory/inventory-api/src/main/scala/com/normation/inventory/domain/NodeInventory.scala
  webapp/sources/ldap-inventory/inventory-fusion/src/test/resources/fusion-inventories/windows2022.ocs
  webapp/sources/ldap-inventory/inventory-fusion/src/test/scala/com/normation/inventory/provisioning/fusion/TestReportParsing.scala
  webapp/sources/ldap-inventory/inventory-repository/src/main/scala/com/normation/inventory/ldap/core/InventoryMapper.scala
  webapp/sources/ldap-inventory/inventory-repository/src/main/scala/com/normation/inventory/ldap/core/LDAPConstants.scala
  webapp/sources/rudder/rudder-web/src/main/resources/ldapObjectAndAttributes.properties
Labels: Ready for merge
