Repository Normation/rudder, pull requests merged in 2022-09, with the labels that each got.

#4461 Fixes #21367: Node certificate expiration date does not follow the same format than the others dates in the UI
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/services/DisplayNode.scala
Labels: Ready for merge

#4453 Fixes #21637: Popups in rules page are missing separation from content
  webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/View.elm
Labels: Ready for merge

#4454 Fixes #21546: When editing a rule, the groups changes do not behave like the directives changes
  webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/ViewRuleDetails.elm
  webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/ViewUtils.elm
Labels: Ready for merge

#4449 Fixes #21654: rudder package command fails on amazon linux
  relay/sources/rudder-pkg/lib/rudder-pkg/rudderPkgUtils.py
Labels: qa: Can't merge

#4464 Fixes #21690: API documentation on how to query node is invalid
  webapp/sources/api-doc/code_samples/curl/nodes/all.sh
Labels: Ready for merge

#4465 Fixes #21695: Group permission of policies is not correctly set anymore in 7.2
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/write/PolicyWriterService.scala
Labels: Ready for merge

#4466 Fixes #21671: missing list of inpacted rules when creating a directive and applying it to a rule
  webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-directives.css
Labels: Ready for merge

#4468 Fixes #21707: Archive import does regenerate techniques/policies
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/ArchiveApi.scala
  webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala
Labels: qa: Can't merge

#4470 Fixes #21714: Cleanup cron job for relay not removed on upgrade ot 7.2
  relay/sources/rudder-relay-postinst
Labels: Ready for merge

#4474 Fixes #21736: when a key is multi-line, the reporting fails because agent add the datetime in fron of each new line
  relay/sources/relayd/src/data/report.rs
Labels: qa: Can't merge, Ready for merge

#4475 Fixes #21748: Syntax errors in scala files
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/RuleDisplayer.scala
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/node/AcceptNode.scala
Labels: qa: Can't merge, Ready for merge

#4476 Fixes #21749: Syntax errors in scala files (bis)
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/node/AcceptNode.scala
Labels: Ready for merge

#4477 Fixes #21371: No link to directives in a rule if the rule is not applied to some nodes
  webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/ViewTabContent.elm
Labels: WIP

#4490 Fixes #21669: Stop using UUIDs as system token
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/api/ApiAccountRepository.scala
  webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala
Labels: qa: Can't merge

#4472 Fixes #8022: Allow users to specify node hostname (FQDN)
  webapp/sources/ldap-inventory/inventory-api/src/main/scala/com/normation/inventory/services/provisioning/InventoryParser.scala
  webapp/sources/ldap-inventory/inventory-fusion/src/main/scala/com/normation/inventory/provisioning/fusion/FusionInventoryParser.scala
  webapp/sources/ldap-inventory/inventory-fusion/src/main/scala/com/normation/inventory/provisioning/fusion/PreInventoryParserCheckConsistency.scala
  webapp/sources/ldap-inventory/inventory-fusion/src/test/resources/fusion-inventories/7.1/node1-4d3a43bc-8508-46a2-92d7-cfe7320309a5.ocs
  webapp/sources/ldap-inventory/inventory-fusion/src/test/resources/fusion-inventories/7.1/node1-4d3a43bc-8508-46a2-92d7-cfe7320309a5.ocs.sign
  webapp/sources/ldap-inventory/inventory-fusion/src/test/resources/fusion-inventories/freebsd-2015-10-25-23-42-29.ocs
  webapp/sources/ldap-inventory/inventory-fusion/src/test/scala/com/normation/inventory/provisioning/fusion/TestReportParsing.scala
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/services/DisplayNode.scala
Labels: qa: Can't merge

#4493 Fixes #21792: Switch campaign schedule from a duration to a end time
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/campaigns/DataTypes.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/campaigns/JsonCampaignSerializer.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/campaigns/MainCampaignService.scala
  webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/MockServices.scala
  webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/rest/CampaignApiTest.scala
Labels: Ready for merge

#4498 Fixes #21802: Add security headers in Lift config - end
  webapp/sources/rudder/rudder-web/src/main/resources/applicationContext-security.xml
  webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/Boot.scala
  webapp/sources/rudder/rudder-web/src/main/webapp/WEB-INF/web.xml
Labels: qa: Can't merge, Ready for merge

#4486 Fixes #21784: add a default value for syslog facility output for agent and server compontent
  webapp/sources/rudder/rudder-web/src/main/resources/rudder-system-global-parameter.conf
Labels: qa: Can't merge, Ready for merge

#4503 Fixes #21811: Campaign json should be versionned
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/campaigns/DataTypes.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/campaigns/JsonCampaignSerializer.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/campaigns/MainCampaignService.scala
  webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/MockServices.scala
  webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/rest/CampaignApiTest.scala
Labels: Ready for merge

#4508 Fixes #21830: Update dependency check for 7.2
  Jenkinsfile-security
  policies/Cargo.lock
  policies/deny.toml
Labels: qa: Can't merge, Ready for merge

#4509 Fixes #21834: Update dependency check for 7.2 - fix log path
  Jenkinsfile-security
Labels: Ready for merge

#4511 Fixes #21849: Campaign events api should be sortable
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/campaigns/CampaignEventRepository.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/campaigns/MainCampaignService.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/CampaignApi.scala
  webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/MockServices.scala
Labels: Ready for merge

#4515 Fixes #21865: One shot schedule condition is invalid
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/campaigns/MainCampaignService.scala
Labels: qa: Can't merge, Ready for merge

#4513 Fixes #21855: Remove X-XSS-Protection header
  webapp/sources/rudder/rudder-web/src/main/resources/applicationContext-security.xml
Labels: Ready for merge

#4512 Fixes #21854: Properly configure CSP violation handler
  webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/Boot.scala
Labels: qa: Can't merge, Ready for merge

#4502 Fixes #21809: Dont redirect other tabs to login form when session cookie is replaced - add a notification
  webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/Boot.scala
Labels: qa: Can't merge, Ready for merge

#4518 Fixes #21875: Update Rust for 7.3
  policies/Cargo.lock
  policies/Dockerfile
  policies/resource-types/directory/src/main.rs
  policies/resource-types/template/Cargo.toml
  policies/resource-types/template/src/main.rs
  policies/rudder-commons/src/lib.rs
  policies/rudder-resource-type/Cargo.toml
  policies/rudder-resource-type/src/cfengine/protocol.rs
  policies/rudder-resource-type/src/lib.rs
  policies/rudder-resource-type/src/parameters.rs
  policies/rudderc/Cargo.toml
  policies/rudderc/src/backends/unix/ncf/technique.rs
  policies/rudderc/src/cli.rs
  policies/rudderc/src/frontends/ncf/method.rs
  policies/rudderc/src/ir/native.rs
  policies/rudderc/src/ir/resource.rs
  policies/rudderc/src/logs.rs
  policies/rust-toolchain.toml
  relay/sources/relayd/Cargo.lock
  relay/sources/relayd/Cargo.toml
  relay/sources/relayd/Dockerfile
  relay/sources/relayd/benches/benches.rs
  relay/sources/relayd/rust-toolchain.toml
  relay/sources/relayd/src/data/report.rs
  relay/sources/relayd/src/data/runlog.rs
  relay/sources/relayd/src/output/database.rs
  relay/sources/relayd/tests/processing_reporting.rs
Labels: qa: Can't merge, Ready for merge

#4514 Fixes #21806:
  webapp/sources/rudder/rudder-web/src/main/resources/configuration.properties.sample
  webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/Boot.scala
  webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala
Labels: qa: Can't merge, Ready for merge

#4517 Fixes #21869: Update scala-lib version due to CVE2022-36944
  webapp/sources/ldap-inventory/inventory-repository/src/main/scala/com/normation/inventory/ldap/core/InventoryHistoryLogRepository.scala
  webapp/sources/ldap-inventory/inventory-repository/src/test/scala/com/normation/inventory/ldap/core/TestInventory.scala
  webapp/sources/pom.xml
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/cfclerk/domain/TechniqueVersion.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/cfclerk/services/impl/GitTechniqueReader.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/cfclerk/services/impl/GitUtilsImpl.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/cfclerk/xmlwriters/SectionSpecWriter.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/eventlog/ArchiveEventLog.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/nodes/Properties.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/jdbc/ReportsJdbcRepository.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/ldap/LDAPDiffMapper.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/xml/RudderPrettyPrinter.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/eventlog/EventLogDetailsService.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/eventlog/EventLogServiceImpl.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/nodes/MergeNodeProperties.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/nodes/NodeInfoService.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/InterpolatedValueCompiler.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/TechniqueAcceptationDatetimeUpdater.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/nodeconfig/NodeConfigurationCacheRepository.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/write/PolicyWriterService.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/queries/DynGroupService.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/quicksearch/QuickSearchQueryParser.scala
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/cfclerk/domain/TechniqueTest.scala
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/hooks/RunNuCommandTest.scala
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/inventory/TestCertificate.scala
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/migration/TestDbMigration.scala
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/repository/jdbc/HistorizationRepositoryTest.scala
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/policies/write/PolicyAgregationTest.scala
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/policies/write/WriteTechniquesTest.scala
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/reports/ExecutionBatchTest.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/RestExtractorService.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/web/services/UserPropertyService.scala
  webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/rest/SystemApiTest.scala
  webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/BootstrapChecks.scala
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/DirectiveEditForm.scala
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/TechniqueEditForm.scala
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/popup/CreateCategoryOrGroupPopup.scala
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/popup/CreateCloneDirectivePopup.scala
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/popup/CreateCloneGroupPopup.scala
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/popup/CreateOrUpdateGlobalParameterPopup.scala
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/popup/CreateRulePopup.scala
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/popup/GiveReasonPopup.scala
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/popup/ModificationValidationPopup.scala
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/popup/RuleModificationValidationPopup.scala
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/services/ReportDisplayer.scala
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/HealthcheckInfo.scala
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/HomePage.scala
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/administration/TechniqueLibraryManagement.scala
  webapp/sources/scala-ldap/src/main/scala/com/normation/ldap/sdk/LDAPConnection.scala
  webapp/sources/scala-ldap/src/main/scala/com/normation/ldap/sdk/LDAPTree.scala
  webapp/sources/scala-ldap/src/test/scala/com/normation/ldap/sdk/LDAPTreeTest.scala
Labels: qa: Can't merge
