Repository Normation/rudder, pull requests merged in 2022-07, with the labels that each got.

#4358 Fixes #21352: In HTTPS mode, we may have errors in logs about duplicate messages that are totally legit
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/reports/ExecutionBatch.scala
Labels: qa: Can't merge, Trigger test

#4337 Fixes #21293: Allow overriding rudder-web.properties parameters with files in rudder-web.properties.d
  webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala
Labels: qa: Can't merge

#4357 Fixes #21350: Missing comment in configuration.properties.sample
  webapp/sources/rudder/rudder-web/src/main/resources/configuration.properties.sample
Labels: Trigger test

#4339 Fixes #21171: Cancel button not showed within disable rule menu
  webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/View.elm
Labels: qa: Can't merge

#4351 Fixes #21238: Rename "classic nodes" to "unix node"
  webapp/sources/ldap-inventory/inventory-api/src/main/scala/com/normation/inventory/domain/AgentTypes.scala
  webapp/sources/rudder/rudder-core/src/main/resources/ldap/bootstrap.ldif
  webapp/sources/rudder/rudder-core/src/main/resources/ldap/init-policy-server.ldif
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/nodes/NodeInfo.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/ncf/TechniqueWriter.scala
  webapp/sources/rudder/rudder-web/src/main/elm/editor/sources/ViewMethodsList.elm
  webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala
  webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/checks/migration/CheckAddSpecialNodeGroupsDescription.scala
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/services/DisplayDirectiveTree.scala
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/configuration/DirectiveManagement.scala
  webapp/sources/rudder/rudder-web/src/main/webapp/secure/configurationManager/directiveManagement.html
  webapp/sources/rudder/rudder-web/src/test/scala/bootstrap/liftweb/checks/migration/TestMigrateSystemTechnique7_0.scala
Labels: Ready for merge

#4344 Fixes #21316: rudder package command should install multiple plugins at once
  relay/sources/rudder-pkg/lib/rudder-pkg/rudderPkg.py
  relay/sources/rudder-pkg/rudder-pkg
Labels: qa: Can't merge, Trigger test

#4361 Fixes #21362: Update embedded openssl to 1.1.1q - relayd
  relay/sources/relayd/Cargo.lock
Labels: qa: Can't merge, Ready for merge

#4362 Fixes #21364: Ignore rudder-lang repos in script checks
  qa-test
Labels: qa: Can't merge, Ready for merge

#4334 Fixes #20603: Reports on method using iterator are wrong in the cli output
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/ncf/TechniqueWriter.scala
  webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/techniques/ncf_techniques/technique_any/1.0/technique.cf
  webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/techniques/ncf_techniques/technique_any/2.0/technique.cf
  webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/techniques/ncf_techniques/technique_by_Rudder/1.0/rudder_reporting.cf
  webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/techniques/ncf_techniques/technique_by_Rudder/1.0/technique.cf
Labels: Ready for merge, Trigger test

#4367 Fixes #21321: Add API endpoint to import an archive of rules/etc
  webapp/sources/api-doc/components/schemas/settings.yml
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/cfclerk/domain/Technique.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/cfclerk/services/TechniqueRepository.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/cfclerk/services/impl/GitTechniqueReader.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/eventlog/EventLog.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/eventlog/Modification.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/apidata/JsonQueryObjects.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/apidata/JsonResponseObjects.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/configuration/ConfigurationRepository.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/logger/ApplicationLogger.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/policies/RuleTarget.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/policies/Tags.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/git/GitFindUtils.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/git/ZipUtils.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/ncf/EditorTechnique.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/ncf/TechniqueWriter.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/xml/GitArchivers.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/xml/GitParseRudderObjects.scala
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/ncf/TestEditorTechniqueWriter.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/appconfig/ConfigService.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/EndpointsDefinition.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/RudderJsonResponse.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/ArchiveApi.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/DirectiveApi.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/LiftApiDispatcher.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/RuleApi.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/SettingsApi.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/web/services/DirectiveEditorService.scala
  webapp/sources/rudder/rudder-rest/src/test/resources/api/api_directives.yml
  webapp/sources/rudder/rudder-rest/src/test/resources/api/api_groups.yml
  webapp/sources/rudder/rudder-rest/src/test/resources/api/api_settings.yml
  webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/MockServices.scala
  webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/rest/ArchiveApiTests.scala
  webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/rest/NodeApiTest.scala
  webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/rest/RestTestSetUp.scala
  webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/rest/TestRestFromFileDef.scala
  webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/configuration/DirectiveManagement.scala
  webapp/sources/rudder/rudder-web/src/test/scala/bootstrap/liftweb/checks/migration/TestMigrateSystemTechnique7_0.scala
  webapp/sources/utils/src/main/scala/com/normation/ObjectVersionCommons.scala
  webapp/sources/utils/src/main/scala/com/normation/ZioCommons.scala
Labels: Ready for merge

#4369 Fixes #21394: Missing API documentation for import/export policies with dependencies
  webapp/sources/api-doc/code_samples/curl/archives/export.sh
  webapp/sources/api-doc/code_samples/curl/archives/import.sh
  webapp/sources/api-doc/openapi.src.yml
  webapp/sources/api-doc/paths/archives/export.yml
  webapp/sources/api-doc/paths/archives/import.yml
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/ncf/TechniqueWriter.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/EndpointsDefinition.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/ArchiveApi.scala
  webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/rest/RestTestSetUp.scala
  webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala
Labels: qa: Can't merge

#4374 Fixes #21430: technique from technique editor not commited in git
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/xml/GitArchivers.scala
Labels: Ready for merge, Trigger test

#4375 Fixes #21435: rudder don't understand the new reports generated for system update
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/reports/Reports.scala
Labels: Ready for merge, Trigger test

#4317 Fixes #21241: API to fetch nodes + software times out on large instance
  webapp/sources/ldap-inventory/inventory-api/src/main/scala/com/normation/inventory/domain/Identifiers.scala
  webapp/sources/ldap-inventory/inventory-repository/src/main/scala/com/normation/inventory/ldap/core/InventoryDit.scala
  webapp/sources/ldap-inventory/inventory-repository/src/main/scala/com/normation/inventory/ldap/core/ReadOnlySoftwareInventoryDAOImpl.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/data/NodeDetailLevel.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/NodeApi.scala
Labels: qa: Can't merge, Trigger test

#4378 Fixes #21440: Update Rust to 1.62.1
  policies/Dockerfile
  policies/rust-toolchain.toml
  relay/sources/relayd/Dockerfile
  relay/sources/relayd/rust-toolchain.toml
  relay/sources/relayd/src/api/system.rs
  relay/sources/relayd/src/data/report.rs
  relay/sources/relayd/src/data/runlog.rs
Labels: qa: Can't merge, Ready for merge

#4373 Fixes #21423: error when processing inventories in 7.2
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/inventory/InventoryFileWatcher.scala
Labels: Ready for merge

#4382 Fixes #21443:
  webapp/sources/rudder/rudder-web/src/main/elm/healthcheck/elm.json
  webapp/sources/rudder/rudder-web/src/main/elm/notifications/elm.json
Labels: Ready for merge

#4380 Fixes #21445:
  webapp/sources/rudder/rudder-web/src/main/webapp/WEB-INF/web.xml
Labels: Ready for merge

#4384 Fixes #21450:
  webapp/sources/rudder/rudder-web/src/main/elm/editor/elm.json
  webapp/sources/rudder/rudder-web/src/main/elm/onboarding/elm.json
  webapp/sources/rudder/rudder-web/src/main/elm/rules/elm.json
Labels: Ready for merge

#4385 Fixes #21453:
  webapp/sources/rudder/rudder-web/src/main/elm/accounts/elm.json
Labels: Ready for merge

#4386 Fixes #21452:
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/services/NodeGrid.scala
  webapp/sources/rudder/rudder-web/src/main/webapp/javascript/rudder/rudder-datatable.js
Labels: Ready for merge

#4387 Fixes #21455:
  webapp/sources/rudder/rudder-web/src/main/elm/hooks/elm.json
Labels: Ready for merge

#4388 Fixes #21457:
  webapp/sources/rudder/rudder-web/src/main/webapp/javascript/rudder/rudder.js
Labels: Ready for merge

#4389 Fixes #21458: JS escape in tags
  webapp/sources/rudder/rudder-web/src/main/webapp/javascript/rudder/rudder-datatable.js
Labels: Ready for merge

#4383 Fixes #21449:
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/services/DisplayNode.scala
Labels: qa: Can't merge, Ready for merge

#4390 Fixes #21461:
  webapp/sources/rudder/rudder-web/src/main/webapp/javascript/rudder/rudder.js
Labels: Ready for merge, Trigger test

#4391 Fixes #21463: URL with "%3B" (ie ';') leads to a stacktrace
  webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/LiftSpringSecurityFilter.scala
Labels: Ready for merge

#4379 Fixes #21170: 502 - Proxy Error when triggering Rudder agent
  relay/sources/apache/rudder-apache-relay-ssl.conf
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/NodeApi.scala
Labels: qa: Can't merge, Ready for merge

#4392 Fixes #21462:
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/services/DisplayDirectiveTree.scala
  webapp/sources/rudder/rudder-web/src/main/webapp/javascript/rudder/angular/ruleDirectives.js
Labels: Ready for merge

#4377 Fixes #21438: Add HSTS config (commented for now)
  relay/sources/apache/rudder-vhost.conf
Labels: Ready for merge

#4376 Fixes #21264: Refresh Button in Rules menu under Directives Tab is not working
  webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/DataTypes.elm
  webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/Rules.elm
  webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/ViewRepairedReports.elm
  webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/ViewTabContent.elm
Labels: qa: Can't merge, Ready for merge

#4394 Fixes #21469:
  webapp/sources/rudder/rudder-web/src/main/elm/editor/sources/ViewMethodsList.elm
  webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/ViewUtils.elm
Labels: qa: Can't merge, Ready for merge

#4393 Fixes #21468:
  webapp/sources/rudder/rudder-web/src/main/elm/accounts/sources/ViewUtils.elm
Labels: qa: Can't merge, Ready for merge

#4396 Fixes #21471:
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/services/DisplayNode.scala
  webapp/sources/rudder/rudder-web/src/main/webapp/javascript/rudder/rudder-datatable.js
  webapp/sources/rudder/rudder-web/src/main/webapp/javascript/rudder/rudder.js
Labels: qa: Can't merge, Ready for merge

#4397 Fixes #21473:
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/services/DisplayNode.scala
Labels: Ready for merge

#4398 Fixes #21474: CSS for tags is broken
  webapp/sources/rudder/rudder-web/src/main/webapp/javascript/rudder/angular/ruleDirectives.js
  webapp/sources/rudder/rudder-web/src/main/webapp/javascript/rudder/rudder-datatable.js
  webapp/sources/rudder/rudder-web/src/main/webapp/templates-hidden/common-layout.html
Labels: Ready for merge

#4403 Fixes #21482: Concurrent delete of policy backup directory can lead to useless error
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/write/PolicyWriterService.scala
Labels: qa: Can't merge

#4401 Fixes #21478: Clean up test configuration repository to use it from plugin
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/policies/NodeConfigData.scala
  webapp/sources/rudder/rudder-rest/src/test/resources/configuration-repository
  webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/MockServices.scala
Labels: qa: Can't merge, Ready for merge

#4399 Fixes #21476: improve contributing doc to state how to generate inventories
  CONTRIBUTING.adoc
Labels: qa: Can't merge, Ready for merge, Trigger test
