Repository Normation/rudder, pull requests merged in 2022-11, with the labels that each got.

#4558 Fixes #22044: Spring-security is impacted by CVE-2022-31692
  webapp/sources/pom.xml
Labels: Ready for merge

#4552 Fixes #21963: Make rudderc technique able to be used by the technique editor
  Jenkinsfile
  policies/Cargo.lock
  policies/Dockerfile
  policies/Makefile
  policies/resource-types/directory/README.md
  policies/resource-types/directory/src/main.rs
  policies/resource-types/directory/tests/test.rs
  policies/resource-types/template/Cargo.toml
  policies/resource-types/template/README.md
  policies/resource-types/template/src/main.rs
  policies/resource-types/template/tests/minijinja.rs
  policies/resource-types/template/tests/mustache.rs
  policies/rudder-commons-test/src/resource_type.rs
  policies/rudder-commons/src/lib.rs
  policies/rudder-resource-type/src/cfengine/protocol.rs
  policies/rudder-resource-type/src/lib.rs
  policies/rudderc/Cargo.toml
  policies/rudderc/docs/examples/ntp.yml
  policies/rudderc/src/backends.rs
  policies/rudderc/src/backends/metadata.rs
  policies/rudderc/src/backends/unix.rs
  policies/rudderc/src/backends/unix/cfengine.rs
  policies/rudderc/src/backends/unix/cfengine/bundle.rs
  policies/rudderc/src/backends/unix/cfengine/promise.rs
  policies/rudderc/src/backends/unix/ncf/method_call.rs
  policies/rudderc/src/backends/unix/ncf/technique.rs
  policies/rudderc/src/backends/windows.rs
  policies/rudderc/src/cli.rs
  policies/rudderc/src/compiler.rs
  policies/rudderc/src/doc.rs
  policies/rudderc/src/frontends/methods/method.rs
  policies/rudderc/src/frontends/methods/reader.rs
  policies/rudderc/src/frontends/yaml.rs
  policies/rudderc/src/ir.rs
  policies/rudderc/src/ir/condition.rs
  policies/rudderc/src/ir/native.rs
  policies/rudderc/src/ir/resource.rs
  policies/rudderc/src/lib.rs
  policies/rudderc/tests/cases/general/ntp.cf
  policies/rudderc/tests/cases/general/ntp.yml
  policies/rudderc/tests/cases/general/with-reporting.cf
  policies/rudderc/tests/cases/general/with-reporting.yml
  policies/rudderc/tests/compile.rs
  policies/rudderc/tests/methods.rs
  policies/rudderc/tests/methods/package_present.cf
  policies/rudderc/tests/methods/package_present.yml
  policies/rudderc/tests/resources/test.cf
  policies/rudderc/tests/resources/test.yml
  policies/rust-toolchain.toml
  relay/sources/relayd/Cargo.lock
  relay/sources/relayd/Dockerfile
  relay/sources/relayd/rust-toolchain.toml
  relay/sources/relayd/src/configuration.rs
  relay/sources/relayd/src/hashing.rs
Labels: qa: Can't merge

#4559 Fixes #22049: Update scala dependencies to latest version
  webapp/sources/pom.xml
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/policies/TestNodeAndGlobalParameterLookup.scala
Labels: Ready for merge

#4570 Fixes #22084: Fix various builds errors after build containers update
  relay/sources/rudder-pkg/requirements.txt
  webapp/sources/rudder/rudder-web/src/main/elm/Dockerfile
Labels: qa: Can't merge, Ready for merge

#4571 Fixes #22085: Fix various builds errors after build containers update - 7.2
  ci/typos.Dockerfile
  language/_typos.toml
  language/docs/operating-systems.adoc
  relay/sources/_typos.toml
  relay/sources/rudder-pkg/lib/rudder-pkg/tests/rudderPkgUtils.test.py
  webapp/sources/api-doc/_typos.toml
  webapp/sources/api-doc/paths/techniques/reload-technique.yml
Labels: qa: Can't merge, Ready for merge

#4573 Fixes #22093: Install npm dependencies in dev build when not present
  webapp/sources/rudder/rudder-web/src/main/build.sh
Labels: qa: Can't merge, Ready for merge

#4578 Fixes #22100: When reading methods, if generic_methods.json does not exists, rudder should generate it
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/ncf/TechniqueReader.scala
Labels: qa: Can't merge, Ready for merge

#4567 Fixes #22074: Generated policies are invalid for Windows using powershell 4
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/ncf/TechniqueWriter.scala
  webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/techniques/ncf_techniques/technique_any/1.0/technique.ps1
  webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/techniques/ncf_techniques/technique_any/2.0/technique.ps1
  webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/techniques/ncf_techniques/technique_by_Rudder/1.0/technique.ps1
Labels: Ready for merge

#4563 Fixes #14371: At least on windows, technique editor parameters can not handle "_" char
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/ncf/TechniqueWriter.scala
  webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/techniques/ncf_techniques/technique_any/1.0/technique.ps1
  webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/techniques/ncf_techniques/technique_any/2.0/technique.ps1
  webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/techniques/ncf_techniques/technique_by_Rudder/1.0/technique.ps1
Labels: qa: Can't merge, Ready for merge

#4582 Fixes #22129: Id to start looking for report json should not be zero but highest id.
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/batch/AutomaticReportLogger.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/campaigns/JSONReportsHandler.scala
Labels: qa: Can't merge, Ready for merge

#4581 Fixes #22124: Log all API errors
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/RudderJsonResponse.scala
  webapp/sources/rudder/rudder-web/src/main/resources/logback.xml
Labels: qa: Can't merge

#4584 Fixes #22126: Windows generic method parameters are always written "mandatory=true" even when "mayBeEmpty"
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/ncf/TechniqueWriter.scala
  webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/techniques/ncf_techniques/technique_by_Rudder/1.0/technique.ps1
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/ncf/TestEditorTechniqueWriter.scala
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/policies/NodeExpectedReportTest.scala
Labels: qa: Can't merge, Ready for merge

#4540 Fixes #21957: Errors of script that write technique.json during upgrade should be ignored
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/ncf/TechniqueReader.scala
  webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/checks/action/CheckNcfTechniqueUpdate.scala
Labels: qa: Can't merge

#4587 Fixes #22134: Click on graph node with "applying" compliance lead to JS error
  webapp/sources/rudder/rudder-web/src/main/webapp/javascript/rudder/homePage.js
  webapp/sources/rudder/rudder-web/src/main/webapp/javascript/rudder/rudder-datatable.js
Labels: Ready for merge

#4589 Fixes #22138: In dashboard in graph by OS, click for some OS lead to AIX
  webapp/sources/rudder/rudder-web/src/main/webapp/javascript/rudder/homePage.js
Labels: qa: Can't merge, Ready for merge

#4593 Fixes #22144: Highest id only fetch at first run, but batch is running
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/campaigns/JSONReportsHandler.scala
Labels: Ready for merge

#4594 Fixes #22148: Correction to avoid infinite campaign event does not work in some case
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/campaigns/MainCampaignService.scala
Labels: qa: Can't merge, Ready for merge
