Repository Normation/rudder, pull requests merged in 2022-03, with the labels that each got.

#4195 Fixes #20844: Broken allowed network curl example
  webapp/sources/api-doc/code_samples/curl/settings/set-allowed-networks-diff.sh
Labels: Trigger test

#4196 Fixes #20851: Regroup report with their values, not with the expanded value
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/reports/StatusReports.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/DeploymentService.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/reports/ExecutionBatch.scala
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/domain/reports/StatusReportTest.scala
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/reports/ExecutionBatchTest.scala
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/services/ComplianceData.scala
  webapp/sources/rudder/rudder-web/src/main/webapp/javascript/rudder/rudder-datatable.js
Labels: Trigger test

#4201 Fixes #20872: Vulnerability in the regex crate
  relay/sources/relayd/Cargo.lock
Labels: qa: Can't merge, Ready for merge, Trigger test

#4194 Fixes #20828: Unexpected/missing for same component, same value
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/DataStructures.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/DeploymentService.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/RuleValService.scala
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/policies/NodeConfigData.scala
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/policies/NodeExpectedReportTest.scala
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/policies/RuleValServiceTest.scala
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/policies/TestNodeAndGlobalParameterLookup.scala
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/policies/write/PolicyAgregationTest.scala
Labels: Trigger test

#4202 Fixes #20873: Vulnerability in the regex crate - rudderc
  rudder-lang/Cargo.lock
Labels: qa: Can't merge, Trigger test

#4203 Fixes #20874: Compilation warning on branche 6.2
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/queries/CmdbQuery.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/queries/LdapQueryProcessor.scala
Labels: qa: Can't merge, Trigger test

#4209 Fixes #20856: Applied directive doesn't show up when there is no node
  webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/ViewTabContent.elm
  webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/ViewUtils.elm
  webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-template.css
Labels: Trigger test

#4205 Fixes #19319: When editing files with the technique editor resources manager, newlines at the end of file are trimmed
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/internal/SharedFilesAPI.scala
  webapp/sources/rudder/rudder-web/src/main/webapp/templates/angular/technique-editor-filemanager/modals.html
Labels: Ready for merge, Trigger test

#4207 Fixes #20883: Built in Techniques using generic methods have no reports with new report id
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/write/BuildBundleSequence.scala
  webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/node-cfe-with-500-directives/rules/cfengine-community/rudder-directives.cf
  webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/node-cfe-with-500-directives/rules/cfengine-community/rudder-system-directives.cf
  webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/node-cfe-with-two-directives/rules/cfengine-community/rudder-directives.cf
  webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/node-cfe-with-two-directives/rules/cfengine-community/rudder-system-directives.cf
  webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/node-gen-var-def-override/rules/cfengine-community/rudder-directives.cf
  webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/node-gen-var-def-override/rules/cfengine-community/rudder-system-directives.cf
  webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/root-default-install/rudder-system-directives.cf
  webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/root-sys-var-false/rudder-system-directives.cf
  webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/root-with-one-multipolicy/rudder-directives.cf
  webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/root-with-one-multipolicy/rudder-system-directives.cf
  webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/root-with-two-directives/rudder-directives.cf
  webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/root-with-two-directives/rudder-system-directives.cf
  webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/technique-and-revisions/rudder-directives.cf
  webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/technique-and-revisions/rudder-system-directives.cf
Labels: Ready for merge

#4208 Fixes #20886: Add name for spring security main auth configuration bean to be used by oauth2
  webapp/sources/rudder/rudder-web/src/main/resources/applicationContext-security.xml
  webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/AppConfigAuth.scala
  webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderProviderManager.java
Labels: Trigger test

#4197 Fixes #20848: We cannot filter rules by tag anymore
  webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/DataTypes.elm
  webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/Init.elm
  webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/Rules.elm
  webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/View.elm
  webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/ViewRulesTable.elm
  webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/ViewUtils.elm
  webapp/sources/rudder/rudder-web/src/main/webapp/secure/configurationManager/ruleManagement.html
  webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-rules.css
  webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-template.css
Labels: Trigger test

#4210 Fixes #20693: Glitch in node compliance details
  webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-datatable.css
Labels: Trigger test

#4211 Fixes #20782: Wrong redirect url for system group in rule page
  webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/ViewUtils.elm
Labels: Trigger test

#4213 Fixes #20901: Remove the AngularJs application from the API accounts page
  webapp/sources/rudder/rudder-web/src/main/webapp/javascript/rudder/angular/apiAccount.js
Labels: Trigger test

#4215 Fixes #20926: Starting policy generation by hand fails if node-configuration-hashes.json
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/nodeconfig/NodeConfigurationCacheRepository.scala
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/comet/AsyncDeployment.scala
Labels: Trigger test

#4218 Fixes #20947: Add new software update fields to API doc
  webapp/sources/api-doc/components/schemas/node-full.yml
Labels: Trigger test

#4219 Fixes #20951: Remove the transparent div that covers the Properties tab and prevents interaction with it.
  webapp/sources/rudder/rudder-web/src/main/webapp/templates-hidden/components/ComponentNodeProperties.html
Labels: Trigger test
