Repository Normation/rudder, pull requests merged in 2022-10, with the labels that each got.

#4522 Fixes #21893: CVE in nuprocess 2.03 and below
  webapp/sources/pom.xml
Labels: qa: Can't merge

#4523 Fixes #21894: Compile error in master following scalac version update
  webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/Boot.scala
Labels: Ready for merge

#4527 Fixes #21900: Broken Java 17 tests on 7.2+
  webapp/sources/Dockerfile
Labels: qa: Can't merge

#4529 Fixes #21911: Chart show the tooltips only when clicking
  webapp/sources/rudder/rudder-web/src/main/webapp/javascript/rudder/homePage.js
Labels: Ready for merge

#4530 Fixes #21913: scalap and compiler dependency are not correct
  webapp/sources/pom.xml
Labels: Ready for merge

#4531 Fixes #21914: Add authorized license Unicode-DFS-2016 in relayd
  relay/sources/relayd/deny.toml
Labels: Ready for merge

#4524 Fixes #21373: Links in {directive|rule|group|technique} "tree" can not be open in a new tab
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/internal/RulesInternalAPI.scala
  webapp/sources/rudder/rudder-web/src/main/elm/editor/sources/ViewTechniqueList.elm
  webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/View.elm
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/DirectiveEditForm.scala
  webapp/sources/rudder/rudder-web/src/main/webapp/javascript/rudder/tree.js
  webapp/sources/rudder/rudder-web/src/main/webapp/secure/configurationManager/ruleManagement.html
  webapp/sources/rudder/rudder-web/src/main/webapp/secure/configurationManager/techniqueEditor.html
Labels: qa: Can't merge, Ready for merge

#4534 Fixes #21935: Format of target group is wrong in API doc
  webapp/sources/api-doc/components/schemas/rule-new.yml
  webapp/sources/api-doc/components/schemas/rule-targets.yml
  webapp/sources/api-doc/components/schemas/rule-update.yml
  webapp/sources/api-doc/components/schemas/rule-with-category.yml
Labels: qa: Can't merge, Ready for merge

#4536 Fixes #21943: Broken session - lastNonCometAccessedTime has an unexpected value
  webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/Boot.scala
Labels: qa: Can't merge, Ready for merge

#4541 Fixes #21961: Start docs for new technique yaml format
  policies/rudderc/docs/examples/ntp.yml
  policies/rudderc/src/backends/unix.rs
  policies/rudderc/src/backends/unix/ncf/method_call.rs
  policies/rudderc/src/ir/resource.rs
  policies/rudderc/tests/cases/general/ntp.cf
  policies/rudderc/tests/cases/general/ntp.yml
  policies/rudderc/tests/cases/general/with-reporting.cf
  policies/rudderc/tests/cases/general/with-reporting.yml
Labels: WIP

#4544 Fixes #21991: Update api doc tooling
  api-doc/Dockerfile
Labels: qa: Can't merge

#4545 Fixes #21994: Add jdk 19 to compatibility tests
  Jenkinsfile
Labels: qa: Can't merge

#4550 Fixes #22015: Missing epoch string in search node query from pie chart
  webapp/sources/rudder/rudder-web/src/main/webapp/javascript/rudder/homePage.js
Labels: qa: Can't merge

#4551 Fixes #22017: [API] Request Sample / documentation false
  webapp/sources/api-doc/components/schemas/node-add.yml
Labels: Ready for merge

#4554 Fixes #22029: rudder_relayd filling /var/log/daemon.log (Invalid report)
  relay/sources/relayd/src/data/report.rs
Labels: Ready for merge
