Repository Normation/rudder, pull requests merged in 2022-06, with the labels that each got.

#4304 Fixes #21201: Allow passing options to postgresql connection URL
  relay/sources/relayd/Cargo.toml
  relay/sources/relayd/src/output/database.rs
Labels: Ready for merge, Trigger test

#4307 Fixes #21197: Prepare new rudderc implementation
  Jenkinsfile
  rudderc/.gitignore
  rudderc/Cargo.lock
  rudderc/Cargo.toml
  rudderc/Dockerfile
  rudderc/Makefile
  rudderc/README.adoc
  rudderc/deny.toml
  rudderc/docs/assets/css/rudder.css
  rudderc/docs/examples/ntp.yml
  rudderc/docs/images/rudder.svg
  rudderc/docs/index.adoc
  rudderc/libs/cfengine.yml
  rudderc/libs/rudder.yml
  rudderc/rust-toolchain
  rudderc/src/backends.rs
  rudderc/src/backends/unix.rs
  rudderc/src/backends/unix/cfengine.rs
  rudderc/src/backends/unix/cfengine/bundle.rs
  rudderc/src/backends/unix/cfengine/promise.rs
  rudderc/src/backends/unix/ncf.rs
  rudderc/src/backends/unix/ncf/method_call.rs
  rudderc/src/backends/unix/ncf/technique.rs
  rudderc/src/backends/windows.rs
  rudderc/src/cli.rs
  rudderc/src/compiler.rs
  rudderc/src/frontends.rs
  rudderc/src/frontends/ncf.rs
  rudderc/src/frontends/ncf/method.rs
  rudderc/src/frontends/ncf/reader.rs
  rudderc/src/frontends/yaml.rs
  rudderc/src/ir.rs
  rudderc/src/ir/native.rs
  rudderc/src/ir/resource.rs
  rudderc/src/lib.rs
  rudderc/src/logs.rs
  rudderc/src/main.rs
  rudderc/techniques/REAME.md
  rudderc/techniques/cis/cis.yml
  rudderc/techniques/ntp/ntp.yml
  rudderc/tests/cases/general/broken.fail.yml
  rudderc/tests/cases/general/ntp.cf
  rudderc/tests/cases/general/ntp.yml
  rudderc/tests/cases/general/wrong-schema.fail.yml
  rudderc/tests/compile.rs
  rudderc/tools/metadata.xml
  rust.makefile
Labels: WIP

#4313 Fixes #21230: Improve performance of display for agent version on homepage
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/HomePage.scala
Labels: qa: Can't merge, Trigger test

#4303 Fixes #21099: Harmonise the color scheme used in Rudder
  webapp/sources/rudder/rudder-web/src/main/elm/accounts/sources/View.elm
  webapp/sources/rudder/rudder-web/src/main/elm/editor/sources/ViewMethod.elm
  webapp/sources/rudder/rudder-web/src/main/elm/editor/sources/ViewTechnique.elm
  webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/View.elm
  webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/ViewRepairedReports.elm
  webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/ViewRuleDetails.elm
  webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/ViewTabContent.elm
  webapp/sources/rudder/rudder-web/src/main/resources/load-page/rudder-loading.html
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/comet/AsyncDeployment.scala
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/NodeGroupForm.scala
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/RuleDisplayer.scala
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/services/ReportDisplayer.scala
  webapp/sources/rudder/rudder-web/src/main/webapp/javascript/rudder/homePage.js
  webapp/sources/rudder/rudder-web/src/main/webapp/javascript/rudder/rudder-datatable.js
  webapp/sources/rudder/rudder-web/src/main/webapp/secure/administration/policyServerManagement.html
  webapp/sources/rudder/rudder-web/src/main/webapp/secure/configurationManager/directiveManagement.html
  webapp/sources/rudder/rudder-web/src/main/webapp/secure/nodeManager/nodes.html
  webapp/sources/rudder/rudder-web/src/main/webapp/secure/utilities/eventLogs.html
  webapp/sources/rudder/rudder-web/src/main/webapp/style/bootstrap/tw-bs-bootstrap-3.3.7.css
  webapp/sources/rudder/rudder-web/src/main/webapp/style/jstree/style.css
  webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-bootstrap.css
  webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-dashboard.css
  webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-datatable.css
  webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-directives.css
  webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-filemanager.css
  webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-groups.css
  webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-healthcheck.css
  webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-menu.css
  webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-node.css
  webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-notifications.css
  webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-plugins.css
  webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-progress-bar.css
  webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-quicksearch.css
  webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-rules.css
  webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-tags.css
  webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-technique-editor.css
  webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-template.css
  webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-wizard.css
  webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder.css
  webapp/sources/rudder/rudder-web/src/main/webapp/templates-hidden/components/ComponentAgentPolicyMode.html
  webapp/sources/rudder/rudder-web/src/main/webapp/templates-hidden/components/ComponentAgentSchedule.html
  webapp/sources/rudder/rudder-web/src/main/webapp/templates-hidden/components/ComponentComplianceMode.html
  webapp/sources/rudder/rudder-web/src/main/webapp/templates-hidden/components/ComponentDirectiveEditForm.html
  webapp/sources/rudder/rudder-web/src/main/webapp/templates-hidden/components/ComponentNodeState.html
  webapp/sources/rudder/rudder-web/src/main/webapp/templates-hidden/components/ComponentRuleEditForm.html
  webapp/sources/rudder/rudder-web/src/main/webapp/templates-hidden/components/ComponentTags.html
Labels: Trigger test

#4292 Fixes #21119: When a technique is not in the active techique tree, it can't be deleted in editor
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/cfclerk/services/TechniqueRepository.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/ncf/TechniqueWriter.scala
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/ncf/TestTechniqueWriter.scala
  webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/rest/TestRestPlusInPath.scala
Labels: qa: Can't merge

#4312 Fixes #21221: Upgrade Bootstrap to 3.4.1
  webapp/sources/rudder/rudder-web/src/main/webapp/index.html
  webapp/sources/rudder/rudder-web/src/main/webapp/javascript/bootstrap/bootstrap-3.3.7.min.js
  webapp/sources/rudder/rudder-web/src/main/webapp/javascript/bootstrap/bootstrap-3.4.1.min.js
  webapp/sources/rudder/rudder-web/src/main/webapp/style/bootstrap/bootstrap-3.4.1.min.css
  webapp/sources/rudder/rudder-web/src/main/webapp/style/bootstrap/bootstrap.min.css.map
  webapp/sources/rudder/rudder-web/src/main/webapp/style/bootstrap/prefix.less
  webapp/sources/rudder/rudder-web/src/main/webapp/style/bootstrap/tw-bs-bootstrap-3.3.7.css
  webapp/sources/rudder/rudder-web/src/main/webapp/templates-hidden/common-layout.html
Labels: qa: Can't merge

#4266 Fixes #21082: List of hooks API
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/apidata/JsonResponseObjects.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/ApiDatastructures.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/EndpointsDefinition.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/RoleApiMapping.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/HookApi.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/SystemApi.scala
  webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala
Labels: Trigger test

#4324 Fixes #21259: Add docs about F# dev environment
  CONTRIBUTING.adoc
  contributing/fsharp.adoc
Labels: Ready for merge

#4325 Fixes #21260: GetMetadataContent does not correctly retrieve content when a revision is given
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/cfclerk/services/impl/GitTechniqueReader.scala
Labels: Trigger test

#4326 Fixes #21263:
  webapp/sources/dependency-check-suppression.xml
Labels: qa: Can't merge, Ready for merge

#4322 Fixes #21253: Query string is not correctly parsed in test API framework
  webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/rest/RestTestSetUp.scala
Labels: qa: Can't merge, Trigger test

#4318 Fixes #18918: Missing icon in technical logs for error messages
  webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-menu.css
Labels: qa: Can't merge

#4329 Fixes #21270: Allow .ocs files as inventory
  relay/sources/relayd/src/processing/inventory.rs
Labels: Ready for merge

#4327 Fixes #21220: When upgrading to 7.1, techniques are not upgraded to the new format and reporting issue occur
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/apidata/JsonResponseObjects.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/ncf/EditorTechnique.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/ncf/TechniqueWriter.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/RestExtractorService.scala
  webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/checks/action/CheckNcfTechniqueUpdate.scala
Labels: Trigger test

#4331 Fixes #21279: relayd error messages about config files are lacking path information
  relay/sources/relayd/src/configuration/logging.rs
  relay/sources/relayd/src/configuration/main.rs
  relay/sources/relayd/src/data/node.rs
  relay/sources/relayd/src/main.rs
  relay/sources/relayd/tests/api_system_status.rs
Labels: qa: Can't merge

#4336 Fixes #21290: Fix typos in techniques API doc
  webapp/sources/api-doc/components/schemas/categories-tree.yml
  webapp/sources/api-doc/paths/techniques/all.yml
  webapp/sources/api-doc/paths/techniques/id-version.yml
  webapp/sources/api-doc/paths/techniques/revisions.yml
  webapp/sources/api-doc/paths/techniques/versions.yml
Labels: Ready for merge

#4340 Fixes #21302: Wrong target for rudderc install
  policies/rudderc/Makefile
Labels: Ready for merge

#4309 Fixes #21225: Move API doc create node in rudder
  webapp/sources/api-doc/code_samples/curl/create-node/all.sh
  webapp/sources/api-doc/components/parameters/node-info.yml
  webapp/sources/api-doc/openapi.src.yml
  webapp/sources/api-doc/paths/create-node/all.yml
  webapp/sources/api-doc/paths/nodes/all.yml
Labels: Ready for merge, Trigger test

#4341 Fixes #21083: Provide a page to list the different hooks of a Rudder server
  webapp/sources/rudder/rudder-web/src/main/elm/hooks/build-dev.sh
  webapp/sources/rudder/rudder-web/src/main/elm/hooks/elm.json
  webapp/sources/rudder/rudder-web/src/main/elm/hooks/sources/ApiCalls.elm
  webapp/sources/rudder/rudder-web/src/main/elm/hooks/sources/DataTypes.elm
  webapp/sources/rudder/rudder-web/src/main/elm/hooks/sources/Hooks.elm
  webapp/sources/rudder/rudder-web/src/main/elm/hooks/sources/Init.elm
  webapp/sources/rudder/rudder-web/src/main/elm/hooks/sources/JsonDecoder.elm
  webapp/sources/rudder/rudder-web/src/main/elm/hooks/sources/JsonEncoder.elm
  webapp/sources/rudder/rudder-web/src/main/elm/hooks/sources/View.elm
  webapp/sources/rudder/rudder-web/src/main/elm/hooks/sources/ViewUtils.elm
  webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/Boot.scala
  webapp/sources/rudder/rudder-web/src/main/webapp/secure/administration/hooksManagement.html
  webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-hooks.css
Labels: Ready for merge

#4348 Fixes #21322: Using '{' in node property lead to error
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/RestDataSerializer.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/RestExtractorService.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/data/NodeDetailLevel.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/NodeApi.scala
  webapp/sources/rudder/rudder-rest/src/test/resources/api/api_nodes_properties.yml
  webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/MockServices.scala
  webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/rest/RestTestSetUp.scala
Labels: qa: Can't merge

#4354 Fixes #21336: Tests fail due to policy mode definition in MockServices
  webapp/sources/rudder/rudder-rest/src/test/resources/api/api_nodes_properties.yml
Labels: Ready for merge

#4355 Fixes #21175: Impossible to put a Rule in a subcategory
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/RuleApi.scala
  webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/RuleTests.scala
Labels: Ready for merge
