Repository Normation/rudder, pull requests merged in 2022-04, with the labels that each got.

#4214 Fixes #20897: "Disable reporting" for windows method calls does produce unexpected reports
  language/src/generator/dsc/syntax.rs
  language/tests/techniques/CIS/technique.ps1
  language/tests/techniques/cdt/technique.ps1
  language/tests/techniques/condition_alias/technique.ps1
  language/tests/techniques/condition_dyn/technique.ps1
  language/tests/techniques/condition_errorprone/technique.ps1
  language/tests/techniques/condition_foreign_variable/technique.ps1
  language/tests/techniques/condition_priority/technique.ps1
  language/tests/techniques/condition_useless_brackets/technique.ps1
  language/tests/techniques/conditional_method/technique.ps1
  language/tests/techniques/deprecated/technique.ps1
  language/tests/techniques/dsc/technique.ps1
  language/tests/techniques/duplicated/technique.ps1
  language/tests/techniques/escaped/technique.ps1
  language/tests/techniques/inner_block/technique.ps1
  language/tests/techniques/multiple_simple/technique.ps1
  language/tests/techniques/parameters/technique.ps1
  language/tests/techniques/parameters_mult/technique.ps1
  language/tests/techniques/simple_block/technique.ps1
  language/tests/techniques/simplest/technique.ps1
  language/tests/techniques/stateless/technique.ps1
  language/tests/techniques/supported_formats/technique.ps1
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/ncf/TechniqueWriter.scala
  webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/techniques/ncf_techniques/technique_any/1.0/technique.ps1
  webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/techniques/ncf_techniques/technique_any/2.0/technique.ps1
  webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/techniques/ncf_techniques/technique_by_Rudder/1.0/technique.ps1
  webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/techniques/ncf_techniques/technique_with_blocks/1.0/technique.ps1
Labels: qa: Can't merge

#4221 Fixes #20954: Edit mode should be enabled by default when creating a rule
  webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/Rules.elm
  webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/ViewRuleDetails.elm
Labels: Trigger test

#4206 Fixes #20692: Displays a warning icon for directives that are not used by any rule.
  webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/ViewTabContent.elm
  webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-template.css
Labels: Trigger test

#4230 Fixes #20972:
  webapp/sources/pom.xml
Labels: qa: Can't merge, Ready for merge

#4232 Fixes #20976: Show more details in exception when parsing an invalid technique version
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/cfclerk/domain/TechniqueVersion.scala
Labels: qa: Can't merge, Ready for merge

#4227 Fixes #20880: Removed report in compliance when calling several times the command_execution with same value
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/reports/StatusReports.scala
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/services/ComplianceData.scala
Labels: Ready for merge

#4235 Fixes #20984: Two same envvar modulo a space at begining of name leads to LDAP error when saving inventory
  webapp/sources/ldap-inventory/inventory-fusion/src/main/scala/com/normation/inventory/provisioning/fusion/FusionReportUnmarshaller.scala
Labels: qa: Can't merge, Ready for merge, Trigger test

#4242 Fixes #21007: Techniques with no component define have no reporting
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/DeploymentService.scala
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/policies/NodeExpectedReportTest.scala
Labels: qa: Can't merge

#4244 Fixes #21016: The display of the DSC icon is broken in the technical editor
  webapp/sources/rudder/rudder-web/src/main/elm/editor/sources/Editor.elm
  webapp/sources/rudder/rudder-web/src/main/elm/editor/sources/ViewMethodsList.elm
  webapp/sources/rudder/rudder-web/src/main/webapp/secure/configurationManager/techniqueEditor.html
  webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-technique-editor.css
Labels: Trigger test

#4246 Fixes #21022: Update spring and logback version because of new CVE
  webapp/sources/pom.xml
Labels: qa: Can't merge, Ready for merge, Trigger test

#4247 Fixes #21027: Ignore CVEs for spring-ldap-core
  webapp/sources/dependency-check-suppression.xml
Labels: Ready for merge, Trigger test

#4250 Fixes #21045: Update Rust toolchain for 7.2
  language/Cargo.lock
  language/Cargo.toml
  language/Dockerfile
  language/rust-toolchain
  relay/sources/relayd/Cargo.lock
  relay/sources/relayd/Cargo.toml
  relay/sources/relayd/Dockerfile
  relay/sources/relayd/rust-toolchain
  relay/sources/relayd/src/api/remote_run.rs
  relay/sources/relayd/src/data/runinfo.rs
  relay/sources/relayd/src/processing/inventory.rs
  relay/sources/relayd/src/processing/reporting.rs
  rust.makefile
Labels: Trigger test
