Repository Normation/rudder, pull requests merged in 2023-11, with the labels that each got.

#5152 Fixes #23686: Make the library path passed to CFEngine absolute
  policies/rudderc/src/backends/unix/cfengine.rs
Labels: Ready for merge

#5155 Fixes #23690: Add a downloader for files from plugin repository
  relay/sources/rudder-package/Cargo.lock
  relay/sources/rudder-package/Cargo.toml
  relay/sources/rudder-package/src/config.rs
  relay/sources/rudder-package/src/lib.rs
  relay/sources/rudder-package/src/repository.rs
  relay/sources/rudder-package/tests/hash/poem.txt
Labels: qa: Can't merge

#5150 Fixes #23687: Add version parsing to rudder-package
  relay/sources/rudder-package/Cargo.lock
  relay/sources/rudder-package/Cargo.toml
  relay/sources/rudder-package/src/lib.rs
  relay/sources/rudder-package/src/versions.rs
Labels: qa: Can't merge, Ready for merge

#5153 Fixes #23688: Import archive must refuse yaml technique with mismatch directory and id
  webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/techniques/ncf_techniques/a_simple_yaml_technique/1.0/resources/something.txt
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/ArchiveApi.scala
  webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/rest/ArchiveApiTest.scala
Labels: qa: Can't merge, Ready for merge

#5151 Fixes #23655: Import archive does not support technique upgrade
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/ArchiveApi.scala
  webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/rest/ArchiveApiTest.scala
Labels: Ready for merge

#5158 Fixes #23695: rudder-package should stroingly type any plugin version
  relay/sources/rudder-package/src/database.rs
  relay/sources/rudder-package/src/plugin.rs
  relay/sources/rudder-package/src/repo_index.rs
  relay/sources/rudder-package/src/versions.rs
  relay/sources/rudder-package/tests/database/plugin_database_update_sample.json.expected
Labels: qa: Can't merge

#5162 Fixes #23703: Add a cleanup step to techniques tests
  policies/rudderc/docs/src/test.md
  policies/rudderc/src/lib.rs
  policies/rudderc/src/test.rs
  policies/rudderc/tests/cases/test/one_param/tests/case1.yml
Labels: qa: Can't merge, Ready for merge

#5164 Fixes #23718: Bundle name collision with cloned techniques
  policies/rudderc/src/backends/unix.rs
  policies/rudderc/src/backends/unix/ncf/method_call.rs
  policies/rudderc/tests/cases/general/escaping/technique.cf
  policies/rudderc/tests/cases/general/form/technique.cf
  policies/rudderc/tests/cases/general/long_method_param_name/technique.cf
  policies/rudderc/tests/cases/general/min/technique.cf
  policies/rudderc/tests/cases/general/ntp/technique.cf
  policies/rudderc/tests/cases/general/reporting/technique.cf
Labels: qa: Can't merge

#5156 Fixes #23606: Creating files with the file explorer fails when using invalid character
  webapp/sources/rudder/rudder-web/src/main/elm/sources/FileManager/Action.elm
  webapp/sources/rudder/rudder-web/src/main/elm/sources/FileManager/Model.elm
  webapp/sources/rudder/rudder-web/src/main/elm/sources/FileManager/Port.elm
  webapp/sources/rudder/rudder-web/src/main/elm/sources/FileManager/Update.elm
  webapp/sources/rudder/rudder-web/src/main/elm/sources/FileManager/Util.elm
  webapp/sources/rudder/rudder-web/src/main/elm/sources/FileManager/wrapper.js
  webapp/sources/rudder/rudder-web/src/main/webapp/secure/configurationManager/techniqueEditor.html
  webapp/sources/rudder/rudder-web/src/main/webapp/templates-hidden/components/ComponentDirectiveEditForm.html
Labels: qa: Can't merge

#5163 Fixes #23707: Implement common zio-json utils for plugins in rudder
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/RudderJsonRequest.scala
Labels: qa: Can't merge

#5166 Fixes #23724:
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/EventLogRepository.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/jdbc/EventLogJdbcRepository.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/eventlog/EventLogServiceImpl.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/eventlog/InventoryEventLogServiceImpl.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/internal/EventLogAPI.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/web/services/EventLogDetailsGenerator.scala
  webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/rest/RestTestSetUp.scala
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/services/EventListDisplayer.scala
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/services/LogDisplayer.scala
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/administration/EventLogsViewer.scala
  webapp/sources/rudder/rudder-web/src/test/scala/bootstrap/liftweb/checks/migration/TestMigrateSystemTechnique7_0.scala
Labels: qa: Can't merge

#5170 Fixes #23736: Implement common utils for compatibility of zio-json API response
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/RudderJsonResponse.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/ArchiveApi.scala
Labels: qa: Can't merge

#5139 Fixes #23657: Compiler warnings should prevent build
  webapp/sources/pom.xml
Labels: qa: Can't merge

#5174 Fixes #23741: Testing json from API definitions in YAML should have a nice display
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/BoxSpecMatcher.scala
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/JsonSpecMatcher.scala
  webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/rest/TraitTestApiFromYamlFiles.scala
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/services/ReportDisplayer.scala
Labels: qa: Can't merge

#5176 Fixes #23711: Add GPG signature verification to rudder-package
  Jenkinsfile
  relay/sources/Makefile
  relay/sources/rudder-package/Cargo.lock
  relay/sources/rudder-package/src/archive.rs
  relay/sources/rudder-package/src/cli.rs
  relay/sources/rudder-package/src/cmd.rs
  relay/sources/rudder-package/src/config.rs
  relay/sources/rudder-package/src/database.rs
  relay/sources/rudder-package/src/dependency.rs
  relay/sources/rudder-package/src/lib.rs
  relay/sources/rudder-package/src/plugin.rs
  relay/sources/rudder-package/src/repo_index.rs
  relay/sources/rudder-package/src/repository.rs
  relay/sources/rudder-package/src/signature.rs
  relay/sources/rudder-package/src/versions.rs
  relay/sources/rudder-package/src/webapp_xml.rs
  relay/sources/rudder-package/tests/signature/SHA512SUMS
  relay/sources/rudder-package/tests/signature/SHA512SUMS.asc
  relay/sources/rudder-package/tests/signature/SHA512SUMS.wrong
  relay/sources/rudder-package/tests/signature/rudder-plugin-zabbix-8.0.0-2.1.rpkg
  relay/sources/rudder-package/tests/signature/rudder-plugin-zabbix-8.0.3-2.1.rpkg
  relay/sources/rudder-package/tools/README.md
  relay/sources/rudder-package/tools/rudder_plugins_key.gpg
Labels: qa: Can't merge

#5181 Fixes #23756: Comparison json should allow to display json diff
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/JsonSpecMatcher.scala
  webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/rest/TraitTestApiFromYamlFiles.scala
Labels: Ready for merge

#5183 Fixes #23759: Make rudder-package able to track installed files
  relay/sources/rudder-package/src/archive.rs
Labels: qa: Can't merge, Ready for merge

#5168 Fixes #23721: Allow testing Windows techniques
  Jenkinsfile
  policies/Cargo.lock
  policies/Dockerfile
  policies/Makefile
  policies/rudder-commons/src/lib.rs
  policies/rudder-module-type/src/lib.rs
  policies/rudderc/Cargo.toml
  policies/rudderc/docs/src/test.md
  policies/rudderc/src/backends/unix.rs
  policies/rudderc/src/backends/unix/prelude.cf
  policies/rudderc/src/backends/windows.rs
  policies/rudderc/src/backends/windows/test.rs
  policies/rudderc/src/lib.rs
  policies/rudderc/src/test.rs
  policies/rudderc/templates/test-directive.ps1.askama
  policies/rudderc/templates/test.ps1.askama
  policies/rudderc/tests/cases/test/one_param_unix/technique.yml
  policies/rudderc/tests/cases/test/one_param_unix/tests/case1.yml
  policies/rudderc/tests/cases/test/one_param_unix/tests/case2.yml
  policies/rudderc/tests/cases/test/one_param_unix/tests/reference.conf
  policies/rudderc/tests/cases/test/one_param_windows/technique.yml
  policies/rudderc/tests/cases/test/one_param_windows/tests/case1.yml
  policies/rudderc/tests/cases/test/one_param_windows/tests/case2.yml
  policies/rudderc/tests/cases/test/one_param_windows/tests/reference.conf
  policies/rudderc/tests/cases/test/zero_param_unix/technique.yml
  policies/rudderc/tests/cases/test/zero_param_unix/tests/case1.yml
  policies/rudderc/tests/cases/test/zero_param_unix/tests/reference.conf
  policies/rudderc/tests/cases/test/zero_param_windows/technique.yml
  policies/rudderc/tests/cases/test/zero_param_windows/tests/case1.yml
  policies/rudderc/tests/cases/test/zero_param_windows/tests/reference.conf
  policies/rudderc/tests/lib/common/10_ncf_internals/initialization.cf
  policies/rudderc/tests/lib/common/30_generic_methods/file_content.cf
  policies/rudderc/tests/test.rs
  policies/supply-chain/audits.toml
  policies/supply-chain/config.toml
  policies/supply-chain/imports.lock
Labels: qa: Can't merge

#5185 Fixes #23763: Improve techniques tests
  policies/Cargo.lock
  policies/Dockerfile
  policies/_typos.toml
  policies/rudderc/Cargo.toml
  policies/rudderc/docs/src/test.md
  policies/rudderc/docs/src/usage.md
  policies/rudderc/src/backends/unix/cfengine.rs
  policies/rudderc/src/backends/windows.rs
  policies/rudderc/src/backends/windows/test.rs
  policies/rudderc/src/cli.rs
  policies/rudderc/src/lib.rs
  policies/rudderc/src/test.rs
  policies/rudderc/templates/test-directive.ps1.askama
  policies/rudderc/templates/test.ps1.askama
  policies/rudderc/tests/cases/general/ntp/metadata.xml
  policies/rudderc/tests/cases/general/ntp/resources/directory/file2.conf
  policies/rudderc/tests/cases/test/one_param_windows/technique.yml
  policies/rudderc/tests/cases/test/one_param_windows/tests/case1.yml
  policies/rudderc/tests/cases/test/one_param_windows/tests/case2.yml
  policies/rudderc/tests/export.rs
  policies/rudderc/tests/test.rs
  policies/supply-chain/audits.toml
  policies/supply-chain/imports.lock
Labels: qa: Can't merge, Ready for merge

#5191 Fixes #23776: Add signature validation for plugins
  relay/sources/rudder-package/src/lib.rs
  relay/sources/rudder-package/src/repository.rs
Labels: qa: Can't merge

#5193 Fixes #23781: Use quick_xml for xml edition
  relay/sources/rudder-package/Cargo.lock
  relay/sources/rudder-package/Cargo.toml
  relay/sources/rudder-package/src/archive.rs
  relay/sources/rudder-package/src/database.rs
  relay/sources/rudder-package/src/lib.rs
  relay/sources/rudder-package/src/signature.rs
  relay/sources/rudder-package/src/webapp.rs
  relay/sources/rudder-package/src/webapp_xml.rs
  relay/sources/rudder-package/tests/webapp_xml/disable_test1.xml.expected
  relay/sources/rudder-package/tests/webapp_xml/disable_when_absent.xml.expected
  relay/sources/rudder-package/tests/webapp_xml/disable_with_multiple_instances.xml.expected
  relay/sources/rudder-package/tests/webapp_xml/enable_test1.xml
  relay/sources/rudder-package/tests/webapp_xml/enable_test1.xml.expected
  relay/sources/rudder-package/tests/webapp_xml/example.xml
Labels: qa: Can't merge

#5195 Fixes #23783: Copy the certificates directly without calling the agent after generation
  webapp/sources/rudder/rudder-core/src/main/resources/hooks.d/policy-generation-finished/50-reload-policy-file-server
Labels: qa: Can't merge

#5201 Bug #23671 : Locale issue: date picker outputs date in wrong order
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/queries/CmdbQuery.scala
Labels: Ready for merge

#5206 Fixes #23798: rudderc method parsing breaks when method contains several bundles
  policies/rudderc/src/frontends/methods/method.rs
  policies/rudderc/tests/methods/package_install.cf
Labels: qa: Can't merge

#5208 Fixes #23800: Fix typos in error message in technique editor
  webapp/sources/ldap-inventory/inventory-repository/src/main/scala/com/normation/history/HistoryLogRepository.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/git/GitItemRepository.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/hooks/RunHooks.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/InterpolatedValueCompiler.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/nodeconfig/NodeConfigurationCacheRepository.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/reports/NodeConfigurationService.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/ArchiveApi.scala
  webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/MockServices.scala
  webapp/sources/rudder/rudder-web/src/main/elm/editor/sources/ViewTechniqueList.elm
  webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/checks/migration/CheckAddSpecialTargetAllPolicyServers.scala
  webapp/sources/scala-ldap/src/main/scala/com/normation/ldap/ldif/LDIFFileLogger.scala
  webapp/sources/scala-ldap/src/main/scala/com/normation/ldap/sdk/LDAPEntry.scala
Labels: qa: Can't merge

#5209 Fixes #23801: Content of warning tooltip for unknow method should not overflow
  webapp/sources/rudder/rudder-web/src/main/elm/editor/sources/ViewTechniqueList.elm
Labels: qa: Can't merge

#5215 Fixes #23807: Add an env var pointing to reports test file
  policies/rudderc/src/lib.rs
  policies/rudderc/src/test.rs
  policies/rudderc/tests/cases/test/one_param_unix/tests/case2.yml
Labels: Ready for merge

#5216 Fixes #23810: Improve docs for techniques testing
  policies/rudderc/docs/src/test.md
Labels: Ready for merge

#5178 Fixes #23735: Exception when bad input for inventory duration config
  webapp/sources/rudder/rudder-web/src/main/resources/configuration.properties.sample
  webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/LiftInitContextListener.scala
  webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala
Labels: qa: Can't merge

#5207 Fixes #23799: Make rudderc able to compile techniques using a per method policy mode override
  policies/_typos.toml
  policies/rudder-commons/src/lib.rs
  policies/rudderc/src/backends/unix/ncf/method_call.rs
  policies/rudderc/src/backends/windows.rs
  policies/rudderc/src/ir/technique.rs
  policies/rudderc/src/technique.schema.json
  policies/rudderc/templates/technique.ps1.askama
  policies/rudderc/tests/cases/general/policy_mode/metadata.xml
  policies/rudderc/tests/cases/general/policy_mode/technique.cf
  policies/rudderc/tests/cases/general/policy_mode/technique.ps1
  policies/rudderc/tests/cases/general/policy_mode/technique.yml
Labels: qa: Can't merge

#5210 Fixes #23802: rudderc should export a technique with ids
  policies/.gitignore
  policies/rudderc/docs/src/usage.md
  policies/rudderc/src/cli.rs
  policies/rudderc/src/ir/condition.rs
  policies/rudderc/src/lib.rs
  policies/rudderc/tests/compile.rs
  policies/rudderc/tests/export.rs
Labels: qa: Can't merge
