Repository Normation/rudder, pull requests merged in 2023-02, with the labels that each got.

#4653 Fixes #22339: Hook timeout may not have the good value
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/hooks/RunHooks.scala
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/hooks/HooksTest.scala
Labels: qa: Can't merge

#4649 Fixes #22326: some nodes are called "localhost" since #8022
  webapp/sources/ldap-inventory/inventory-fusion/src/main/scala/com/normation/inventory/provisioning/fusion/FusionInventoryParser.scala
  webapp/sources/ldap-inventory/inventory-fusion/src/test/resources/fusion-inventories/rudder-tag/invalid-hostname-localhost-alternative-error.ocs
  webapp/sources/ldap-inventory/inventory-fusion/src/test/resources/fusion-inventories/rudder-tag/invalid-hostname-localhost-alternative-ok.ocs
  webapp/sources/ldap-inventory/inventory-fusion/src/test/resources/fusion-inventories/rudder-tag/invalid-hostname-localhost.ocs
  webapp/sources/ldap-inventory/inventory-fusion/src/test/scala/com/normation/inventory/provisioning/fusion/TestReportParsing.scala
Labels: qa: Can't merge

#4655 Fixes #22206: Allow user to define custom roles in rudder-user.xml
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/logger/ApplicationLogger.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/Authorizations.scala
  webapp/sources/rudder/rudder-web/src/main/resources/demo-rudder-users.xml
  webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/AppConfigAuth.scala
  webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala
  webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderUserDetailsFile.scala
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/Authz.scala
  webapp/sources/rudder/rudder-web/src/test/scala/bootstrap/liftweb/RudderUserDetailsTest.scala
Labels: qa: Can't merge

#4658 Fixes #22351: Update the embedded openssl to 1.1.1t
  relay/sources/relayd/Cargo.lock
Labels: qa: Can't merge

#4660 Fixes #22354: Ignore CVE-2023-22895 in relayd
  relay/sources/relayd/deny.toml
Labels: qa: Can't merge

#4656 Fixes #22345: Add Raspbian to the list of recognized OS
  webapp/sources/ldap-inventory/inventory-api/src/main/scala/com/normation/inventory/domain/NodeInventory.scala
  webapp/sources/ldap-inventory/inventory-fusion/src/test/resources/fusion-inventories/raspbian.ocs
  webapp/sources/ldap-inventory/inventory-fusion/src/test/scala/com/normation/inventory/provisioning/fusion/TestReportParsing.scala
  webapp/sources/ldap-inventory/inventory-repository/src/main/scala/com/normation/inventory/ldap/core/InventoryMapper.scala
  webapp/sources/ldap-inventory/inventory-repository/src/main/scala/com/normation/inventory/ldap/core/LDAPConstants.scala
  webapp/sources/rudder/rudder-web/src/main/resources/ldapObjectAndAttributes.properties
  webapp/sources/rudder/rudder-web/src/main/webapp/images/os/raspbian-logo.svg
  webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-node.css
Labels: Ready for merge

#4664 Fixes #22374: Allow iframes from the same origin
  webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/Boot.scala
Labels: qa: Can't merge

#4659 Fixes #22353: Administrator doesn't have any access anymore
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/Authorizations.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/web/services/CurrentUser.scala
  webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderUserDetailsFile.scala
Labels: qa: Can't merge

#4667 Fixes #20834: File from shared folder method does not support special characters in the source path
  relay/sources/relayd/src/api/shared_folder.rs
  relay/sources/relayd/tests/api_shared_folder/c745a140-40bc-4b86-b6dc-084488fc906b/37817c4d-fbf7-4850-a985-50021f4e8f41/file with space
  relay/sources/relayd/tests/shared_folder.rs
Labels: Ready for merge

#4666 Fixes #22378: Generate policies for campaigns before it starts officially, delete them after it stops (1 hour delay each)
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/campaigns/MainCampaignService.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/hooks/RunHooks.scala
  webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/MockServices.scala
  webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala
Labels: qa: Can't merge

#4661 Fixes #22357: Reloading user must discared previously registered custom-roles
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/Authorizations.scala
  webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderUserDetailsFile.scala
  webapp/sources/rudder/rudder-web/src/test/scala/bootstrap/liftweb/RudderUserDetailsTest.scala
Labels: qa: Can't merge, Ready for merge

#4651 Fixes #22333: Avoid sync group when importing a rule archive
  webapp/sources/api-doc/code_samples/curl/archives/import.sh
  webapp/sources/api-doc/paths/archives/import.yml
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/ArchiveApi.scala
  webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/rest/ArchiveApiTest.scala
  webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/rest/RestTestSetUp.scala
Labels: qa: Can't merge

#4662 Fixes #22359: Make parsing "process" in inventory optional
  webapp/sources/ldap-inventory/inventory-fusion/src/main/scala/com/normation/inventory/provisioning/fusion/FusionInventoryParser.scala
  webapp/sources/ldap-inventory/inventory-fusion/src/test/scala/com/normation/inventory/provisioning/fusion/TestReportParsing.scala
  webapp/sources/rudder/rudder-web/src/main/resources/configuration.properties.sample
  webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala
Labels: qa: Can't merge, Ready for merge
