Repository Normation/rudder, pull requests merged in 2023-12, with the labels that each got.

#5226 Fixes #23332: Serde errors do not point to the correct line number
  policies/rudderc/src/frontends.rs
  policies/rudderc/src/ir/technique.rs
Labels: qa: Can't merge

#5223 Fixes #23819: Sometimes, tooltips in the directives tree remain displayed
  webapp/sources/rudder/rudder-web/src/main/javascript/rudder/rudder.js
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/configuration/DirectiveManagement.scala
Labels: qa: Can't merge

#5194 Fixes #23588: In Technique Editor, the quicksearch window still appears behind the navigation menu
  webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder-technique-editor.css
Labels: qa: Can't merge

#5232 Fixes #23836: Event log migration should not be done every time
  webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/checks/migration/MigrateEventLogEnforceSchema.scala
  webapp/sources/rudder/rudder-web/src/test/scala/bootstrap/liftweb/checks/migration/TestMigrateEventLogEnforceSchema.scala
Labels: qa: Can't merge

#5233 Fixes #23837: Enforce change request and workflow table schema
  webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala
  webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/checks/migration/DbCommonMigration.scala
  webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/checks/migration/MigrateChangeValidationEnforceSchema.scala
  webapp/sources/rudder/rudder-web/src/test/scala/bootstrap/liftweb/checks/migration/TestMigrateChangeValidationEnforceSchema.scala
Labels: qa: Can't merge

#5213 Fixes #23804: Add some services available to improve system update performance
  webapp/sources/ldap-inventory/inventory-api/src/main/scala/com/normation/inventory/services/provisioning/InventorySaver.scala
  webapp/sources/ldap-inventory/inventory-provisioning-core/src/main/scala/com/normation/inventory/ldap/provisioning/DefaultInventorySaver.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/NodeApi.scala
  webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/rest/RestTestSetUp.scala
  webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala
  webapp/sources/scala-ldap/src/main/scala/com/normation/ldap/sdk/LDAPConnection.scala
Labels: qa: Can't merge

#5225 Fixes #23789: system status tab show normal directives rather than system directives
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/EndpointsDefinition.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/ComplianceApi.scala
  webapp/sources/rudder/rudder-web/src/main/elm/sources/NodeCompliance/ApiCalls.elm
  webapp/sources/rudder/rudder-web/src/main/elm/sources/NodeCompliance/DataTypes.elm
  webapp/sources/rudder/rudder-web/src/main/elm/sources/NodeCompliance/Init.elm
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/ShowNodeDetailsFromNode.scala
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/services/ReportDisplayer.scala
Labels: qa: Can't merge, Ready for merge

#5246 Fixes #23895: We can access system rules detail page from node system status tab
  webapp/sources/rudder/rudder-web/src/main/elm/sources/NodeCompliance/ViewUtils.elm
Labels: Ready for merge

#5253 Fixes #23865: Common style for Rust CLI output
  policies/rudder-cli/src/logs.rs
  relay/sources/rudder-package/src/lib.rs
  relay/sources/rudder-package/src/main.rs
Labels: qa: Can't merge

#5255 Fixes #22170: A new group display no nodes while all linux are selected
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/popup/CreateCategoryOrGroupPopup.scala
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/popup/CreateCloneGroupPopup.scala
Labels: qa: Can't merge

#5254 Fixes #23446: Change request on special:all_nodes_without_role lead to error
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/policies/RuleTarget.scala
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/domain/policies/RuleTargetTest.scala
Labels: qa: Can't merge, Ready for merge

#5248 Fixes #23878: Rename the "Create global property" button in "Create"
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/configuration/ParameterManagement.scala
Labels: qa: Can't merge

#5273 Fixes #23940: rudderc code is not properly formatted due to a failed resolution of merge
  policies/rudderc/src/backends/unix/ncf/method_call.rs
Labels: Ready for merge

#5250 Fixes #23883: The "Category" field in the technique editor is displayed as a mandatory field even if it is an unmutable one
  webapp/sources/rudder/rudder-web/src/main/elm/editor/sources/ViewTechniqueTabs.elm
Labels: qa: Can't merge

#5274 Fixes #23941: Improve rudderc test error message when no library is passed in the parameters
  policies/rudderc/src/lib.rs
Labels: Ready for merge

#5283 Fixes #23953: Improve rudderc error message when a parameter is missing from a method call
  policies/rudderc/src/compiler.rs
Labels: Ready for merge

#5264 Fixes #23891: The health check page has an unnecessary "Show check list" button
  webapp/sources/rudder/rudder-web/src/main/elm/healthcheck/sources/DataTypes.elm
  webapp/sources/rudder/rudder-web/src/main/elm/healthcheck/sources/Healthcheck.elm
  webapp/sources/rudder/rudder-web/src/main/elm/healthcheck/sources/Init.elm
  webapp/sources/rudder/rudder-web/src/main/elm/healthcheck/sources/View.elm
Labels: qa: Can't merge

#5268 Fixes #23856: Impact of RBAC node filtering on compliance
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/policies/RuleApplicationStatus.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/policies/RuleTarget.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/facts/nodes/NodeFact.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/NodeGroupRepository.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/DeploymentService.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/RuleApplicationStatusService.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/RuleValService.scala
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/domain/policies/RuleTargetTest.scala
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/policies/RuleValServiceTest.scala
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/policies/TestBuildNodeConfiguration.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/UserService.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/ApiAuthorization.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/ArchiveApi.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/ComplianceApi.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/DirectiveApi.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/GroupsApi.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/NodeApi.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/ParametersApi.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/RuleApi.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/SettingsApi.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/TechniqueApi.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/web/services/CurrentUser.scala
  webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/rest/RestTestSetUp.scala
  webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/rest/TraitTestApiFromYamlFiles.scala
  webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/NodeGroupForm.scala
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/RuleGrid.scala
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/popup/ExpectedPolicyPopup.scala
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/services/ComplianceData.scala
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/HomePage.scala
Labels: Ready for merge

#5288 Fixes #23929: Display compliance score in the Node summary tab
  webapp/sources/rudder/rudder-web/src/main/elm/sources/Compliance/JsonDecoder.elm
  webapp/sources/rudder/rudder-web/src/main/elm/sources/Compliance/Utils.elm
  webapp/sources/rudder/rudder-web/src/main/elm/sources/ComplianceScore/ApiCalls.elm
  webapp/sources/rudder/rudder-web/src/main/elm/sources/ComplianceScore/DataTypes.elm
  webapp/sources/rudder/rudder-web/src/main/elm/sources/ComplianceScore/Init.elm
  webapp/sources/rudder/rudder-web/src/main/elm/sources/ComplianceScore/JsonDecoder.elm
  webapp/sources/rudder/rudder-web/src/main/elm/sources/ComplianceScore/View.elm
  webapp/sources/rudder/rudder-web/src/main/elm/sources/ComplianceScore/ViewUtils.elm
  webapp/sources/rudder/rudder-web/src/main/elm/sources/Compliancescore.elm
  webapp/sources/rudder/rudder-web/src/main/elm/sources/DirectiveCompliance/Init.elm
  webapp/sources/rudder/rudder-web/src/main/elm/sources/DirectiveCompliance/JsonDecoder.elm
  webapp/sources/rudder/rudder-web/src/main/elm/sources/Node.elm
  webapp/sources/rudder/rudder-web/src/main/elm/sources/Node/ApiCalls.elm
  webapp/sources/rudder/rudder-web/src/main/elm/sources/Node/DataTypes.elm
  webapp/sources/rudder/rudder-web/src/main/elm/sources/Node/Init.elm
  webapp/sources/rudder/rudder-web/src/main/elm/sources/Node/View.elm
  webapp/sources/rudder/rudder-web/src/main/elm/sources/NodeCompliance/Init.elm
  webapp/sources/rudder/rudder-web/src/main/elm/sources/NodeCompliance/JsonDecoder.elm
  webapp/sources/rudder/rudder-web/src/main/elm/sources/Rules/Init.elm
  webapp/sources/rudder/rudder-web/src/main/elm/sources/Rules/JsonDecoder.elm
  webapp/sources/rudder/rudder-web/src/main/elm/sources/Rules/ViewRulesTable.elm
  webapp/sources/rudder/rudder-web/src/main/elm/sources/Rules/ViewTabContent.elm
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/services/DisplayNode.scala
  webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder-bootstrap.css
  webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder-compliance.scss
  webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder-dashboard.css
  webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder-node.scss
  webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder-template.css
  webapp/sources/rudder/rudder-web/src/main/webapp/images/score-badges/rudder-score-badge-A.svg
  webapp/sources/rudder/rudder-web/src/main/webapp/images/score-badges/rudder-score-badge-B.svg
  webapp/sources/rudder/rudder-web/src/main/webapp/images/score-badges/rudder-score-badge-C.svg
  webapp/sources/rudder/rudder-web/src/main/webapp/images/score-badges/rudder-score-badge-D.svg
  webapp/sources/rudder/rudder-web/src/main/webapp/images/score-badges/rudder-score-badge-E.svg
  webapp/sources/rudder/rudder-web/src/main/webapp/images/score-badges/rudder-score-badge-F.svg
  webapp/sources/rudder/rudder-web/src/main/webapp/images/score-badges/rudder-score-badge-X.svg
  webapp/sources/rudder/rudder-web/src/main/webapp/images/score-badges/rudder-score-badge-sm-A.svg
  webapp/sources/rudder/rudder-web/src/main/webapp/images/score-badges/rudder-score-badge-sm-B.svg
  webapp/sources/rudder/rudder-web/src/main/webapp/images/score-badges/rudder-score-badge-sm-C.svg
  webapp/sources/rudder/rudder-web/src/main/webapp/images/score-badges/rudder-score-badge-sm-D.svg
  webapp/sources/rudder/rudder-web/src/main/webapp/images/score-badges/rudder-score-badge-sm-E.svg
  webapp/sources/rudder/rudder-web/src/main/webapp/images/score-badges/rudder-score-badge-sm-F.svg
  webapp/sources/rudder/rudder-web/src/main/webapp/images/score-badges/rudder-score-badge-sm-X.svg
  webapp/sources/rudder/rudder-web/src/main/webapp/secure/nodeManager/node.html
  webapp/sources/rudder/rudder-web/src/main/webapp/templates-hidden/common-layout.html
Labels: qa: Can't merge, Ready for merge

#5272 Fixes #23935: API for node group compliance
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/policies/RuleTarget.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/EndpointsDefinition.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/RoleApiMapping.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/data/Compliance.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/ComplianceApi.scala
  webapp/sources/rudder/rudder-rest/src/test/resources/api/api_compliance.yml
  webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/MockServices.scala
  webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/rest/RestTestSetUp.scala
  webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/rest/TestRestFromFileDef.scala
Labels: qa: Can't merge
