Repository Normation/rudder, pull requests merged in 2023-03, with the labels that each got.

#4675 Fixes #22371: missing report in change only
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/reports/ExecutionBatch.scala
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/reports/ExecutionBatchTest.scala
Labels: Ready for merge

#4682 Fixes #22430: Healthcheck on file descriptor should be max 64000
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/healthcheck/HealthcheckService.scala
Labels: qa: Can't merge

#4685 Fixes #22435: Directive compliance API version is 10 in place of 17
  webapp/sources/api-doc/openapi.src.yml
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/ApiDatastructures.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/EndpointsDefinition.scala
  webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala
Labels: qa: Can't merge, Ready for merge

#4704 Fixes #18215: Persisted rule should have sorted groups/directives
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/marshalling/XmlSerialisationImpl.scala
Labels: Ready for merge

#4702 Fixes #22475: There is one more minus in deleted resources counter within technique editor
  webapp/sources/rudder/rudder-web/src/main/elm/editor/sources/ViewTechnique.elm
Labels: Ready for merge

#4701 Fixes #21369: Technique ID and group ID are juste listed as "ID" in the UI when other IDs are listed with their long name
  webapp/sources/rudder/rudder-web/src/main/elm/editor/sources/ViewTechniqueTabs.elm
  webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/ViewTabContent.elm
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/NodeGroupCategoryForm.scala
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/NodeGroupForm.scala
Labels: Ready for merge

#4686 Fixes #22392: Directive detail is really slow to load in 7.3
  webapp/sources/rudder/rudder-web/src/main/elm/directivecompliance/sources/DataTypes.elm
  webapp/sources/rudder/rudder-web/src/main/elm/directivecompliance/sources/Directivecompliance.elm
  webapp/sources/rudder/rudder-web/src/main/elm/directivecompliance/sources/Init.elm
  webapp/sources/rudder/rudder-web/src/main/elm/directivecompliance/sources/View.elm
  webapp/sources/rudder/rudder-web/src/main/elm/directivecompliance/sources/ViewNodesCompliance.elm
  webapp/sources/rudder/rudder-web/src/main/elm/directivecompliance/sources/ViewRulesCompliance.elm
  webapp/sources/rudder/rudder-web/src/main/elm/directivecompliance/sources/ViewUtils.elm
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/DirectiveEditForm.scala
  webapp/sources/rudder/rudder-web/src/main/webapp/templates-hidden/components/ComponentDirectiveEditForm.html
Labels: Ready for merge

#4671 Fixes #22383: Password tag should be optionnal
  webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderUserDetailsFile.scala
  webapp/sources/rudder/rudder-web/src/test/scala/bootstrap/liftweb/RudderUserDetailsTest.scala
Labels: Ready for merge

#4678 Fixes #21731: Rule is in mixed mode even though she has only one directive in audit
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/web/services/ComputePolicyMode.scala
  webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/web/services/ComputePolicyModeTest.scala
Labels: Ready for merge

#4681 Fixes #22428: Missing tooltip on unused directives icon
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/services/DisplayDirectiveTree.scala
  webapp/sources/rudder/rudder-web/src/main/webapp/javascript/rudder/tree.js
Labels: Ready for merge

#4703 Fixes #21924: Policy generation broken when defining a group with invert result of inclusion of another group
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/nodes/MergeNodeProperties.scala
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/nodes/TestMergeGroupProperties.scala
Labels: Ready for merge

#4708 Fixes #22489: Add a JSON schema validation
  policies/Cargo.lock
  policies/rudderc/Cargo.toml
  policies/rudderc/src/lib.rs
  policies/rudderc/src/technique.schema.json
  policies/rudderc/tests/compile.rs
Labels: qa: Can't merge, Ready for merge

#4710 Fixes #22509: Improve introduction of relay arch docs
  relay/arch-doc/README.md
  relay/arch-doc/rudder-6-reporting-relayd.md
  relay/arch-doc/rudder-7-communications-security.md
Labels: qa: Can't merge, Ready for merge

#4711 Fixes #22511: Add a json schema file to describe the rudder technique yaml format
  policies/rudderc/src/technique.schema.json
Labels: qa: Can't merge, Ready for merge

#4716 Fixes #22532:
  relay/sources/relayd/Cargo.lock
  relay/sources/relayd/Dockerfile
  relay/sources/relayd/rust-toolchain
  relay/sources/relayd/rust-toolchain.toml
Labels: Ready for merge

#4718 Fixes #22543: Allow BSD-2-Clause licences
  policies/deny.toml
Labels: Ready for merge

#4714 Fixes #22512: Arch doc for frontend security
  webapp/arch-doc/rudder-7-3-frontend-security.md
Labels: qa: Can't merge, Ready for merge

#4721 Fixes #22545: Refactor CLI to work on a local directory
  policies/Cargo.lock
  policies/Makefile
  policies/module-types/template/Cargo.toml
  policies/rudder-commons-test/Cargo.toml
  policies/rudder-commons/src/lib.rs
  policies/rudder-module-type/src/parameters.rs
  policies/rudderc/Cargo.toml
  policies/rudderc/docs/examples/ntp/technique.yml
  policies/rudderc/docs/index.adoc
  policies/rudderc/src/backends.rs
  policies/rudderc/src/backends/metadata.rs
  policies/rudderc/src/backends/unix.rs
  policies/rudderc/src/backends/unix/ncf/method_call.rs
  policies/rudderc/src/backends/windows.rs
  policies/rudderc/src/cli.rs
  policies/rudderc/src/compiler.rs
  policies/rudderc/src/doc.rs
  policies/rudderc/src/frontends/methods.rs
  policies/rudderc/src/frontends/methods/method.rs
  policies/rudderc/src/frontends/yaml.rs
  policies/rudderc/src/ir/technique.rs
  policies/rudderc/src/lib.rs
  policies/rudderc/src/technique.schema.json
  policies/rudderc/tests/compile.rs
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/ncf/TechniqueReader.scala
Labels: qa: Can't merge

#4722 Fixes #22522: Allow iframes from the same origin
  webapp/sources/rudder/rudder-web/src/main/resources/applicationContext-security.xml
Labels: Ready for merge

#4730 Fixes #22535: Mustache template is not capable to render technique parameters
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/ncf/TechniqueWriter.scala
  webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/techniques/ncf_techniques/technique_any/1.0/technique.ps1
  webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/techniques/ncf_techniques/technique_any/2.0/technique.ps1
  webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/techniques/ncf_techniques/technique_by_Rudder/1.0/technique.ps1
Labels: Ready for merge
