Repository Normation/rudder, pull requests merged in 2023-01, with the labels that each got.

#4613 Fixes #22209: Dynamic group logs must not be conflated with scheduled job ones
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/batch/UpdateDynamicGroups.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/logger/ApplicationLogger.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/queries/DynGroupService.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/queries/DynGroupUpdaterService.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/SystemApi.scala
  webapp/sources/rudder/rudder-web/src/main/resources/logback.xml
Labels: qa: Can't merge, Ready for merge

#4616 Fixes #7526: Housekeeping of /var/rudder/inventories/received|failed|etc
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/batch/PurgeDeletedInventories.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/batch/PurgeOldInventoryFiles.scala
  webapp/sources/rudder/rudder-web/src/main/resources/configuration.properties.sample
  webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala
Labels: Ready for merge

#4608 Fixes #22191: Test various known escaping problems
  Jenkinsfile
  policies/Cargo.lock
  policies/Dockerfile
  policies/module-types/directory/Cargo.toml
  policies/module-types/directory/rudder_module_type.yml
  policies/module-types/directory/src/main.rs
  policies/module-types/template/rudder_module_type.yml
  policies/rudder-commons-test/src/module_type.rs
  policies/rudder-commons-test/src/test.cf
  policies/rudder-module-type/src/cfengine.rs
  policies/rudder-module-type/src/cfengine/header.rs
  policies/rudder-module-type/src/cfengine/protocol.rs
  policies/rudder-module-type/src/cfengine/runner.rs
  policies/rudder-module-type/src/parameters.rs
  policies/rudderc/src/backends/metadata.rs
  policies/rudderc/src/backends/unix/cfengine.rs
  policies/rudderc/src/backends/unix/ncf/method_call.rs
  policies/rudderc/src/ir/technique.rs
  policies/rudderc/tests/cases/general/escaping/metadata.xml
  policies/rudderc/tests/cases/general/escaping/technique.cf
  policies/rudderc/tests/cases/general/escaping/technique.ps1
  policies/rudderc/tests/cases/general/escaping/technique.yml
  policies/rust-toolchain.toml
  relay/sources/relayd/Cargo.lock
  relay/sources/relayd/Dockerfile
  relay/sources/relayd/rust-toolchain.toml
  relay/sources/relayd/src/data/runlog.rs
  relay/sources/relayd/tests/shared_files.rs
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/ncf/TechniqueReader.scala
  webapp/sources/rudder/rudder-web/src/main/webapp/javascript/angular/angular-animate.min.js.map
  webapp/sources/rudder/rudder-web/src/main/webapp/javascript/angular/angular-touch.min.js.map
  webapp/sources/rudder/rudder-web/src/main/webapp/style/jquery-ui/images/ui-icons_444444_256x240.png
  webapp/sources/rudder/rudder-web/src/main/webapp/style/jquery-ui/images/ui-icons_555555_256x240.png
  webapp/sources/rudder/rudder-web/src/main/webapp/style/jquery-ui/images/ui-icons_777620_256x240.png
  webapp/sources/rudder/rudder-web/src/main/webapp/style/jquery-ui/images/ui-icons_777777_256x240.png
  webapp/sources/rudder/rudder-web/src/main/webapp/style/jquery-ui/images/ui-icons_cc0000_256x240.png
  webapp/sources/rudder/rudder-web/src/main/webapp/style/jquery-ui/images/ui-icons_ffffff_256x240.png
Labels: qa: Can't merge

#4629 Fixes #22249: Ignore RUSTSEC-2023-0001 in relayd
  relay/sources/relayd/deny.toml
Labels: qa: Can't merge, Ready for merge

#4628 Fixes #22248: Add includeSubdomains to HSTS header
  webapp/sources/rudder/rudder-web/src/main/resources/configuration.properties.sample
  webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/Boot.scala
  webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala
Labels: qa: Can't merge

#4635 Fixes #22270: Use npm to maintain gauge.js
  webapp/sources/rudder/rudder-web/src/main/javascript/gauge/gauge.min.js
  webapp/sources/rudder/rudder-web/src/main/package-lock.json
  webapp/sources/rudder/rudder-web/src/main/package.json
  webapp/sources/rudder/rudder-web/src/main/webapp/secure/index.html
Labels: Ready for merge

#4634 Fixes #22274: Add includeSubdomains to HSTS header with correct property name
  Jenkinsfile
  webapp/sources/rudder/rudder-web/src/main/resources/configuration.properties.sample
  webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala
Labels: qa: Can't merge

#4623 Fixes #22239: Windows policy generation
  policies/Cargo.lock
  policies/module-types/template/Cargo.toml
  policies/rudder-commons/Cargo.toml
  policies/rudderc/Cargo.toml
  policies/rudderc/src/backends.rs
  policies/rudderc/src/backends/unix.rs
  policies/rudderc/src/backends/unix/ncf/method_call.rs
  policies/rudderc/src/backends/windows.rs
  policies/rudderc/templates/technique.ps1.askama
  policies/rudderc/tests/cases/general/escaping/technique.cf
  policies/rudderc/tests/cases/general/escaping/technique.ps1
  policies/rudderc/tests/cases/general/min/technique.cf
  policies/rudderc/tests/cases/general/min/technique.ps1
  policies/rudderc/tests/cases/general/ntp/technique.cf
  policies/rudderc/tests/cases/general/ntp/technique.ps1
  policies/rudderc/tests/cases/general/reporting/technique.cf
  policies/rudderc/tests/cases/general/reporting/technique.ps1
  policies/rudderc/tests/compile.rs
  relay/sources/relayd/Cargo.lock
  relay/sources/relayd/Cargo.toml
  relay/sources/relayd/deny.toml
  relay/sources/relayd/src/hashing.rs
Labels: qa: Can't merge

#4640 Fixes #22299: Add a line break at the end if inventory rejection log file
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/inventory/InventoryProcessor.scala
Labels: qa: Can't merge, Ready for merge

#4641 Fixes #22300: Update the toml crate to 0.6
  .cargo/config.toml
  policies/Cargo.lock
  relay/sources/relayd/Cargo.lock
  relay/sources/relayd/Cargo.toml
Labels: qa: Can't merge

#4621 Fixes #22226: Typo and missing log info in cleaning old inventory file parent ticket
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/batch/PurgeOldInventoryFiles.scala
Labels: qa: Can't merge

#4627 Fixes #22139: Running deleted campaign don't get their directive cleaned-up
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/campaigns/CampaignEventRepository.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/campaigns/MainCampaignService.scala
Labels: Ready for merge

#4643 Fixes #22307: Fix npm security alerts
  webapp/sources/rudder/rudder-web/src/main/.nsprc
  webapp/sources/rudder/rudder-web/src/main/package-lock.json
  webapp/sources/rudder/rudder-web/src/main/package.json
Labels: qa: Can't merge, Ready for merge

#4648 Fixes #22324: Ignore DoS in npm dependencies
  webapp/sources/rudder/rudder-web/src/main/.nsprc
Labels: Ready for merge

#4650 Fixes #22328: Ignore RUSTSEC-2022-0082
  relay/sources/relayd/deny.toml
  relay/sources/rudder-pkg/requirements.txt
Labels: qa: Can't merge, Ready for merge

#4652 Fixes #22336: Update outdated npm packages
  webapp/sources/rudder/rudder-web/src/main/package-lock.json
Labels: Ready for merge

#4646 Fixes #22314: Cannot list directives with API
  webapp/sources/rudder/rudder-core/src/main/resources/ldap/bootstrap.ldif
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/queries/TestQueryProcessor.scala
  webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala
  webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/checks/action/RemoveFaultyLdapEntries.scala
Labels: Ready for merge

#4647 Fixes #22318: Refactor case insensitivity property for users
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/Authorizations.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/RoleApiMapping.scala
  webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/AppConfigAuth.scala
  webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala
  webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderUserDetailsFile.scala
  webapp/sources/rudder/rudder-web/src/test/scala/bootstrap/liftweb/RudderUserDetailsTest.scala
  webapp/sources/rudder/rudder-web/src/test/scala/bootstrap/liftweb/RudderUserPasswordEncoderTest.scala
Labels: qa: Can't merge

#4626 Fixes #22072: Display compliance by directive
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/reports/ReportingService.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/EndpointsDefinition.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/RoleApiMapping.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/data/Compliance.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/ComplianceApi.scala
  webapp/sources/rudder/rudder-web/src/main/elm/directivecompliance/elm.json
  webapp/sources/rudder/rudder-web/src/main/elm/directivecompliance/sources/ApiCalls.elm
  webapp/sources/rudder/rudder-web/src/main/elm/directivecompliance/sources/ComplianceUtils.elm
  webapp/sources/rudder/rudder-web/src/main/elm/directivecompliance/sources/DataTypes.elm
  webapp/sources/rudder/rudder-web/src/main/elm/directivecompliance/sources/Directivecompliance.elm
  webapp/sources/rudder/rudder-web/src/main/elm/directivecompliance/sources/Init.elm
  webapp/sources/rudder/rudder-web/src/main/elm/directivecompliance/sources/JsonDecoder.elm
  webapp/sources/rudder/rudder-web/src/main/elm/directivecompliance/sources/View.elm
  webapp/sources/rudder/rudder-web/src/main/elm/directivecompliance/sources/ViewNodesCompliance.elm
  webapp/sources/rudder/rudder-web/src/main/elm/directivecompliance/sources/ViewRulesCompliance.elm
  webapp/sources/rudder/rudder-web/src/main/elm/directivecompliance/sources/ViewUtils.elm
  webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/ViewUtils.elm
  webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/DirectiveEditForm.scala
  webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder-directives.css
  webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder-menu.css
  webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder-progress-bar.css
  webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder-template.css
  webapp/sources/rudder/rudder-web/src/main/webapp/secure/configurationManager/directiveManagement.html
  webapp/sources/rudder/rudder-web/src/main/webapp/templates-hidden/components/ComponentDirectiveEditForm.html
Labels: qa: Can't merge
