Repository Normation/rudder, pull requests merged in 2023-08, with the labels that each got.

#4929 Fixes #23175: Build rust binaries with cargo auditable
  ci/rust.sh
  policies/Makefile
  rust.makefile
Labels: qa: Can't merge, Ready for merge

#4932 Fixes #23180: Switch to tracing for logging
  policies/Cargo.lock
  policies/rudderc/Cargo.toml
  policies/rudderc/src/backends/unix.rs
  policies/rudderc/src/backends/unix/cfengine.rs
  policies/rudderc/src/compiler.rs
  policies/rudderc/src/frontends.rs
  policies/rudderc/src/lib.rs
  policies/rudderc/src/logs.rs
  policies/rudderc/src/main.rs
  policies/supply-chain/audits.toml
  policies/supply-chain/config.toml
  policies/supply-chain/imports.lock
Labels: qa: Can't merge, Ready for merge

#4924 Fixes #23060: Rewrite angular app "passwordForm" in JavaScript
  webapp/sources/rudder/rudder-web/src/main/javascript/rudder/angular/passwordForm.js
  webapp/sources/rudder/rudder-web/src/main/javascript/rudder/directive-inputs.js
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/model/DirectiveFieldEditors.scala
  webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder-directives.css
  webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder-main.css
  webapp/sources/rudder/rudder-web/src/main/webapp/index.html
  webapp/sources/rudder/rudder-web/src/main/webapp/templates-hidden/components/passwordInput.html
Labels: WIP

#4933 Fixes #23185: Allow JSON output
  policies/rudder-commons/src/logs.rs
  policies/rudderc/src/cli.rs
  policies/rudderc/src/logs.rs
  policies/rudderc/src/main.rs
Labels: Ready for merge

#4936 Fixes #23191: Install cargo-auditable before building
  rust.makefile
Labels: Ready for merge

#4938 Fixes #23194: Warn on deprecated methods
  policies/rudderc/src/compiler.rs
  policies/rudderc/src/ir/value.rs
Labels: Ready for merge

#4939 Fixes #23195: Fix JSON output of the lib command
  policies/rudder-commons/src/methods.rs
  policies/rudderc/src/doc.rs
  policies/rudderc/src/lib.rs
Labels: Ready for merge

#4940 Fixes #23200: Password form in User directives does not works properly
  webapp/sources/rudder/rudder-web/src/main/javascript/rudder/directive-inputs.js
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/model/DirectiveFieldEditors.scala
  webapp/sources/rudder/rudder-web/src/main/webapp/templates-hidden/components/passwordInput.html
Labels: Ready for merge

#4923 Fixes #23004: Interface color inconsistency for non compliance display
  webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder-datatable.css
Labels: Ready for merge

#4943 Fixes #23177: in the technique editor, the drop down list for condition is truncated
  webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-technique-editor.css
Labels: Ready for merge

#4942 Fixes #23201: Rewrite angular app tags.js in Elm
  webapp/sources/rudder/rudder-web/src/main/elm/sources/Tags.elm
  webapp/sources/rudder/rudder-web/src/main/elm/sources/Tags/ApiCalls.elm
  webapp/sources/rudder/rudder-web/src/main/elm/sources/Tags/DataTypes.elm
  webapp/sources/rudder/rudder-web/src/main/elm/sources/Tags/Init.elm
  webapp/sources/rudder/rudder-web/src/main/elm/sources/Tags/JsonDecoder.elm
  webapp/sources/rudder/rudder-web/src/main/elm/sources/Tags/JsonEncoder.elm
  webapp/sources/rudder/rudder-web/src/main/elm/sources/Tags/View.elm
  webapp/sources/rudder/rudder-web/src/main/javascript/rudder/angular/passwordForm.js
  webapp/sources/rudder/rudder-web/src/main/javascript/rudder/angular/tags.js
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/TagsEditForm.scala
  webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder-tags.css
  webapp/sources/rudder/rudder-web/src/main/webapp/secure/administration/apiManagement.html
  webapp/sources/rudder/rudder-web/src/main/webapp/secure/configurationManager/directiveManagement.html
  webapp/sources/rudder/rudder-web/src/main/webapp/secure/configurationManager/ruleManagement.html
  webapp/sources/rudder/rudder-web/src/main/webapp/secure/nodeManager/node.html
  webapp/sources/rudder/rudder-web/src/main/webapp/secure/nodeManager/searchNodes.html
  webapp/sources/rudder/rudder-web/src/main/webapp/templates-hidden/components/ComponentDirectiveEditForm.html
  webapp/sources/rudder/rudder-web/src/main/webapp/templates-hidden/components/ComponentTags.html
Labels: qa: Can't merge

#4945 Fixes #23212: N/A report message when a block expression is not valid is not rendered correctly
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/ncf/TechniqueWriter.scala
  webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/techniques/ncf_techniques/technique_by_Rudder/1.0/rudder_reporting.cf
Labels: qa: Can't merge

#4947 Fixes #22830: Message “Error getting directive compliance” when creating new directive
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/DirectiveEditForm.scala
  webapp/sources/rudder/rudder-web/src/main/webapp/templates-hidden/components/ComponentDirectiveEditForm.html
Labels: qa: Can't merge, Ready for merge

#4951 Fixes #23219: Remove unused Rust dependencies
  ci/rust.sh
  policies/Cargo.lock
  policies/module-types/template/Cargo.toml
  policies/rudder-commons/Cargo.toml
  policies/rudderc/Cargo.toml
  policies/supply-chain/audits.toml
  policies/supply-chain/config.toml
  policies/supply-chain/imports.lock
  relay/sources/relayd/Cargo.lock
  relay/sources/relayd/Cargo.toml
  relay/sources/relayd/supply-chain/audits.toml
  relay/sources/relayd/supply-chain/config.toml
  relay/sources/relayd/supply-chain/imports.lock
Labels: qa: Can't merge, Ready for merge

#4950 Fixes #23216: Update Rust compiler to 1.71.1 for security fix
  policies/Dockerfile
  policies/rudder-module-type/src/cfengine/protocol.rs
  policies/rudderc/src/ir/technique.rs
  policies/rudderc/src/logs.rs
  policies/rust-toolchain.toml
  relay/sources/relayd/Dockerfile
  relay/sources/relayd/rust-toolchain.toml
Labels: qa: Can't merge, Ready for merge

#4953 Fixes #22379: Rename "global parameters" to "global properties"
  webapp/sources/api-doc/openapi.src.yml
  webapp/sources/api-doc/paths/parameters/parameters-id.yml
  webapp/sources/api-doc/paths/parameters/parameters.yml
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/popup/CreateOrUpdateGlobalParameterPopup.scala
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/configuration/ParameterManagement.scala
  webapp/sources/rudder/rudder-web/src/main/webapp/secure/configurationManager/parameterManagement.html
Labels: qa: Can't merge, Ready for merge

#4954 Fixes #23224: rudder package doesn't upgrade openscap, and it brings a lot of chaos
  relay/sources/rudder-pkg/lib/rudder-pkg/rudderPkg.py
Labels: Ready for merge

#4949 Fixes #23218: Windows agent cannot get immediatly its policies right after being accepted
  webapp/sources/rudder/rudder-core/src/main/resources/hooks.d/policy-generation-finished/50-reload-policy-file-server
Labels: Ready for merge

#4956 Fixes #23226:
  relay/sources/api-doc/components/parameters/file-id.yml
  relay/sources/api-doc/paths/shared-files.yml
  relay/sources/relayd/Cargo.lock
  relay/sources/relayd/Cargo.toml
  relay/sources/relayd/src/api.rs
  relay/sources/relayd/src/api/remote_run.rs
  relay/sources/relayd/src/api/shared_files.rs
  relay/sources/relayd/src/api/shared_folder.rs
  relay/sources/relayd/src/data/shared_file.rs
  relay/sources/relayd/src/output/database.rs
Labels: qa: Can't merge, Ready for merge

#4957 Fixes #23227:
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/ApiAuthorization.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/internal/EventLogAPI.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/internal/RestApiAccounts.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/internal/RestCompletion.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/internal/RestQuicksearch.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/internal/SharedFilesAPI.scala
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/services/DisplayNode.scala
Labels: qa: Can't merge, Ready for merge

#4961 Fixes #23229:
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/internal/SharedFilesAPI.scala
Labels: qa: Can't merge, Ready for merge

#4962 Fixes #23230:
  webapp/sources/pom.xml
Labels: qa: Can't merge, Ready for merge

#4963 Fixes #23231: CVE-2016-1000027 false positive detection
  webapp/sources/dependency-check-suppression.xml
Labels: qa: Can't merge, Ready for merge

#4964 Fixes #23233:
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/internal/RestApiAccounts.scala
  webapp/sources/rudder/rudder-web/src/main/elm/accounts/sources/Accounts.elm
  webapp/sources/rudder/rudder-web/src/main/elm/accounts/sources/ApiCalls.elm
  webapp/sources/rudder/rudder-web/src/main/elm/accounts/sources/DataTypes.elm
  webapp/sources/rudder/rudder-web/src/main/elm/accounts/sources/ViewUtils.elm
  webapp/sources/rudder/rudder-web/src/main/webapp/secure/administration/apiManagement.html
Labels: qa: Can't merge, Ready for merge

#4960 Fixes #23228:
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/api/DataStructures.scala
Labels: qa: Can't merge, Ready for merge

#4967 Fixes #23240: Windows technique generated function name is incoherent with the generated directives
  policies/rudderc/src/backends/windows.rs
  policies/rudderc/templates/technique.ps1.askama
  policies/rudderc/tests/cases/general/escaping/technique.ps1
  policies/rudderc/tests/cases/general/form/technique.ps1
  policies/rudderc/tests/cases/general/min/technique.ps1
  policies/rudderc/tests/cases/general/ntp/metadata.xml
  policies/rudderc/tests/cases/general/ntp/technique.cf
  policies/rudderc/tests/cases/general/ntp/technique.ps1
  policies/rudderc/tests/cases/general/ntp/technique.yml
  policies/rudderc/tests/cases/general/reporting/technique.ps1
Labels: qa: Can't merge, Ready for merge

#4968 Fixes #23246: Rudderc does not escape correctly the double quotes in componentKey in windows techniques
  policies/rudderc/templates/technique.ps1.askama
  policies/rudderc/tests/cases/general/escaping/technique.ps1
  policies/rudderc/tests/cases/general/ntp/technique.ps1
Labels: Ready for merge

#4972 Fixes #23252: Improve serde deserialization error messages
  policies/Cargo.lock
  policies/rudderc/Cargo.toml
  policies/rudderc/src/compiler.rs
  policies/rudderc/src/frontends.rs
  policies/supply-chain/audits.toml
  policies/supply-chain/config.toml
  policies/supply-chain/imports.lock
Labels: qa: Can't merge, Ready for merge

#4977 Fixes #23275: Improve some messages in the interface
  webapp/sources/rudder/rudder-web/src/main/elm/sources/Editor/ViewTechnique.elm
  webapp/sources/rudder/rudder-web/src/main/elm/sources/Editor/ViewTechniqueTabs.elm
  webapp/sources/rudder/rudder-web/src/main/elm/sources/Rules/View.elm
  webapp/sources/rudder/rudder-web/src/main/elm/sources/Rules/ViewRepairedReports.elm
  webapp/sources/rudder/rudder-web/src/main/elm/sources/Rules/ViewRuleDetails.elm
  webapp/sources/rudder/rudder-web/src/main/elm/sources/Rules/ViewTabContent.elm
  webapp/sources/rudder/rudder-web/src/main/elm/sources/TechniqueVersion/View.elm
  webapp/sources/rudder/rudder-web/src/main/elm/sources/TechniqueVersion/ViewUtils.elm
  webapp/sources/rudder/rudder-web/src/main/javascript/rudder/rudder.js
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/DirectiveEditForm.scala
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/RuleDisplayer.scala
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/services/DisplayDirectiveTree.scala
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/services/DisplayNode.scala
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/services/ReportDisplayer.scala
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/administration/Archives.scala
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/configuration/DirectiveManagement.scala
  webapp/sources/rudder/rudder-web/src/main/webapp/secure/nodeManager/manageNewNode.html
  webapp/sources/rudder/rudder-web/src/main/webapp/secure/nodeManager/searchNodes.html
  webapp/sources/rudder/rudder-web/src/main/webapp/secure/utilities/archiveManagement.html
  webapp/sources/rudder/rudder-web/src/main/webapp/templates-hidden/components/ComponentNodeProperties.html
  webapp/sources/rudder/rudder-web/src/main/webapp/templates-hidden/components/NodeGroupForm.html
  webapp/sources/rudder/rudder-web/src/main/webapp/templates-hidden/node_logs_tabs.html
  webapp/sources/rudder/rudder-web/src/main/webapp/templates-hidden/reports_server.html
Labels: qa: Can't merge

#4978 Fixes #23276: Improve some messages
  Jenkinsfile
  relay/_typos.toml
  webapp/sources/api-doc/components/schemas/campaign-software-update.yml
  webapp/sources/api-doc/paths/info/all.yml
  webapp/sources/api-doc/paths/secret/id.yml
  webapp/sources/api-doc/paths/usermanagement/id.yml
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/batch/AutomaticReportsCleaner.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/ncf/TechniqueWriter.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/RuleRepository.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/nodes/MergeNodeProperties.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/nodes/RemoveNodeService.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/DeploymentService.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/JavascriptEngine.scala
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/domain/policies/RuleTargetTest.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/UserService.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/ApiAuthorization.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/ArchiveApi.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/DirectiveApi.scala
  webapp/sources/rudder/rudder-web/doc/dev/desPaquetsDePolitiquesAuxPromisesCFE.mkdwn
  webapp/sources/rudder/rudder-web/doc/dev/dev.mkdwn
  webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala
Labels: qa: Can't merge

#4971 Fixes #23234: Hash API tokens
  api-doc/package-lock.json
  api-doc/package.json
  webapp/sources/api-doc/assets/APISettings.png
  webapp/sources/api-doc/assets/api-tokens.png
  webapp/sources/api-doc/assets/api-user.png
  webapp/sources/api-doc/assets/custom-acl.png
  webapp/sources/api-doc/components/securitySchemes/token.yml
  webapp/sources/api-doc/introduction.md
  webapp/sources/api-doc/openapi.src.yml
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/api/ApiAccountRepository.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/api/DataStructures.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/internal/RestApiAccounts.scala
  webapp/sources/rudder/rudder-web/src/main/elm/sources/Accounts.elm
  webapp/sources/rudder/rudder-web/src/main/elm/sources/Accounts/DataTypes.elm
  webapp/sources/rudder/rudder-web/src/main/elm/sources/Accounts/Init.elm
  webapp/sources/rudder/rudder-web/src/main/elm/sources/Accounts/JsonEncoder.elm
  webapp/sources/rudder/rudder-web/src/main/elm/sources/Accounts/View.elm
  webapp/sources/rudder/rudder-web/src/main/elm/sources/Accounts/ViewModals.elm
  webapp/sources/rudder/rudder-web/src/main/elm/sources/Accounts/ViewUtils.elm
  webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder-menu.css
  webapp/sources/rudder/rudder-web/src/main/webapp/secure/administration/apiManagement.html
Labels: qa: Can't merge

#4984 Fixes #23292: TLS 1.3 everywhere
  policies/rudderc/src/backends/unix/prelude.cf
  relay/sources/apache/rudder-apache-relay-ssl.conf
  relay/sources/relayd/src/http_client.rs
Labels: qa: Can't merge

#4979 Fixes #23283: Improve password hash scheme names
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/model/DirectiveFieldEditors.scala
Labels: qa: Can't merge

#4991 Fixes #23319: Add rudder 8.0 inventories to unit tests
  webapp/sources/ldap-inventory/inventory-fusion/src/test/resources/fusion-inventories/8.0/centos8.ocs
  webapp/sources/ldap-inventory/inventory-fusion/src/test/resources/fusion-inventories/8.0/centos8.ocs.sign
  webapp/sources/ldap-inventory/inventory-fusion/src/test/resources/fusion-inventories/8.0/debian11.ocs
  webapp/sources/ldap-inventory/inventory-fusion/src/test/resources/fusion-inventories/8.0/debian11.ocs.sign
  webapp/sources/ldap-inventory/inventory-fusion/src/test/resources/fusion-inventories/8.0/sles15.ocs
  webapp/sources/ldap-inventory/inventory-fusion/src/test/resources/fusion-inventories/8.0/sles15.ocs.sign
  webapp/sources/ldap-inventory/inventory-fusion/src/test/resources/fusion-inventories/8.0/ubuntu20_04.ocs
  webapp/sources/ldap-inventory/inventory-fusion/src/test/resources/fusion-inventories/8.0/ubuntu20_04.ocs.sign
  webapp/sources/ldap-inventory/inventory-fusion/src/test/scala/com/normation/inventory/provisioning/fusion/TestReportParsing.scala
Labels: qa: Can't merge

#4994 Fixes #23322: Add back RUDDER_VERIFY_CERTIFICATES to rudder.json
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/cfclerk/services/impl/SystemVariableSpecServiceImpl.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/write/PrepareTemplateVariables.scala
  webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/node-cfe-with-500-directives/rules/cfengine-community/rudder.json
  webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/node-cfe-with-two-directives/rules/cfengine-community/rudder.json
  webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/node-gen-var-def-override/rules/cfengine-community/rudder.json
  webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/root-default-install/rudder.json
  webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/root-sys-var-false/rudder.json
  webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/root-with-one-multipolicy/rudder.json
  webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/root-with-two-directives/rudder.json
  webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/technique-and-revisions/rudder.json
Labels: qa: Can't merge

#4998 Fixes #23334: Move "technique parameters" section at the beginning
  policies/rudderc/src/backends/metadata.rs
  policies/rudderc/tests/cases/general/escaping/metadata.xml
  policies/rudderc/tests/cases/general/form/metadata.xml
  policies/rudderc/tests/cases/general/ntp/metadata.xml
Labels: qa: Can't merge

#5001 Fixes #23341: Rudderc transform some method parameter name in an incorrect manner
  policies/rudderc/src/backends/windows.rs
  policies/rudderc/templates/technique.ps1.askama
  policies/rudderc/tests/cases/general/long_method_param_name/metadata.xml
  policies/rudderc/tests/cases/general/long_method_param_name/technique.cf
  policies/rudderc/tests/cases/general/long_method_param_name/technique.ps1
  policies/rudderc/tests/cases/general/long_method_param_name/technique.yml
  policies/rudderc/tests/lib/common/30_generic_methods/report_if_condition.cf
Labels: qa: Can't merge

#4986 Fixes #23196: Inconsistent color of save button in directives
  webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder-main.css
Labels: qa: Can't merge

#5004 Fixes #23098: Plugin cannot add custom roles or it will be overwritten by boot custom roles
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/Authorizations.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/ApiDatastructures.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/RoleApiMapping.scala
  webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderUserDetailsFile.scala
  webapp/sources/rudder/rudder-web/src/test/scala/bootstrap/liftweb/RudderUserDetailsTest.scala
Labels: qa: Can't merge

#5017 Fixes #23364: Update scala dependencies before beta
  webapp/sources/pom.xml
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/Authorizations.scala
Labels: Ready for merge

#5008 Fixes #23352: Import/Export yaml with technique editor
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/EndpointsDefinition.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/RestUtils.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/TechniqueApi.scala
  webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/rest/RestTestSetUp.scala
  webapp/sources/rudder/rudder-web/src/main/elm/sources/Editor.elm
  webapp/sources/rudder/rudder-web/src/main/elm/sources/Editor/ApiCalls.elm
  webapp/sources/rudder/rudder-web/src/main/elm/sources/Editor/DataTypes.elm
  webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala
Labels: Ready for merge
