Repository Normation/rudder, pull requests merged in 2023-10, with the labels that each got.

#5076 Fixes #23524: rudder package should not totally fail when parsing index if one entry
  relay/sources/rudder-pkg/lib/rudder-pkg/plugin.py
Labels: Ready for merge

#5074 Fixes #23517: String node poperties are displayed in quotes
  webapp/sources/rudder/rudder-web/src/main/elm/sources/NodeProperties/ViewUtils.elm
Labels: Ready for merge

#5077 Fixes #23536: Ansi color escape code in captured rudderc output
  policies/rudderc/src/logs.rs
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/ncf/TechniqueCompiler.scala
Labels: qa: Can't merge

#5078 Fixes #22527: PostgreSQL error doobie.util.invariant$UnexpectedEnd$
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/campaigns/CampaignEventRepository.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/campaigns/MainCampaignService.scala
  webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/MockServices.scala
Labels: qa: Can't merge, Ready for merge

#5083 Fixes #23544: Parameter name in metadata.xml should be its id
  policies/rudderc/src/backends/metadata.rs
  policies/rudderc/tests/cases/general/escaping/metadata.xml
  policies/rudderc/tests/cases/general/form/metadata.xml
  policies/rudderc/tests/cases/general/ntp/metadata.xml
Labels: Ready for merge

#5084 Fixes #23545: Parameter name in metadata.xml should be its uppercased id
  policies/rudderc/src/backends/metadata.rs
  policies/rudderc/tests/cases/general/escaping/metadata.xml
  policies/rudderc/tests/cases/general/form/metadata.xml
  policies/rudderc/tests/cases/general/ntp/metadata.xml
Labels: Ready for merge

#5085 Fixes #23546: Migration of techniques is failling when there is a resource.
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/ncf/EditorTechnique.scala
Labels: Ready for merge

#5090 Fixes #23555: When migrating json technique to yaml, canonify parameter name
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/apidata/JsonResponseObjects.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/ncf/EditorTechnique.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/ncf/TechniqueCompiler.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/ncf/migration/MigrateJsonTechniquesService.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/ncf/yaml/YamlTechnique.scala
  webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/testing_variables_in_conditions/1.0/metadata.xml
  webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/testing_variables_in_conditions/1.0/technique.cf
  webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/testing_variables_in_conditions/1.0/technique.yml
  webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/techniques/ncf_techniques/technique_any/1.0/metadata.xml
  webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/techniques/ncf_techniques/technique_any/1.0/technique.cf
  webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/techniques/ncf_techniques/technique_any/1.0/technique.yml
  webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/techniques/ncf_techniques/technique_any/2.0/metadata.xml
  webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/techniques/ncf_techniques/technique_any/2.0/technique.cf
  webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/techniques/ncf_techniques/technique_by_Rudder/1.0/metadata.xml
  webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/techniques/ncf_techniques/technique_by_Rudder/1.0/technique.cf
  webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/techniques/ncf_techniques/technique_by_Rudder/1.0/technique.yml
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/ncf/TestEditorTechniqueWriter.scala
  webapp/sources/rudder/rudder-web/src/test/resources/configuration-repository-migrate-json-8_0/post-migration/ncf_techniques/technique_with_parameters/1.0/metadata.xml
  webapp/sources/rudder/rudder-web/src/test/resources/configuration-repository-migrate-json-8_0/post-migration/ncf_techniques/technique_with_parameters/1.0/resources/test_resources.txt
  webapp/sources/rudder/rudder-web/src/test/resources/configuration-repository-migrate-json-8_0/post-migration/ncf_techniques/technique_with_parameters/1.0/technique.cf
  webapp/sources/rudder/rudder-web/src/test/resources/configuration-repository-migrate-json-8_0/post-migration/ncf_techniques/technique_with_parameters/1.0/technique.ps1
  webapp/sources/rudder/rudder-web/src/test/resources/configuration-repository-migrate-json-8_0/post-migration/ncf_techniques/technique_with_parameters/1.0/technique.yml
  webapp/sources/rudder/rudder-web/src/test/resources/configuration-repository-migrate-json-8_0/techniques/ncf_techniques/technique_with_parameters/1.0/metadata.xml
  webapp/sources/rudder/rudder-web/src/test/resources/configuration-repository-migrate-json-8_0/techniques/ncf_techniques/technique_with_parameters/1.0/resources/test_resources.txt
  webapp/sources/rudder/rudder-web/src/test/resources/configuration-repository-migrate-json-8_0/techniques/ncf_techniques/technique_with_parameters/1.0/rudder_reporting.cf
  webapp/sources/rudder/rudder-web/src/test/resources/configuration-repository-migrate-json-8_0/techniques/ncf_techniques/technique_with_parameters/1.0/technique.cf
  webapp/sources/rudder/rudder-web/src/test/resources/configuration-repository-migrate-json-8_0/techniques/ncf_techniques/technique_with_parameters/1.0/technique.json
  webapp/sources/rudder/rudder-web/src/test/resources/configuration-repository-migrate-json-8_0/techniques/ncf_techniques/technique_with_parameters/1.0/technique.ps1
  webapp/sources/rudder/rudder-web/src/test/scala/bootstrap/liftweb/checks/migration/TestMigrateJsonTechniquesToYaml.scala
Labels: Ready for merge

#5093 Fixes #23564: Always display generic method name
  webapp/sources/rudder/rudder-web/src/main/elm/editor/sources/ViewMethod.elm
Labels: Ready for merge

#5082 Fixes #23541: Add new Windows OS conditions to the technique editor
  webapp/sources/rudder/rudder-web/src/main/elm/sources/Editor/MethodConditions.elm
Labels: Ready for merge

#5095 Fixes #23525: Document in logback.xml loggers that display secret at debug level
  webapp/sources/rudder/rudder-web/src/main/resources/logback.xml
Labels: qa: Can't merge

#5094 Fixes #23568: Mark yaml format as 1.0
  policies/rudderc/src/frontends.rs
  policies/rudderc/src/ir/technique.rs
Labels: Ready for merge

#5097 Fixes #23573: Make sources compatible with Windows
  policies/minifusion/Cargo.toml
  policies/minifusion/src/main.rs
  policies/rudderc/tests/test.rs
Labels: Ready for merge

#5098 Fixes #23574: Ignore CVE 2023-4759 (false positive in jgit 6.7.0.202309050840-r)
  webapp/sources/dependency-check-suppression.xml
Labels: Ready for merge

#5099 Fixes #23579: Broken double quote escaping in Windows policies
  policies/rudderc/templates/technique.ps1.askama
  policies/rudderc/tests/cases/general/escaping/metadata.xml
  policies/rudderc/tests/cases/general/escaping/technique.cf
  policies/rudderc/tests/cases/general/escaping/technique.ps1
  policies/rudderc/tests/cases/general/escaping/technique.yml
  policies/rudderc/tests/cases/general/min/technique.ps1
  policies/rudderc/tests/cases/general/reporting/technique.ps1
Labels: qa: Can't merge, Ready for merge

#5103 Fixes #23586: Missing UI for parameter name and description new format
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/ncf/EditorTechnique.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/ncf/TechniqueCompiler.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/ncf/migration/MigrateJsonTechniquesService.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/ncf/yaml/YamlTechnique.scala
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/ncf/TestEditorTechniqueWriter.scala
  webapp/sources/rudder/rudder-web/src/main/elm/sources/Editor.elm
  webapp/sources/rudder/rudder-web/src/main/elm/sources/Editor/AgentValueParser.elm
  webapp/sources/rudder/rudder-web/src/main/elm/sources/Editor/DataTypes.elm
  webapp/sources/rudder/rudder-web/src/main/elm/sources/Editor/JsonDecoder.elm
  webapp/sources/rudder/rudder-web/src/main/elm/sources/Editor/JsonEncoder.elm
  webapp/sources/rudder/rudder-web/src/main/elm/sources/Editor/ViewTechniqueTabs.elm
  webapp/sources/rudder/rudder-web/src/test/resources/configuration-repository-migrate-json-8_0/post-migration/ncf_techniques/technique_with_parameters/1.0/technique.yml
Labels: Ready for merge

#5104 Fixes #23583: Broken parsing of some complex expressions
  policies/rudderc/src/ir/value.rs
Labels: Ready for merge

#5107 Fixes #23592: Typo in warning message
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/administration/PluginManagement.scala
Labels: qa: Can't merge

#5115 Fixes #17813: user with read_only right has button that allows to create a technique
  webapp/sources/rudder/rudder-web/src/main/elm/editor/sources/ViewTechnique.elm
Labels: qa: Can't merge

#5108 Fixes #23591: Feature switch for archive API is still present
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/appconfig/ConfigService.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/ArchiveApi.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/SettingsApi.scala
  webapp/sources/rudder/rudder-rest/src/test/resources/api/api_settings.yml
  webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/rest/ArchiveApiTest.scala
  webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/rest/RestTestSetUp.scala
  webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala
Labels: Ready for merge

#5116 Fixes #23609: Assessments of several low impact CVE in current 7.3.x reported by contrastsecurity tool
  webapp/sources/pom.xml
  webapp/sources/rudder/rudder-core/pom.xml
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/batch/GitGC.scala
  webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/rest/SharedFilesApiTest.scala
  webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderUserDetailsFile.scala
Labels: qa: Can't merge

#5070 Fixes #23172: Improve deleted directive screen
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/DirectiveEditForm.scala
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/configuration/DirectiveManagement.scala
  webapp/sources/rudder/rudder-web/src/main/webapp/secure/configurationManager/directiveManagement.html
Labels: Ready for merge

#5109 Fixes #15019: Tag are not displayed with a nice diff in eventLog
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/policies/DirectiveDiff.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/policies/PolicyMode.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/ldap/LDAPDiffMapper.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/eventlog/EventLogDetailsService.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/eventlog/EventLogFactory.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/modification/DiffService.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/web/services/EventLogDetailsGenerator.scala
  webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/MockServices.scala
Labels: qa: Can't merge

#5123 Fixes #23624: Continue implementing the installation part of the rudder-package rust port
  relay/sources/rudder-package/src/rpkg/archive.rs
  relay/sources/rudder-package/src/rpkg/database.rs
  relay/sources/rudder-package/src/rpkg/mod.rs
  relay/sources/rudder-package/src/rpkg/plugin.rs
  relay/sources/rudder-package/src/rpkg/repo_index.rs
  relay/sources/rudder-package/src/rpkg/webapp_xml.rs
Labels: qa: Can't merge

#5124 Fixes #23625: Implement CI config for rudder-package
  Jenkinsfile
  Jenkinsfile-security
  relay/sources/rudder-package/Cargo.lock
  relay/sources/rudder-package/Cargo.toml
  relay/sources/rudder-package/Dockerfile
  relay/sources/rudder-package/Makefile
  relay/sources/rudder-package/deny.toml
  relay/sources/rudder-package/rust-toolchain.toml
  relay/sources/rudder-package/src/main.rs
  relay/sources/rudder-package/src/rpkg/archive.rs
  relay/sources/rudder-package/src/rpkg/database.rs
  relay/sources/rudder-package/src/rpkg/repo_index.rs
  relay/sources/rudder-package/src/rpkg/webapp_xml.rs
Labels: qa: Can't merge

#5129 Fixes #23630: Add logging basics
  relay/sources/rudder-package/Cargo.lock
  relay/sources/rudder-package/Cargo.toml
  relay/sources/rudder-package/src/archive.rs
  relay/sources/rudder-package/src/cli.rs
  relay/sources/rudder-package/src/config.rs
  relay/sources/rudder-package/src/database.rs
  relay/sources/rudder-package/src/lib.rs
  relay/sources/rudder-package/src/main.rs
  relay/sources/rudder-package/src/plugin.rs
  relay/sources/rudder-package/src/repo_index.rs
  relay/sources/rudder-package/src/rpkg/mod.rs
  relay/sources/rudder-package/src/webapp_xml.rs
  relay/sources/rudder-package/tests/config/rudder-pkg.conf
  relay/sources/rudder-package/tests/config/rudder-pkg.proxy.conf
Labels: qa: Can't merge, Ready for merge

#5135 Fixes #23645: Add doc for OpenSCAP plugin API
  webapp/sources/api-doc/code_samples/curl/openscap/report.sh
  webapp/sources/api-doc/openapi.src.yml
  webapp/sources/api-doc/paths/openscap/report.yml
Labels: qa: Can't merge

#5118 Fixes #23607: When a mandatory field in a technique is not defined, we can save a technique and we have a nasty error
  policies/rudder-commons/src/lib.rs
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/ncf/EditorTechniqueReader.scala
  webapp/sources/rudder/rudder-core/src/test/resources/ncf/generic_methods.json
Labels: qa: Can't merge

#5134 Fixes #22518: Recent changes drop down cannot be read
  webapp/sources/rudder/rudder-web/pom.xml
  webapp/sources/rudder/rudder-web/src/main/elm/rules/elm.json
  webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/ViewRepairedReports.elm
  webapp/sources/rudder/rudder-web/src/main/elm/rules/tests/ViewRepairedReportsTest.elm
Labels: qa: Can't merge

#5137 Fixes #23653: Lint shell code examples
  qa-test
  relay/sources/api-doc/code_samples/curl/shared-folder/get.sh
  webapp/sources/api-doc/code_samples/curl/archives/export.sh
  webapp/sources/api-doc/code_samples/curl/branding/update.sh
  webapp/sources/api-doc/code_samples/curl/directives/create.sh
  webapp/sources/api-doc/code_samples/curl/directives/update.sh
  webapp/sources/api-doc/code_samples/curl/groups/category-id-new.sh
  webapp/sources/api-doc/code_samples/curl/groups/create.sh
  webapp/sources/api-doc/code_samples/curl/nodes/id-update.sh
  webapp/sources/api-doc/code_samples/curl/scale-out-relay/promote.sh
  webapp/sources/api-doc/code_samples/curl/systemUpdate/campaignEventResult.sh
Labels: qa: Can't merge

#5138 Fixes #23010: When we are logged out, the logout button doesn't work
  webapp/sources/rudder/rudder-web/src/main/javascript/rudder/rudder.js
  webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/Boot.scala
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/UserInformation.scala
Labels: qa: Can't merge

#5143 Fixes #23666: Fix elm tests
  webapp/sources/rudder/rudder-web/pom.xml
  webapp/sources/rudder/rudder-web/src/main/elm/elm.json
Labels: Ready for merge

#5145 Fixes #23610: The "Required/May be empy" button in the parameters of a technique is not intuitive enough
  webapp/sources/rudder/rudder-web/src/main/elm/editor/sources/ViewTechniqueTabs.elm
  webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder-technique-editor.css
  webapp/sources/rudder/rudder-web/src/main/webapp/secure/configurationManager/techniqueEditor.html
Labels: qa: Can't merge, Ready for merge

#5146 Fixes #23674: Incorrect rudderc binary download link in documentation
  policies/rudderc/docs/src/usage.md
Labels: Ready for merge

#5147 Fixes #23683: When a technique scope variable is used in a component key in a method call, logger fails to define the noop conditions in not_applicable cases
  policies/rudderc/src/backends/unix/ncf/method_call.rs
  policies/rudderc/tests/cases/general/escaping/technique.cf
  policies/rudderc/tests/cases/general/form/technique.cf
  policies/rudderc/tests/cases/general/ntp/technique.cf
  policies/rudderc/tests/cases/general/reporting/technique.cf
Labels: Ready for merge
