Repository Normation/rudder, pull requests merged in 2023-06, with the labels that each got.

#4811 Fixes #22816: Use cargo vet to check Rust dependencies
  Jenkinsfile-security
  ci/rust.sh
  policies/Cargo.lock
  policies/Dockerfile
  policies/module-types/template/Cargo.toml
  policies/module-types/template/src/main.rs
  policies/module-types/template/tests/minijinja.rs
  policies/rust-toolchain.toml
  policies/supply-chain/audits.toml
  policies/supply-chain/config.toml
  policies/supply-chain/imports.lock
  relay/sources/relayd/Cargo.lock
  relay/sources/relayd/Cargo.toml
  relay/sources/relayd/Dockerfile
  relay/sources/relayd/rust-toolchain.toml
  relay/sources/relayd/supply-chain/audits.toml
  relay/sources/relayd/supply-chain/config.toml
  relay/sources/relayd/supply-chain/imports.lock
Labels: qa: Can't merge

#4809 Fixes #22807: OS and hardware inventory information are not discoverable
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/services/DisplayNode.scala
Labels: qa: Can't merge

#4818 Fixes #22868: docopt completion is installed in /usr/local/bin
  relay/sources/Makefile
Labels: Ready for merge

#4819 Fixes #22870: Use 8080 port to talk with the webapp in hooks
  webapp/sources/rudder/rudder-core/src/main/resources/hooks.d/node-inventory-received-accepted/hook-template
  webapp/sources/rudder/rudder-core/src/main/resources/hooks.d/node-inventory-received-accepted/readme.adoc
  webapp/sources/rudder/rudder-core/src/main/resources/hooks.d/node-inventory-received-failed/hook-template
  webapp/sources/rudder/rudder-core/src/main/resources/hooks.d/node-inventory-received-pending/auto-accept-nodes.example
  webapp/sources/rudder/rudder-core/src/main/resources/hooks.d/node-inventory-received-pending/hook-template
  webapp/sources/rudder/rudder-core/src/main/resources/hooks.d/node-inventory-received-pending/readme.adoc
  webapp/sources/rudder/rudder-core/src/main/resources/hooks.d/node-post-acceptance/hook-template
  webapp/sources/rudder/rudder-core/src/main/resources/hooks.d/node-post-deletion/10-clean-policies
  webapp/sources/rudder/rudder-core/src/main/resources/hooks.d/node-post-deletion/hook-template
  webapp/sources/rudder/rudder-core/src/main/resources/hooks.d/node-pre-deletion/hook-template
  webapp/sources/rudder/rudder-core/src/main/resources/hooks.d/policy-generation-failed/hook-template
  webapp/sources/rudder/rudder-core/src/main/resources/hooks.d/policy-generation-finished/40-nodelist-relay-configuration
  webapp/sources/rudder/rudder-core/src/main/resources/hooks.d/policy-generation-finished/50-reload-policy-file-server
  webapp/sources/rudder/rudder-core/src/main/resources/hooks.d/policy-generation-finished/60-trigger-node-update
  webapp/sources/rudder/rudder-core/src/main/resources/hooks.d/policy-generation-finished/hook-template
  webapp/sources/rudder/rudder-core/src/main/resources/hooks.d/policy-generation-finished/readme.adoc
  webapp/sources/rudder/rudder-core/src/main/resources/hooks.d/policy-generation-node-finished/hook-template
  webapp/sources/rudder/rudder-core/src/main/resources/hooks.d/policy-generation-node-ready/10-cf-promise-check
  webapp/sources/rudder/rudder-core/src/main/resources/hooks.d/policy-generation-node-ready/42-ignore_disabled_non_exec
  webapp/sources/rudder/rudder-core/src/main/resources/hooks.d/policy-generation-node-ready/42-ignore_extension.disabled
  webapp/sources/rudder/rudder-core/src/main/resources/hooks.d/policy-generation-node-ready/hook-template
  webapp/sources/rudder/rudder-core/src/main/resources/hooks.d/policy-generation-started/hook-template
  webapp/sources/rudder/rudder-core/src/main/resources/hooks.d/readme.adoc
Labels: qa: Can't merge, Ready for merge

#4823 Fixes #22874: NPE gz inventory file is corrupted
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/inventory/InventoryFileWatcher.scala
Labels: Ready for merge

#4826 Fixes #22880: TODOs in the UI
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/popup/CreateCloneDirectivePopup.scala
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/popup/CreateOrUpdateGlobalParameterPopup.scala
Labels: Ready for merge

#4827 Fixes #22881: Update elm dependencies
  webapp/sources/rudder/rudder-web/src/main/elm/elm.json
  webapp/sources/rudder/rudder-web/src/main/elm/sources/Accounts/JsonDecoder.elm
  webapp/sources/rudder/rudder-web/src/main/elm/sources/DirectiveCompliance/JsonDecoder.elm
  webapp/sources/rudder/rudder-web/src/main/elm/sources/Rules/JsonDecoder.elm
Labels: Ready for merge

#4794 Fixes #21236: When we arrive on the node search page with a query pre-filed, the query is done twice
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/node/SearchNodes.scala
  webapp/sources/rudder/rudder-web/src/main/webapp/javascript/rudder/rudder.js
  webapp/sources/rudder/rudder-web/src/main/webapp/secure/nodeManager/searchNodes.html
Labels: qa: Can't merge

#4835 Fixes #22911: JS diff library stop working
  webapp/sources/rudder/rudder-web/src/main/javascript/rudder/rudder.js
Labels: Ready for merge

#4838 Fixes #22924: Typos-cli does not build anymore
  Jenkinsfile
  ci/typos.Dockerfile
Labels: Ready for merge

#4832 Fixes #22879: Too many "Policy Update Started" in event logs
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/batch/AsyncDeploymentActor.scala
Labels: qa: Can't merge

#4842 Fixes #22943:
  relay/sources/relayd/Cargo.lock
Labels: qa: Can't merge, Ready for merge

#4841 Fixes #22871: Disable post-generation remote-run by default
  webapp/sources/rudder/rudder-core/src/main/resources/hooks.d/policy-generation-finished/60-trigger-node-update
  webapp/sources/rudder/rudder-core/src/main/resources/hooks.d/policy-generation-finished/60-trigger-node-update.properties
  webapp/sources/rudder/rudder-web/src/main/resources/configuration.properties.sample
Labels: qa: Can't merge

#4846 Fixes #22946: NodeProperties value are not correctly serialized in event log
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/properties/Properties.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/jdbc/EventLogJdbcRepository.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/eventlog/EventLogFactory.scala
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/domain/properties/NodePropertiesTest.scala
Labels: qa: Can't merge

#4822 Fixes #22864: Display inventory variables and values in node details
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/ShowNodeDetailsFromNode.scala
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/services/DisplayNode.scala
  webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-datatable.css
  webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-node.css
  webapp/sources/rudder/rudder-web/src/main/webapp/style/rudder/rudder-template.css
  webapp/sources/rudder/rudder-web/src/main/webapp/templates-hidden/components/ComponentNodeProperties.html
Labels: qa: Can't merge

#4849 Fixes #22950: In rudder 7.3, we need to use npm for jsondiffpatch
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/domain/properties/NodePropertiesTest.scala
  webapp/sources/rudder/rudder-web/src/main/gulpfile.js
  webapp/sources/rudder/rudder-web/src/main/package-lock.json
  webapp/sources/rudder/rudder-web/src/main/package.json
  webapp/sources/rudder/rudder-web/src/main/webapp/javascript/jsondiffpatch/formatters-styles/html.css
  webapp/sources/rudder/rudder-web/src/main/webapp/javascript/jsondiffpatch/jsondiffpatch.umd.js
  webapp/sources/rudder/rudder-web/src/main/webapp/secure/utilities/eventLogs.html
Labels: qa: Can't merge

#4843 Fixes #22941: Titles are not consistant in the new Operatin System inventory tab with group search
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/domain/properties/NodePropertiesTest.scala
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/ShowNodeDetailsFromNode.scala
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/services/DisplayNode.scala
Labels: qa: Can't merge, Ready for merge

#4836 Fixes #22914: add label to rudder docker images
  api-doc/Dockerfile
  ci/asciidoctor.Dockerfile
  ci/pylint.Dockerfile
  ci/shellcheck.Dockerfile
  ci/typos.Dockerfile
  docker/rudder-agent/cf-execd.Dockerfile
  docker/rudder-agent/cf-serverd.Dockerfile
  docker/rudder-relay-split/cf-execd.Dockerfile
  docker/rudder-relay-split/cf-serverd.Dockerfile
  docker/rudder-relay-split/httpd.Dockerfile
  docker/rudder-relay-split/relayd.Dockerfile
  docker/rudder-relay/Dockerfile
  language/Dockerfile
  policies/Dockerfile
  relay/sources/relayd/Dockerfile
  relay/sources/rudder-pkg/Dockerfile
  webapp/sources/Dockerfile
  webapp/sources/rudder/rudder-web/src/main/elm/Dockerfile
Labels: qa: Can't merge, Ready for merge

#4850 Fixes #22951: backport parent to 7.3
  relay/sources/Makefile
Labels: Ready for merge

#4815 Fixes #22849: Generator for Windows policies
  ci/rust.sh
  policies/Cargo.lock
  policies/rudder-commons/src/lib.rs
  policies/rudder-module-type/src/cfengine/header.rs
  policies/rudderc/Cargo.toml
  policies/rudderc/docs/src/syntax.md
  policies/rudderc/libs/cfengine.yml
  policies/rudderc/libs/rudder.yml
  policies/rudderc/libs/vars.yml
  policies/rudderc/src/backends/metadata.rs
  policies/rudderc/src/backends/unix/ncf/method_call.rs
  policies/rudderc/src/backends/windows.rs
  policies/rudderc/src/ir.rs
  policies/rudderc/src/ir/condition.rs
  policies/rudderc/src/ir/technique.rs
  policies/rudderc/src/ir/value.rs
  policies/rudderc/src/lib.rs
  policies/rudderc/src/technique.schema.json
  policies/rudderc/src/test.rs
  policies/rudderc/templates/technique.ps1.askama
  policies/rudderc/tests/cases/general/escaping/technique.cf
  policies/rudderc/tests/cases/general/escaping/technique.ps1
  policies/rudderc/tests/cases/general/escaping/technique.yml
  policies/rudderc/tests/cases/general/min/technique.ps1
  policies/rudderc/tests/cases/general/ntp/technique.cf
  policies/rudderc/tests/cases/general/ntp/technique.ps1
  policies/rudderc/tests/cases/general/ntp/technique.yml
  policies/rudderc/tests/cases/general/reporting/technique.ps1
  policies/rudderc/tests/cases/general/reporting/technique.yml
  policies/supply-chain/audits.toml
  policies/supply-chain/config.toml
  policies/supply-chain/imports.lock
  relay/sources/relayd/Cargo.lock
  relay/sources/relayd/src/input/watch.rs
  relay/sources/relayd/supply-chain/audits.toml
  relay/sources/relayd/supply-chain/config.toml
  relay/sources/relayd/supply-chain/imports.lock
Labels: qa: Can't merge

#4854 Fixes #22967: Spurious test error about length of generated password
  webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderUserDetailsFile.scala
Labels: qa: Can't merge

#4860 Fixes #22980: Error in parent correction
  webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderUserDetailsFile.scala
Labels: Ready for merge

#4866 Fixes #22989: Finer grained warning exclusion for fastparse nowarn problem
  webapp/sources/pom.xml
Labels: Ready for merge

#4868 Fixes #22973: Call rudderc with correct parameters
  policies/rudderc/src/cli.rs
  policies/rudderc/src/lib.rs
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/ncf/TechniqueCompiler.scala
  webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala
Labels: Ready for merge
