Repository Normation/rudder, pull requests merged in 2023-05, with the labels that each got.

#4739 Fixes #22573: Allow generating runnable techniques
  policies/Cargo.lock
  policies/Dockerfile
  policies/module-types/template/Cargo.toml
  policies/rudderc/Cargo.toml
  policies/rudderc/docs/src/SUMMARY.md
  policies/rudderc/docs/src/test.md
  policies/rudderc/src/backends.rs
  policies/rudderc/src/backends/metadata.rs
  policies/rudderc/src/backends/unix.rs
  policies/rudderc/src/backends/unix/cfengine.rs
  policies/rudderc/src/backends/unix/prelude.cf
  policies/rudderc/src/backends/windows.rs
  policies/rudderc/src/cli.rs
  policies/rudderc/src/compiler.rs
  policies/rudderc/src/doc.rs
  policies/rudderc/src/frontends/methods.rs
  policies/rudderc/src/frontends/methods/reader.rs
  policies/rudderc/src/ir/technique.rs
  policies/rudderc/src/lib.rs
  policies/rudderc/src/technique.schema.json
  policies/rudderc/src/test.rs
  policies/rudderc/tests/cases/test/one_param/technique.yml
  policies/rudderc/tests/cases/test/one_param/tests/case1.yml
  policies/rudderc/tests/cases/test/one_param/tests/reference.conf
  policies/rudderc/tests/compile.rs
  policies/rudderc/tests/lib/README.md
  policies/rudderc/tests/lib/common/10_ncf_internals/initialization.cf
  policies/rudderc/tests/lib/common/10_ncf_internals/list-compatible-inputs
  policies/rudderc/tests/lib/common/30_generic_methods/file_content.cf
  policies/rudderc/tests/lib/common/30_generic_methods/package_install.cf
  policies/rudderc/tests/lib/common/30_generic_methods/package_install.yml
  policies/rudderc/tests/lib/common/30_generic_methods/package_present.cf
  policies/rudderc/tests/lib/common/30_generic_methods/package_present.yml
  policies/rudderc/tests/methods.rs
  policies/rudderc/tests/test.rs
  policies/rust-toolchain.toml
  policies/techniques/anssi_bp_028/technique.yml
  policies/techniques/anssi_bp_028/test.yml
  relay/sources/relayd/Cargo.lock
  relay/sources/relayd/Dockerfile
  relay/sources/relayd/rust-toolchain.toml
  webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala
Labels: qa: Can't merge

#4780 Fixes #22719: Fallback on /var/rudder/ncf/ for library
  policies/rudderc/src/cli.rs
  policies/rudderc/src/lib.rs
Labels: qa: Can't merge

#4785 Fixes #22625: Healthcheck notification is displayed when a user have no right
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/HealthcheckInfo.scala
  webapp/sources/rudder/rudder-web/src/main/webapp/secure/utilities/healthcheck.html
Labels: qa: Can't merge, Ready for merge

#4786 Fixes #19545: Warn sign in nodes list for disabled nodes
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/NodeApi.scala
Labels: qa: Can't merge, Ready for merge

#4788 Fixes #22729: Upmerge breaks 7.3/master
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/HealthcheckInfo.scala
Labels: Ready for merge

#4787 Fixes #19519:
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/eventlog/EventLogFactory.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/marshalling/XmlSerialisationImpl.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/marshalling/XmlUnserialisationImpl.scala
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/marshalling/TestXmlUnserialisation.scala
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/node/AcceptNode.scala
Labels: qa: Can't merge

#4793 Fixes #22387: No local account shown on windows
  webapp/sources/ldap-inventory/inventory-fusion/src/main/scala/com/normation/inventory/provisioning/fusion/FusionInventoryParser.scala
  webapp/sources/ldap-inventory/inventory-fusion/src/test/scala/com/normation/inventory/provisioning/fusion/TestReportParsing.scala
Labels: Ready for merge

#4790 Fixes #22671: Inconsistent colors in hover on the dashboard
  webapp/sources/rudder/rudder-web/src/main/javascript/rudder/homePage.js
Labels: Trigger test

#4800 Fixes #22775: inconsistence in hover color
  webapp/sources/rudder/rudder-web/src/main/javascript/rudder/homePage.js
Labels: Ready for merge

#4799 Fixes #22774: Heathcheck can not be displayed anymore
  webapp/sources/rudder/rudder-web/src/main/webapp/secure/utilities/healthcheck.html
Labels: Ready for merge

#4797 Fixes #22764: Correct warning due to nowarn or release in 7.2 branch
  webapp/sources/pom.xml
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/batch/AutomaticReportsCleaner.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/batch/CheckInventoryUpdate.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/batch/PurgeUnreferencedSoftwares.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/inventory/InventoryProcessor.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/xml/ItemArchiveManagerImpl.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/healthcheck/HealthcheckNotificationService.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/marshalling/XmlUnserialisationImpl.scala
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/cfclerk/services/JGitRepositoryTest.scala
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/policies/TestJsEngine.scala
  webapp/sources/rudder/rudder-web/src/test/scala/bootstrap/liftweb/RudderUserDetailsTest.scala
Labels: qa: Can't merge
