Repository Normation/rudder, pull requests merged in 2024-09, with the labels that each got.

#5853 Fixes #25311: Remove expected reports from NodeStatusReport
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/db/Doobie.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/logger/DebugComplianceLogger.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/reports/StatusReports.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/jdbc/ComplianceRepository.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/reports/ComputeNodeStatusReportService.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/reports/ExecutionBatch.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/reports/NodeStatusReportRepository.scala
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/domain/reports/StatusReportTest.scala
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/reports/CachedFindRuleNodeStatusReportsTest.scala
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/reports/ReportingServiceUtilsTest.scala
  webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/MockServices.scala
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/services/ReportDisplayer.scala
Labels: Ready for merge

#5854 Fixes #25396: Persist compliance in base
  webapp/sources/pom.xml
  webapp/sources/rudder/rudder-core/src/main/resources/reportsSchema.sql
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/cfclerk/domain/TechniqueVersion.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/db/Doobie.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/policies/PolicyTypes.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/reports/ExpectedReports.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/reports/StatusReports.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/DeploymentService.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/reports/ExecutionBatch.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/reports/NodeStatusReportRepository.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/reports/ReportingServiceImpl.scala
  webapp/sources/rudder/rudder-core/src/test/resources/node-facts/node-001-machine-physical-v2.json
  webapp/sources/rudder/rudder-core/src/test/resources/node-facts/node-001-machine-physical.json
  webapp/sources/rudder/rudder-core/src/test/resources/node-facts/node-001-machine-unknown-v2.json
  webapp/sources/rudder/rudder-core/src/test/resources/node-facts/node-001-machine-unknown-vm-v2.json
  webapp/sources/rudder/rudder-core/src/test/resources/node-facts/node-001-machine-unknown-vm.json
  webapp/sources/rudder/rudder-core/src/test/resources/node-facts/node-001-machine-unknown.json
  webapp/sources/rudder/rudder-core/src/test/resources/node-facts/node-930dccb0-5b06-4385-ab7a-80a7e56eb969-v2.json
  webapp/sources/rudder/rudder-core/src/test/resources/node-facts/node-930dccb0-5b06-4385-ab7a-80a7e56eb969.json
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/facts/nodes/TestNodeFactSerialisation.scala
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/reports/CachedFindRuleNodeStatusReportsTest.scala
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/reports/ReportingServiceUtilsTest.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/data/Compliance.scala
  webapp/sources/rudder/rudder-rest/src/test/resources/api/api_nodes.yml
  webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/MockServices.scala
  webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/domain/reports/JsonPostresqlSerializationTest.scala
  webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala
  webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/checks/action/LoadNodeComplianceCache.scala
  webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/checks/migration/CheckTableNodeLastCompliance.scala
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/services/ComplianceData.scala
  webapp/sources/utils/src/main/scala/com/normation/utils/DateFormaterService.scala
Labels: Ready for merge

#5857 Fixes #25409: User identity does not show up in bar when user has last login
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/UserInformation.scala
Labels: qa: Can't merge

#5858 Fixes #25414: IO forgot to run in spring filter to invalidate session in 25322
  webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/UserSessionInvalidationFilter.scala
Labels: Ready for merge

#5747 Fixes #24789: Archive API for import/export doesn't know about technique
  webapp/sources/Dockerfile
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/cfclerk/domain/TechniqueCategory.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/cfclerk/services/impl/GitTechniqueReader.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/git/ZipUtils.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/ItemArchiveManager.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/xml/GitArchivers.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/xml/GitParseRudderObjects.scala
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/cfclerk/services/JGitRepositoryTest.scala
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/ncf/TestEditorTechniqueWriter.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/ArchiveApi.scala
  webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/rest/ArchiveApiTest.scala
  webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala
Labels: qa: Can't merge

#5866 Fixes #25407:
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/users/User.scala
  webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/Boot.scala
  webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/UserSessionInvalidationFilter.scala
Labels: qa: Can't merge, Ready for merge

#5874 Fixes #25438: The severity ERROR for Node with ID ‘xxx’ was not found in Rudder’ is too strict
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/logger/ApplicationLogger.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/RestUtils.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/RudderJsonResponse.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/LiftApiDispatcher.scala
  webapp/sources/rudder/rudder-templates/src/main/scala/com/normation/templates/FillTemplatesService.scala
Labels: qa: Can't merge

#5881 Fixes #25477: rootAdmin user can't log-in anymore
  webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/AppConfigAuth.scala
Labels: Ready for merge

#5883 Fixes #25478: Normalize authentication logs
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/logger/ApplicationLogger.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/users/UserRepository.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/Authorizations.scala
  webapp/sources/rudder/rudder-web/src/main/resources/logback.xml
  webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderProviderManager.java
  webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderUserDetailsFile.scala
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/CommonLayout.scala
Labels: qa: Can't merge

#5886 Fixes #25490: User cleanup actions are logged every time even there is no change
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/batch/CleanupUsers.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/users/UserRepository.scala
Labels: Ready for merge

#5887 Fixes #25489: Parent ticket prevents passing a work directory to rudderc
  policies/rudderc/src/lib.rs
Labels: qa: Can't merge

#5890 Fixes #25499: Event log table default period of two hours is too short
  webapp/sources/rudder/rudder-web/src/main/javascript/rudder/rudder.js
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/services/EventListDisplayer.scala
Labels: qa: Can't merge

#5895 Fixes #25506: Add a splay-time for relays
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/SystemVariableService.scala
Labels: Ready for merge

#5888 Fixes #24332: Technical logs are not loaded when visiting the tab - rudder 8.1
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/services/LogDisplayer.scala
Labels: Ready for merge

#5896 Fixes #25524: Limit number of rust jobs in build jobs
  rust.makefile
Labels: Ready for merge

#5894 Fixes #25504: Remove webapp technique compilation fallback
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/ncf/TechniqueCompiler.scala
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/cfclerk/services/JGitRepositoryTest.scala
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/ncf/TestEditorTechniqueWriter.scala
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/ncf/TestEditorTechniqueWriterFallback.scala
  webapp/sources/rudder/rudder-web/src/main/elm/sources/Editor/DataTypes.elm
  webapp/sources/rudder/rudder-web/src/main/elm/sources/Editor/JsonDecoder.elm
  webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala
  webapp/sources/rudder/rudder-web/src/test/resources/configuration-repository-migrate-json-8_0/post-migration/ncf_techniques/technique_with_error/1.0/compilation-config.yml
  webapp/sources/rudder/rudder-web/src/test/resources/configuration-repository-migrate-json-8_0/post-migration/ncf_techniques/technique_with_error/1.0/compilation-output.yml
  webapp/sources/rudder/rudder-web/src/test/resources/configuration-repository-migrate-json-8_0/techniques/ncf_techniques/technique_with_error/1.0/compilation-config.yml
  webapp/sources/rudder/rudder-web/src/test/scala/bootstrap/liftweb/checks/migration/TestMigrateJsonTechniquesToYaml.scala
Labels: Ready for merge

#5899 Fixes #25545: Techniques no longer compile with error in rudderc arguments
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/ncf/TechniqueCompiler.scala
  webapp/sources/rudder/rudder-web/src/test/resources/configuration-repository-migrate-json-8_0/post-migration/ncf_techniques/technique_with_error/1.0/compilation-config.yml
  webapp/sources/rudder/rudder-web/src/test/resources/configuration-repository-migrate-json-8_0/techniques/ncf_techniques/technique_with_error/1.0/compilation-config.yml
Labels: qa: Can't merge, Ready for merge

#5838 Fixes #25364: Fix the system-updates module
  Cargo.lock
  ci/typos.Dockerfile
  policies/Dockerfile
  policies/minifusion/src/os_release.rs
  policies/module-types/system-updates/Cargo.toml
  policies/module-types/system-updates/src/campaign.rs
  policies/module-types/system-updates/src/cli.rs
  policies/module-types/system-updates/src/db.rs
  policies/module-types/system-updates/src/output.rs
  policies/module-types/system-updates/src/package_manager.rs
  policies/module-types/system-updates/src/package_manager/apt.rs
  policies/module-types/system-updates/src/package_manager/rpm.rs
  policies/module-types/system-updates/src/packages.sql
  policies/module-types/system-updates/src/scheduler.rs
  policies/module-types/system-updates/src/state.rs
  policies/module-types/template/src/main.rs
  policies/rudder-module-type/src/lib.rs
  relay/sources/relayd/Dockerfile
  relay/sources/relayd/src/api/remote_run.rs
  relay/sources/relayd/src/api/shared_files.rs
  relay/sources/relayd/src/output/upstream.rs
  relay/sources/rudder-package/Dockerfile
  rust-toolchain.toml
  sbom/Dockerfile
Labels: qa: Can't merge, Ready for merge

#5904 Fixes #25507: Target selection has a weird vertical text
  webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder-template.scss
Labels: Ready for merge

#5902 Fixes #25553: It's "AlmaLinux" and not "Alma Linux"
  webapp/sources/rudder/rudder-web/src/main/resources/ldapObjectAndAttributes.properties
Labels: Ready for merge

#5897 Fixes #25538: Detect local install tentative in rudder package
  relay/sources/rudder-package/src/database.rs
Labels: qa: Can't merge, Ready for merge

#5891 Fixes #25453: When accepting a node with a duplicate hostname, there's no error displayed
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/node/AcceptNode.scala
Labels: Ready for merge

#5906 Fixes #25557: Spaces as a default value provided by node properties are now refused
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/cfclerk/domain/Technique.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/cfclerk/domain/VariableAndSectionSpec.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/DataStructures.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/DeploymentService.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/MergePolicyService.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/RuleValService.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/write/BuildBundleSequence.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/write/PolicyWriterService.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/write/PrepareTemplateVariables.scala
  webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/node-cfe-with-two-directives/rules/cfengine-community/rudder-directives.cf
  webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/techniques/ncf_techniques/Create_file/1.0/metadata.xml
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/MockServices.scala
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/policies/NodeConfigData.scala
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/policies/TestBuildNodeConfiguration.scala
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/policies/write/PolicyAgregationTest.scala
  webapp/sources/rudder/rudder-rest/src/test/resources/api/api_directives.yml
Labels: qa: Can't merge, Ready for merge

#5909 Fixes #25579: System variable can be empty early on the generation process
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/DataStructures.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/write/PrepareTemplateVariables.scala
Labels: qa: Can't merge, Ready for merge
