Repository Normation/rudder, pull requests merged in 2024-04, with the labels that each got.

#5564 Fixes #24613: Enabling directive modal has margin between table and change log
  webapp/sources/rudder/rudder-web/src/main/webapp/templates-hidden/Popup/ModificationValidationPopup.html
Labels: Ready for merge

#5567 Fixes #24647: Only ignored status is displayed in Node page
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/services/DisplayNode.scala
Labels: Ready for merge

#5569 Fixes #24648: Parent ticket should also modify the bundle name of the technique in the metadata
  policies/rudderc/src/backends/windows.rs
  policies/rudderc/templates/technique.ps1.askama
  policies/rudderc/tests/cases/general/escaping/metadata.xml
  policies/rudderc/tests/cases/general/form/metadata.xml
  policies/rudderc/tests/cases/general/long_method_param_name/metadata.xml
  policies/rudderc/tests/cases/general/min/metadata.xml
  policies/rudderc/tests/cases/general/ntp/metadata.xml
  policies/rudderc/tests/cases/general/param_in_condition/metadata.xml
  policies/rudderc/tests/cases/general/reporting/metadata.xml
Labels: Ready for merge

#5580 Fixes #24675: When sending inventory with no software update anymore, inventory stored is not updated and keeps previous updates
  webapp/sources/ldap-inventory/inventory-repository/src/main/scala/com/normation/inventory/ldap/core/FullInventoryRepositoryImpl.scala
Labels: Ready for merge

#5581 Fixes #24680: Plugin backup status file format is incompatible between 8.0 and 8.1
  relay/sources/rudder-package/src/database.rs
  relay/sources/rudder-package/src/lib.rs
  relay/sources/rudder-package/tests/status_backup_file/database.json
  relay/sources/rudder-package/tests/status_backup_file/webapp.xml
Labels: qa: Can't merge, Ready for merge

#5570 Fixes #24655: Reformat the rudderc technique Json schema to match the one published in the schemastore repository
  policies/rudderc/src/technique.schema.json
Labels: qa: Can't merge

#5584 Fixes #24568: Disabled plugins are enabled when upgrading to 8.1
  Cargo.lock
  relay/sources/rudder-package/Cargo.toml
  relay/sources/rudder-package/src/database.rs
  relay/sources/rudder-package/src/lib.rs
  relay/sources/rudder-package/tests/status_backup_file/backup.expected
Labels: qa: Can't merge, Ready for merge

#5598 Fixes #24605: The ul and ol lists have the same markdown rendering
  webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder-main.scss
Labels: Ready for merge

#5585 Fixes #24674: Tenant API documentation has several problems
  webapp/sources/api-doc/code_samples/curl/securitytags/deleteOnNodes.sh
  webapp/sources/api-doc/code_samples/curl/securitytags/nodes.sh
  webapp/sources/api-doc/code_samples/curl/securitytags/setOnNodes.sh
  webapp/sources/api-doc/code_samples/curl/tenants/add.sh
  webapp/sources/api-doc/code_samples/curl/tenants/delete.sh
  webapp/sources/api-doc/code_samples/curl/tenants/set.sh
  webapp/sources/api-doc/paths/securitytags/nodes.yml
  webapp/sources/api-doc/paths/tenants/all.yml
Labels: Ready for merge

#5586 Fixes #24487: Missing icon in the rule creation page
  webapp/sources/rudder/rudder-web/src/main/elm/sources/Rules/ViewRuleDetails.elm
Labels: qa: Can't merge, Ready for merge

#5583 Fixes #24681: Also remove tree from machine
  webapp/sources/ldap-inventory/inventory-repository/src/main/scala/com/normation/inventory/ldap/core/FullInventoryRepositoryImpl.scala
Labels: Ready for merge

#5527 Fixes #24498: There is no easy way to copy a property/inventory variable name to clipboard
  webapp/sources/rudder/rudder-web/src/main/elm/sources/NodeProperties/View.elm
  webapp/sources/rudder/rudder-web/src/main/elm/sources/NodeProperties/ViewUtils.elm
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/services/DisplayNode.scala
  webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder-datatable.css
Labels: qa: Can't merge

#5588 Fixes #24497: Node properties override hovers are not well rendered
  webapp/sources/rudder/rudder-web/src/main/elm/sources/NodeProperties/ViewUtils.elm
Labels: Ready for merge

#5602 Fixes #24717: The font weight of labels is too low
  webapp/sources/rudder/rudder-web/src/main/elm/sources/Editor/ViewTechniqueTabs.elm
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/DirectiveEditForm.scala
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/NodeGroupForm.scala
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/TechniqueCategoryEditForm.scala
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/popup/RuleCategoryPopup.scala
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/model/RudderBaseField.scala
  webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder-bootstrap.scss
  webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder-main.scss
  webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder.css
  webapp/sources/rudder/rudder-web/src/main/webapp/templates-hidden/components/ComponentDirectiveEditForm.html
  webapp/sources/rudder/rudder-web/src/main/webapp/templates-hidden/components/ComponentRuleEditForm.html
  webapp/sources/rudder/rudder-web/src/main/webapp/templates-hidden/components/NodeGroupForm.html
  webapp/sources/rudder/rudder-web/src/main/webapp/templates-hidden/server/server_details.html
Labels: Ready for merge

#5538 Fixes #24550: Nodes table should not be displayed in every tab of group details
  webapp/sources/rudder/rudder-web/src/main/javascript/rudder/rudder-datatable.js
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/SearchNodeComponent.scala
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/services/SrvGrid.scala
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/node/Nodes.scala
  webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder-template.scss
Labels: qa: Can't merge, Ready for merge

#5582 Fixes #24679: File picker is broken in 8.0
  webapp/sources/rudder/rudder-web/src/main/elm/sources/FileManager/wrapper.js
  webapp/sources/rudder/rudder-web/src/main/javascript/rudder/rudder.js
  webapp/sources/rudder/rudder-web/src/main/webapp/secure/configurationManager/directiveManagement.html
  webapp/sources/rudder/rudder-web/src/main/webapp/templates-hidden/components/ComponentDirectiveEditForm.html
Labels: qa: Can't merge

#5592 Fixes #24698: Empty description of technique parameter is not allowed
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/apidata/JsonResponseObjects.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/ncf/EditorTechnique.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/ncf/TechniqueCompiler.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/ncf/migration/MigrateJsonTechniquesService.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/ncf/yaml/YamlTechnique.scala
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/ncf/TestEditorTechniqueWriter.scala
  webapp/sources/rudder/rudder-web/src/main/elm/sources/Editor.elm
  webapp/sources/rudder/rudder-web/src/main/elm/sources/Editor/DataTypes.elm
  webapp/sources/rudder/rudder-web/src/main/elm/sources/Editor/JsonDecoder.elm
  webapp/sources/rudder/rudder-web/src/main/elm/sources/Editor/JsonEncoder.elm
  webapp/sources/rudder/rudder-web/src/main/elm/sources/Editor/ViewTechnique.elm
  webapp/sources/rudder/rudder-web/src/main/elm/sources/Editor/ViewTechniqueTabs.elm
  webapp/sources/rudder/rudder-web/src/test/resources/configuration-repository-migrate-json-8_0/post-migration/ncf_techniques/technique_with_parameters/1.0/metadata.xml
  webapp/sources/rudder/rudder-web/src/test/resources/configuration-repository-migrate-json-8_0/post-migration/ncf_techniques/technique_with_parameters/1.0/technique.yml
  webapp/sources/rudder/rudder-web/src/test/resources/configuration-repository-migrate-json-8_0/techniques/ncf_techniques/technique_with_parameters/1.0/metadata.xml
Labels: qa: Can't merge, Ready for merge

#5547 Fixes #12791: Have a reset-keys button on the node screen
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/EndpointsDefinition.scala
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/services/DisplayNode.scala
Labels: qa: Can't merge

#5610 Fixes #24740: The webapp is needlessly restarted when enabled an already enabled plugin
  relay/sources/rudder-package/src/archive.rs
  relay/sources/rudder-package/src/webapp.rs
Labels: qa: Can't merge

#5572 Fixes #24665: Number of nodes in rule badge is not correct with tenants
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/policies/RuleTarget.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/NodeGroupRepository.scala
Labels: qa: Can't merge

#5576 Fixes #24671: API authorization error: secure/api/compliance/nodes/{id}/system
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/RoleApiMapping.scala
Labels: qa: Can't merge

#5600 Fixes #22525: Directives applied twice don't show in rule details (they should be skipped)
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/data/Compliance.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/ComplianceApi.scala
  webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/DataTypes.elm
  webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/JsonDecoder.elm
  webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/ViewUtils.elm
Labels: qa: Can't merge

#5615 Fixes #24749: Disabled LDAP users can still login and use Rudder
  webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/AppConfigAuth.scala
Labels: qa: Can't merge

#5623 Fixes #24767: Broken compliance score for E
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/score/ComplianceScore.scala
Labels: Ready for merge

#5621 Fixes #24723: Tree group is slow to load up because it contains the list of nodes in the tree
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/apidata/JsonResponseObjects.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/EndpointsDefinition.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/internal/GroupsInternalAPI.scala
  webapp/sources/rudder/rudder-rest/src/test/resources/api/api_groupsinternal.yml
  webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/rest/RestTestSetUp.scala
  webapp/sources/rudder/rudder-web/src/main/elm/sources/Groups/ApiCalls.elm
  webapp/sources/rudder/rudder-web/src/main/elm/sources/Groups/DataTypes.elm
  webapp/sources/rudder/rudder-web/src/main/elm/sources/Groups/JsonDecoder.elm
  webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala
Labels: qa: Can't merge

#5608 Fixes #24708: Groups node ids list in API is still exhaustive even with restricted tenant access
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/eventlog/EventLog.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/batch/UpdateDynamicGroups.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/configuration/ConfigurationRepository.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/queries/NodeQueryCriteriaData.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/ncf/DeleteEditorTechnique.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/ItemArchiveManager.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/NodeGroupRepository.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/ldap/LDAPNodeGroupRepository.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/xml/ItemArchiveManagerImpl.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/modification/ModificationService.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/nodes/NewNodeManager.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/queries/DynGroupUpdaterService.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/queries/NodeFactQueryProcessor.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/queries/QueryProcessor.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/workflows/CommitAndDeployChangeRequestService.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/workflows/WorkflowService.scala
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/MockServices.scala
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/queries/TestNodeFactQueryProcessor.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/internal/EventLogAPI.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/ArchiveApi.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/DirectiveApi.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/GroupsApi.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/ParametersApi.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/RuleApi.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/SystemApi.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/web/model/JsInitContextLinkUtil.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/web/services/DiffDisplayer.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/web/services/EventLogDetailsGenerator.scala
  webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/MockServices.scala
  webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/rest/ArchiveApiTest.scala
  webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/rest/RestTestSetUp.scala
  webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala
  webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/checks/onetimeinit/CheckInitXmlExport.scala
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/SearchNodeComponent.scala
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/popup/CreateCloneGroupPopup.scala
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/popup/CreateOrUpdateGlobalParameterPopup.scala
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/popup/ModificationValidationPopup.scala
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/popup/RuleModificationValidationPopup.scala
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/administration/Archives.scala
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/configuration/ParameterManagement.scala
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/node/Groups.scala
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/node/SearchNodes.scala
Labels: qa: Can't merge

#5625 Fixes #24772: RuleTarget compliance is very slow to compute
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/policies/RuleTarget.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/NodeGroupRepository.scala
Labels: qa: Can't merge

#5634 Fixes #24792: relayd stops runlog processing on invalid run info
  relay/sources/relayd/src/processing/reporting.rs
  relay/sources/relayd/tests/processing_reporting.rs
Labels: qa: Can't merge, Ready for merge
