Repository Normation/rudder, pull requests merged in 2024-11, with the labels that each got.

#5951 Fixes #25681: OIDC users are marked as deleted after a new user is provisionned
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/users/UserRepository.scala
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/users/UserRepositoryTest.scala
Labels: qa: Can't merge

#5958 Fixes #25715: Avoid Content-Security-Policy-Report-Only headers in dev mode
  webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/Boot.scala
Labels: qa: Can't merge

#5961 Fixes #25663: Tooltips in nodes compliance are not displayed
  webapp/sources/rudder/rudder-web/src/main/elm/sources/NodeCompliance/ViewUtils.elm
  webapp/sources/rudder/rudder-web/src/main/elm/sources/Nodecompliance.elm
  webapp/sources/rudder/rudder-web/src/main/elm/sources/Rules/ViewTabContent.elm
Labels: qa: Can't merge

#5962 Fixes #25701: Search on RAM fails in node groups
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/queries/NodeQueryCriteriaData.scala
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/queries/TestNodeFactQueryProcessor.scala
Labels: qa: Can't merge

#5963 Fixes #25720: Technical and event logs get log from browser timezone instead of server timezone
  webapp/sources/rudder/rudder-web/src/main/javascript/rudder/rudder.js
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/services/EventListDisplayer.scala
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/services/LogDisplayer.scala
Labels: qa: Can't merge

#5990 Fixes #25767: Create a variant of API token file with curl header parameter syntax
  webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/AppConfigAuth.scala
  webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala
  webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/checks/action/CreateSystemToken.scala
  webapp/sources/rudder/rudder-web/src/test/scala/bootstrap/liftweb/checks/action/TestCreateSystemToken.scala
  webapp/sources/rudder/rudder-web/src/test/scala/bootstrap/liftweb/checks/migration/TestMigrateSystemTechnique7_0.scala
Labels: qa: Can't merge

#5992 Fixes #25799: Upmerge addUser method in tests added for OIDC provisioning
  webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/MockServices.scala
Labels: Ready for merge

#5953 Fixes #25687: Same as parent ticket for branch 8.1
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/GroupsApi.scala
Labels: qa: Can't merge

#5982 Fixes #25770: Override audit/enforce mode does not work with iterator
  policies/rudderc/src/backends/unix/ncf/method_call.rs
  policies/rudderc/tests/cases/general/escaping/technique.cf
  policies/rudderc/tests/cases/general/escaping/technique.ps1
  policies/rudderc/tests/cases/general/form/technique.cf
  policies/rudderc/tests/cases/general/form/technique.ps1
  policies/rudderc/tests/cases/general/long_method_param_name/technique.cf
  policies/rudderc/tests/cases/general/long_method_param_name/technique.ps1
  policies/rudderc/tests/cases/general/min/technique.cf
  policies/rudderc/tests/cases/general/min/technique.ps1
  policies/rudderc/tests/cases/general/ntp/technique.cf
  policies/rudderc/tests/cases/general/ntp/technique.ps1
  policies/rudderc/tests/cases/general/param_in_condition/technique.cf
  policies/rudderc/tests/cases/general/param_in_condition/technique.ps1
  policies/rudderc/tests/cases/general/policy_mode/technique.cf
  policies/rudderc/tests/cases/general/policy_mode/technique.ps1
  policies/rudderc/tests/cases/general/reporting/technique.cf
  policies/rudderc/tests/cases/general/reporting/technique.ps1
Labels: qa: Can't merge

#5999 Fixes #25829: Improve config log wording
  policies/rudderc/tests/cases/general/reporting/technique.cf
  policies/rudderc/tests/cases/general/variables/technique.cf
  webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala
Labels: qa: Can't merge, Ready for merge

#6000 Fixes #25830: Bad postgresql time conversion for event log cleaning in 8.1
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/batch/PurgeOldInventoryData.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/nodes/history/impl/InventoryHistoryJdbcRepository.scala
Labels: qa: Can't merge

#6006 Fixes #25843: Update Rust dependencies
  Cargo.lock
  ci/rust.sh
  ci/typos.Dockerfile
  policies/Dockerfile
  policies/minifusion/Cargo.toml
  policies/minifusion/src/main.rs
  policies/rudder-commons/Cargo.toml
  policies/rudderc/Cargo.toml
  policies/rudderc/tests/cases/general/escaping/metadata.xml
  policies/rudderc/tests/cases/general/form/metadata.xml
  policies/rudderc/tests/cases/general/long_method_param_name/metadata.xml
  policies/rudderc/tests/cases/general/min/metadata.xml
  policies/rudderc/tests/cases/general/ntp/metadata.xml
  policies/rudderc/tests/cases/general/param_in_condition/metadata.xml
  policies/rudderc/tests/cases/general/policy_mode/metadata.xml
  policies/rudderc/tests/cases/general/reporting/metadata.xml
  policies/rudderc/tests/cases/general/variables/metadata.xml
  policies/rudderc/tests/metadata/serialized.xml
  relay/sources/relayd/Cargo.toml
  relay/sources/relayd/Dockerfile
  relay/sources/relayd/benches/benches.rs
  relay/sources/relayd/src/configuration/main.rs
  relay/sources/relayd/src/output/database.rs
  relay/sources/rudder-package/Cargo.toml
  relay/sources/rudder-package/Dockerfile
  rust-toolchain.toml
  rust.makefile
  sbom/Dockerfile
Labels: qa: Can't merge

#5984 Fixes #25776: Create a global method call counter to help provide more unicity
  policies/rudderc/src/backends/unix.rs
  policies/rudderc/src/backends/unix/cfengine/bundle.rs
  policies/rudderc/src/backends/unix/cfengine/promise.rs
  policies/rudderc/src/backends/unix/ncf/dry_run_mode.rs
  policies/rudderc/src/backends/unix/ncf/method_call.rs
  policies/rudderc/src/backends/unix/ncf/technique.rs
  policies/rudderc/tests/cases/general/escaping/technique.cf
  policies/rudderc/tests/cases/general/form/technique.cf
  policies/rudderc/tests/cases/general/long_method_param_name/technique.cf
  policies/rudderc/tests/cases/general/min/technique.cf
  policies/rudderc/tests/cases/general/ntp/technique.cf
  policies/rudderc/tests/cases/general/param_in_condition/technique.cf
  policies/rudderc/tests/cases/general/policy_mode/technique.cf
  policies/rudderc/tests/cases/general/reporting/technique.cf
  policies/rudderc/tests/cases/general/variables/technique.cf
Labels: qa: Can't merge

#6005 Fixes #24968: Upgrade to ZIO 2.1.2
  webapp/sources/pom.xml
  webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/UserSessionInvalidationFilter.scala
  webapp/sources/utils/src/main/scala/com/normation/ZioCommons.scala
Labels: qa: Can't merge

#6015 Fixes #25873: Use secrecy to store the password
  Cargo.lock
  relay/sources/rudder-package/Cargo.toml
  relay/sources/rudder-package/src/config.rs
  relay/sources/rudder-package/src/repository.rs
Labels: qa: Can't merge

#5976 Fixes #25758: Update Scala dependencies
  webapp/sources/pom.xml
Labels: qa: Can't merge

#6016 Fixes #25871: Allow validating JSON parameters in methods
  Cargo.lock
  policies/rudder-commons/Cargo.toml
  policies/rudder-commons/src/lib.rs
Labels: qa: Can't merge

#6019 Fixes #25786: Add timezone field in campaign schedule
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/campaigns/DataTypes.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/campaigns/JsonCampaignSerializer.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/campaigns/MainCampaignService.scala
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/MockServices.scala
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/campaign/CampaignSchedulerTest.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/CampaignApi.scala
  webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/rest/CampaignApiTest.scala
Labels: qa: Can't merge

#6008 Fixes #25866: After restart, nodes that were set back to default policy mode return to their previous overriden mode
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/ldap/LDAPEntityMapper.scala
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/facts/nodes/TestCoreNodeFactInventory.scala
Labels: qa: Can't merge

#6009 Fixes #25847: The setup initial page should not be displayed if rudder-pkg.conf has been modified
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/plugins/PluginSettings.scala
  webapp/sources/rudder/rudder-core/src/test/resources/plugins/rudder-pkg-default.conf
  webapp/sources/rudder/rudder-core/src/test/resources/plugins/rudder-pkg-empty.conf
  webapp/sources/rudder/rudder-core/src/test/resources/plugins/rudder-pkg-example.conf
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/plugins/TestPluginSettingsService.scala
  webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/SetupRedirect.scala
Labels: qa: Can't merge

#6034 Fixes #25925: Error in update campaign - yum always reboots
  policies/module-types/system-updates/src/package_manager/yum.rs
Labels: qa: Can't merge

#6035 Fixes #25926: Dont output package lists in report
  policies/module-types/system-updates/src/hooks.rs
  policies/module-types/system-updates/src/output.rs
  policies/module-types/system-updates/src/package_manager/apt.rs
  policies/module-types/system-updates/src/package_manager/rpm.rs
  policies/module-types/system-updates/src/package_manager/yum.rs
  policies/module-types/system-updates/src/package_manager/zypper.rs
  policies/module-types/system-updates/src/system.rs
Labels: qa: Can't merge

#6041 Fixes #25941: Spurious failing test for inherited properties rest API
  webapp/sources/rudder/rudder-rest/src/test/resources/api/api_nodes.yml
  webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/rest/TestInheritedProperties.scala
  webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/rest/TestRestFromFileDef.scala
  webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/rest/TraitTestApiFromYamlFiles.scala
Labels: qa: Can't merge

#5986 Fixes #25780: Clean-up support for rsa key for inventory signature
  webapp/sources/ldap-inventory/inventory-api/src/main/scala/com/normation/inventory/domain/AgentTypes.scala
  webapp/sources/ldap-inventory/inventory-api/src/main/scala/com/normation/inventory/domain/DataTypes.scala
  webapp/sources/ldap-inventory/inventory-api/src/main/scala/com/normation/inventory/services/provisioning/CheckInventoryDigest.scala
  webapp/sources/ldap-inventory/inventory-api/src/test/scala/com/normation/inventory/domain/AgentTypesTest.scala
  webapp/sources/ldap-inventory/inventory-repository/src/main/scala/com/normation/inventory/ldap/core/InventoryMapper.scala
  webapp/sources/ldap-inventory/inventory-repository/src/main/scala/com/normation/inventory/ldap/core/LDAPConstants.scala
  webapp/sources/ldap-inventory/inventory-repository/src/test/resources/ldap-data/schema/099-0-inventory.ldif
  webapp/sources/ldap-inventory/inventory-repository/src/test/scala/com/normation/inventory/ldap/core/TestNodeUnserialisation.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/RudderLDAPConstants.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/nodes/Node.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/nodes/NodeInfo.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/facts/nodes/NodeFact.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/ldap/LDAPEntityMapper.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/eventlog/EventLogDetailsService.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/nodes/NodeInfoService.scala
  webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/root-sys-var-false/common/1.0/cf-serverd.cf
  webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/root-sys-var-false/rudder-service-relayd/1.0/relay/nodeslist.json
  webapp/sources/rudder/rudder-core/src/test/resources/ldap-data/inventory-sample-data.ldif
  webapp/sources/rudder/rudder-core/src/test/resources/ldap-data/schema/099-0-inventory.ldif
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/MockServices.scala
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/domain/nodes/NodeKeyHashTest.scala
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/policies/NodeConfigData.scala
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/policies/TestWriteNodeCertificatesPem.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/RestExtractorService.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/data/CreateNodeData.scala
  webapp/sources/rudder/rudder-rest/src/test/resources/api/api_nodes.yml
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/services/DisplayNode.scala
Labels: Ready for merge

#6023 Fixes #25887: Migrate from lift-json to zio-json in LDAPEntityMapper
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/RudderDit.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/policies/ActiveTechnique.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/facts/nodes/NodeFact.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/reports/ReportingConfiguration.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/DirectiveRepository.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/ldap/LDAPDirectiveRepository.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/ldap/LDAPEntityMapper.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/marshalling/XmlSerialisationImpl.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/marshalling/XmlUnserialisationImpl.scala
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/cfclerk/services/TechniqueRepositoryTest.scala
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/facts/nodes/MockLdapFactStorage.scala
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/repository/ldap/GlobalParamMigration61Test.scala
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/repository/ldap/LDAPEntityMapperTest.scala
  webapp/sources/rudder/rudder-web/src/main/elm/sources/Agentschedule.elm
  webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/AgentScheduleEditForm.scala
Labels: Ready for merge

#6047 Fixes #25892: Error when accepting 2 or more nodes
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/jdbc/RudderDatasourceProvider.scala
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/db/DBCommon.scala
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/db/GenerateCompliance.scala
  webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala
  webapp/sources/scala-ldap/src/main/scala/com/normation/ldap/sdk/LDAPConnectionProvider.scala
Labels: qa: Can't merge, Ready for merge

#6056 Fixes #25971: Allow installing the licenses with rudder-package
  Cargo.lock
  relay/sources/rudder-package/Cargo.toml
  relay/sources/rudder-package/src/lib.rs
  relay/sources/rudder-package/src/license.rs
  relay/sources/rudder-package/src/repository.rs
  relay/sources/rudder-package/tests/licenses.tar.gz
Labels: Ready for merge

#6052 Fixes #25959: rudderc fails to compile string with vars and regex
  policies/rudderc/src/ir/value.rs
  policies/rudderc/tests/cases/general/escaping/metadata.xml
  policies/rudderc/tests/cases/general/escaping/technique.cf
  policies/rudderc/tests/cases/general/escaping/technique.ps1
  policies/rudderc/tests/cases/general/escaping/technique.yml
  policies/rudderc/tests/cases/general/form/metadata.xml
  policies/rudderc/tests/cases/general/ntp/metadata.xml
  policies/rudderc/tests/cases/general/param_in_condition/metadata.xml
Labels: qa: Can't merge, Ready for merge

#6032 Fixes #25917: Add a dedicated Readme for rudder-package
  relay/sources/rudder-pkg/README.md
Labels: qa: Can't merge

#6054 Fixes #25815: tooltip broken for groups description
  webapp/sources/rudder/rudder-web/src/main/elm/sources/Groups/View.elm
Labels: qa: Can't merge
