Repository Normation/rudder, pull requests merged in 2024-05, with the labels that each got.

#5620 Fixes #24762: Add basic elm-review config
  webapp/sources/Dockerfile
  webapp/sources/rudder/rudder-web/pom.xml
  webapp/sources/rudder/rudder-web/src/main/elm/elm.json
  webapp/sources/rudder/rudder-web/src/main/elm/review/elm.json
  webapp/sources/rudder/rudder-web/src/main/elm/review/src/ReviewConfig.elm
  webapp/sources/rudder/rudder-web/src/main/package-lock.json
  webapp/sources/rudder/rudder-web/src/main/package.json
Labels: qa: Can't merge

#5624 Fixes #24768: Update Scala dependencies
  webapp/sources/pom.xml
Labels: qa: Can't merge

#5647 Fixes #24828: Never return a password for plugin settings
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/PluginApi.scala
Labels: qa: Can't merge, Ready for merge

#5646 Fixes #24817: When there are more nodes than supported by licenses, no logs in webapp states it
  webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/Boot.scala
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/plugins/PluginStatus.scala
Labels: qa: Can't merge

#5629 Fixes #24788: Empty space in global compliance bar
  webapp/sources/rudder/rudder-web/src/main/javascript/rudder/homePage.js
  webapp/sources/rudder/rudder-web/src/main/javascript/rudder/rudder-datatable.js
  webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder-dashboard.css
  webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder-progress-bar.css
Labels: qa: Can't merge

#5650 Fixes #24832: Migrate rudder-web to zio-json
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/services/DisplayNode.scala
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/node/AcceptNode.scala
Labels: qa: Can't merge

#5655 Fixes #24839: We cannot login with a user login containing uppercase letter if the option case-sensitivity is set to false
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/users/UserRepository.scala
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/users/UserRepositoryTest.scala
  webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/AppConfigAuth.scala
  webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderUserDetailsFile.scala
  webapp/sources/rudder/rudder-web/src/test/scala/bootstrap/liftweb/RudderUserDetailsTest.scala
Labels: Ready for merge

#5651 Fixes #24745: Add an option to inhibit webapp restart
  relay/sources/rudder-package/src/lib.rs
  relay/sources/rudder-package/src/webapp.rs
Labels: Ready for merge

#5630 Fixes #24097: Skipped directive does not show in node compliance tree
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/data/Compliance.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/ComplianceApi.scala
  webapp/sources/rudder/rudder-web/src/main/elm/sources/Compliance/DataTypes.elm
  webapp/sources/rudder/rudder-web/src/main/elm/sources/NodeCompliance/DataTypes.elm
  webapp/sources/rudder/rudder-web/src/main/elm/sources/NodeCompliance/JsonDecoder.elm
  webapp/sources/rudder/rudder-web/src/main/elm/sources/NodeCompliance/ViewUtils.elm
  webapp/sources/rudder/rudder-web/src/main/elm/sources/Rules/DataTypes.elm
  webapp/sources/rudder/rudder-web/src/main/elm/sources/Rules/JsonDecoder.elm
  webapp/sources/rudder/rudder-web/src/main/elm/sources/Rules/ViewUtils.elm
Labels: qa: Can't merge

#5638 Fixes #24799: Move user-management plugin to rudder
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/RoleApiMapping.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/UserManagementApi.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/users/RudderUserDetailsFile.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/users/UserManagement.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/users/UserManagementService.scala
  webapp/sources/rudder/rudder-rest/src/test/resources/api/api_usermanagement.yml
  webapp/sources/rudder/rudder-rest/src/test/resources/test-users.xml
  webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/MockServices.scala
  webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/rest/RestTestSetUp.scala
  webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/rest/RoleComputationTest.scala
  webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/rest/users/SerializationTest.scala
  webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/rest/users/UserManagementServiceTest.scala
  webapp/sources/rudder/rudder-web/src/main/elm/sources/UserManagement.elm
  webapp/sources/rudder/rudder-web/src/main/elm/sources/UserManagement/ApiCalls.elm
  webapp/sources/rudder/rudder-web/src/main/elm/sources/UserManagement/DataTypes.elm
  webapp/sources/rudder/rudder-web/src/main/elm/sources/UserManagement/Init.elm
  webapp/sources/rudder/rudder-web/src/main/elm/sources/UserManagement/JsonDecoder.elm
  webapp/sources/rudder/rudder-web/src/main/elm/sources/UserManagement/JsonEncoder.elm
  webapp/sources/rudder/rudder-web/src/main/elm/sources/UserManagement/View.elm
  webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/AppConfigAuth.scala
  webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/Boot.scala
  webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderAuthorizationFileReloadCallback.scala
  webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala
  webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/UserAuthorisationLevel.scala
  webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder-user-management.scss
  webapp/sources/rudder/rudder-web/src/main/webapp/secure/administration/userManagement.html
  webapp/sources/rudder/rudder-web/src/test/scala/bootstrap/liftweb/RudderUserDetailsTest.scala
  webapp/sources/rudder/rudder-web/src/test/scala/bootstrap/liftweb/RudderUserPasswordEncoderTest.scala
Labels: qa: Can't merge

#5661 Fixes #24856:
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/xml/GitArchivers.scala
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/repository/xml/TestBuildPathUtils.scala
Labels: qa: Can't merge

#5664 Fixes #24864: Fix upmerge of 24856 in 8.1
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/xml/GitArchivers.scala
Labels: Ready for merge

#5671 Fixes #24877: Upmerge breaks build from 8.0 and up
  webapp/sources/utils/src/main/scala/com/normation/utils/DateFormaterService.scala
Labels: Ready for merge

#5673 Fixes #24888: Technique tags can be arbitrary objects
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/ncf/EditorTechnique.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/ncf/yaml/YamlTechnique.scala
Labels: qa: Can't merge

#5663 Fixes #24834: When we save an API Token, the UI is grayed out
  webapp/sources/rudder/rudder-web/src/main/elm/sources/Accounts.elm
  webapp/sources/rudder/rudder-web/src/main/elm/sources/Accounts/DataTypes.elm
  webapp/sources/rudder/rudder-web/src/main/elm/sources/Accounts/Init.elm
  webapp/sources/rudder/rudder-web/src/main/elm/sources/Accounts/View.elm
  webapp/sources/rudder/rudder-web/src/main/elm/sources/Accounts/ViewModals.elm
  webapp/sources/rudder/rudder-web/src/main/elm/sources/Accounts/ViewUtils.elm
  webapp/sources/rudder/rudder-web/src/main/elm/sources/GroupRelatedRules/View.elm
  webapp/sources/rudder/rudder-web/src/main/elm/sources/NodeProperties/ViewUtils.elm
  webapp/sources/rudder/rudder-web/src/main/elm/sources/Rules/View.elm
Labels: qa: Can't merge

#5649 Fixes #24830: Update to Rust 1.78
  Cargo.lock
  ci/typos.Dockerfile
  policies/Dockerfile
  policies/minifusion/Cargo.toml
  policies/module-types/template/Cargo.toml
  policies/rudderc/Cargo.toml
  policies/rudderc/src/compiler.rs
  policies/rudderc/src/lib.rs
  relay/sources/relayd/Cargo.toml
  relay/sources/relayd/Dockerfile
  relay/sources/relayd/src/data/node.rs
  relay/sources/rudder-package/Cargo.toml
  relay/sources/rudder-package/Dockerfile
  relay/sources/rudder-package/src/database.rs
  relay/sources/rudder-package/src/lib.rs
  rust-toolchain.toml
  sbom/Dockerfile
Labels: qa: Can't merge

#5643 Fixes #24629: Score details columns in node tables cannot be saved
  webapp/sources/rudder/rudder-web/src/main/javascript/rudder/rudder-datatable.js
Labels: Ready for merge

#5648 Fixes #24829: Replace compliance chart with Score chart and and new details score charts
  webapp/sources/rudder/rudder-web/src/main/javascript/rudder/homePage.js
  webapp/sources/rudder/rudder-web/src/main/javascript/rudder/rudder-datatable.js
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/HomePage.scala
  webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder-dashboard.scss
  webapp/sources/rudder/rudder-web/src/main/webapp/secure/index.html
Labels: Ready for merge

#5656 Fixes #24833: Migrate NodeApi to zio-json in rudder-rest and utils
  webapp/sources/ldap-inventory/inventory-api/pom.xml
  webapp/sources/ldap-inventory/inventory-api/src/main/scala/com/normation/inventory/domain/JsonSerializers.scala
  webapp/sources/ldap-inventory/inventory-api/src/main/scala/com/normation/inventory/domain/MachineInventory.scala
  webapp/sources/ldap-inventory/inventory-api/src/main/scala/com/normation/inventory/domain/NodeInventory.scala
  webapp/sources/ldap-inventory/inventory-api/src/test/scala/com/normation/inventory/domain/InventorySerialisationTest.scala
  webapp/sources/pom.xml
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/apidata/JsonQueryObjects.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/apidata/JsonResponseObjects.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/apidata/NodeDetailLevel.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/apidata/RestDataSerializer.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/logger/ApplicationLogger.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/facts/nodes/NodeFact.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/nodes/RemoveNodeService.scala
  webapp/sources/rudder/rudder-core/src/test/resources/node-facts/node-001-machine-physical-v2.json
  webapp/sources/rudder/rudder-core/src/test/resources/node-facts/node-001-machine-physical.json
  webapp/sources/rudder/rudder-core/src/test/resources/node-facts/node-001-machine-unknown-v2.json
  webapp/sources/rudder/rudder-core/src/test/resources/node-facts/node-001-machine-unknown-vm-v2.json
  webapp/sources/rudder/rudder-core/src/test/resources/node-facts/node-001-machine-unknown-vm.json
  webapp/sources/rudder/rudder-core/src/test/resources/node-facts/node-001-machine-unknown.json
  webapp/sources/rudder/rudder-core/src/test/resources/node-facts/node-930dccb0-5b06-4385-ab7a-80a7e56eb969-v2.json
  webapp/sources/rudder/rudder-core/src/test/resources/node-facts/node-930dccb0-5b06-4385-ab7a-80a7e56eb969.json
  webapp/sources/rudder/rudder-core/src/test/resources/node-facts/root.json
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/facts/nodes/TestNodeFactSerialisation.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/RestExtractorService.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/data/RestData.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/NodeApi.scala
  webapp/sources/rudder/rudder-rest/src/test/resources/api/api_nodes.yml
  webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/rest/RestTestSetUp.scala
  webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala
  webapp/sources/utils/src/main/scala/com/normation/ZioCommons.scala
Labels: qa: Can't merge

#5696 Fixes #24951: Change 'No score' label
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/HomePage.scala
Labels: Ready for merge

#5698 Fixes #24956: Windows agent used to test windows policies was deleted
  policies/Makefile
Labels: qa: Can't merge, Ready for merge

#5687 Fixes #24937: Query in get pending node API doesn't match anything
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/queries/LdapQueryProcessor.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/queries/NodeFactQueryProcessor.scala
Labels: qa: Can't merge, Trigger test
