Repository Normation/rudder, pull requests merged in 2024-10, with the labels that each got.

#5913 Fixes #25513: worst report by percentage seems to be non fonctionnal
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/reports/StatusReports.scala
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/reports/ExecutionBatchTest.scala
Labels: Ready for merge

#5914 Fixes #25600: Compliance reporting with type worst-case-percent is not known by rudderc
  policies/rudderc/docs/src/syntax.md
  policies/rudderc/src/ir/technique.rs
  policies/rudderc/src/technique.schema.json
  policies/rudderc/tests/cases/general/reporting/metadata.xml
  policies/rudderc/tests/cases/general/reporting/technique.cf
  policies/rudderc/tests/cases/general/reporting/technique.ps1
  policies/rudderc/tests/cases/general/reporting/technique.yml
Labels: Ready for merge

#5915 Fixes #25508: No system status in 8.2
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/ComplianceApi.scala
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/node/Node.scala
Labels: Ready for merge

#5877 Fixes #25466: A user should not be able to delete themselves in user management 8.2
  webapp/sources/rudder/rudder-web/src/main/elm/sources/UserManagement/View.elm
Labels: Ready for merge

#5905 Fixes #25527: List techniques with compilation failure in bar for generation status
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/batch/AsyncDeploymentActor.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/batch/CheckPolicyTemplateLibrary.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/logger/StatusLogger.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/ncf/TechniqueCompilationCache.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/ncf/TechniqueCompiler.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/ncf/TechniqueWriter.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/xml/GitArchivers.scala
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/ncf/TestEditorTechniqueWriter.scala
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/ncf/TestTechniqueCompilationCache.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/TechniqueApi.scala
  webapp/sources/rudder/rudder-web/src/main/resources/logback.xml
  webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala
  webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/checks/action/CheckTechniqueCompilationStatus.scala
  webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/checks/migration/MigrateJsonTechniquesToYaml.scala
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/comet/AsyncDeployment.scala
  webapp/sources/rudder/rudder-web/src/test/scala/bootstrap/liftweb/checks/migration/TestMigrateJsonTechniquesToYaml.scala
Labels: qa: Can't merge

#5920 Fixes #25332: When changing node properties the old table is sometimes still displayed
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/GroupsApi.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/NodeApi.scala
  webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/rest/RestTestSetUp.scala
  webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala
Labels: qa: Can't merge

#5927 Fixes #25636: New README for Rudder
  README.adoc
  README.md
  readme-resources/dashboard.png
  readme-resources/visual.svg
Labels: qa: Can't merge

#5926 Fixes #25637: Sometimes tests with lift actor fails
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/ncf/TechniqueCompilationCache.scala
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/ncf/TestTechniqueCompilationCache.scala
Labels: qa: Can't merge

#5916 Fixes #25517: System rules are now always shown in directives compliance
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/ComplianceApi.scala
Labels: qa: Can't merge

#5930 Fixes #3615: IP search field with slash notation
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/queries/NodeQueryCriteriaData.scala
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/domain/queries/CmdbQueryTest.scala
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/domain/queries/NodeQueryCriteriaDataTest.scala
Labels: qa: Can't merge

#5860 Fixes #25419: Add tests for the case where there is conflicts
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/MockServices.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/ParametersApi.scala
  webapp/sources/rudder/rudder-rest/src/test/resources/api/api_parameters.yml
  webapp/sources/rudder/rudder-rest/src/test/resources/api_inherited_prop/global_group_param.yml
  webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/rest/RestTestSetUp.scala
  webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/rest/TestInheritedProperties.scala
Labels: qa: Can't merge

#5944 Fixes #25661: Fix APT output collection
  policies/module-types/system-updates/src/db.rs
  policies/module-types/system-updates/src/package_manager/apt.rs
  policies/module-types/system-updates/src/package_manager/zypper.rs
  policies/module-types/system-updates/src/scheduler.rs
  policies/module-types/system-updates/src/state.rs
Labels: Ready for merge

#5939 Fixes #25658: Remove the Clipboard js library as it is no longer required
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/NodeGroupForm.scala
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/services/DisplayNode.scala
  webapp/sources/rudder/rudder-web/src/main/webapp/index.html
  webapp/sources/rudder/rudder-web/src/main/webapp/templates-hidden/common-layout.html
Labels: Ready for merge

#5945 Fixes #25675: Add 127.0.0.1 as ServerAlias for multi-vhost server configuration
  relay/sources/apache/rudder-vhost.conf
Labels: qa: Can't merge

#5954 Fixes #25693: Software update campaign does not work on SLES 15
  policies/module-types/system-updates/src/package_manager/zypper.rs
Labels: qa: Can't merge, Ready for merge

#5956 Fixes #25709: OpenAPI documentation is invalid with duplicate /nodes/pending endpoints
  api-doc/build.py
  api-doc/redocly.yml
  webapp/sources/api-doc/openapi.src.yml
  webapp/sources/api-doc/paths/nodes/pending-all.yml
  webapp/sources/api-doc/paths/nodes/pending-update.yml
Labels: qa: Can't merge, Ready for merge

#5942 Fixes #25589: Lost manufacturer & serial for BIOS between 7.3 and 8.0
  webapp/sources/ldap-inventory/inventory-api/src/main/scala/com/normation/inventory/domain/MachineInventory.scala
  webapp/sources/ldap-inventory/inventory-fusion/src/main/scala/com/normation/inventory/provisioning/fusion/FusionInventoryParser.scala
  webapp/sources/ldap-inventory/inventory-fusion/src/test/scala/com/normation/inventory/provisioning/fusion/TestReportParsing.scala
  webapp/sources/ldap-inventory/inventory-repository/src/main/scala/com/normation/inventory/ldap/core/InventoryMapper.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/apidata/NodeDetailLevel.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/queries/NodeQueryCriteriaData.scala
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/services/DisplayNode.scala
Labels: qa: Can't merge, Ready for merge

#5979 Fixes #25771: Broken parsing of node inventory variable
  policies/rudderc/src/ir/value.rs
Labels: qa: Can't merge

#5972 Fixes #25754: Stacktrace in relayd on invalid run time file name
  relay/sources/relayd/src/main.rs
Labels: Ready for merge

#5949 Fixes #25652: Default settings for new nodes are not applied on a accepted node
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/nodes/NewNodeManager.scala
  webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala
Labels: qa: Can't merge, Ready for merge
