Repository Normation/rudder, pull requests merged in 2024-03, with the labels that each got.

#5424 Fixes #24301: Adapt Jenkinsfile after warning-ng plugin upgrade
  Jenkinsfile
Labels: qa: Can't merge, Ready for merge

#5431 Fixes #24310: Display of node compliance info message is broken
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/services/ReportDisplayer.scala
  webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder.css
Labels: qa: Can't merge, Ready for merge

#5432 Fixes #24311: Checkbox for selecting all nodes for acceptance doesn't work
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/web/model/DirectiveEditor.scala
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/services/ReportDisplayer.scala
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/node/AcceptNode.scala
Labels: qa: Can't merge, Ready for merge

#5440 Fixes #24336: Filter button on group page doesn't do anything
  webapp/sources/rudder/rudder-web/src/main/elm/sources/Groups/View.elm
  webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder-rules.css
  webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder-template.scss
Labels: Ready for merge

#5438 Fixes #24322: Modal titles are unreadable
  webapp/sources/rudder/rudder-web/src/main/elm/sources/Editor/ViewTechnique.elm
  webapp/sources/rudder/rudder-web/src/main/elm/sources/NodeProperties/ViewUtils.elm
  webapp/sources/rudder/rudder-web/src/main/elm/sources/Rules/View.elm
  webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder-bootstrap.scss
  webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder-main.css
Labels: Ready for merge

#5447 Fixes #24349: Odd rendering on tooltips in search node page
  webapp/sources/rudder/rudder-web/src/main/webapp/templates-hidden/server/server_details.html
Labels: Ready for merge

#5446 Fixes #24351: Tooltips persisted on refresh button on the table in search node page
  webapp/sources/rudder/rudder-web/src/main/javascript/rudder/rudder-datatable.js
Labels: Ready for merge

#5445 Fixes #24354: Description in API account is outside of the header
  webapp/sources/rudder/rudder-web/src/main/elm/sources/Accounts/View.elm
Labels: Ready for merge

#5444 Fixes #24346: Warning icon on log out should be on healthcheck heart logo
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/HealthcheckInfo.scala
  webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder-bootstrap.scss
  webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder-main.css
  webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder-menu.scss
Labels: Ready for merge

#5442 Fixes #24350: The technique editor enforces optional parameter presence
  webapp/sources/rudder/rudder-web/src/main/elm/sources/Editor/ViewMethod.elm
Labels: Ready for merge

#5433 Fixes #24313: Wrong lalel on tab in compliance group
  webapp/sources/rudder/rudder-web/src/main/elm/sources/DirectiveCompliance/View.elm
  webapp/sources/rudder/rudder-web/src/main/elm/sources/GroupCompliance/View.elm
Labels: Ready for merge

#5450 Fixes #24369: The height of node tabs is higher than the height of their container
  webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder-node.scss
  webapp/sources/rudder/rudder-web/src/main/webapp/templates-hidden/server/server_details.html
Labels: Ready for merge

#5451 Fixes #24371: Broken detection of incorrect parameter names
  policies/rudderc/src/compiler.rs
Labels: Ready for merge

#5420 Fixes #23881: When the documentation of a technique is very long, the user has to scroll a long way before creating a directive from this technique
  webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder-main.css
Labels: Ready for merge

#5394 Fixes #24174: The display of the description field is broken
  webapp/sources/rudder/rudder-web/src/main/javascript/rudder/rudder.js
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/DirectiveEditForm.scala
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/NodeGroupForm.scala
  webapp/sources/rudder/rudder-web/src/main/webapp/templates-hidden/components/ComponentDirectiveEditForm.html
  webapp/sources/rudder/rudder-web/src/main/webapp/templates-hidden/components/NodeGroupForm.html
Labels: Ready for merge

#5437 Fixes #24233: Update Rudder CSS to support bug fixes in plugins interface
  webapp/sources/rudder/rudder-web/src/main/elm/sources/Accounts/ViewModals.elm
  webapp/sources/rudder/rudder-web/src/main/style/rudder/_rudder-variables.scss
  webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder-bootstrap.scss
  webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder-compliance.scss
  webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder-elm-datepicker.css
  webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder-main.scss
  webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder-node.scss
  webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder-template.scss
  webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder.css
  webapp/sources/rudder/rudder-web/src/main/webapp/templates-hidden/components/ComponentRuleEditForm.html
Labels: Ready for merge

#5457 Fixes #24380: Rename policy_mode to policy_mode_override
  policies/rudder-commons/src/lib.rs
  policies/rudderc/docs/src/syntax.md
  policies/rudderc/src/backends/unix.rs
  policies/rudderc/src/backends/unix/ncf/method_call.rs
  policies/rudderc/src/backends/windows.rs
  policies/rudderc/src/ir/technique.rs
  policies/rudderc/src/technique.schema.json
  policies/rudderc/templates/technique.ps1.askama
  policies/rudderc/tests/cases/general/policy_mode/technique.yml
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/ncf/yaml/YamlTechnique.scala
  webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/techniques/ncf_techniques/technique_any/1.0/technique.yml
  webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/techniques/ncf_techniques/technique_by_Rudder/1.0/technique.yml
  webapp/sources/rudder/rudder-web/src/main/elm/sources/Editor/ViewBlock.elm
  webapp/sources/rudder/rudder-web/src/main/elm/sources/Editor/ViewMethod.elm
Labels: Ready for merge

#5419 Fixes #24283: Margin is too small on Global compliance details module in dashboard
  webapp/sources/rudder/rudder-web/src/main/javascript/rudder/homePage.js
  webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder-dashboard.css
Labels: qa: Can't merge, Ready for merge

#5455 Fixes #24316: Tooltips on system-updates in score-details is not standard
  webapp/sources/rudder/rudder-web/src/main/elm/sources/SystemUpdateScore.elm
Labels: Ready for merge

#5458 Fixes #24348: Odd spacing with filters elements in node search page
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/SearchNodeComponent.scala
  webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder-groups.css
  webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder-main.scss
  webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder-node.scss
  webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder-rules.css
  webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder.css
  webapp/sources/rudder/rudder-web/src/main/webapp/templates-hidden/server/server_details.html
Labels: Ready for merge

#5461 Fixes #24389: Improve rudder-package CLI doc
  relay/sources/rudder-package/src/cli.rs
Labels: Ready for merge

#5418 Fixes #24289: windows Node in tests has invalid certificate, failing test in plugin windows
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/policies/NodeConfigData.scala
Labels: qa: Can't merge

#5462 Fixes #24391: API popup for copying token does not appear
  webapp/sources/rudder/rudder-web/src/main/elm/sources/Accounts/View.elm
  webapp/sources/rudder/rudder-web/src/main/elm/sources/Accounts/ViewModals.elm
Labels: Ready for merge

#5456 Fixes #24366: Group compliance stays empty
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/ComplianceApi.scala
  webapp/sources/rudder/rudder-rest/src/test/resources/api/api_compliance.yml
  webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/MockServices.scala
Labels: qa: Can't merge

#5467 Fixes #24302: Add outcome conditions in rudderc docs
  policies/rudderc/src/doc.rs
Labels: qa: Can't merge

#5468 Fixes #24428: Directives button to set parameters on new directive does nothing
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/DirectiveEditForm.scala
Labels: Ready for merge

#5469 Fixes #24432: Broken pipe when piping rudder-package output
  policies/rudder-cli/src/lib.rs
  policies/rudderc/src/lib.rs
  relay/sources/rudder-package/src/lib.rs
Labels: qa: Can't merge

#5463 Fixes #24405: Node tabs have onclick event handlers assigned on unrendered elements
  webapp/sources/rudder/rudder-web/src/main/javascript/rudder/rudder.js
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/services/ReportDisplayer.scala
  webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder.css
  webapp/sources/rudder/rudder-web/src/main/webapp/templates-hidden/reports_server.html
Labels: qa: Can't merge, Ready for merge

#5472 Fixes #24456: Missing primary key statement for user sessions table creation when migrating
  webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/checks/migration/CheckTableUsers.scala
Labels: qa: Can't merge, Ready for merge

#5476 Fixes #24490: Add a quiet argument to rudder-package
  relay/sources/rudder-package/src/cli.rs
  relay/sources/rudder-package/src/lib.rs
Labels: Ready for merge

#5480 Fixes #24516: Vulnerability in mio
  relay/sources/relayd/Cargo.lock
Labels: qa: Can't merge

#5479 Fixes #24515: Rudder should finish to migrate all techniques when booting instead of stopping on first error
  webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/checks/action/CheckNcfTechniqueUpdate.scala
Labels: qa: Can't merge

#5481 Fixes #24517: Ignore angularjs DoS in 7.3
  webapp/sources/rudder/rudder-web/src/main/.nsprc
Labels: qa: Can't merge, Ready for merge

#5485 Fixes #24463: It is hard to differentiate between real values and placeholders in inputs
  webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder-bootstrap.scss
Labels: Ready for merge

#5486 Fixes #24520: Async tests are failing for node certificates
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/policies/TestWriteNodeCertificatesPem.scala
Labels: Ready for merge

#5471 Fixes #24236: Overriding properties should have the same type as overridden
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/apidata/JsonResponseObjects.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/properties/Properties.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/nodes/MergeNodeProperties.scala
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/nodes/TestMergeGroupProperties.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/GroupsApi.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/NodeApi.scala
  webapp/sources/rudder/rudder-rest/src/test/resources/api/api_groups.yml
  webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/rest/RestTestSetUp.scala
  webapp/sources/rudder/rudder-web/src/main/elm/sources/NodeProperties/DataTypes.elm
  webapp/sources/rudder/rudder-web/src/main/elm/sources/NodeProperties/JsonDecoder.elm
  webapp/sources/rudder/rudder-web/src/main/elm/sources/NodeProperties/View.elm
  webapp/sources/rudder/rudder-web/src/main/elm/sources/NodeProperties/ViewUtils.elm
  webapp/sources/rudder/rudder-web/src/main/elm/sources/Nodeproperties.elm
  webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala
Labels: qa: Can't merge

#5473 Fixes #24467: Improve technique parameter UI
  webapp/sources/rudder/rudder-web/src/main/elm/sources/Editor.elm
  webapp/sources/rudder/rudder-web/src/main/elm/sources/Editor/DataTypes.elm
  webapp/sources/rudder/rudder-web/src/main/elm/sources/Editor/ViewTechniqueTabs.elm
  webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder-technique-editor.css
Labels: Ready for merge

#5493 Fixes #24528: Nodes tables height is too small
  webapp/sources/rudder/rudder-web/src/main/javascript/rudder/rudder-datatable.js
  webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder-datatable.css
  webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder-template.scss
  webapp/sources/rudder/rudder-web/src/main/webapp/templates-hidden/components/NodeGroupForm.html
Labels: qa: Can't merge, Ready for merge

#5497 Fixes #24546: Group parameters tab is always displayed
  webapp/sources/rudder/rudder-web/src/main/webapp/templates-hidden/components/NodeGroupForm.html
Labels: Ready for merge

#5504 Fixes #23400: JS error when clicking on a technique with several version in directive screen
  webapp/sources/rudder/rudder-web/src/main/webapp/secure/configurationManager/directiveManagement.html
Labels: Ready for merge

#5498 Fixes #24489: Group page UI is missing several key things
  webapp/sources/rudder/rudder-web/src/main/elm/sources/Groups.elm
  webapp/sources/rudder/rudder-web/src/main/elm/sources/Groups/DataTypes.elm
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/NodeGroupCategoryForm.scala
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/NodeGroupForm.scala
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/model/RudderBaseField.scala
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/node/Groups.scala
  webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder-groups.scss
  webapp/sources/rudder/rudder-web/src/main/webapp/secure/nodeManager/groups.html
  webapp/sources/rudder/rudder-web/src/main/webapp/templates-hidden/components/NodeGroupForm.html
Labels: qa: Can't merge

#5500 Fixes #24549: Resizing node tab in group page should stop at header
  webapp/sources/rudder/rudder-web/src/main/javascript/rudder/rudder-datatable.js
Labels: qa: Can't merge

#5515 Fixes #24576: Rudder-package cli help for install command should document file
  relay/sources/rudder-package/src/cli.rs
Labels: qa: Can't merge

#5505 Fixes #24563: JS error when opening directive form more than once
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/services/DisplayDirectiveTree.scala
  webapp/sources/rudder/rudder-web/src/main/webapp/secure/configurationManager/directiveManagement.html
  webapp/sources/rudder/rudder-web/src/main/webapp/templates-hidden/components/ComponentDirectiveEditForm.html
Labels: qa: Can't merge, Ready for merge

#5522 Fixes #24586: Compilation output tab icon in technique is not aligned
  webapp/sources/rudder/rudder-web/src/main/elm/sources/Editor/ViewTechnique.elm
Labels: qa: Can't merge, Ready for merge

#5526 Fixes #24548: Tags displayed in directive form are broken
  webapp/sources/rudder/rudder-web/src/main/elm/sources/Tags/View.elm
Labels: qa: Can't merge

#5525 Fixes #24499: Wrong error message when no result are found when using a compliance filter
  webapp/sources/rudder/rudder-web/src/main/elm/sources/NodeCompliance/View.elm
Labels: qa: Can't merge

#5528 Fixes #24592: Allow technique id starting with a number
  policies/rudderc/src/backends/unix.rs
  policies/rudderc/src/backends/unix/ncf/method_call.rs
  policies/rudderc/src/ir/technique.rs
  policies/rudderc/src/technique.schema.json
  policies/rudderc/templates/technique.ps1.askama
  policies/rudderc/tests/cases/general/escaping/technique.ps1
  policies/rudderc/tests/cases/general/form/technique.ps1
  policies/rudderc/tests/cases/general/long_method_param_name/technique.ps1
  policies/rudderc/tests/cases/general/min/technique.ps1
  policies/rudderc/tests/cases/general/ntp/technique.ps1
  policies/rudderc/tests/cases/general/param_in_condition/technique.ps1
  policies/rudderc/tests/cases/general/reporting/technique.ps1
  policies/rudderc/tests/compile.rs
Labels: qa: Can't merge

#5495 Fixes #24466: when we search for a group in the search engine, the group page we arrive on is messed
  webapp/sources/rudder/rudder-web/src/main/elm/sources/Groups/Init.elm
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/node/Groups.scala
  webapp/sources/rudder/rudder-web/src/main/webapp/secure/nodeManager/groups.html
Labels: qa: Can't merge

#5541 Fixes #24590: Directive errors section is not consistent and always redirects to first tab
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/DirectiveEditForm.scala
Labels: qa: Can't merge

#5506 Fixes #24352: Plugin information is too empty when there is no plugin
  webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder-plugins.css
  webapp/sources/rudder/rudder-web/src/main/webapp/secure/plugins/pluginInformation.html
Labels: qa: Can't merge

#5477 Fixes #24416: Elm properties app is loaded multiple times
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/NodeGroupForm.scala
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/node/Groups.scala
  webapp/sources/rudder/rudder-web/src/main/webapp/secure/nodeManager/groups.html
  webapp/sources/rudder/rudder-web/src/main/webapp/templates-hidden/components/ComponentNodeProperties.html
  webapp/sources/rudder/rudder-web/src/main/webapp/templates-hidden/components/NodeGroupForm.html
Labels: qa: Can't merge

#5521 Fixes #24295: API export of groups doesn't export the categories as dependencies
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/NodeGroupRepository.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/ldap/LDAPNodeGroupRepository.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/ArchiveApi.scala
  webapp/sources/rudder/rudder-rest/src/test/resources/api/api_groups.yml
  webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/MockServices.scala
  webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/rest/ArchiveApiTest.scala
  webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/rest/RestTestSetUp.scala
  webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala
Labels: qa: Can't merge

#5544 Fixes #24421: system updates score details is empty when the node is up-to-date
  webapp/sources/rudder/rudder-web/src/main/elm/sources/SystemUpdateScore.elm
  webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder-compliance.scss
Labels: Ready for merge

#5507 Fixes #24408: Button for archiving/deleting reports is not visible
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/administration/DatabaseManagement.scala
Labels: Ready for merge
