Repository Normation/rudder, pull requests merged in 2024-07, with the labels that each got.

#5754 Fixes #25087: Remove unexpected interpretation choice for vars because it's not meaningful anymore
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/reports/ExecutionBatch.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/reports/ReportingServiceImpl.scala
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/repository/jdbc/ReportingServiceTest.scala
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/reports/CachedFindRuleNodeStatusReportsTest.scala
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/reports/ComplianceTest.scala
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/reports/ExecutionBatchTest.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/appconfig/ConfigService.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/SettingsApi.scala
  webapp/sources/rudder/rudder-rest/src/test/resources/api/api_settings.yml
  webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/administration/PropertiesManagement.scala
  webapp/sources/rudder/rudder-web/src/main/webapp/secure/administration/policyServerManagement.html
Labels: Ready for merge

#5741 Fixes #25042: Generation error logs are unreadable in the interface
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/comet/AsyncDeployment.scala
  webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder-main.css
Labels: qa: Can't merge

#5751 Fixes #25053: Error 500 when we visit for the first time the campaign page
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/campaigns/CampaignRepository.scala
Labels: Ready for merge

#5752 Fixes #25054: No documentation on built-in techniques
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/TechniqueEditForm.scala
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/configuration/DirectiveManagement.scala
  webapp/sources/rudder/rudder-web/src/main/webapp/secure/configurationManager/directiveManagement.html
  webapp/sources/rudder/rudder-web/src/main/webapp/templates-hidden/components/ComponentRuleEditForm.html
Labels: qa: Can't merge

#5765 Fixes #25120: Use node properties to decide how long compliance is valid
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/logger/DebugComplianceLogger.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/reports/NodeComplianceExpiration.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/reports/StatusReports.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/reports/execution/ReportsExecutionService.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/jdbc/ComplianceRepository.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/reports/ComplianceExpirationService.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/reports/ComputeNodeStatusReportService.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/reports/ExecutionBatch.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/reports/NodeChangesService.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/reports/NodeStatusReportRepository.scala
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/domain/reports/StatusReportTest.scala
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/reports/CachedFindRuleNodeStatusReportsTest.scala
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/reports/ComplianceExpirationServiceTest.scala
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/reports/ExecutionBatchTest.scala
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/reports/ReportingServiceUtilsTest.scala
  webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/MockServices.scala
  webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/services/ReportDisplayer.scala
Labels: qa: Can't merge

#5768 Fixes #25143: Make apache configuration easier to automatically split
  relay/sources/Makefile
  relay/sources/apache/rudder-vhost.conf
Labels: qa: Can't merge

#5769 Fixes #25091: Add VARIABLE_NAME to technique so that we can use valid parameter name in techniques
  policies/rudderc/src/backends/metadata.rs
  policies/rudderc/tests/cases/general/escaping/metadata.xml
  policies/rudderc/tests/cases/general/form/metadata.xml
  policies/rudderc/tests/cases/general/ntp/metadata.xml
  policies/rudderc/tests/cases/general/param_in_condition/metadata.xml
  policies/rudderc/tests/metadata/serialized.xml
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/cfclerk/domain/VariableAndSectionSpec.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/cfclerk/xmlparsers/CfclerkXmlConstants.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/cfclerk/xmlparsers/VariableSpecParser.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/ncf/TechniqueCompiler.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/write/BuildBundleSequence.scala
  webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/expected-share/testing_variables_in_conditions/1.0/metadata.xml
  webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/techniques/ncf_techniques/technique_any/1.0/metadata.xml
  webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/techniques/ncf_techniques/technique_any/2.0/metadata.xml
  webapp/sources/rudder/rudder-core/src/test/resources/configuration-repository/techniques/ncf_techniques/technique_by_Rudder/1.0/metadata.xml
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/cfclerk/domain/VariableTest.scala
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/cfclerk/services/DummyTechniqueRepository.scala
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/domain/policies/SectionValTest.scala
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/policies/NodeExpectedReportTest.scala
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/policies/RuleValServiceTest.scala
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/policies/TestJsEngine.scala
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/policies/TestNodeAndGlobalParameterLookup.scala
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/policies/write/PolicyAgregationTest.scala
  webapp/sources/rudder/rudder-web/src/test/scala/com/normation/rudder/web/services/Section2FieldServiceTest.scala
Labels: qa: Can't merge, Ready for merge

#5770 Fixes #25148: Rudderc fails to render "plain" variables on Windows
  policies/rudderc/src/backends/windows.rs
  policies/rudderc/src/ir/value.rs
  policies/rudderc/tests/cases/general/escaping/metadata.xml
  policies/rudderc/tests/cases/general/escaping/technique.ps1
Labels: qa: Can't merge

#5778 Fixes #25116: Add parameter to change maximum limit on a quicksearch
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/quicksearch/QuickSearchDomain.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/quicksearch/QuickSearchQueryParser.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/quicksearch/QuickSearchService.scala
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/quicksearch/QSRegexQueryParserTest.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/internal/RestQuicksearch.scala
Labels: Ready for merge

#5780 Fixes #24634: API to find usage of a node property in Directives
  webapp/sources/rudder/rudder-web/src/main/elm/sources/NodeProperties/ApiCalls.elm
  webapp/sources/rudder/rudder-web/src/main/elm/sources/NodeProperties/DataTypes.elm
  webapp/sources/rudder/rudder-web/src/main/elm/sources/NodeProperties/Init.elm
  webapp/sources/rudder/rudder-web/src/main/elm/sources/NodeProperties/View.elm
  webapp/sources/rudder/rudder-web/src/main/elm/sources/NodeProperties/ViewUtils.elm
  webapp/sources/rudder/rudder-web/src/main/elm/sources/Nodeproperties.elm
  webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder-datatable.css
  webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder-template.scss
Labels: Ready for merge

#5781 Fixes #25184: Missing header XMLHttpRequest for quicksearch call in find property usage
  webapp/sources/rudder/rudder-web/src/main/elm/sources/NodeProperties/ApiCalls.elm
  webapp/sources/rudder/rudder-web/src/main/elm/sources/NodeProperties/ViewUtils.elm
  webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder-template.scss
Labels: Ready for merge

#5784 Fixes #25190: Improve the error handling in the Windows techniques
  policies/rudderc/templates/technique.ps1.askama
  policies/rudderc/tests/cases/general/escaping/technique.ps1
  policies/rudderc/tests/cases/general/form/technique.ps1
  policies/rudderc/tests/cases/general/long_method_param_name/technique.ps1
  policies/rudderc/tests/cases/general/min/technique.ps1
  policies/rudderc/tests/cases/general/ntp/technique.ps1
  policies/rudderc/tests/cases/general/param_in_condition/technique.ps1
  policies/rudderc/tests/cases/general/policy_mode/technique.ps1
  policies/rudderc/tests/cases/general/reporting/technique.ps1
  policies/rudderc/tests/cases/general/variables/technique.ps1
Labels: Ready for merge

#5788 Fixes #25213: The policies Dockerfile does not fail when the rudder agent fails to install
  Jenkinsfile
  policies/Dockerfile
Labels: qa: Can't merge, Ready for merge

#5775 Fixes #25161: Node inventory hooks are are not working properly
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/inventory/PostCommits.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/nodes/NewNodeManager.scala
  webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala
Labels: Ready for merge

#5792 Fixes #25227: Don't update plugin password if nothing was given
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/plugins/PluginSettings.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/PluginApi.scala
  webapp/sources/rudder/rudder-web/src/main/elm/sources/Onboarding.elm
  webapp/sources/rudder/rudder-web/src/main/elm/sources/Onboarding/DataTypes.elm
  webapp/sources/rudder/rudder-web/src/main/elm/sources/Onboarding/Init.elm
  webapp/sources/rudder/rudder-web/src/main/elm/sources/Onboarding/JsonDecoder.elm
  webapp/sources/rudder/rudder-web/src/main/elm/sources/Onboarding/JsonEncoder.elm
  webapp/sources/rudder/rudder-web/src/main/elm/sources/Onboarding/View.elm
Labels: Ready for merge

#5793 Fixes #25228: Error when saving
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/plugins/PluginSettings.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/EndpointsDefinition.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/PluginApi.scala
  webapp/sources/rudder/rudder-web/src/main/elm/sources/Onboarding.elm
  webapp/sources/rudder/rudder-web/src/main/elm/sources/Onboarding/DataTypes.elm
  webapp/sources/rudder/rudder-web/src/main/elm/sources/Onboarding/Init.elm
  webapp/sources/rudder/rudder-web/src/main/elm/sources/Onboarding/JsonDecoder.elm
  webapp/sources/rudder/rudder-web/src/main/elm/sources/Onboarding/JsonEncoder.elm
  webapp/sources/rudder/rudder-web/src/main/elm/sources/Onboarding/View.elm
  webapp/sources/rudder/rudder-web/src/main/webapp/secure/administration/setup.html
Labels: Ready for merge

#5795 Fixes #25246: Unauthorized access to API should not be logged as error
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/ApiDatastructures.scala
Labels: Ready for merge
