Repository Normation/rudder, pull requests merged in 2024-02, with the labels that each got.

#5368 Fixes #24117: Missing policy generation status
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/users/User.scala
  webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/Boot.scala
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/comet/AsyncDeployment.scala
Labels: Ready for merge

#5375 Fixes #24131: rudder package unpacks scripts.txz in the wrong place
  relay/sources/rudder-package/src/archive.rs
Labels: Ready for merge

#5360 Fixes #24096: Add score on top of tabs
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/score/ComplianceScore.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/score/Score.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/score/SystemUpdateScore.scala
  webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/ShowNodeDetailsFromNode.scala
  webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder-compliance.scss
  webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder-node.scss
  webapp/sources/rudder/rudder-web/src/main/webapp/templates-hidden/server/server_details.html
Labels: Ready for merge

#5374 Fixes #24129: For delete API for node, add a message for node already deleted
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/servers/RemoveNodeService.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/NodeApi.scala
Labels: qa: Can't merge

#5382 Fixes #24152: Jstree links are broken
  webapp/sources/rudder/rudder-web/src/main/javascript/rudder/tree.js
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/services/DisplayNodeGroupTree.scala
Labels: qa: Can't merge

#5386 Fixes #24172: Active buttons no longer have shadow
  webapp/sources/rudder/rudder-web/src/main/elm/sources/GroupCompliance/ViewUtils.elm
  webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder-bootstrap.scss
Labels: qa: Can't merge, Ready for merge

#5387 Fixes #24177: Make spotless only check source of current project
  webapp/sources/pom.xml
Labels: qa: Can't merge, Ready for merge

#5298 Fixes #23968: Display a global view of group compliances
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/NodeGroupRepository.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/ldap/LDAPNodeGroupRepository.scala
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/MockServices.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/EndpointsDefinition.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/RoleApiMapping.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/ComplianceApi.scala
  webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/MockServices.scala
  webapp/sources/rudder/rudder-web/src/main/elm/sources/GroupRelatedRules/View.elm
  webapp/sources/rudder/rudder-web/src/main/elm/sources/Groups.elm
  webapp/sources/rudder/rudder-web/src/main/elm/sources/Groups/ApiCalls.elm
  webapp/sources/rudder/rudder-web/src/main/elm/sources/Groups/DataTypes.elm
  webapp/sources/rudder/rudder-web/src/main/elm/sources/Groups/Init.elm
  webapp/sources/rudder/rudder-web/src/main/elm/sources/Groups/JsonDecoder.elm
  webapp/sources/rudder/rudder-web/src/main/elm/sources/Groups/View.elm
  webapp/sources/rudder/rudder-web/src/main/elm/sources/Groups/ViewGroupsTable.elm
  webapp/sources/rudder/rudder-web/src/main/elm/sources/Groups/ViewUtils.elm
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/NodeGroupForm.scala
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/node/Groups.scala
  webapp/sources/rudder/rudder-web/src/main/webapp/secure/nodeManager/groups.html
Labels: qa: Can't merge

#5383 Fixes #24165: Add Score in nodes table
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/score/ScoreService.scala
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/reports/CachedFindRuleNodeStatusReportsTest.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/NodeApi.scala
  webapp/sources/rudder/rudder-web/src/main/javascript/rudder/rudder-datatable.js
  webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/services/SrvGrid.scala
  webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder-compliance.scss
Labels: Ready for merge

#5395 Fixes #24170: The active tab indicator no longer works
  webapp/sources/rudder/rudder-web/src/main/elm/sources/DirectiveCompliance/View.elm
  webapp/sources/rudder/rudder-web/src/main/elm/sources/Editor/ViewTechnique.elm
  webapp/sources/rudder/rudder-web/src/main/elm/sources/GroupCompliance/View.elm
  webapp/sources/rudder/rudder-web/src/main/elm/sources/Rules/ViewCategoryDetails.elm
  webapp/sources/rudder/rudder-web/src/main/elm/sources/Rules/ViewRuleDetails.elm
  webapp/sources/rudder/rudder-web/src/main/javascript/rudder/rudder.js
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/NodeGroupCategoryForm.scala
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/NodeGroupForm.scala
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/ShowNodeDetailsFromNode.scala
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/services/DisplayNode.scala
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/services/ReportDisplayer.scala
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/node/PendingHistoryGrid.scala
  webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder-bootstrap.scss
  webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder-groups.css
  webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder-main.css
  webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder-node.scss
  webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder-template.scss
  webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder.css
  webapp/sources/rudder/rudder-web/src/main/webapp/secure/nodeManager/manageNewNode.html
  webapp/sources/rudder/rudder-web/src/main/webapp/templates-hidden/components/ComponentDirectiveEditForm.html
  webapp/sources/rudder/rudder-web/src/main/webapp/templates-hidden/components/ComponentRuleEditForm.html
  webapp/sources/rudder/rudder-web/src/main/webapp/templates-hidden/components/NodeGroupForm.html
  webapp/sources/rudder/rudder-web/src/main/webapp/templates-hidden/server/server_details.html
Labels: qa: Can't merge, Ready for merge

#5403 Fixes #24204: Hooks page looks broken since bootstrap 5 update
  webapp/sources/rudder/rudder-web/src/main/elm/sources/Hooks.elm
  webapp/sources/rudder/rudder-web/src/main/elm/sources/Hooks/Init.elm
  webapp/sources/rudder/rudder-web/src/main/elm/sources/Hooks/View.elm
  webapp/sources/rudder/rudder-web/src/main/elm/sources/Hooks/ViewUtils.elm
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/services/DisplayNode.scala
  webapp/sources/rudder/rudder-web/src/main/style/rudder/_rudder-variables.scss
  webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder-hooks.scss
  webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder-template.scss
  webapp/sources/rudder/rudder-web/src/main/webapp/secure/administration/hooksManagement.html
  webapp/sources/rudder/rudder-web/src/main/webapp/secure/administration/policyServerManagement.html
Labels: Ready for merge

#5398 Fixes #24150: when we have conditions on blocks, the condition text is not correctly positionned when the block is opened
  webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder-technique-editor.css
Labels: qa: Can't merge

#5407 Fixes #24226: rudderc canonifies already canonified condition expression resulting in loss of logic operators such as ) and |
  policies/rudderc/src/backends/unix/cfengine/promise.rs
  policies/rudderc/tests/cases/general/escaping/technique.cf
  policies/rudderc/tests/cases/general/form/technique.cf
  policies/rudderc/tests/cases/general/ntp/technique.cf
  policies/rudderc/tests/cases/general/param_in_condition/technique.cf
  policies/rudderc/tests/cases/general/reporting/technique.cf
Labels: qa: Can't merge

#5404 Fixes #24207: We need a setting to force change request validation
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/appconfig/ConfigService.scala
Labels: qa: Can't merge, Ready for merge

#5409 Fixes #24238: Rudder-package should log the package scripts outputs and errors
  relay/sources/rudder-pkg/lib/rudder-pkg/rudderPkg.py
  relay/sources/rudder-pkg/lib/rudder-pkg/rudderPkgUtils.py
Labels: qa: Can't merge

#5391 Fixes #24140: Have a source of known-tenants in rudder-core
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/facts/nodes/NodeFact.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/facts/nodes/NodeFactRepository.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/tenants/TenantService.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/tenants/Tenants.scala
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/MockServices.scala
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/facts/nodes/TestCoreNodeFactInventory.scala
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/facts/nodes/TestFullInventoryRepoProxy.scala
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/facts/nodes/TestSaveInventory.scala
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/repository/jdbc/ReportingServiceTest.scala
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/queries/TestNodeFactQueryProcessor.scala
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/reports/CachedFindRuleNodeStatusReportsTest.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/ApiDatastructures.scala
  webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala
  webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderUserDetailsFile.scala
  webapp/sources/rudder/rudder-web/src/test/scala/bootstrap/liftweb/RudderUserDetailsTest.scala
Labels: qa: Can't merge

#5415 Fixes #24285: Empty role in users file is logged as warning
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/Authorizations.scala
Labels: qa: Can't merge, Ready for merge
