Repository Normation/rudder, pull requests merged in 2024-12, with the labels that each got.

#6055 Fixes #25705: search on event log must also search on event type
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/internal/EventLogAPI.scala
Labels: qa: Can't merge, Ready for merge

#6046 Fixes #25960: Remove unused and duplicate rest extractor lift-json methods
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/apidata/JsonQueryObjects.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/config/UserPropertyService.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/json/JsonExctractorUtils.scala
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/nodes/TestMergeGroupProperties.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/RestExtractorService.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/RestUtils.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/RudderJsonRequest.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/DirectiveApi.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/GroupsApi.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/NodeApi.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/RuleApi.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/SettingsApi.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/TechniqueApi.scala
  webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/rest/RestTestSetUp.scala
  webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/TechniqueEditForm.scala
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/popup/CreateCategoryOrGroupPopup.scala
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/popup/CreateCloneDirectivePopup.scala
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/popup/CreateCloneGroupPopup.scala
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/popup/CreateOrUpdateGlobalParameterPopup.scala
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/popup/CreateRulePopup.scala
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/popup/GiveReasonPopup.scala
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/popup/ModificationValidationPopup.scala
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/popup/RuleModificationValidationPopup.scala
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/administration/TechniqueLibraryManagement.scala
Labels: qa: Can't merge, Ready for merge

#6007 Fixes #25842: scoreService and scoreServiceManager are not initialized where they should
  webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala
Labels: qa: Can't merge

#6051 Fixes #25973: Acceptation error with new node on hostname duplication is not hightlitghed
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/node/AcceptNode.scala
Labels: qa: Can't merge

#6073 Fixes #26017: Migrate old internal EventLog APIs to zio-json
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/logger/ApplicationLogger.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/json/JsonExctractorUtils.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/ApiAuthorization.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/EndpointsDefinition.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/RestExtractorService.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/RoleApiMapping.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/data/EventLog.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/internal/EventLogAPI.scala
  webapp/sources/rudder/rudder-rest/src/test/resources/api/api_eventlogs.yml
  webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/rest/RestTestSetUp.scala
  webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/rest/TestRestFromFileDef.scala
  webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/Boot.scala
  webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala
Labels: Ready for merge

#6069 Fixes #25824: Properties tab : Non-rearrangement of the pop-ups
  webapp/sources/rudder/rudder-web/src/main/elm/sources/NodeProperties/ViewUtils.elm
  webapp/sources/rudder/rudder-web/src/main/elm/sources/Nodeproperties.elm
  webapp/sources/rudder/rudder-web/src/main/elm/sources/Nodes/ApiCalls.elm
  webapp/sources/rudder/rudder-web/src/main/elm/sources/Nodes/DataTypes.elm
  webapp/sources/rudder/rudder-web/src/main/elm/sources/Nodes/Init.elm
  webapp/sources/rudder/rudder-web/src/main/elm/sources/Nodes/JsonDecoder.elm
  webapp/sources/rudder/rudder-web/src/main/elm/sources/Nodes/JsonEncoder.elm
  webapp/sources/rudder/rudder-web/src/main/elm/sources/Nodes/View.elm
  webapp/sources/rudder/rudder-web/src/main/elm/sources/Nodes/ViewUtils.elm
  webapp/sources/rudder/rudder-web/src/main/javascript/rudder/rudder.js
  webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder-main.scss
Labels: qa: Can't merge

#6067 Fixes #25996: Refuse inventory too far from "now"
  webapp/sources/ldap-inventory/inventory-fusion/src/main/scala/com/normation/inventory/provisioning/fusion/PreInventoryParserCheckConsistency.scala
  webapp/sources/ldap-inventory/inventory-fusion/src/main/scala/com/normation/inventory/provisioning/fusion/PreInventoryParserCheckInventoryAge.scala
  webapp/sources/ldap-inventory/inventory-fusion/src/test/scala/com/normation/inventory/provisioning/fusion/TestPreParsingDate.scala
  webapp/sources/rudder/rudder-web/src/main/resources/configuration.properties.sample
  webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala
Labels: qa: Can't merge

#5773 Fixes #25156: rudder-package fails to parse old plugin version numbers, breaking the upgrade
  relay/sources/rudder-package/src/versions.rs
Labels: qa: Can't merge, Ready for merge

#6082 Fixes #26002: The directive page is much slower with Rudder 8.1 than in 7.3
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/configuration/DirectiveManagement.scala
Labels: qa: Can't merge

#6083 Fixes #26064: Group query select attribute has different name in create and update payload
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/apidata/JsonQueryObjects.scala
  webapp/sources/rudder/rudder-rest/src/test/resources/api/api_groups.yml
Labels: qa: Can't merge, Ready for merge

#6050 Fixes #25669:
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/appconfig/RudderWebProperty.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/appconfig/ConfigService.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/EndpointsDefinition.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/RoleApiMapping.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/SettingsApi.scala
  webapp/sources/rudder/rudder-web/src/main/resources/configuration.properties.sample
  webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/AppConfigAuth.scala
Labels: qa: Can't merge

#6087 Fixes #26071: Default configuration for user API tokens should be disabled for OIDC and OAuth2
  webapp/sources/rudder/rudder-web/src/main/resources/configuration.properties.sample
  webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/AppConfigAuth.scala
Labels: qa: Can't merge

#6094 Fixes #26082: Use sequoia in rudder-package
  Cargo.lock
  Jenkinsfile
  policies/techniques/anssi_bp_028/technique.yml
  policies/techniques/anssi_bp_028/test.yml
  relay/sources/rudder-package/Cargo.toml
  relay/sources/rudder-package/Dockerfile
  relay/sources/rudder-package/src/lib.rs
  relay/sources/rudder-package/src/repository.rs
  relay/sources/rudder-package/src/signature.rs
  relay/sources/rudder-package/tools/rudder_plugins_key.gpg
Labels: qa: Can't merge

#6071 Fixes #26022: Status should not be on error when there is technique compilator error on disable techniques
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/ncf/TechniqueCompilationCache.scala
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/ncf/TestTechniqueCompilationCache.scala
  webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/comet/AsyncDeployment.scala
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/TechniqueEditForm.scala
  webapp/sources/rudder/rudder-web/src/test/scala/bootstrap/liftweb/checks/migration/TestMigrateJsonTechniquesToYaml.scala
Labels: qa: Can't merge

#6025 Fixes #25841: Create an instance id on each root server
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/servers/InstanceIdService.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/servers/PolicyServerData.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/servers/ServerSummaryService.scala
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/servers/TestInstanceIdService.scala
  webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala
  webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/checks/action/CreateInstanceUuid.scala
  webapp/sources/rudder/rudder-web/src/test/scala/bootstrap/liftweb/checks/action/TestCreateInstanceUuid.scala
Labels: Ready for merge

#6044 Fixes #25948: Score breakdown has inconsistent numbers
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/facts/nodes/NodeFactChangeEventCallback.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/inventory/PostCommits.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/score/GlobalScoreRepository.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/score/ScoreRepository.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/score/ScoreService.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/nodes/NewNodeManager.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/nodes/RemoveNodeService.scala
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/MockServices.scala
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/repository/jdbc/ReportingServiceTest.scala
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/score/ScoreServiceTest.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/NodeApi.scala
  webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/HomePage.scala
Labels: qa: Can't merge

#6097 Fixes #26075: Trying to save a group with empty criteria removes all entries
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/ldap/LDAPDiffMapper.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/ldap/LDAPEntityMapper.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/queries/CmdbQueryParser.scala
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/MockServices.scala
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/repository/ldap/GlobalParamMigration61Test.scala
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/marshalling/TestXmlUnserialisation.scala
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/queries/TestNodeFactQueryProcessor.scala
  webapp/sources/rudder/rudder-rest/src/test/resources/api/api_groups.yml
  webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/SearchNodeComponent.scala
Labels: qa: Can't merge
