Repository Normation/rudder, pull requests merged in 2025-06, with the labels that each got.

#6354 Fixes #26823: “Users” standard technique : Fails setting secondary groups when already correct.
  policies/lib/tree/20_cfe_basics/cfengine/paths.cf
Labels: Ready for merge

#6414 Fixes #27011: JGit vulnerability (XXE)
  webapp/sources/pom.xml
Labels: qa: Can't merge, Ready for merge

#6428 Fixes #26810: rudder agent check complains “egrep: warning: egrep is obsolescent; using grep -E”
  policies/lib/tests/acceptance/30_generic_methods/command_execution.cf
  policies/lib/tests/acceptance/default.cf.sub
  policies/lib/tests/acceptance/testall
  policies/lib/tests/quick/all_shell_test_should_be_set_e.sh
  policies/lib/tests/quick/bundles_starting_with_underscore_must_not_modify_the_system.sh
  policies/lib/tests/quick/dont_use_perms_on_group_root.sh
  policies/lib/tree/10_ncf_internals/modules/packages/freebsd_ports
  policies/lib/tree/20_cfe_basics/cfengine/packages.cf
  policies/lib/tree/20_cfe_basics/services.cf
Labels: Ready for merge

#6423 Fixes #27035: ReportType json serialization in base is incorrect
  webapp/sources/pom.xml
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/reports/ReportType.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/reports/StatusReports.scala
  webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/domain/reports/JsonPostresqlSerializationTest.scala
Labels: qa: Can't merge

#6425 Fixes #27005: License setup should update the list of plugins
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/plugins/settings/PluginSettings.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/data/Plugin.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/internal/PluginInternalApi.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/PluginApi.scala
  webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/rest/TestRestPluginInfo.scala
  webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala
Labels: qa: Can't merge

#6436 Fixes #27051: Event logs rollback does not do any action
  webapp/sources/rudder/rudder-web/src/main/javascript/rudder/rudder-datatable.js
  webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder-menu.scss
Labels: qa: Can't merge

#6440 Fixes #27065: double path in parent code
  policies/lib/tree/30_generic_methods/file_from_template_jinja2.cf
Labels: Ready for merge

#6443 Fixes #27074: rpmvercmp can be called from its old path
  policies/lib/tree/20_cfe_basics/packages.cf
Labels: Ready for merge

#6421 Fixes #27034: Switch to Scala 3
  webapp/sources/.scalafix.conf
  webapp/sources/.scalafmt.conf
  webapp/sources/ldap-inventory/inventory-api/src/main/scala/com/normation/inventory/domain/JsonSerializers.scala
  webapp/sources/ldap-inventory/inventory-repository/pom.xml
  webapp/sources/ldap-inventory/inventory-repository/src/main/scala/com/normation/inventory/ldap/core/FullInventoryRepositoryImpl.scala
  webapp/sources/pom.xml
  webapp/sources/rudder/rudder-core/pom.xml
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/cfclerk/services/impl/GitTechniqueReader.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/cfclerk/services/impl/TechniqueRepositoryImpl.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/apidata/JsonResponseObjects.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/batch/AutomaticReportsCleaner.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/reports/ExpectedReports.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/reports/StatusReports.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/inventory/InventoryFileWatcher.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/jdbc/ExpectedReportsJdbcRepository.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/marshalling/XmlUnserialisationImpl.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/JavascriptEngine.scala
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/repository/jdbc/GitModificationRepositoryTest.scala
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/repository/jdbc/ReportsTest.scala
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/policies/TestJsEngine.scala
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/reports/ReportingServiceUtilsTest.scala
  webapp/sources/rudder/rudder-rest/pom.xml
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/Authorizations.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/EndpointsDefinition.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/internal/EventLogAPI.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/DirectiveApi.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/SettingsApi.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/web/model/FilePermissions.scala
  webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/domain/reports/JsonPostresqlSerializationTest.scala
  webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/rest/ArchiveApiTest.scala
  webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/rest/RestTestSetUp.scala
  webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/rest/TraitTestApiFromYamlFiles.scala
  webapp/sources/rudder/rudder-templates-cli/pom.xml
  webapp/sources/rudder/rudder-web/pom.xml
  webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/Boot.scala
  webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala
  webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/checks/endconfig/consistency/CheckRudderGlobalParameter.scala
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/plugins/RudderPluginJson.scala
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/popup/ModificationValidationPopup.scala
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/services/NodeGrid.scala
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/node/Node.scala
  webapp/sources/rudder/rudder-web/src/test/scala/bootstrap/liftweb/RudderUserDetailsTest.scala
  webapp/sources/rudder/rudder-web/src/test/scala/bootstrap/liftweb/checks/earlyconfig/db/TestMigrateTableReportsExecution.scala
  webapp/sources/utils/pom.xml
  webapp/sources/utils/src/test/scala/com/normation/utils/EnumLaws.scala
Labels: Ready for merge

#6455 Fixes #27094: Improving the clarity of error messages in the template module.
  policies/module-types/template/src/cli.rs
  policies/module-types/template/src/lib.rs
Labels: Ready for merge

#6444 Fixes #27067: Error when parsing date for last user loggin awaited format is EEE MMM dd HH:mm
  webapp/sources/ldap-inventory/inventory-fusion/src/main/scala/com/normation/inventory/provisioning/fusion/FusionInventoryParser.scala
  webapp/sources/ldap-inventory/inventory-fusion/src/test/resources/fusion-inventories/9.0/a79d82c6-4baf-4866-801c-6883d07559c3.ocs
  webapp/sources/ldap-inventory/inventory-fusion/src/test/resources/fusion-inventories/9.0/a79d82c6-4baf-4866-801c-6883d07559c3.ocs.sign
  webapp/sources/ldap-inventory/inventory-fusion/src/test/scala/com/normation/inventory/provisioning/fusion/TestReportParsing.scala
Labels: Ready for merge

#6459 Fixes #27107: Still missing cats-effect-std_3
  webapp/sources/pom.xml
  webapp/sources/rudder/rudder-core/pom.xml
  webapp/sources/rudder/rudder-web/pom.xml
Labels: Ready for merge

#6442 Fixes #27028: Improve error messages and reporting in augeas module
  Cargo.lock
  policies/Dockerfile
  policies/lib/tree/20_cfe_basics/files.cf
  policies/lib/tree/30_generic_methods/file_augeas.cf
  policies/module-types/augeas/Cargo.toml
  policies/module-types/augeas/src/augeas.rs
  policies/module-types/augeas/src/bin/raugtool.rs
  policies/module-types/augeas/src/dsl/comparator.rs
  policies/module-types/augeas/src/dsl/interpreter.rs
  policies/module-types/augeas/src/dsl/parser.rs
  policies/module-types/augeas/src/dsl/raugeas.pest
  policies/module-types/augeas/src/dsl/script.rs
  policies/module-types/augeas/tests/module.rs
  policies/rudderc/docs/src/modules/augeas.md
Labels: qa: Can't merge, Ready for merge
