Repository Normation/rudder, pull requests merged in 2025-03, with the labels that each got.

#6221 Fixes #26455: Changes for scala 3 migration - branch 8.3
  webapp/sources/pom.xml
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/plugins/PluginData.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/reports/ComplianceLevel.scala
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/cfclerk/domain/VariableTest.scala
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/hooks/HooksTest.scala
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/metrics/NodeCountHistorizationTest.scala
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/ncf/TestTechniqueCompilationCache.scala
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/repository/jdbc/ReportsTest.scala
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/score/ComplianceScoreEventHandlerTest.scala
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/policies/RuleValServiceTest.scala
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/reports/CachedFindRuleNodeStatusReportsTest.scala
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/servers/TestInstanceIdService.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/ApiAccountApi.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/users/UserManagement.scala
  webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/rest/CampaignApiTest.scala
  webapp/sources/rudder/rudder-web/src/test/scala/bootstrap/liftweb/checks/endconfig/migration/TestMigrateJsonTechniquesToYaml.scala
  webapp/sources/scala-ldap/src/test/scala/com/normation/ldap/sdk/LoadDemoDataTest.scala
Labels: Ready for merge

#6223 Fixes #26459: Missing commit in parent PR
  webapp/sources/pom.xml
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/cfclerk/services/impl/TechniqueRepositoryImpl.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/batch/AutomaticReportsCleaner.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/facts/nodes/NodeFact.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/properties/MergeNodeProperties.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/healthcheck/HealthcheckNotificationService.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/reports/NodeStatusReportRepository.scala
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/domain/queries/NodeQueryCriteriaDataTest.scala
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/domain/reports/StatusReportTest.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/RudderJsonResponse.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/data/Compliance.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/ArchiveApi.scala
  webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/rest/TraitTestApiFromYamlFiles.scala
  webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/checks/earlyconfig/ldap/CheckAddSpecialNodeGroupsDescription.scala
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/services/AsyncComplianceService.scala
  webapp/sources/rudder/rudder-web/src/test/scala/com/normation/plugins/RudderPluginJsonTest.scala
  webapp/sources/rudder/rudder-web/src/test/scala/com/normation/rudder/web/services/ReportLineTest.scala
  webapp/sources/utils/src/test/scala/com/normation/ZioCommonsTest.scala
Labels: qa: Can't merge, Ready for merge

#6228 Fixes #26481: Add 8.3 api doc and 8.2 api deprecation
  webapp/sources/api-doc/openapi.src.yml
  webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala
Labels: Ready for merge

#6224 Fixes #26464: Stackoverflow in NodeStatusReports event computing
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/reports/ComputeNodeStatusReportService.scala
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/reports/CachedFindRuleNodeStatusReportsTest.scala
Labels: qa: Can't merge

#6235 Fixes #26487: Global properties generated by security benchmarks are displayed on Global Properties GUI
  webapp/sources/rudder/rudder-core/src/main/resources/ldap/rudder.schema
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/RudderLDAPConstants.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/properties/Properties.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/ldap/LDAPEntityMapper.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/marshalling/XmlUnserialisationImpl.scala
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/MockServices.scala
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/repository/ldap/GlobalParamMigration61Test.scala
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/nodes/TestMergeGroupProperties.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/ParametersApi.scala
  webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/rest/TestInheritedProperties.scala
  webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/checks/endconfig/consistency/CheckRudderGlobalParameter.scala
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/popup/CreateOrUpdateGlobalParameterPopup.scala
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/configuration/ParameterManagement.scala
Labels: qa: Can't merge

#6241 Fixes #26513: makes agent template module compile on windows
  policies/rudder-module-type/src/lib.rs
Labels: Ready for merge

#6222 Fixes #26264: The refresh button from the nodes webpage change the list of nodes in the other tab
  webapp/sources/rudder/rudder-web/src/main/javascript/rudder/rudder-datatable.js
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/services/SrvGrid.scala
Labels: qa: Can't merge

#6239 Fixes #26503: API documentation for API account rest API
  webapp/sources/api-doc/code_samples/curl/api-accounts/all.sh
  webapp/sources/api-doc/code_samples/curl/api-accounts/create.sh
  webapp/sources/api-doc/code_samples/curl/api-accounts/delete.sh
  webapp/sources/api-doc/code_samples/curl/api-accounts/get.sh
  webapp/sources/api-doc/code_samples/curl/api-accounts/regenerate.sh
  webapp/sources/api-doc/code_samples/curl/api-accounts/update.sh
  webapp/sources/api-doc/components/parameters/api-account-id.yml
  webapp/sources/api-doc/components/schemas/api-account-new.yml
  webapp/sources/api-doc/components/schemas/api-account-update.yml
  webapp/sources/api-doc/components/schemas/api-account.yml
  webapp/sources/api-doc/openapi.src.yml
  webapp/sources/api-doc/paths/api-accounts/all.yml
  webapp/sources/api-doc/paths/api-accounts/id.yml
  webapp/sources/api-doc/paths/api-accounts/regenerate-token.yml
Labels: qa: Can't merge

#6242 Fixes #26512: rudderc generate invalid method call when using methods that are not compatible with Linux
  policies/rudderc/src/backends/unix/ncf/method_call.rs
Labels: Ready for merge

#6234 Fixes #26465: Rejected inventory with `dummy-node-id` when version missing version section in SOFTWARE/RUDDER
  webapp/sources/ldap-inventory/inventory-fusion/src/main/scala/com/normation/inventory/provisioning/fusion/FusionInventoryParser.scala
  webapp/sources/ldap-inventory/inventory-fusion/src/test/resources/fusion-inventories/WIN-2017-rudder-4-1.ocs
  webapp/sources/ldap-inventory/inventory-fusion/src/test/resources/fusion-inventories/WIN-AI8CLNPLOV5-2014-06-20-18-15-49.ocs
  webapp/sources/ldap-inventory/inventory-fusion/src/test/resources/fusion-inventories/cpus-count.ocs
  webapp/sources/ldap-inventory/inventory-fusion/src/test/resources/fusion-inventories/freebsd-2015-10-25-23-42-29.ocs
  webapp/sources/ldap-inventory/inventory-fusion/src/test/resources/fusion-inventories/mint.ocs
  webapp/sources/ldap-inventory/inventory-fusion/src/test/resources/fusion-inventories/rudder-tag/debian-no-security-token.ocs
  webapp/sources/ldap-inventory/inventory-fusion/src/test/resources/fusion-inventories/rudder-tag/invalid-hostname-localhost-alternative-error.ocs
  webapp/sources/ldap-inventory/inventory-fusion/src/test/resources/fusion-inventories/rudder-tag/invalid-hostname-localhost-alternative-ok.ocs
  webapp/sources/ldap-inventory/inventory-fusion/src/test/resources/fusion-inventories/rudder-tag/invalid-hostname-localhost.ocs
  webapp/sources/ldap-inventory/inventory-fusion/src/test/resources/fusion-inventories/rudder-tag/minimal-two-agents-fails.ocs
  webapp/sources/ldap-inventory/inventory-fusion/src/test/resources/fusion-inventories/sovma136-2014-02-10-07-13-43.ocs
  webapp/sources/ldap-inventory/inventory-fusion/src/test/resources/fusion-inventories/virtual-memory-more-than-2to.ocs
  webapp/sources/ldap-inventory/inventory-fusion/src/test/resources/fusion-inventories/virtuozzo.ocs
  webapp/sources/ldap-inventory/inventory-fusion/src/test/scala/com/normation/inventory/provisioning/fusion/TestPreParsing.scala
  webapp/sources/ldap-inventory/inventory-fusion/src/test/scala/com/normation/inventory/provisioning/fusion/TestReportParsing.scala
Labels: qa: Can't merge

#6249 Fixes #26535: prettify parameter is ignored in API calls
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/RudderJsonResponse.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/LiftApiDispatcher.scala
Labels: qa: Can't merge

#6230 Fixes #26493: rudder package update never test nor use the crendentials
  relay/sources/rudder-package/src/repository.rs
Labels: qa: Can't merge

#6270 Fixes #26588: Use 8.3 package in 9.0 tests for now
  Jenkinsfile
Labels: Ready for merge

#6268 Fixes #25936: Port condition_from methods to log v4+
  policies/lib/tests/integration/condition_from_expression_test.rs
  policies/lib/tests/integration/condition_from_variable_existence_test.rs
  policies/lib/tests/integration/condition_from_variable_match_test.rs
  policies/lib/tests/integration/mod.rs
  policies/lib/tests/testlib/given.rs
  policies/lib/tests/testlib/method_to_test.rs
  policies/lib/tests/testlib/test_result.rs
  policies/lib/tree/30_generic_methods/condition_from_expression.cf
  policies/lib/tree/30_generic_methods/condition_from_expression_persistent.cf
  policies/lib/tree/30_generic_methods/condition_from_variable_existence.cf
  policies/lib/tree/30_generic_methods/condition_from_variable_match.cf
  policies/lib/tree/30_generic_methods/condition_once.cf
  policies/lib/tree/30_generic_methods/directory_absent.cf
Labels: Ready for merge

#6275 Fixes #26593: Fallback on gpgv on SLES
  relay/sources/Makefile
  relay/sources/rudder-package/Cargo.toml
  relay/sources/rudder-package/Makefile
  relay/sources/rudder-package/src/lib.rs
  relay/sources/rudder-package/src/repository.rs
  relay/sources/rudder-package/src/signature.rs
  relay/sources/rudder-package/src/signature/gpgv.rs
  relay/sources/rudder-package/src/signature/sequoia.rs
  relay/sources/rudder-package/tools/rudder_plugins_key.asc
  relay/sources/rudder-package/tools/rudder_plugins_key.gpg
Labels: qa: Can't merge, Ready for merge

#6278 Fixes #26532: Menu color leads to unclarity of meaning
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/BootstrapMenu.scala
  webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder-menu.scss
Labels: Ready for merge

#6288 Fixes #26544: SearchNodes page in Rudder : Error 404
  webapp/sources/rudder/rudder-web/src/main/javascript/rudder/homePage.js
Labels: qa: Can't merge, Ready for merge

#6283 Fixes #26614: Adding Ansible compatible filters for minijinja engine
  Cargo.lock
  policies/module-types/template/Cargo.toml
  policies/module-types/template/README.md
  policies/module-types/template/src/cli.rs
  policies/module-types/template/src/lib.rs
  policies/module-types/template/src/minijinja_filters.rs
  policies/module-types/template/tests/cli.rs
  policies/module-types/template/tests/minijinja.rs
Labels: qa: Can't merge, Ready for merge

#6289 Fixes #26630: Dubius vertical alignement in generic method
  webapp/sources/rudder/rudder-web/src/main/elm/sources/Editor/ViewMethod.elm
  webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder-technique-editor.scss
Labels: Ready for merge

#6294 Fixes #26646: Upmerge of compliance by directive change breaks 8.3
  webapp/sources/rudder/rudder-rest/src/test/resources/api/api_compliance.yml
Labels: Ready for merge
