Repository Normation/rudder, pull requests merged in 2025-10, with the labels that each got.

#6604 Fixes #27585: Test the command_execution_options generic method
  policies/lib/tests/integration/command_execution_options_test.rs
  policies/lib/tests/integration/mod.rs
  policies/lib/tests/quick/ordering.pl
  policies/lib/tree/20_cfe_basics/common.cf
  policies/lib/tree/30_generic_methods/command_execution_options.cf
  policies/module-types/commands/src/lib.rs
Labels: qa: Can't merge

#6635 Fixes #27674: Inconsistency in campaigneventstate between init and DB migration
  webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/checks/earlyconfig/db/MigrateTableCampaignEvents.scala
Labels: Ready for merge

#6637 Fixes #27684: Pin the typos-cli version
  ci/common.Dockerfile
  policies/rudderc/src/backends/windows/test.rs
  relay/sources/rudder-package/src/repository.rs
Labels: qa: Can't merge, Ready for merge

#6638 Fixes #27683: Error with command_execution_results but everything looks ok
  policies/module-types/commands/src/lib.rs
Labels: qa: Can't merge, Ready for merge

#6611 Fixes #27574: Post-hooks for campaigns should be executed even even if pre-hooks are in failure
  webapp/sources/rudder/rudder-core/src/main/resources/hooks.d/campaigns/hook-template
  webapp/sources/rudder/rudder-core/src/main/resources/hooks.d/campaigns/readme.adoc
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/campaigns/CampaignEventRepository.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/campaigns/CampaignHooksService.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/campaigns/CampaignOrchestrationLogic.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/campaigns/DataTypes.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/hooks/RunHooks.scala
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/campaign/CampaignOrchestrationLogicTest.scala
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/hooks/HooksTest.scala
Labels: qa: Can't merge
