Repository Normation/rudder, pull requests merged in 2025-04, with the labels that each got.

#6300 Fixes #26652: Compliance repeated when using the new “foreach” loops
  policies/rudderc/src/ir/technique.rs
  policies/rudderc/tests/cases/general/loops/metadata.xml
  policies/rudderc/tests/cases/general/loops/technique.cf
  policies/rudderc/tests/cases/general/loops/technique.ps1
  policies/rudderc/tests/cases/general/loops_with_main_branch_without_condition/metadata.xml
  policies/rudderc/tests/cases/general/loops_with_main_branch_without_condition/technique.cf
  policies/rudderc/tests/cases/general/loops_with_main_branch_without_condition/technique.ps1
Labels: qa: Can't merge, Ready for merge

#6303 Fixes #26429: Changing the system group category hierarchy breaks Rudder
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/GroupsApi.scala
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/NodeGroupCategoryForm.scala
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/NodeGroupForm.scala
Labels: qa: Can't merge, Ready for merge

#6307 Fixes #26684: Inventory trigger method broken on Linux
  policies/lib/tree/30_generic_methods/rudder_inventory_trigger.cf
Labels: qa: Can't merge, Ready for merge

#6302 Fixes #26675: Error in documentation /api/changeRequests response data
  webapp/sources/api-doc/paths/change-requests/accept.yml
  webapp/sources/api-doc/paths/change-requests/all.yml
  webapp/sources/api-doc/paths/change-requests/id.yml
Labels: Ready for merge

#6304 Fixes #26680: When the menu is collapsed, category titles have a transparent background.
  webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder-menu.scss
Labels: qa: Can't merge, Ready for merge

#6316 Fixes #26715: Add a mechanism to bypass plugin indexing in the public repositories
  relay/sources/rudder-package/src/plugin.rs
Labels: qa: Can't merge

#6319 Fixes #26732: Migrate methods to logger v4
  policies/lib/tests/integration/file_content_test.rs
  policies/lib/tests/integration/mod.rs
  policies/lib/tests/testlib/method_to_test.rs
  policies/lib/tree/30_generic_methods/environment_variable.cf
  policies/lib/tree/30_generic_methods/file_content.cf
  policies/lib/tree/30_generic_methods/file_from_local_source_recursion.cf
  policies/lib/tree/30_generic_methods/file_from_template_jinja2.cf
  policies/lib/tree/30_generic_methods/file_lines_present.cf
Labels: qa: Can't merge, Ready for merge

#6321 Fixes #26650: Technique loop copy box pastes wrong value
  webapp/sources/rudder/rudder-web/src/main/elm/sources/Editor/ViewTabForeach.elm
Labels: qa: Can't merge

#6324 Fixes #26106: Sometimes when we click on an element (technique or rule), the whole page reloads
  webapp/sources/rudder/rudder-web/src/main/elm/sources/Editor/ViewTechniqueList.elm
  webapp/sources/rudder/rudder-web/src/main/elm/sources/GroupRelatedRules/View.elm
  webapp/sources/rudder/rudder-web/src/main/elm/sources/Groups/View.elm
  webapp/sources/rudder/rudder-web/src/main/elm/sources/Rules/View.elm
  webapp/sources/rudder/rudder-web/src/main/elm/sources/Rules/ViewTabContent.elm
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/node/Groups.scala
  webapp/sources/rudder/rudder-web/src/main/webapp/secure/configurationManager/ruleManagement.html
  webapp/sources/rudder/rudder-web/src/main/webapp/secure/configurationManager/techniqueEditor.html
Labels: qa: Can't merge

#6315 Fixes #26707: Upgrade spring security dependency to correct CVE-2025-22228
  webapp/sources/pom.xml
Labels: qa: Can't merge

#6299 Fixes #26679: Remove leftover apache config backup files
  relay/sources/rudder-relay-postinst
Labels: qa: Can't merge

#6336 Fixes #26773: Do not store nodecompliancelevels by default
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/appconfig/ConfigService.scala
  webapp/sources/rudder/rudder-rest/src/test/resources/api/api_settings.yml
Labels: qa: Can't merge

#6292 Fixes #26642: Compliance right should not give access to techniques and global parameters
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/Authorizations.scala
  webapp/sources/rudder/rudder-rest/src/test/resources/api/api_usermanagement.yml
Labels: qa: Can't merge

#6333 Fixes #25374: System group description is editable in the UI but cannot be saved
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/NodeGroupForm.scala
Labels: qa: Can't merge

#6340 Fixes #26768: Randomize port used in relayd test
  Cargo.lock
  relay/sources/relayd/Cargo.toml
  relay/sources/relayd/src/lib.rs
  relay/sources/relayd/src/main.rs
  relay/sources/relayd/tests/api_shared_files/37817c4d-fbf7-4850-a985-50021f4e8f41/files/e745a140-40bc-4b86-b6dc-084488fc906b/file-old.metadata
  relay/sources/relayd/tests/api_system_info.rs
  relay/sources/relayd/tests/api_system_reload.rs
  relay/sources/relayd/tests/api_system_status.rs
  relay/sources/relayd/tests/common/mod.rs
  relay/sources/relayd/tests/http_client.rs
  relay/sources/relayd/tests/processing_reporting.rs
  relay/sources/relayd/tests/processing_reporting_old.rs
  relay/sources/relayd/tests/remote_run.rs
  relay/sources/relayd/tests/server.py
  relay/sources/relayd/tests/shared_files.rs
  relay/sources/relayd/tests/shared_folder.rs
Labels: qa: Can't merge, Ready for merge

#6335 Fixes #26712: When directives are skipped, they are multiplied in the directive tab of the rule
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/reports/StatusReports.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/DataStructures.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/reports/ExecutionBatch.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/reports/ReportingService.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/reports/ReportingServiceImpl.scala
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/domain/reports/StatusReportTest.scala
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/reports/ExecutionBatchTest.scala
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/reports/ReportingServiceUtilsTest.scala
  webapp/sources/rudder/rudder-rest/pom.xml
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/data/Compliance.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/ComplianceApi.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/web/services/ComputePolicyMode.scala
  webapp/sources/rudder/rudder-rest/src/test/resources/api/api_compliance.yml
  webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/MockServices.scala
  webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/domain/reports/JsonPostresqlSerializationTest.scala
  webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/rest/RunComplianceComputation.scala
  webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/rest/TestDirectiveComplianceCsv.scala
  webapp/sources/rudder/rudder-web/src/main/elm/sources/DirectiveCompliance/DataTypes.elm
  webapp/sources/rudder/rudder-web/src/main/elm/sources/DirectiveCompliance/JsonDecoder.elm
  webapp/sources/rudder/rudder-web/src/main/elm/sources/DirectiveCompliance/ViewUtils.elm
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/ShowNodeDetailsFromNode.scala
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/services/ComplianceData.scala
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/services/ReportDisplayer.scala
  webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder-main.scss
Labels: qa: Can't merge

#6338 Fixes #26648: We cannot scroll to the bottom page of all Settings pages
  webapp/sources/rudder/rudder-web/src/main/elm/sources/Onboarding/View.elm
  webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder-settings.scss
  webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder-template.scss
  webapp/sources/rudder/rudder-web/src/main/webapp/secure/administration/settings.html
  webapp/sources/rudder/rudder-web/src/main/webapp/templates-hidden/components/administration/policyServerManagement.html
Labels: Ready for merge

#6339 Fixes #26774: Clean up reporting node compliance tables
  webapp/sources/api-doc/components/schemas/settings.yml
  webapp/sources/rudder/rudder-core/src/main/resources/reportsSchema.sql
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/reports/execution/ReportsExecutionService.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/ComplianceRepository.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/ExpectedReportsRepository.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/jdbc/ComplianceRepository.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/jdbc/ExpectedReportsJdbcRepository.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/system/DatabaseManager.scala
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/db/GenerateCompliance.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/appconfig/ConfigService.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/SettingsApi.scala
  webapp/sources/rudder/rudder-rest/src/test/resources/api/api_settings.yml
  webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala
  webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/checks/endconfig/migration/DropNodeComplianceTables.scala
  webapp/sources/rudder/rudder-web/src/test/scala/bootstrap/liftweb/checks/endconfig/migration/TestDropNodeComplianceTables.scala
  webapp/sources/utils/src/main/scala/com/normation/ZioCommons.scala
Labels: qa: Can't merge, Ready for merge

#6346 Fixes #26847: A user that has only the "deployer_read" right does not have access to the settings API
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/EndpointsDefinition.scala
Labels: Ready for merge
