Repository Normation/rudder, pull requests merged in 2025-08, with the labels that each got.

#6541 Fixes #27364: Add a generic json codec for enumeratum
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/campaigns/DataTypes.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/properties/PropertyHierarchy.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/reports/NodeComplianceExpiration.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/data/ApiAccount.scala
  webapp/sources/utils/src/main/scala/zio/json/other/package.scala
  webapp/sources/utils/src/test/scala/zio/json/other/EnumCodecTest.scala
Labels: qa: Can't merge

#6553 Fixes #27370: Dashboard will not display charts when switching between bechmarks
  webapp/sources/rudder/rudder-web/src/main/javascript/rudder/homePage.js
Labels: qa: Can't merge

#6515 Fixes #26767:
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/Authorizations.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/ApiAuthorization.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/UserManagementApi.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/users/RudderUserDetailsFile.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/users/User.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/users/UserManagement.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/users/UserManagementService.scala
  webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/rest/RestTestSetUp.scala
  webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/rest/TraitTestApiFromYamlFiles.scala
  webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/AppConfigAuth.scala
Labels: qa: Can't merge

#6560 Fixes #27404: Finish Rust dependency update
  Cargo.lock
  deny.toml
  policies/Dockerfile
  policies/module-types/augeas/Cargo.toml
  policies/module-types/augeas/src/augeas.rs
  policies/module-types/augeas/src/dsl/parser.rs
  policies/module-types/inventory/Cargo.toml
  policies/module-types/system-updates/Cargo.toml
  policies/rudder-commons/Cargo.toml
  policies/rudder-commons/src/lib.rs
  policies/rudderc/Cargo.toml
  policies/rudderc/src/ir/value.rs
  policies/rudderc/src/lib.rs
  relay/sources/relayd/Cargo.toml
  relay/sources/relayd/Dockerfile
  relay/sources/relayd/src/api.rs
  relay/sources/relayd/src/api/remote_run.rs
  relay/sources/relayd/tests/common/mod.rs
  relay/sources/rudder-package/Cargo.toml
  relay/sources/rudder-package/Dockerfile
  relay/sources/rudder-package/src/archive.rs
  relay/sources/rudder-package/src/dependency.rs
  relay/sources/rudder-package/src/list.rs
  relay/sources/rudder-package/src/webapp.rs
  rust-toolchain.toml
  sbom/Dockerfile
Labels: qa: Can't merge, Ready for merge

#6563 Fixes #27437: Ignore CVEs for icu4j
  webapp/sources/dependency-check-suppression.xml
Labels: Ready for merge

#6568 Fixes #27450: Fix the rudder_info! macro to make it usable in audit mode
  policies/rudder-module-type/src/cfengine/log.rs
Labels: Ready for merge, rust
