Repository Normation/rudder, pull requests merged in 2025-01, with the labels that each got.

#6108 Fixes #26119: All rule show up in directive compliance
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/ComplianceApi.scala
  webapp/sources/rudder/rudder-rest/src/test/resources/api/api_compliance.yml
  webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/MockServices.scala
Labels: qa: Can't merge

#6110 Fixes #26134: Change Rudder current-year to 2025
  webapp/sources/pom.xml
Labels: qa: Can't merge

#6115 Fixes #26149: Handle the plugin metadata for license requirement
  relay/sources/rudder-package/src/database.rs
  relay/sources/rudder-package/src/list.rs
  relay/sources/rudder-package/src/plugin.rs
  relay/sources/rudder-package/src/repo_index.rs
  relay/sources/rudder-package/tests/cli/cli-list-out.json
  relay/sources/rudder-package/tests/database/plugin_database_update_sample.json
  relay/sources/rudder-package/tests/database/plugin_database_update_sample.json.expected
Labels: qa: Can't merge

#6100 Fixes #26105: The statistics on the dashboard are hardly readable
  webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder-dashboard.scss
  webapp/sources/rudder/rudder-web/src/main/webapp/secure/index.html
Labels: qa: Can't merge

#6111 Fixes #26136: Add instance ID in group search criteria
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/queries/CmdbQuery.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/queries/NodeQueryCriteriaData.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/queries/NodeFactQueryProcessor.scala
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/MockServices.scala
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/queries/TestNodeFactQueryProcessor.scala
  webapp/sources/rudder/rudder-web/src/main/resources/ldapObjectAndAttributes.properties
  webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/SearchNodeComponent.scala
Labels: qa: Can't merge

#6113 Fixes #26059: Create a new ‘About’ page for easy access to technical information
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/metrics/DataTypes.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/metrics/HistorizeNodeCountService.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/metrics/SystemInfoService.scala
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/metrics/NodeCountHistorizationTest.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/data/About.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/SystemApi.scala
  webapp/sources/rudder/rudder-rest/src/test/resources/api/api_system.yml
  webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/rest/RestTestSetUp.scala
  webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/rest/SystemApiTest.scala
  webapp/sources/rudder/rudder-web/src/main/elm/sources/About.elm
  webapp/sources/rudder/rudder-web/src/main/elm/sources/About/ApiCalls.elm
  webapp/sources/rudder/rudder-web/src/main/elm/sources/About/DataTypes.elm
  webapp/sources/rudder/rudder-web/src/main/elm/sources/About/Init.elm
  webapp/sources/rudder/rudder-web/src/main/elm/sources/About/JsonDecoder.elm
  webapp/sources/rudder/rudder-web/src/main/elm/sources/About/JsonEncoder.elm
  webapp/sources/rudder/rudder-web/src/main/elm/sources/About/View.elm
  webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/Boot.scala
  webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala
  webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/metrics/SystemInfoServiceImpl.scala
  webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder-about.scss
  webapp/sources/rudder/rudder-web/src/main/webapp/secure/administration/about.html
  webapp/sources/utils/src/main/scala/com/normation/utils/DateFormaterService.scala
Labels: qa: Can't merge, Ready for merge

#6124 Fixes #26173: Add windows 2025 data info in Rudder server
  webapp/sources/ldap-inventory/inventory-api/src/main/scala/com/normation/inventory/domain/NodeInventory.scala
  webapp/sources/ldap-inventory/inventory-fusion/src/test/resources/fusion-inventories/8.3/AGENT1-c6642a36-b1ed-43e4-a7b7-7d0e1f85063e.ocs
  webapp/sources/ldap-inventory/inventory-fusion/src/test/resources/fusion-inventories/8.3/AGENT1-c6642a36-b1ed-43e4-a7b7-7d0e1f85063e.ocs.sign
  webapp/sources/ldap-inventory/inventory-fusion/src/test/scala/com/normation/inventory/provisioning/fusion/TestReportParsing.scala
  webapp/sources/ldap-inventory/inventory-repository/src/main/scala/com/normation/inventory/ldap/core/InventoryMapper.scala
  webapp/sources/ldap-inventory/inventory-repository/src/main/scala/com/normation/inventory/ldap/core/LDAPConstants.scala
  webapp/sources/rudder/rudder-web/src/main/resources/ldapObjectAndAttributes.properties
  webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder-main.scss
Labels: qa: Can't merge

#6122 Fixes #26144: Allow to install plugins from user interface
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/plugins/PluginSettings.scala
  webapp/sources/rudder/rudder-rest/src/test/resources/api/api_plugins.yml
  webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/rest/RestTestSetUp.scala
  webapp/sources/rudder/rudder-web/src/main/elm/sources/Plugins.elm
  webapp/sources/rudder/rudder-web/src/main/elm/sources/Plugins/ApiCalls.elm
  webapp/sources/rudder/rudder-web/src/main/elm/sources/Plugins/DataTypes.elm
  webapp/sources/rudder/rudder-web/src/main/elm/sources/Plugins/Init.elm
  webapp/sources/rudder/rudder-web/src/main/elm/sources/Plugins/JsonDecoder.elm
  webapp/sources/rudder/rudder-web/src/main/elm/sources/Plugins/JsonEncoder.elm
  webapp/sources/rudder/rudder-web/src/main/elm/sources/Plugins/View.elm
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/plugins/RudderPlugin.scala
  webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder-plugins.css
  webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder-plugins.scss
  webapp/sources/rudder/rudder-web/src/main/webapp/secure/administration/pluginInformation.html
  webapp/sources/rudder/rudder-web/src/test/scala/com/normation/plugins/PluginSettingTest.scala
Labels: qa: Can't merge

#6117 Fixes #26161: Allow to enable/disable technique from the directive tree scree
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/DependencyAndDeletionService.scala
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/DirectiveEditForm.scala
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/services/DisplayDirectiveTree.scala
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/configuration/DirectiveManagement.scala
  webapp/sources/rudder/rudder-web/src/main/webapp/secure/configurationManager/directiveManagement.html
Labels: qa: Can't merge, Ready for merge

#6141 Fixes #26194: Patch management campaigns on CentOS 7 end in error
  policies/module-types/system-updates/src/package_manager.rs
  policies/module-types/system-updates/src/package_manager/yum.rs
  policies/module-types/system-updates/src/package_manager/zypper.rs
Labels: qa: Can't merge, Ready for merge

#6134 Fixes #26207: Plugin management operations need confirmation popup and license error info
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/plugins/PluginSettings.scala
  webapp/sources/rudder/rudder-web/src/main/elm/elm.json
  webapp/sources/rudder/rudder-web/src/main/elm/sources/Plugins.elm
  webapp/sources/rudder/rudder-web/src/main/elm/sources/Plugins/ApiCalls.elm
  webapp/sources/rudder/rudder-web/src/main/elm/sources/Plugins/DataTypes.elm
  webapp/sources/rudder/rudder-web/src/main/elm/sources/Plugins/Init.elm
  webapp/sources/rudder/rudder-web/src/main/elm/sources/Plugins/View.elm
  webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder-plugins.scss
Labels: qa: Can't merge, Ready for merge

#6130 Fixes #25586: Persistant tooltips on rules page
  webapp/sources/rudder/rudder-web/src/main/javascript/rudder/rudder.js
Labels: Ready for merge

#6140 Fixes #26206: Directive will not be displayed when clicking on a technique then on directive in tree
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/configuration/DirectiveManagement.scala
Labels: Ready for merge

#6128 Fixes #26062: There is no "refresh" on the compliance in directive page and group page
  webapp/sources/rudder/rudder-web/src/main/elm/sources/DirectiveCompliance/ViewNodesCompliance.elm
  webapp/sources/rudder/rudder-web/src/main/elm/sources/DirectiveCompliance/ViewRulesCompliance.elm
  webapp/sources/rudder/rudder-web/src/main/elm/sources/GroupCompliance/DataTypes.elm
  webapp/sources/rudder/rudder-web/src/main/elm/sources/GroupCompliance/ViewUtils.elm
  webapp/sources/rudder/rudder-web/src/main/elm/sources/Groupcompliance.elm
Labels: qa: Can't merge

#6137 Fixes #26244: License repository errors should result in different exit codes
  relay/sources/rudder-package/src/lib.rs
  relay/sources/rudder-package/src/main.rs
  relay/sources/rudder-package/src/repository.rs
Labels: qa: Can't merge, Ready for merge

#6144 Fixes #26138: Undefined variables can lead to unwated policy override overrides
  policies/rudderc/src/backends/unix.rs
  policies/rudderc/src/backends/unix/cfengine/bundle.rs
  policies/rudderc/src/backends/unix/cfengine/promise.rs
  policies/rudderc/src/backends/unix/ncf/method_call.rs
  policies/rudderc/tests/cases/general/escaping/technique.cf
  policies/rudderc/tests/cases/general/form/technique.cf
  policies/rudderc/tests/cases/general/long_method_param_name/technique.cf
  policies/rudderc/tests/cases/general/min/technique.cf
  policies/rudderc/tests/cases/general/min_yaml/technique.cf
  policies/rudderc/tests/cases/general/ntp/technique.cf
  policies/rudderc/tests/cases/general/param_in_condition/technique.cf
  policies/rudderc/tests/cases/general/policy_mode/technique.cf
  policies/rudderc/tests/cases/general/reporting/technique.cf
  policies/rudderc/tests/cases/general/variables/technique.cf
Labels: qa: Can't merge

#6145 Fixes #26270: Add policy type in rudderc
  policies/rudderc/src/backends/metadata.rs
  policies/rudderc/src/ir/technique.rs
  policies/rudderc/src/technique.schema.json
  policies/rudderc/tests/cases/test/zero_param_windows/technique.yml
  policies/rudderc/tests/metadata/serialized.xml
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/cfclerk/xmlparsers/TechniqueParser.scala
Labels: qa: Can't merge
