Repository Normation/rudder, pull requests merged in 2025-02, with the labels that each got.

#6156 Fixes #26292: Allow to choose api account ID on creation
  webapp/sources/rudder/rudder-core/src/main/resources/ldap/rudder.schema
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/api/ApiAccountRepository.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/api/DataStructures.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/apidata/RestDataSerializer.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/ldap/LDAPDiffMapper.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/repository/ldap/LDAPEntityMapper.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/marshalling/XmlSerialisationImpl.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/marshalling/XmlUnserialisationImpl.scala
  webapp/sources/rudder/rudder-core/src/test/resources/ldap-data/schema/099-1-rudder.ldif
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/RestExtractorService.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/internal/GroupsInternalAPI.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/internal/RestApiAccounts.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/internal/RulesInternalAPI.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/users/User.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/web/services/EventLogDetailsGenerator.scala
  webapp/sources/rudder/rudder-web/src/main/elm/sources/Accounts/JsonDecoder.elm
  webapp/sources/rudder/rudder-web/src/main/elm/sources/Accounts/ViewModals.elm
  webapp/sources/rudder/rudder-web/src/main/elm/sources/Accounts/ViewUtils.elm
  webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/AppConfigAuth.scala
  webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/checks/endconfig/action/CreateSystemToken.scala
  webapp/sources/rudder/rudder-web/src/test/resources/ldap-data/schema/099-1-rudder.ldif
  webapp/sources/rudder/rudder-web/src/test/scala/bootstrap/liftweb/checks/endconfig/action/TestCreateSystemToken.scala
Labels: qa: Can't merge

#6155 Fixes #26286: InstanceId check must be in early bootstrap checks
  webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/BootstrapChecks.scala
  webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala
  webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/checks/earlyconfig/db/CheckPostgreConnection.scala
  webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/checks/earlyconfig/db/CheckTableReportsExecutionTz.scala
  webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/checks/earlyconfig/db/CheckTableScore.scala
  webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/checks/earlyconfig/db/CheckTableUsers.scala
  webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/checks/earlyconfig/db/CheckUsersFile.scala
  webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/checks/earlyconfig/db/CreateTableNodeFacts.scala
  webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/checks/earlyconfig/db/DeleteArchiveTables.scala
  webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/checks/earlyconfig/db/MigrateChangeValidationEnforceSchema.scala
  webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/checks/earlyconfig/db/MigrateEventLogEnforceSchema.scala
  webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/checks/earlyconfig/ldap/CheckLdapConnection.scala
  webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/checks/endconfig/action/CreateInstanceUuid.scala
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/comet/AsyncDeployment.scala
  webapp/sources/utils/src/main/scala/com/normation/utils/DateFormaterService.scala
Labels: qa: Can't merge

#6162 Fixes #26290: The relayd reports parser can break on multiline fields in logs
  relay/sources/relayd/src/data/report.rs
Labels: qa: Can't merge

#6166 Fixes #26323: Create a doc for Rust agent support
  policies/module-types/platform-support.md
Labels: qa: Can't merge

#6178 Fixes #26175: “rudder package upgrade” alone does not upgrade any plugin
  relay/sources/rudder-package/src/lib.rs
Labels: qa: Can't merge, Ready for merge

#6175 Fixes #26338: Prettify About page
  webapp/sources/rudder/rudder-web/src/main/elm/sources/About/View.elm
  webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder-about.scss
Labels: qa: Can't merge

#5977 Fixes #25759: Improve APT/dpkg output collecter
  Cargo.lock
  policies/module-types/system-updates/Cargo.toml
  policies/module-types/system-updates/src/db.rs
  policies/module-types/system-updates/src/package_manager/apt.rs
  policies/module-types/system-updates/src/package_manager/apt/progress.rs
Labels: qa: Can't merge

#6181 Fixes #26370: Make rudder jenkins task work with ns-remap
  Jenkinsfile
  Jenkinsfile-security
  api-doc/Dockerfile
  ci/common.Dockerfile
  ci/pylint.Dockerfile
  ci/shellcheck.Dockerfile
  ci/typos.Dockerfile
  policies/minifusion/src/properties.rs
  policies/techniques/anssi_bp_028/technique.yml
  policies/techniques/anssi_bp_028/test.yml
  relay/_typos.toml
  relay/sources/rudder-package/src/lib.rs
  webapp/sources/Dockerfile
Labels: qa: Can't merge

#6194 Fixes #26414: Cache is not shared anymode
  Jenkinsfile
  Jenkinsfile-security
Labels: Ready for merge

#6197 Fixes #26424: Parent break enable/disable commands
  relay/sources/rudder-package/src/lib.rs
Labels: Ready for merge

#6179 Fixes #26325: Resolved properties conflicts still appear as errors in status
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/properties/Properties.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/properties/MergeNodeProperties.scala
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/rudder/services/nodes/TestMergeGroupProperties.scala
Labels: Ready for merge

#6152 Fixes #26278: Add foreach on blocks
  webapp/sources/rudder/rudder-web/src/main/elm/sources/Editor.elm
  webapp/sources/rudder/rudder-web/src/main/elm/sources/Editor/DataTypes.elm
  webapp/sources/rudder/rudder-web/src/main/elm/sources/Editor/ViewBlock.elm
  webapp/sources/rudder/rudder-web/src/main/elm/sources/Editor/ViewMethod.elm
  webapp/sources/rudder/rudder-web/src/main/elm/sources/Editor/ViewTabForeach.elm
  webapp/sources/rudder/rudder-web/src/main/elm/sources/Editor/ViewTechnique.elm
Labels: qa: Can't merge

#6201 Fixes #26428: rudder-pkg reports a success when installing a plugin even if the postinst plugin script was in error
  relay/sources/rudder-package/src/plugin.rs
Labels: qa: Can't merge

#6205 Fixes #26438: Parent produces errors on stderr and a global error status for the event
  Cargo.lock
  policies/module-types/system-updates/Cargo.toml
  policies/module-types/system-updates/src/package_manager/apt.rs
  policies/module-types/system-updates/src/package_manager/apt/progress.rs
Labels: qa: Can't merge, Ready for merge

#6207 Fixes #26442: Update cargo auditable for Rust 2024
  ci/rust.sh
Labels: Ready for merge

#6196 Fixes #26422: Clean-up old API account
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/apidata/RestDataSerializer.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/RestExtractorService.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/internal/RestApiAccounts.scala
  webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/Boot.scala
  webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/administration/ApiAccounts.scala
  webapp/sources/rudder/rudder-web/src/main/webapp/secure/access/apiManagement.html
Labels: qa: Can't merge, Ready for merge

#6177 Fixes #26336: Improve user interaction and displayed information on plugins management page
  webapp/sources/rudder/rudder-web/src/main/elm/elm.json
  webapp/sources/rudder/rudder-web/src/main/elm/sources/Plugins.elm
  webapp/sources/rudder/rudder-web/src/main/elm/sources/Plugins/Action.elm
  webapp/sources/rudder/rudder-web/src/main/elm/sources/Plugins/ApiCalls.elm
  webapp/sources/rudder/rudder-web/src/main/elm/sources/Plugins/DataTypes.elm
  webapp/sources/rudder/rudder-web/src/main/elm/sources/Plugins/Init.elm
  webapp/sources/rudder/rudder-web/src/main/elm/sources/Plugins/JsonDecoder.elm
  webapp/sources/rudder/rudder-web/src/main/elm/sources/Plugins/JsonEncoder.elm
  webapp/sources/rudder/rudder-web/src/main/elm/sources/Plugins/PluginData.elm
  webapp/sources/rudder/rudder-web/src/main/elm/sources/Plugins/Select.elm
  webapp/sources/rudder/rudder-web/src/main/elm/sources/Plugins/Tests/PluginsTests.elm
  webapp/sources/rudder/rudder-web/src/main/elm/sources/Plugins/View.elm
  webapp/sources/rudder/rudder-web/src/main/resources/load-page/rudder-loading.html
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/snippet/PluginExpirationInfo.scala
  webapp/sources/rudder/rudder-web/src/main/style/rudder/_rudder-variables.scss
  webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder-plugins.scss
Labels: qa: Can't merge, Ready for merge

#6195 Fixes #26417: Keep line breaks in reports
  webapp/sources/rudder/rudder-web/src/main/elm/sources/DirectiveCompliance/ViewUtils.elm
  webapp/sources/rudder/rudder-web/src/main/elm/sources/GroupCompliance/ViewUtils.elm
  webapp/sources/rudder/rudder-web/src/main/elm/sources/NodeCompliance/ViewUtils.elm
  webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder-datatable.css
  webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder-template.scss
Labels: qa: Can't merge

#6219 Fixes #26451: Allow skipping the postinst
  relay/sources/rudder-package/src/archive.rs
  relay/sources/rudder-package/src/lib.rs
Labels: qa: Can't merge, Ready for merge

#6216 Fixes #26399: Hooks documentation link redirects to non-existing page
  webapp/sources/rudder/rudder-web/src/main/elm/sources/Hooks/View.elm
Labels: qa: Can't merge

#6200 Fixes #25962: Authorize global parameter names that are not alpha numeric only
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/properties/Properties.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/DataStructures.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/RestExtractorService.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/lift/ParametersApi.scala
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/popup/CreateOrUpdateGlobalParameterPopup.scala
Labels: qa: Can't merge

#6220 Fixes #26449: Improve accessibility of filter, actions and errors on plugins page
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/plugins/cli/RudderPackagePlugin.scala.scala
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/plugins/cli/RudderPackageServiceTest.scala
  webapp/sources/rudder/rudder-web/src/main/elm/sources/Plugins.elm
  webapp/sources/rudder/rudder-web/src/main/elm/sources/Plugins/DataTypes.elm
  webapp/sources/rudder/rudder-web/src/main/elm/sources/Plugins/Init.elm
  webapp/sources/rudder/rudder-web/src/main/elm/sources/Plugins/Select.elm
  webapp/sources/rudder/rudder-web/src/main/elm/sources/Plugins/Tests/PluginsTests.elm
  webapp/sources/rudder/rudder-web/src/main/elm/sources/Plugins/View.elm
  webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder-menu.scss
  webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder-plugins.scss
  webapp/sources/rudder/rudder-web/src/main/style/rudder/rudder-template.scss
Labels: qa: Can't merge, Ready for merge

#6214 Fixes #26446: Every time webapp starts the logback file gets duplicate XML to configure fixed log file
  webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/checks/endconfig/migration/FixedPathLoggerMigration.scala
  webapp/sources/rudder/rudder-web/src/test/scala/bootstrap/liftweb/checks/endconfig/migration/TestMigrateLogbackXml.scala
Labels: Ready for merge

#6204 Fixes #26439: Fix display of license information
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/plugins/PluginData.scala
  webapp/sources/rudder/rudder-core/src/main/scala/com/normation/plugins/PluginError.scala
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/plugins/PluginDataTest.scala
  webapp/sources/rudder/rudder-core/src/test/scala/com/normation/plugins/PluginErrorTest.scala
  webapp/sources/rudder/rudder-rest/src/main/scala/com/normation/rudder/rest/data/About.scala
  webapp/sources/rudder/rudder-rest/src/test/resources/api/api_plugins.yml
  webapp/sources/rudder/rudder-rest/src/test/scala/com/normation/rudder/rest/RestTestSetUp.scala
  webapp/sources/rudder/rudder-web/src/main/elm/sources/About/View.elm
  webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/Boot.scala
  webapp/sources/rudder/rudder-web/src/main/scala/com/normation/plugins/RudderPlugin.scala
  webapp/sources/rudder/rudder-web/src/test/scala/com/normation/plugins/RudderPluginTest.scala
Labels: qa: Can't merge, Ready for merge
